### ISSUE TITLE
Color picker sample gone?

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#1015]
Was the color picker sample that used to be at one side of the hex code removed in one of the updates? It doesn't show anymore for some reason. I deleted any custom CSS, cleared cache and still can't see it.

**Comment by Shelob9** [comment]
@101010f It's still there for me. I'm testing with Caldera Forms 1.4.6.1, WordPress 4.7, TwentySeventeen and no other plugins.

 Did you check for JavaScript error in your console?
