### ISSUE TITLE
conditional display with unnecessary characters

### ISSUE THREAD

**Issue by antoinekoud** [CalderaWP/Caldera-Forms#1021]
Hi, my name is Thony
After updating my caldera form this morning, i have found out these useless characters on the block that displays my form objet. These two fields are displayed only under specific conditions. Does anyone have an idea about where the problem can come from and how to set it? Thanks in advance
![bug caldera form](https://cloud.githubusercontent.com/assets/24542228/21134634/b058b34c-c116-11e6-9c17-7fe8baba7c36.png)

**Comment by Shelob9** [comment]
@antoinekoud This is a conflict with a plugin or theme (probably a theme applying HTML markup to our inline Javascript. Please see my response to your email this morning. 

I am closing as this in not a bug, but a support request.

**Comment by antoinekoud** [comment]
Thanks for the suggestion, i ll get a look at and get back to you
