### ISSUE TITLE
After upgrading to 1.4.6.1, summary magic tag producing one-letter values

### ISSUE THREAD

**Issue by cbomkamp** [CalderaWP/Caldera-Forms#1027]
I installed Caldera Forms on my site on October 30, so whatever was the latest version at that time is what I had previously. I setup one or two forms and some auto-responders with just the {summary} tag in the body. All was working fine at that point. I'm using the Mailgun plugin to send mail through WP.

I upgraded to 1.4.6.1 yesterday and now the emails come through looking like this:

> **First Name**
> C
> 
> **Last Name**
> B
> 
> **Email Address**
> c
> 
> **Your Age (must be 21 or older)**
> 2
> 

I'm only getting the first character of each field value. It doesn't matter what I enter in the fields. I always just get 1 character.

The data shows correctly in the entries list in the admin panel.

Also, I can use the individual field tags in the processor and they will show up fine. For example, if I put in %first_name%, I get the full first name value.

**Comment by cbomkamp** [comment]
Just noticed this was posted on the support forums:

https://wordpress.org/support/topic/summary-magic-tag-problem/

**Comment by Shelob9** [comment]
@cbomkamp Thanks for using Caldera Forms. I'm not seeing this in any of my test environments. If possible, can you please send me an export file for your form (Josh@CalderaWP.com) also can you try it with no other plugins active and with the default theme?

**Comment by crataz** [comment]
Same problem for me, I sent you an email.

**Comment by cbomkamp** [comment]
@Shelob9 I sent you an email.

**Comment by Shelob9** [comment]
@crataz @cbomkamp Thanks for sending those exports, I will test later today. It would be very helpful to know what PHP versions both of you are using. Please look in the Caldera Forms support submenu, under the debug info tab.

**Comment by cbomkamp** [comment]
WordPress Version: 4.6.1

PHP Version: 5.2.17

**Comment by crataz** [comment]
WordPress Version: 4.7

PHP Version: 5.3.29

MySQL Version: 5.5.52

Server Software: Apache

**Comment by Shelob9** [comment]
Thank you both for that info. I'll see if your out of date PHP could be the
cause.

I strongly recommend both of you update to PHP 5.6. Your versions of PHP
are out of date, slow and potentially insecure.

**Comment by cbomkamp** [comment]
Any progress?

**Comment by cbomkamp** [comment]
I used the WP Rollback plugin to rollback the Caldera Forms plugin one version at a time, starting with 1.4.6. 1.4.6 still has the issue but 1.4.5.1 does not, it is outputting the full values correctly in the email. So it appears to to have been introduced with 1.4.6.

I'm going to stay on 1.4.5.1 for the time being but if there's anything else I can do to help, let me know.

Regarding the PHP version, I have talked with the primary developer of the site and we do plan to upgrade to the latest version soon, but we need more time to plan it out and test everything thoroughly. It wouldn't surprise me if the PHP version was related considering there don't seem to be many people reporting this issue.

**Comment by Shelob9** [comment]
@cbomkamp Sorry I was traveling for Christmas/ New Years and didn't get a chance to build an environment to test this in. That said, this should be a quick fix for you, most hosts let you fix your PHP version in a few clicks. PHP has put in no breaking changes between 5.2 and 5.6 that I know of. PHP7 deprecated named constructors, which can be an issue in WordPress due to legacy PHP4 style code in some plugins, doesn't break anything, but will make warnings.

**Comment by Shelob9** [comment]
https://secure.helpscout.net/conversation/300090472/0/ confirms this is an issue related to dinoPHP, which we should fix, but also no one should use PHP5.3, it's bad and slow.

**Comment by Shelob9** [comment]
Close via #1086
