### ISSUE TITLE
Some notices are still showing in our admin. 

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1028]
Hey

I forgot the issue...it is somewhere but I wanted to show a screenshot of the Forms screen with update/warning nofications.

![screen shot 2016-12-16 at 16 46 34](https://cloud.githubusercontent.com/assets/5323259/21268518/744c2352-c3af-11e6-8e62-25d871af1d96.png)

**Comment by Shelob9** [comment]
Close via 	94c3782

**Comment by Shelob9** [comment]
Thanks @paaljoachim for the report!
