### ISSUE TITLE
checkbox entries in email appear as JSON data

### ISSUE THREAD

**Issue by qubez** [CalderaWP/Caldera-Forms#1032]
This is almost identical to #888, but now the problem has been reversed - instead of the CSV file showing the weird JSON data, now custom emails that use checkboxes show the JSON data from internal database names. It was working for a while, but the latest update messed this up.

Using a similar form to the previous bug ([checkbox-test-export-htmlemail.json.txt](https://github.com/CalderaWP/Caldera-Forms/files/659494/checkbox-test-export-htmlemail.json.txt)), here's what I put in the email message field:
```
<h3>Checkbox html output test:</h3>
<p>emailaddress: <strong>%emailaddress%</strong></p>
<p>single_item_checkbox: <strong>%single_item_checkbox%</strong></p>
<p>single_checkbox_left_unchecked: <strong>%single_checkbox_left_unchecked%</strong></p>
<p>multiple_item_checkbox: <strong>%multiple_item_checkbox%</strong></p>
<p>bulk_insert_checkbox: <strong>%bulk_insert_checkbox%</strong></p>
More text: %more_text%
<p>End of Email</p>
{summary}

```

Notice that I've used both custom HTML, and then end the email with the magic summary tag. I receive this email:
<h3>Checkbox html output test:</h3>
<p>emailaddress: <strong>tst@email.com</strong></p>
<p>single_item_checkbox: <strong>{"opt1233463":"Option Checked"}</strong></p>
<p>single_checkbox_left_unchecked: <strong></strong></p>
<p>multiple_item_checkbox: <strong>{"opt1376749":"Option 1","opt1721046":"Option 2"}</strong></p>
<p>bulk_insert_checkbox: <strong>{"opt2810742":"Option c","opt3267257":"Option d"}</strong></p>
<p>More text: More typing</p>
<p>End of Email</p>
<p><strong>Email Address</strong></p>
<div style="margin-bottom:20px;">tst@email.com</div>
<p><strong>Single Item Checkbox</strong></p>
<div style="margin-bottom:20px;">Option Checked</div>
<p><strong>Multiple Item Checkbox</strong></p>
<div style="margin-bottom:20px;">Option 1, Option 2</div>
<p><strong>Bulk insert checkbox</strong></p>
<div style="margin-bottom:20px;">Option c, Option d</div>
<p><strong>More Text</strong></p>
<div style="margin-bottom:20px;">More typing</div>

**Comment by Shelob9** [comment]
@qubez Is this auto-responder or the main email notification that is not translating properly?

If it's main email processor, then something is wrong with the fix I did for #888 (https://github.com/CalderaWP/Caldera-Forms/blob/bbd4f039d2513b4baa9988539c4c2bd4b18bbace/classes/save.php#L155-L166)

If it's in auto-responder, then problem is that code doesn't run on auto-responder, https://github.com/CalderaWP/Caldera-Forms/blob/bbd4f039d2513b4baa9988539c4c2bd4b18bbace/classes/core.php#L886

**Comment by qubez** [comment]
It is the main email message reply. I just reverted to 1.4.5.1 and it is working as expected again. HTML source of message received with unbugged email:

```
<h3>Checkbox html output test:</h3>
<p>emailaddress: <strong>djfoa@fjaofa.com</strong></p>
<p>single_item_checkbox: <strong>Option Checked</strong></p>
<p>single_checkbox_left_unchecked: <strong></strong></p>
<p>multiple_item_checkbox: <strong>Option 1, Option 2</strong></p>
<p>bulk_insert_checkbox: <strong>Option c, Option d</strong></p>
<p>More text: This is a text box input</p>
<p>End of Email</p>
<p><strong>Email Address</strong></p>
<div style="margin-bottom:20px;">djfoa@fjaofa.com</div>
<p><strong>Single Item Checkbox</strong></p>
<div style="margin-bottom:20px;">Option Checked</div>
<p><strong>Multiple Item Checkbox</strong></p>
<div style="margin-bottom:20px;">Option 1, Option 2</div>
<p><strong>Bulk insert checkbox</strong></p>
<div style="margin-bottom:20px;">Option c, Option d</div>
<p><strong>More Text</strong></p>
<div style="margin-bottom:20px;">This is a text box input</div>
```

**Comment by Shelob9** [comment]
@qubez Thanks for the info, I am going to look into this today, along with #1027 which I suspect is related. If I can get a fix, I'll do a 1.4.7 release, trying to keep the point releases small and swift while I work on 1.5, which is the big one.

**Comment by Shelob9** [comment]
This was broken in #996

**Comment by Shelob9** [comment]
This was fixed via 		083fe0b

@qubez I'd appreciate if you could double check that this fixes it. I will do full QA tomorrow.

**Comment by qubez** [comment]
That seems to have gotten things working as expected. Thanks for your quick attention!

The name of your pull is odd - emails broke even without summary. I don't use the summary. Actually would prefer HTML email message composition without having wpautop or any visual editor to mangle the code (after putting my HTML5 through a style inliner, I _then_ have to make it all one line).

I've about to deploy one of the most complex forms and emails probably ever made with your plugin, with over 100 fields on 5 pages, 40+ conditions, and multipage printable email HTML replacing a paper form - to where it starts to bog down the browser. Fingers crossed!

**Comment by Shelob9** [comment]
@qubez Thanks for testing.

I'm about to do #1048 for you.

**Comment by Shelob9** [comment]
Close via 083fe0b
