### ISSUE TITLE
Use a hook for wpautop on email messages so it can be unhooked

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1048]

**Comment by Shelob9** [comment]
Formatting can now be removed with `remove_filter( 'caldera_forms_mailer', array( Caldera_Forms::get_instance(), 'format_message' ) );`

**Comment by Shelob9** [comment]
close via 	bc0aaec

**Comment by qubez** [comment]
Thanks for this. Will there be a UI option for this so that dummies like me can easily disable it?

**Comment by Shelob9** [comment]
No UI option. Mailer tab has too much going on already. Put that in
functions.php of your child theme.
