### ISSUE TITLE
Using hiddens

### ISSUE THREAD

**Issue by AlchemyUnited** [CalderaWP/Caldera-Forms#1052]
Having the ability to add hidden is great, obviously. 

However, I kinda expected {summary} not to include them. 

The workaround was simple enough, just add each individual field. NBD.

But it might be cool / helpful to have {summary_all} {summary_hidden_only} {summary_no_hidden}

In short, we're capturing the post_id, as well as the post_title the form is on. That's not something customers need to know / see in their confirmation email. 

Again, this is minor but still a worthy FYI.

**Comment by AlchemyUnited** [comment]
That being said, now that I think about it. It would nice to have 2 different emails. One that goes back to the submitter / site visitor. And one that goes to the site admin / owner. It would then make sense to show the visitor what they submitted, but the owner all the fields, inclusing hiddens.

**Comment by Shelob9** [comment]
@AlchemyUnited The summary magic tag was intended to be used to send site owner, not submitter all the details. You can have as many emails as you want, just add auto-responder processors for as many emails as you want.

That said, you present a valid and common use case. I am opening #1054 for a filter and #1055 for UI option
