### ISSUE TITLE
 Rich Editor and Summery fields edit pencil doesn't do anything

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1057]
Hi Josh

Create a new form from the starter template.
Drag the Rich Editor (later test out the summery field) into the form. 
Try and select the Rich Editor field/Summery field. Clicking the pencil icon nothing happens.

![screen shot 2016-12-20 at 23 33 25](https://cloud.githubusercontent.com/assets/5323259/21370605/bde23c8a-c70c-11e6-8e30-d8b2f46214cd.png)

Hmm this affects all the form fields.

**Comment by Shelob9** [comment]
This got fixed somewhere along the way
