### ISSUE TITLE
Clicking the CF button to insert a form does nothing

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1060]
I went to a page and clicked the CF button to insert a form and nothing happened.
No reaction.

Version 1.5.x

**Comment by Shelob9** [comment]
Thsi comment is probably applicable here: https://github.com/CalderaWP/Caldera-Forms/issues/1064#issuecomment-268631320

**Comment by Shelob9** [comment]
Fixxed via 		128278a
