### ISSUE TITLE
Scroll To Top On Submit - Form settings repeated 2 times

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1061]
Hey

Scroll To Top On Submit in the Form settings is repeated twice.

![screen shot 2016-12-21 at 11 20 26](https://cloud.githubusercontent.com/assets/5323259/21385650/a300763a-c76f-11e6-9733-97311f0a0c3a.png)

**Comment by Shelob9** [comment]
Second one should be deleted

**Comment by Shelob9** [comment]
Close via #1104
