### ISSUE TITLE
Using shortcode does not transform into previewing form in content.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1064]
Hey

Since the CF button to insert the form is not working right now I am instead using the shortcodes.
(Btw the mega huge green shortcode bar is not included in 1.5.x. It was a bit big..)

Inserting a shortcode I would expect it to automatically adjust to a preview of the form that I am using, but it does not. It continues to show the shortcode. Clicking the pencil icon in a preview could just show the shortcode.

**Comment by Shelob9** [comment]
Javascript that makes this work probably isn't loading, means new script loading abstraction is wrong or implemented wrong for post editor.

**Comment by Shelob9** [comment]
close via 	128278a
