### ISSUE TITLE
HTML fields are not rendering shortcodes

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1065]
A client uses the Avada theme and she has built an image carousel using the Fusion page builder. I had to copy the full HTML into a HTML area in CF to use it.
http://celias.no/bestilling/ (uses the newest 1.4 something version of CF)

![screen shot 2016-12-21 at 21 18 31](https://cloud.githubusercontent.com/assets/5323259/21404766/10189f24-c7c3-11e6-80ed-5cd0e901de78.png)

I am noticing that in 1.5.x that I am seeing the code and not the image carousel on the frontend.

![screen shot 2016-12-21 at 21 19 08](https://cloud.githubusercontent.com/assets/5323259/21404791/23a20dfa-c7c3-11e6-9506-142cb218be09.png)

**Comment by Shelob9** [comment]
@paaljoachim Can you clarify that the issue here is that the shortcode is not longer being rendered and that the issue is not that HTML tags are not being rendered?

I must have lost a `do_shortcode()` somewhere, that's an easy fix, but I want to make sure that `<strong>Hi Paal</strong>` in HTML field is still working for you.

**Comment by paaljoachim** [comment]
Using the starter contact form template that contains the html field with
```
<h2>Your Details</h2>
<p>Let us know how to get back to you.</p>
<hr>
```
Shows up as it should.

The problem here is adding all the HTML from an image carousel made with Fusion Builder for another page and then just taking that HTML into an HTML field in CF.  It renders showing the image carousel in version 1.4 something but not in 1.5.

**Comment by Shelob9** [comment]
@paaljoachim Thanks for the clarification, I am renaming to reflect what the issue is. Should be an easy fix.

**Comment by Shelob9** [comment]
Close via 3d565ff3706ab8041ea72e343ad3d5c16a2ca618
