### ISSUE TITLE
Checkbox bug mentioned earlier.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1066]
Hey

The following is a field the user needs to check to accept the sales terms. 

Here is the result in the entry list:

![screen shot 2016-12-21 at 12 21 30](https://cloud.githubusercontent.com/assets/5323259/21387517/3a3d0ce0-c778-11e6-9d70-987e78d538c8.png)

In the detailed view it shows as it should.

**Comment by Shelob9** [comment]
@paaljoachim Which version? This should be fixed in Caldera Forms 1.4.7,  but maybe you are saying that fix didn't make it to 1.5.x branch?

**Comment by paaljoachim** [comment]
I think it was fixed in version 1.4.something. But the fix did not make it over into 1.4.6.7.
As I am seeing the same behavior in that version as well as in 1.5.
