### ISSUE TITLE
Entry View Header (sub menu) remove space for description.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1067]
Hey

![screen shot 2016-12-21 at 12 02 35](https://cloud.githubusercontent.com/assets/5323259/21387591/94d66b7e-c778-11e6-88f8-784aa7cdcea7.png)

Move the edit button closer to the CF logo and form name.

**Comment by Shelob9** [comment]
close via 	1d21c81
