### ISSUE TITLE
activate/deactivate Bug

### ISSUE THREAD

**Issue by hkben** [CalderaWP/Caldera-Forms#1071]
Creating a new form and click 'Deactivate ' . Then , click 'Activate' and click 'Deactivate' again . It doesn't activate the form .

I have checked the response from Ajax . It was { success : true } . And it changed 'form_daft' from 1 to 0 in wp_options . 

I just checked the code . Some of the checking for 'form_draft' is using isset() . Both 0 and 1 can pass though isset(). I suspect this may cause this bug.

**Comment by Shelob9** [comment]
@hkben  Thanks for the report. Which version of Caldera Forms are you using?

**Comment by hkben** [comment]
version 1.4.7

**Comment by Shelob9** [comment]
This was resolved via a separate issue
