### ISSUE TITLE
In some cases BCC is going to TO in mailer.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1075]
I'm not sure why, as this isn't happening to me, but it is being reported by users.

**Comment by Shelob9** [comment]
Helpscout 567 has a screenshot that is useful for this.

**Comment by Shelob9** [comment]
FYI I tried this and mailcatcher said it was wrong and Gmail said it was right. I suspect the case might be that some email clients don't handle BCC right. It is getting added in phpmailer using the bcc method...

**Comment by Shelob9** [comment]
@andrewlimaza Can you please test this? I think its just that some email clients are wrong, but I would like a second opinion. Read helpscout ticket 567 first.

**Comment by andrewlimaza** [comment]
@Shelob9 sure thing will test this and give feedback shortly.

**Comment by andrewlimaza** [comment]
@Shelob9 unable to recreate this issue. 

I tested on:

* Gmail
* Thunderbird
* iOS mail

I also tested with magic tag for the 'Email Recipients' and 'BCC' as same mail as I assumed from the screenshot it might have been the same mail. 

I am unable to recreate this issue.

**Comment by Shelob9** [comment]
Closing as can't reproduce.
