### ISSUE TITLE
On form submission, Check email already exist or not

### ISSUE THREAD

**Issue by rish30990** [CalderaWP/Caldera-Forms#1078]
I don't know if this is correct place for this question but still, Is it possible in this plugin to check whether email already exist in database or not (on form submission). If email already exist then it don’t submit form but instead shows a message “Email Already exist”. If email doesn’t exist only then it submit the form.

Please let me know if this can be done in this plugin or not. If not then can we hope to get this feature in near future?

**Comment by Shelob9** [comment]
@rish30990 This is a feature of the entry limiter add-on: https://calderaforms.com/downloads/caldera-forms-entry-limiter/

**Comment by rish30990** [comment]
@Shelob9 Ok I solved my problem somehow But I wanna tell you a bug that already being told you long time ago. I am not starting new issue here on this because it already been discussed. When form deactivates then it never get activate again. This problem is pissing me off so badly. The "Edit" and "Deactivate" option are so close, someone mistakenly did click on deactivate option and by that all our submitted enteries gone. We have to choice but to make new form by clone option But where will we get those entries back since only export entries option are available (not import!!). If you can't remove this bug soon then atleast change the position of deactivate option, put this option some where alone (best would be inside form edit) so that we dont get click on it by mistake and also we can save our submission hystories (user's entries). Thanks in advance :)
