### ISSUE TITLE
Input masking on phone fields incompatible with autocomplete

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1079]
![cf-autophone-fail](https://cloud.githubusercontent.com/assets/1994311/21596025/1216827a-d103-11e6-88e6-5c8acc59061f.png)

One work around is to turn off the auto-complete for all telephone fields, which can be done with this JavaScript:
`jQuery( 'input[type="tel"]' ).attr("autocomplete", "off");`

Another option, which is better is to disable input masking by using a text field and changing its type to "tel" that way it works on mobile properly and auto-complete also works.

I am re-opening #902 to make sure this is not an issue with the new and improved phone fields in 1.5.0

**Comment by marioernestoms** [comment]
@Shelob9, In my opinion, is not good to use a mask for the phone because caldera-forms is a global solution for forms, and there are many differents types of phone number format in a world and is very difficult find a way that works well.

**Comment by Shelob9** [comment]
@marioernestoms I agree. Current phone field is going to be discontinued. See #902

**Comment by Shelob9** [comment]
I am closing as old  phone fields will be discontinued as we have a better simple option -- input field with tel option, and 1.5 introduces better phone fields.

#1111
