### ISSUE TITLE
Ajax submission saves the data in database but doesn't show success message

### ISSUE THREAD

**Issue by haris4090** [CalderaWP/Caldera-Forms#1082]
Hi, I have created a form using caldera, it was working fine till yesterday but today in the morning i submitted the form and it didn't redirect me to the page defined in the redirect processor. I disabled the ajax submission from the settings and now its working fine, but i want the ajax to work. Any Ideas why I am having this issue
I analyzed the Network tab in developer tools of chrome and it was showing the following code:

`<link rel="stylesheet" href="https://unpkg.com/purecss@0.6.1/build/pure-min.css" integrity="sha384-CCTZv2q9I9m3UOxRLaJneXrrqKwUNOzZ6NGEUMwHtShDJ+nCoiXJCAgi05KfkLGY" crossorigin="anonymous">
{"url":"http:\/\/localhost\/formsplugin\/offers?cf_id=44","result":"Taking you to Payment","data":{"cf_id":"44"},"html":"<div class=\" alert alert-success\">Taking you to Payment<\/div>","type":"complete","form_id":"CF585b620c20dc6","form_name":"Events Form","status":"complete"}`

This was visible inside the preview tab of network. 
P.S I am including a stylesheet in the header which is visible in the above code. I hope it isn't causing any issue.

**Comment by Shelob9** [comment]
@haris4090 If you remove that stylesheet link, does it resolve this issue? If so, it sounds like that is the problem. You should use wp_enqueue_style() to add it the WordPress way to avoid these issues.

If you need additional help, please open a support ticket at https://calderaforms.com/support

**Comment by haris4090** [comment]
@Shelob9 Thanks a lot, removing that stylesheet link solved the problem.
