### ISSUE TITLE
&nbsp; should not be used in radio field

### ISSUE THREAD

**Issue by Troglobitten** [CalderaWP/Caldera-Forms#1087]
This plugin uses &nbsp; in it's output on radio type input fields. These have no use except for spacing the separate radio fields. Spacing should be left to the stylesheet.

**Comment by Shelob9** [comment]
I agree. Easy fix here: https://github.com/CalderaWP/Caldera-Forms/blob/master/fields/radio/field.php#L37

**Comment by Shelob9** [comment]
Close via #1093
