### ISSUE TITLE
typo in email tab 

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1088]
Under Email notification settings > Email message description: "Magic tags, are replaced with submitted data. Use {summary} to build an automatic mail based on form content. Leaving the mailer blank, will create and automatic summary." Should be "...an automatic summary."

**Comment by andrewlimaza** [comment]
Here is the PR - https://github.com/CalderaWP/Caldera-Forms/pull/1112

**Comment by Shelob9** [comment]
Close via #1112
