### ISSUE TITLE
Download a file on backend uploaded by the user on frontend

### ISSUE THREAD

**Issue by iamharisali** [CalderaWP/Caldera-Forms#1091]
In my form user can upload any file while filling the form. When the form is submitted I want to to download that file uploaded by the user from the wp-backend. How can I do that? While viewing the entry lists page I can see the file but when I right click on it and click "save link as.." the download fails saying "Failed- No File". Is this a issue or I am doing it wrong? I have Attached the image. When I click the capture2.png link this no file found thing happens.

![caldera](https://cloud.githubusercontent.com/assets/24894958/21670924/db286a24-d339-11e6-833d-37e5d1c5036a.PNG)

**Comment by haris4090** [comment]
This is the link shown in the browser where file is stored: 
http://localhost/formsplugin/wp-content/uploads/771d6a048c160cfc04a0bbdfd0d5442e/Capture-2.png
but I cant see "771d6a048c160cfc04a0bbdfd0d5442e" this folder inside the uploads folder in directory.

**Comment by haris4090** [comment]
if I uncheck "Organize my uploads into month- and year-based folders" in media settings, It works fine.

**Comment by vinnycaldera** [comment]
Thanks for using Caldera Forms. I'm sorry you're having these issues.

In order to help you we need some information:
* Did it worked as expected before? 
* Can you please provide your PHP, WordPress and CalderaForms version numbers?
* Are you using File or Advanced File Uploader field?
* Did you enabled any option like Attach to mailer, Allow Multiple or Add to Media Library?

Take care,
Vinny

**Comment by Shelob9** [comment]
If you have not set the files to be uploaded to the media library, they will not be saved, by design:

https://calderaforms.com/doc/how-caldera-forms-file-attachments-uploads-work/

**Comment by Lednerb** [comment]
Just had the same issue.

It's important to check the `Add to Media Library` checkbox.

It's not very intuitive anyhow.
When a user creates a form with a file upload he expects to have access to this file (without reading the docs an figuring out what's going wrong...).

Maybe this get's refactored some day to have an storing of files out-of-the-box.


Thanks @Shelob9 for the hint!
