### ISSUE TITLE
Modal Forms not rendering on subsites of a WordPress Network

### ISSUE THREAD

**Issue by vinnycaldera** [CalderaWP/Caldera-Forms#1096]
When a form is set to modal on a sub-site it doesn't render.

Check: site base url on `jQuery.get()`

**Comment by chiareu** [comment]
Strange, I run a multisite network and forms was rendered on all subsites as modal perfectly until last update.
A problem appeared after Version 1.4.9 when the caldera CSS are not loaded in page when we are using modals.

**Comment by chiareu** [comment]
previous update – the modal fail to load the css
actual update – the modal are not working at all.

**Comment by Shelob9** [comment]
@chiareu I changed how modals work a ton in 1.5.0.4 can you try with latest changes on master?

Closing as related to funtioanlity removed in #1318

**Comment by chiareu** [comment]
Hi I just tested the release. The modal is working with standard WP theme :)
WordPress Version: 4.7.2 PHP Version: 5.6.29 MySQL Version: 5.6.35 Caldera Forms Version: 1.5.0.4

Still seams that there are some issues with DIVI Theme from Elegant Themes

**Comment by Luis-Goncalves-Searchprof** [comment]
@chiareu 
I'm having issues with the modal also, it doesnt show. Any hack or fix for this?
