### ISSUE TITLE
Alphabetical order get_pages

### ISSUE THREAD

**Issue by Q-style** [CalderaWP/Caldera-Forms#1097]
My developer and I tried everything to get this function to order the resulting pages alphabetically, but nothing seems to work. My developer thinks it's something that's hard-coded in the plugin that stops the function from getting it right.
Could you please confirm?
Thanks!
`
add_filter( 'caldera_forms_render_get_field', function( $field )  {
    if ( 'bouwonderdeel_pagina' == $field[ 'slug' ]  ) {
	    
	$args = array('exclude' => array(1360,101,701), 'post_type' => 'page', 'post_status' => 'publish', 'sort_order' => 'asc', 'sort_column' => 'post_title',); 
	    
	$pages = get_pages($args);

        if ( ! empty( $pages ) ) {
            foreach( $pages as $page ) {
                $field[ 'config' ][ 'option' ][ $page->ID ] = array(		                       
		    'value' => $page->post_title,
	            'label' => $page->post_title,                     
                );

            }
 
        }
    }

    return $field;
 
});
`

**Comment by vinnycaldera** [comment]
Greetings Q-style,

What is the expected result? Can you serialize and post here the `$field` variable?

Thanks.

**Comment by Shelob9** [comment]
Most likely the problem is that you are keying the array by post ID, try ` $field[ 'config' ][ 'option' ][ $page->ID ] = array(...` instead.

This is not a support channel, if you need help troubelshooting this, please open a support ticket at https://calderaforms.com/support
