### ISSUE TITLE
Conditions applied for value

### ISSUE THREAD

**Issue by lejardindeden** [CalderaWP/Caldera-Forms#1098]
Hi, 

Beginner with Caldera-Forms, by the way it's a really great plugin, I would like to use conditions on the values and not just on the fields. In my case for example, I have two drop-down list with different values for both and I want to show specific values for the second drop-down list depending on the value selected from the first drop-down list. 

I don't know if that is possible but it could really help me a lot. If not it could be great for a new update ;)

Thank you for your help.

**Comment by vinnycaldera** [comment]
Greetings lejardindeden!

Sorry, but this is not yet a feature of Caldera Forms. They are totally standard HTML form fields, so you could do this with JavaScript.
However, if you are unable to code, you can achieve a similar result creating multiple dropdowns for each options of your first dropdown. Then use conditions to show the field corresponding to the value. Take in mind that if you use it that way you can't set your second field to `required`.

Take Care,
Vincius Rezende
