### ISSUE TITLE
I received an error when try to register.

### ISSUE THREAD

**Issue by faisal-calderalabs** [CalderaWP/Caldera-Forms#1103]
I got the following error when try to register on the site by using cf-users add on.

**Catchable fatal error: Argument 1 passed to Caldera_Forms_Magic_Summary::should_use_label() must be of the type array, boolean given, called in E:\xampp\htdocs\calderaforms.dev\wp-content\plugins\Caldera-Forms-master\classes\magic\summary.php on line 106 and defined in E:\xampp\htdocs\calderaforms.dev\wp-content\plugins\Caldera-Forms-master\classes\magic\summary.php on line 175**

User was created successfully but getting the same error message on login unless reload the page.

- **Caldera Forms** version 1.4.7
- **Caldera Forms Users** add on version 1.3.7
- **WordPress** version 4.7
- **PHP** version 5.6.11
- **MySQL** version 5.6.25

**Comment by Shelob9** [comment]
close via 		7c85ef2
