### ISSUE TITLE
Post install banner add-on link is 404 :(

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1106]
I added a 301 redirect on site, but still

**Comment by andrewlimaza** [comment]
@Shelob9 you referring to -

`<img src="<?php echo CFCORE_URL; ?>/assets/images/new-icon.png"  class="caldera_forms-logo" style="width:80px;hieght:80px;"/>` and surrounding code?

**Comment by Shelob9** [comment]
Close via 25433cd
