### ISSUE TITLE
Hidden row 1px height.

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#1107]
Hi, is there a reason for the `min-height: 1px;` in the .col-sm, xs, lg etc.? Having a couple of fields that add up and create extra space.

**Comment by Shelob9** [comment]
@101010f To be honest, I don't know. That CSS is copied from Bootstrap. 

If you want to remove it, I think I'd be Ok with that. Feel free to submit a pull request against the 1.5.x branch.
