### ISSUE TITLE
Form unresponsive script warnings on front and back end

### ISSUE THREAD

**Issue by sm2239** [CalderaWP/Caldera-Forms#1108]
Hi guys, 

We have a multi page form, which has started to freeze and come up with unresponsive script warnings now on both the front and back end. It's quiet a long form with some basic calculations. 

Tested it with the default theme and all plugins disabled but still the same. Debug log shows there's an error in wp-includes/class-wp-hook.php. Wordpress version is 4.71. 

Any suggestions would be welcome. 

Thanks

**Comment by Shelob9** [comment]
@sm2239 I'm sorry you are having this issue. Can you please provide the error?

Also, please keep in mind if you need prompt support, you should use https://CalderaForms.com/support

**Comment by sm2239** [comment]
The previous error related to class-wp-hook.php has been fixed but unfortunately the form is still freezing up. 

The error shown is: 

"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
Script: ../wp-ad…lupload,zxcvbn-async&ver=4.7.1:2" 
and "Script:  …jquery-migrate.min.js?ver=1.4.1:2"

There's no new log in debug.
