### ISSUE TITLE
unregister caldera media_button in admin edit screen

### ISSUE THREAD

**Issue by jonakangou** [CalderaWP/Caldera-Forms#1122]
Is it possible to unregister caldera media_button in "function.php" like this 
`function remove_caldera_shortcode_button () {
    remove_action( 'media_buttons', array( kind of code here ), 12 );
}
$user = wp_get_current_user();
if ( in_array( 'author', (array) $user->roles ) ) {
    //The user has the "author" role
add_action( 'admin_init', 'remove_caldera_shortcode_button', 14 );
}`

if yes what is the code to put instead of "kind of code" ? Could be a good think to put this function on plugin parameter for non-developper user of caldera

**Comment by Shelob9** [comment]
@jonakangou Thanks for using Caldera Forms. Here is documentation about how to do this:
https://calderaforms.com/doc/remove-caldera-forms-shortcode-button-post-editor/

Please note, this is not the correct venue for support. If you need help implimenting this, please open a ticket at https://calderaforms.com/support
