### ISSUE TITLE
Bug Version 1.4.7 

### ISSUE THREAD

**Issue by TheGreenArrow** [CalderaWP/Caldera-Forms#1123]
Hello,

After last update Version 1.4.7, i found 2 bugs : 

- Confirmation message doesn't appear anymore (just a small loading icon that disappear quickly).
- The form is sent twice.

Please fix this bugs.

**Comment by Shelob9** [comment]
@TheGreenArrow Thanks for using Caldera Forms. This doesn't sound like a bug with Caldera Forms, as it's not a consistent problem. It sounds like a bug on your site. We'd be happy to help if you can provide more information, and open a support ticket, please read https://calderaforms.com/support
