### ISSUE TITLE
HTML tags showing in admin e-mail

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1129]
Hey

The form:
http://spirituellfilm.no/pamelding-til-film/

The admin e-mail shows HTML tags:

![screen shot 2017-01-19 at 18 27 09](https://cloud.githubusercontent.com/assets/5323259/22117625/fd6fe59e-de74-11e6-9523-e71abd08fc02.png)

CF version 1.4.8.

**Comment by Shelob9** [comment]
@paaljoachim What is your content type? Is it HTML or text? If text this is dupe of #1128 else new issue.

Is this autoresponder or email notifcation tab?

**Comment by paaljoachim** [comment]
These are regular CF fields. Not HTML fields. So yes this seems like a duplicate of the existing issue. I will close this one.
