### ISSUE TITLE
Phone number input mask

### ISSUE THREAD

**Issue by quadrochave** [CalderaWP/Caldera-Forms#113]
Custom mask for phone number works fine on the settings - back-end, but not on the front-end

**Comment by lmartins** [comment]
Im not sure if what @quadrochave reports is the same issue im seeing, but heres the problem im seeing.

On the Dashboard im inserting a custom mask like so:
![screenshot 2015-07-31 18 21 52](https://cloud.githubusercontent.com/assets/151981/9012993/0fab304a-37b1-11e5-9986-e7b1c502fa2e.png)

However, no matter what I do on the front-end it seems that it is always using the "Local" mask style:
![screenshot 2015-07-31 18 22 59](https://cloud.githubusercontent.com/assets/151981/9013011/2e40970c-37b1-11e5-862f-53b8d8b135c5.png)

Hopefully this helps to identify the problem, if any.

Cheers.

**Comment by maix4648** [comment]
I have same problem, backend everything is showing fine, but frontend show a default mask like as Local. This problem is only for element Phone number. 

My simple hack is change Phone number to Single line and setup mask 999-999-999. This solution is works fine for me.

**Comment by Desertsnowman** [comment]
I can confirm this issue.

**Comment by Shelob9** [comment]
@Desertsnowman Another issue here is that you cant add a space in masked inputs.

**Comment by Shelob9** [comment]
https://wordpress.org/support/topic/custom-input-mask-in-phone-field?replies=2#post-8610097

**Comment by Shelob9** [comment]
@Desertsnowman I'm putting this back on 1.3.6 as it is pretty easy, can punt, but would be good to fix.

**Comment by Desertsnowman** [comment]
closed via 9bf0482
