### ISSUE TITLE
BUG: Edit field doesn't appear when minified JS/CSS is loaded in admin

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1160]
V1.5 doesn't show edit field when clicking on edit, no errors thrown in console.

When unminified it works as expected.

**Comment by Shelob9** [comment]
@andrewlimaza Do you  have the change made in 5c1e1fe ? That should have fixed this.

**Comment by andrewlimaza** [comment]
@Shelob9 I updated to the latest 1.5.x from the repo and issue seems to be resolved.
