### ISSUE TITLE
BUG: Color Picker field shows up as text field

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1164]
Color Picker field shows up as text field

**Comment by andrewlimaza** [comment]
![color_pic](https://cloud.githubusercontent.com/assets/12629136/22339894/3e9ec8b2-e3f4-11e6-8333-4be21f5fec62.png)

Another bug, the color preview extends across whole container when minimized and restored in browser. Happens occasionally.

**Comment by Shelob9** [comment]
Need to load the core color picker, and initialize color picker fields.

**Comment by Shelob9** [comment]
Close 	ff88179

**Comment by 101010f** [comment]
Has this issue been fixed in 1.5.0? Still getting text color pickers on my side.
