### ISSUE TITLE
the dropdown menu has no arrows when displayed on page

### ISSUE THREAD

**Issue by andrewmartinmyanmar** [CalderaWP/Caldera-Forms#1168]
when displaying a dropdown select menu on the page there are no arrows to indicate that the field is a dropdown select field. How do we display the arrow for the dropdown menu. I tried using tt-styled-select but its not working in the custom class. By right it should be showing the arrow for dropdown lists
![issue 1](https://cloud.githubusercontent.com/assets/25361564/22324284/ccc5efc6-e3d6-11e6-877d-8ef38fc4857d.PNG)

**Comment by Shelob9** [comment]
@andrewmartinmyanmar Thanksf or using Caldera Forms. This is not a support channel. If you need prompt support please use https://calderaforms.com/support

We do add that arrow, your theme's CSS must be hiding it. If you need help identifying the conflicting CSS, please contact support.
