### ISSUE TITLE
BUG: Default value doesn't work

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1171]
The default value for a dropdown field doesn't work, it displays the last value in the options.

Temp solution is to set the last value to 'Choose an option' and select as default, but when you click on the drop down your positioning is at the bottom.

Here is the field settings -
![dropdown_backend](https://cloud.githubusercontent.com/assets/12629136/22375341/47a725da-e4b2-11e6-9a1a-c86571416c27.png)

Here is the front end -
![drop_down_frontend](https://cloud.githubusercontent.com/assets/12629136/22375366/67c35744-e4b2-11e6-8571-a729786b319c.png)

You can see that the last value is always selected on initial load.

**Comment by Shelob9** [comment]
@andrewlimaza I can't reproduce this. Can you retest with latest?

**Comment by andrewlimaza** [comment]
@shelob9 this works on latest version.
