### ISSUE TITLE
form not send

### ISSUE THREAD

**Issue by paulosurya** [CalderaWP/Caldera-Forms#1172]
Hi, I'm using the "caldera forms" in the free version. I'm loving using the "caldera forms".
But I'm having a recurring problem. The form simply stops working. When we identified the problem we already lost some contacts.
I solve the problem by simply entering the configuration and saving it again. But this is causing a terrible problem.
If I can not solve it, I'll have to take it easy to use Caldera Forms.
This problem is happening on several sites at the same time.
Help me

**Comment by Shelob9** [comment]
@paulosurya  Thanks for using Caldera Forms. I'm sorry you are having this issue on your site. This is is likely a conflict with something on your site, or your configuration.  We can walk you through the process of finding what that is and getting it resolved, if you open a support ticket at https://calderaforms.com/support and provide all of the requested information.

This is not a support channel, and I hope you understand that the service you are requesting is a paid service. I hope you will find that the low prices we charge for add-ons, which come with Caldera Forms support it worth supporting this free plugin you rely on.
