### ISSUE TITLE
HTML field not working

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1186]
Version 1.5-b-2

HTML form not rendering any HTML (i.e. `<h2>Some simple header</h2>`)

No errors in console. 

Not sure if this is site specific, PHP 5.5

**Comment by Shelob9** [comment]
@andrewlimaza Does it never render anything? IE if you don't use HTML, does that work?

**Comment by andrewlimaza** [comment]
@shelob9 yea even plain text not wrapped in any HTML tags doesn't show.

**Comment by andrewlimaza** [comment]
@Shelob9 the div for the HTML is outputting to the browser, just no data for it.

**Comment by andrewlimaza** [comment]
Update: issue seems to be with the sanitization.

**Comment by andrewlimaza** [comment]
@Shelob9 PR -> https://github.com/CalderaWP/Caldera-Forms/pull/1191

**Comment by Shelob9** [comment]
Close via  #1191
