### ISSUE TITLE
In some cases, preview link is wrong

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1187]

**Comment by Shelob9** [comment]
Actually two problems:

1) My form ID has a space at the beginning -- need to trim when creating. Possibly related to #1182
2) When checking ID on preview not trimming the ID.

**Comment by andrewlimaza** [comment]
This seems resolved with latest version @Shelob9 

Thoroughly testing this in the latest build of 1.5 to see if I can recreate this.

**Comment by Shelob9** [comment]
Close via 		05ea84c
