### ISSUE TITLE
TOOGLE SWITCH ERROR HTML

### ISSUE THREAD

**Issue by flaviomfrodrigues** [CalderaWP/Caldera-Forms#1194]
Hi,
I'm developing a form to set up a Gaming PC.
This desktop will have a basic version and a pro version. In this sense, i was using Toogle Swich, however when I click the basic or Pro button, I get this code HTML:

Code HTML:

<span class="caldera-forms-conditional-field" role="region" aria-live="polite" id="conditional_fld_6317068_1">

**/*

<label id="fld_6317068Label" for="fld_6317068_1" class="control-label">Processador</label><div class="">

<select id="fld_6317068_1" data-field="fld_6317068" class="form-control" name="fld_6317068" aria-labelledby="fld_6317068Label">
<option value=""></option>
<option value="1">1</option>
<option value="2">2</option>

</select>
</div>
**/*]]&gt;*/**
</span>

HTML ERRORS IN Browser view:
**/***Processador
Dropdown Select
**/*]]>*/** 

Is there any way to fix this error?
Alternatively and with Caldera Forms, how can I develop this type of form? 
Thanks,
Flávio
![error-caldera-forms](https://cloud.githubusercontent.com/assets/25464017/22521678/b6385954-e8b0-11e6-9c0f-8bcfccab4a18.jpg)

**Comment by Shelob9** [comment]
@flaviomfrodrigues Thanks for using Caldera Forms.

What version of Caldera Forms are you using?

Does this problem persist when you switch to default theme?

**Comment by flaviomfrodrigues** [comment]
Hi,
I tried changing the theme to Twenty Seventeen, but the problem keeps getting the same. Attached print.

The Caldera version is 1.4.8.

Is there any way to fix this bug or another way to build this kind of form with Caldera?

Thank you.
Flávio.
![error-caldera-forms_new theme](https://cloud.githubusercontent.com/assets/25464017/22546500/3a40d198-e935-11e6-83e7-eb9f979498e1.jpg)

**Comment by Shelob9** [comment]
Thanks for doing that test. I'm trying to understand what about your site could be causing this problem. Something is adding extra markup to your page and causing more layout issues then just this.

Did you try disabling your other plugins?

I know the screenshot of your console I can see you're hiding JavaScript errors. Are there any? What about network errors?

What host are you using? Have you tried testing on another server?

Are you using a CDN or WAF?

**Comment by flaviomfrodrigues** [comment]
Hi, 

No use CDN or WAF.

I desativate all plugins and the problem is with W3 Total Cache.
If i active this plugin in conditional toogle switch apperece this code HTML:

HTML ERRORS IN Browser view:
*/Processador
Dropdown Select
**/]]>/
Any tips to solve this incompatibility?

Thanks for Help.
Flávio.

**Comment by Shelob9** [comment]
@flaviomfrodrigues When using Caldera Forms with w3tc you need to put a cache exemption for the page with your forms or it will not work.

**Comment by flaviomfrodrigues** [comment]
Hi, 

Can you indicate a tutorial to do this? I do not know how to do.
Thanks.
Flávio.
