### ISSUE TITLE
Files are always attached in email

### ISSUE THREAD

**Issue by massemanseb** [CalderaWP/Caldera-Forms#1195]
Hello,
I have an issue with my form which using advanced file upload fields.
Whatever the value of the check box "Attach To Mailer", files are always attached to my email. Everything works perfectly but as files uploaded are too eavy for an email, the email can't be sent.

Thanks for your help.
(this issue was already raised by another user #1102)

Caldera form : V1.4.8
Wordpress : V4.7.4
PHP : V5.6.21

**Comment by Shelob9** [comment]
@massemanseb Thanks for the bug report and using Caldera Forms.

@andrewlimaza I am asigning this to you. Please test that saving/ attaching is working as described in the docs and report back.

**Comment by andrewlimaza** [comment]
@Shelob9 Yea files are attached even when 'Attach to Mailer' is deselected. All other features around the advanced uploader seem to work.

Tested on version 1.4.8

**Comment by Shelob9** [comment]
@andrewlimaza Please test now, on 1.4.x branch and confirm fix or send me an export that illustrates that fix is not a fix.

**Comment by andrewlimaza** [comment]
@shelob9 currently receiving the following JS error - 

![adv_file_error](https://cloud.githubusercontent.com/assets/12629136/22884340/2424a256-f1fd-11e6-80db-af1afdecde05.png)

I tested the non-advanced file upload and this is working in terms of not adding file to mailer when not selected + adding to media library.

However when the form is submitted, it does not redirect to the 'Form was successfully submitted' notification and does not show in anyway that the data was successfully sent.

**Comment by Shelob9** [comment]
This new error is becacuse filters are running out of order beacuse of change made in 9fd818dc8b0d3157ee1616414f903130b6ae2216 for #1221 cf_ajax_register_scripts() runs to late, and therefore the extra form attributes for AJAX submissions are now not running at `caldera_forms_render_form_attributes`

**Comment by andrewlimaza** [comment]
@Shelob9 this is a lot more stable with minor issues.

Here are the issues I've encountered -

* When editing an entry, no errors are shown when file upload size exceeds upload limit
* When editing an entry, file upload does not update


* Not a real issue, but if you have a multipage form and the upload field is not on the final page, you do not know if the files are uploading successfully or not.

**Comment by Shelob9** [comment]
@andrewlimaza Interesting, but these are new issues.

Can you make a new issue for your each of your first two points? We can address in 1.5.1

**Comment by Shelob9** [comment]
Close via 	35be0f3  #1223 and 	13eda03
