### ISSUE TITLE
Calculate age based in a capture of date of birth

### ISSUE THREAD

**Issue by Ensuprecio** [CalderaWP/Caldera-Forms#1201]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Ensuprecio** [comment]
Hi. I need calculate age of an user, based in capture of date of birth.
May you help me, please??
Thanks a lot.

**Comment by Shelob9** [comment]
@Ensuprecio Thanks for using Caldera Forms. This is not a feature of Caldera Forms calculation fields. If you need help finding a workaround, please open a support ticket at https://CalderaForms.com/support
