### ISSUE TITLE
Allow file upload limit

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1203]
## Is This A Feature Request?
Ability to set the file upload size within the edit field settings for File Upload/Advanced File Upload

**Comment by regiside** [comment]
Really surprised this isn't implemented yet. It's such a necessity for public uploads. Seems like it wouldn't take more than a couple hours to implement.

**Comment by Shelob9** [comment]
This feature is already completed for version 1.8

https://github.com/CalderaWP/Caldera-Forms/pull/2823

**Comment by Shelob9** [comment]
Closing as duplicate of #1399
