### ISSUE TITLE
Discontinued fields not showing in modal

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1204]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.4.8 / 1.5.x

## What Is The Unexpected Beahviour?
`define( 'CFCORE_SHOW_DISCONTINUED_FIELDS', true );` adds the discontinued menu item to the 'add field' modal but doesn't show any fields (totally blank).

It does show discontinued fields if you select 'Field Type' in field settings panel to the right when editing a field.

**Comment by Shelob9** [comment]
I'm closing this. Not worth the effort to support fields that are not needed anyway. pretty sure only field this affects is the psycosomatic recaptcha.
