### ISSUE TITLE
Two Percent Signs in HTML field causes non-display of field contents

### ISSUE THREAD

**Issue by qubez** [CalderaWP/Caldera-Forms#1206]
Software versions:
Caldera Forms 1.4.8; Wordpress 4.7.2; PHP 5.4;

Steps to reproduce:

- Make a new form or modify an existing one,
- Add a HTML field to your form,
- As the content, insert some normal text, wrapped in a `<p></p>` tag if you like,
- Insert shortcode on your page and see the form and your custom HTML displayed normally.

then

- modify your HTML content, inserting two separate % signs within the text,
- save and view your form,
- the entire contents of the HTML field is not displayed.

Percent sign should be valid HTML. Only using one % character, and it still works. Workaround: escaping the percent signs as `&#37;` seems to work, but should not be necessary.

edit: this seems to be related to theme's code mangling; using the Raw HTML plugin to insert the form shortcode seems to solve the particular problem.

**Comment by andrewlimaza** [comment]
Hi @qubez 

I have tried to recreate this issue but unable to do so.

For example I tried variations of the `%` placement in an HTML field in Caldera Forms.

For example here is some HTML code variations that I have tried -

`
%%

<h1>Some Text</h1>
`
 or
`
% 
<h1>Some Text %</h1>
`

This displays correctly all the time and shows the percentages except for the first example as this is indicating a magic tag (which is blank), but it still shows the H1 content?

Would you mind sending through some example HTML code that you are using so I may try and recreate this issue?

**Comment by qubez** [comment]
In a new "starter contact form" template, I simply set the description to:
_Let us % know % how to get back to you._
and the whole HTML block was not displayed in the page.

I will chalk this one up to a theme, which seems to have some weird reprocessing of its own. We'd hope that a theme couldn't mess with plugin HTML code, but the _insertion of br tag_ bug #1189 showed that they do. Indeed I fired up a site with Cyberchimps "responsive" theme (very basic) and couldn't replicate.

For example, in its theme-functions.php (I don't know if this is specifically what mucks Caldera's display):
```

/**
 * Disable Automatic Formatting on Posts
 * Thanks to TheBinaryPenguin (http://wordpress.org/support/topic/plugin-remove-wpautop-wptexturize-with-a-shortcode)
 */
function theme_formatter($content) {
	$new_content = '';
	$pattern_full = '{(\[raw\].*?\[/raw\])}is';
	$pattern_contents = '{\[raw\](.*?)\[/raw\]}is';
	$pieces = preg_split($pattern_full, $content, -1, PREG_SPLIT_DELIM_CAPTURE);
	
	foreach ($pieces as $piece) {
		if (preg_match($pattern_contents, $piece, $matches)) {
			$new_content .= $matches[1];
		} else {
			$new_content .= wptexturize(wpautop($piece));
		}
	}

	return $new_content;
}
remove_filter('the_content',	'wpautop');
remove_filter('the_content',	'wptexturize');

add_filter('the_content', 'theme_formatter', 99);

```

**Comment by Shelob9** [comment]
@qubez Unfortunately, what this theme is doing is going to prevent our field JavaScript for magic tags from working. Nothing we can do to support that. I would not recommend using a theme that removes WordPress' formatting like that.
