### ISSUE TITLE
Give an invalid html warning when user inserts invalid html.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1234]
I downloaded and made a local dev from a live site to test version 1.5 beta 2.

I added a HTML
Add text/html content field. Btw it should probably say text/html/shortcodes.

I installed Meta Slider. Made a few slides and inserted the shortcode into the HTML field.
Saved the form and previewed. The shortcode -> meta slider slides did not show up.

I tried with new and old form templates with the same result. I also tested another local site and the shortcodes are just not showing the slider.

**Comment by Shelob9** [comment]
@paaljoachim Can you please retest with latest. This should be fixed with #1186

That said, if your shortcode adds a form, script or iframe tag in 1.5.x it will not display. They never should have supported that.

**Comment by paaljoachim** [comment]
Testing now and will update this comment in a moment....

**Comment by paaljoachim** [comment]
One more thing.
Using `</br>` gives an error.  Using `<br>` works fine.

So I will close this issue.

**Comment by paaljoachim** [comment]
Give a warning saying invalid HTML below HTML text field.
