### ISSUE TITLE
Variables in Calculation field not saving

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1239]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.4.9 (This was also the case in 1.4.8)

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
The issue occurs when using a calculation field and a static variable. When adding an operational group using the builder.

This is still to be tested with a manual formula.

**Comment by Shelob9** [comment]
Possible duplicate: #882

**Comment by Shelob9** [comment]
Close via #3374
