### ISSUE TITLE
condition logic issue

### ISSUE THREAD

**Issue by aaryabhatt** [CalderaWP/Caldera-Forms#1252]
Hi,

I am new to wordpress and php and found very interested caldera forms plugin for forms, first of all thanks for creating this wonderful plugin. 

I am facing a issue regarding condition logic. I am creating a team registration form, in which i am trying to use 16 people in toggle switch, each people have 5 field (name, father's name, address, mobile, photo). I tried in sample with four people that time it worked, but when I try to use more than 4 people then listing of people start creating problems, like when I click on 4th than 2nd person form options did not come, or when I click on 9th or 10th then I shows only 1st and 9th or 10th. 

So I am not able to understand the condition logic which should I use for 16 people. I search a lot and see the video available, but could not find it. 

It would be very helpful if you could help me or direct me to accomplish this task.

wordpress version:- 4.7.2
php version is 5.6
OS- debian jessie
caldera forms Version 1.4.9.1 

--
Regards

Amit Bondwal

**Comment by Shelob9** [comment]
I'm glad you're using Caldera Forms. To be honest, this sort of thing is super hard to do with Caldera Forms. It's something I've wanted to create a better system for, I will prioritize it after 1.5.0 - #1253
