### ISSUE TITLE
New form processors for 1.5 not available

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1254]
The new form processors such as conditional email is not showing under processors.

I have taken a look @ the $form_processor array and they are not added to this array when displaying the processors.

**Comment by andrewlimaza** [comment]
Here is the PR (hope it's correct) -> https://github.com/CalderaWP/Caldera-Forms/pull/1255

**Comment by Shelob9** [comment]
Close via #1255
