### ISSUE TITLE
Duplicate Forms on Admin View

### ISSUE THREAD

**Issue by manoloxxl** [CalderaWP/Caldera-Forms#1259]
Related to:
https://wordpress.org/support/topic/duplicate-forms-on-admin-view/

Still same problem in 1.5.0

**Comment by Shelob9** [comment]
@manoloxxl  I'm sorry you're having this issue, some error must be happening during submission of the new form form.

 Can you please check for JavaScript errors using the JavaScript console and PHP errors, using PHP debug logging, that happen during form creation.

How to check your JavaScript console in any browser - http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
How to use the WordPress debug log to find hidden errors - https://calderaforms.com/2016/05/wordpress-debug-logging/

**Comment by manoloxxl** [comment]
Hi,

there are no JavaScript errors during creation.

So i duplicated the forms now, deleted the old ones and it seems to be okay now.

Thanks!
