### ISSUE TITLE
HTML fields strip accents, and do not support cyrilic (and other character sets?)

### ISSUE THREAD

**Issue by proweb** [CalderaWP/Caldera-Forms#1260]
### Short Debug Information

WordPress Version: 4.7.2PHP Version: 7.0.13-0ubuntu0.16.04.1MySQL Version: 5.7.17Caldera Forms Version: 1.5.0WP_DEBUG: 1
Full Debug Information
![_104](https://cloud.githubusercontent.com/assets/680073/23208966/3461a472-f908-11e6-852a-32696531955a.png)

WordPress Version: 4.7.2

PHP Version: 7.0.13-0ubuntu0.16.04.1

MySQL Version: 5.7.17

Server Software: Apache/2.4.18 (Ubuntu)

Your User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: dev_

WP Multisite Mode: No

WP Memory Limit: 128M

Currently Active Plugins:

Admin Menu Manager: 1.0.3
Caldera Forms: 1.5.0
Caldera Forms Translation: 1.0.7
Contact Form 7: 4.6.1
Cyr to Lat enhanced: 3.5
Duplicate Post: 3.1.2
Google XML Sitemaps: 4.0.8
Post Thumbnail Editor: 2.4.8
Query Monitor: 2.13.3
Regenerate Thumbnails: 2.2.6
Scalable Vector Graphics (SVG): 3.3
The SEO Framework: 2.8.2
Widgets Control: 1.5.0
WordPress Importer: 0.6.3
WP Remove Category Base: 1.0
ДСП-декоры (Custom post type): 1.0

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
NO

## What Is The Unexpected Beahviour?
Just Updated from 1.4.9 version.
All of my HTML-fields with Russian text in it now looks ugly.
It's must be  some unicode error. See my screenshot
Labels and fields values are OK, but text in HTML-field shows incorrect
![](http://storage2.static.itmages.com/i/17/0222/h_1487761489_2273402_19241b6d24.png)
 

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms and for reporting this issue. I will get it fixed in 1.5.0.1

**Comment by Shelob9** [comment]
close via 	0eeafa0
