### ISSUE TITLE
Entry viewer doesn't work with classic arg

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1269]
`I am using the shortcode to show entries on the front end...see shortcode,...[caldera_forms_entry_viewer id="CF58ad19ca5a6b" type="classic" with_toolbar="true"]...the entry viewer displays nothing. This worked in the Beta and RC versons. Was hoping you could point ne in the right direction.`

**Comment by Shelob9** [comment]
Close via 	78ab441

**Comment by grafixone** [comment]
Hi Josh. To add to this.  It also displays "You are not allowed to view this".  This error is also true for the default shortcode.. [caldera_forms_entry_viewer id="CF58ad19ca5a6b"].  Maybe this info helps.
Thanks Andre

**Comment by Shelob9** [comment]
Are you seeing this while logged in as an admin? If you're logged in with any other role,and have not settle role argument, as explained in the docs,this is the correct behavior.

**Comment by grafixone** [comment]
Hi Josh

Thought of using this email to update you
I updated to 1.5.0.2 via the repo and noticed the following..
when I add the shortcode in the Beaver Text module it only displays a 
"1" nothing more BUT when I add it in a post (no Beaver it displays 
correctly. Type="2" not classic.

cheers

**Comment by MalauryB** [comment]
Hello, I had the same problem. I solved it by transfer my page in https with a SSL.
