### ISSUE TITLE
version 1.5.0.1	contain some issue

### ISSUE THREAD

**Issue by ilyasx** [CalderaWP/Caldera-Forms#1279]
Hi, 

Recently, I have updated my plugin to 1.5.0.1 (svn). Afterwards, my web getting Error 500. I have deleted and reinstall my plugin back. It has a same issue.

**Comment by RedHippo** [comment]
Indeed I have exactly the same issue after updating this morning, an Error 500.

**Comment by shubaly** [comment]
Same problem here.

**Comment by Shelob9** [comment]
Yes, the 1.5.0.1 package from WordPress.org is very wrong, please use 1.5.0 or 1.5.0.2
