### ISSUE TITLE
while Caldera is activated, it cuts off HTML from loading

### ISSUE THREAD

**Issue by dingman** [CalderaWP/Caldera-Forms#1281]
After the most recent update, activating Caldera forms prevents the rest of my HTML from loading where I have the short code.

When I deactivate it, it works just fine.

**Comment by Shelob9** [comment]
We are having a problem with the updates, see: https://wordpress.org/support/topic/1-5-0-2-seriously-broken/#post-8839716 You will need to replace your Caldera Forms folder with what you can download here: https://github.com/CalderaWP/Caldera-Forms/archive/master.zip or rollback to your backup from before the upadate or use WP Rollback to go to 1.5.0 or 1.4.9

**Comment by dingman** [comment]
@Shelob9  can we wait until you've resolved the issues to upgrade straight through the dashboard? I used WP Rollback to get on 1.4.9 and it's working fine for me right now
