### ISSUE TITLE
Cloning doesn’t copy mailer settings

### ISSUE THREAD

**Issue by Drahnoel** [CalderaWP/Caldera-Forms#1282]
Hey. I´m working on a quite large site which will finally include about 150 forms that are similar. Everything is working well, but there is one reallly akward thing happening. when i clone my master form only the layout is cloned and mailer settings are not!
What´s happening here?? 
Please help!!

**Comment by LeslieM1019** [comment]
+1 this. When cloning a form, Form Settings and Email settings do not clone and it reverts to default values. Running into this challenge as well.

**Comment by Shelob9** [comment]
This will be fixed in 1.7.3 (need to rebased 5fe42b8 into develop if #2692 is merged for 1.8 not 1.7)

**Comment by Shelob9** [comment]
close via 0877442
