### ISSUE TITLE
After updating to Caldera Forms 1.5.0.2, form entries are no more shown

### ISSUE THREAD

**Issue by Maurillo1960** [CalderaWP/Caldera-Forms#1287]
Short Debug Information
WordPress Version: 4.7.2PHP Version: 5.6.30-0+deb8u1MySQL Version: 5.6.35Caldera Forms Version: 1.5.0.2WP_DEBUG:

Issue
After updating to Caldera Forms 1.5.0.2, form entries are no more shown

when i click to "Entries" in every form
wp-baldrick-full.min.js?ver=1.5.0.2:2 Uncaught a {description: undefined, fileName: undefined, lineNumber: undefined, message: "You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined", name: "Error"…}
f @ wp-baldrick-full.min.js?ver=1.5.0.2:2
a.compile @ wp-baldrick-full.min.js?ver=1.5.0.2:2
filter @ wp-baldrick-full.min.js?ver=1.5.0.2:3
c @ wp-baldrick-full.min.js?ver=1.5.0.2:2
success @ wp-baldrick-full.min.js?ver=1.5.0.2:3
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp…:2
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp…:2
y @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp…:4
c @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp…:4

**Comment by Shelob9** [comment]
@Maurillo1960  this was a problem with the 1.5.0.2 package on WordPress.org, please update to 1.5.0.3 or re-install from Github.
