### ISSUE TITLE
[Feature] Duplicate Field/ Row/ Group

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#129]
So let's say @Shelob9 was making a form with a ton of repetitive field. Wouldn't it be awesome if he could make that field once and then duplicate it five times, change the name in each and be done? Yes, it would be awesome.

**Comment by Desertsnowman** [comment]
working on it! ( hence all the array issues you're seeing )

**Comment by paaljoachim** [comment]
Very cool!

**Comment by osalcedo** [comment]
+1 :)

**Comment by paaljoachim** [comment]
Having a small duplicate icon in the field row would be good.

**Comment by paaljoachim** [comment]
A suggestion by adding a duplicate icon to the layout field, and adding up and down arrow to select to move a field by either dragging or using the arrow keys.

![caldera-forms-field-duplicate-move-row](https://cloud.githubusercontent.com/assets/5323259/11915628/2e8d48dc-a6af-11e5-9cd4-d06a5817a9e5.jpg)

**Comment by brandbrilliance** [comment]
+1

**Comment by dwithnall** [comment]
+1

**Comment by Desertsnowman** [comment]
closed via 77dc73b
