### ISSUE TITLE
URGENT: Caldera Forms Not Working With Latest Version of Wordpress

### ISSUE THREAD

**Issue by npsdesign** [CalderaWP/Caldera-Forms#1290]
Fatal error: Class 'Caldera_Forms_Sync_Factory' not found in /home/npsa09611/public_html/wp-content/plugins/caldera-forms/classes/field/input.php on line 33

WP:  WordPress 4.7.2 running Avada theme.

**Comment by npsdesign** [comment]
Warning: include(/home/content/98/3609498/html/mypushnotification/wp-content/plugins/caldera-forms/ui/entries/viewer.php): failed to open stream: No such file or directory in /home/content/98/3609498/html/mypushnotification/wp-content/plugins/caldera-forms/classes/entry/viewer.php on line 25

Warning: include(): Failed opening '/home/content/98/3609498/html/mypushnotification/wp-content/plugins/caldera-forms/ui/entries/viewer.php' for inclusion (include_path='.:/usr/local/php5_4/lib/php') in /home/content/98/3609498/html/mypushnotification/wp-content/plugins/caldera-forms/classes/entry/viewer.php on line 25

Was able to get into my WP, I've got this error in the Caldera Forms Plugin. 

Please assist urgently as one of our clients uses this form with one of our mobile apps.

**Comment by Shelob9** [comment]
I'm sorry but the WordPress.org package is wrong. We are working to get a new version done, but have to test it very thoroughly now.

You can use the download link on GitHub to get the correct version, or use the plugin WP Rollback to rollback to 1.4.9
