### ISSUE TITLE
After updating to 1.5.0.3, hidden labels disappear still

### ISSUE THREAD

**Issue by dingman** [CalderaWP/Caldera-Forms#1291]
When I upgraded from 1.4.9.1 to 1.5.0.3, the hidden labels that were inline of the input disappeared.

Rolling back to 1.4.9.1 they show up as expected

https://www.screencast.com/t/hcp2BI6Qs

**Comment by Shelob9** [comment]
@dingman I do not see this with TwentySeventeen, I suspect that this is a theme conflict -- IE your theme is loading CSS before Caldera Forms does. I would recommend checking on your staging site if this happens with the default theme and 1.5.0.3. If that resolves the issue, turn back on your theme, and then check to make sure that your theme styles load after `caldera-forms-front.min.css`

**Comment by dingman** [comment]
This has been resolved with 1.5.04.

Thank you!!
