### ISSUE TITLE
Auto responder mail is sending in plain text instead of HTML

### ISSUE THREAD

**Issue by Serhansolo** [CalderaWP/Caldera-Forms#1292]
**Version:** 1.5.0 and newer
**Problem:**
When the autoresponder processor is used it only sends a plain text format email. While the previous versions (1.4.x and lower) send the mail in HTML format.

**Comment by Shelob9** [comment]
@Serhansolo I can not reproduce this. I am seeing a `Content-Type: text/html; charset=UTF-8` header on emails sent from the auto-responder and I'm also seeing that in `wp_mail()` the value `text/html` is passed on line 419 ( `$phpmailer->ContentType = $content_type;`)

Are you using WordPress emails or a third-party service?

**Comment by dcitelecom** [comment]
We have the same problem with Caldera 1.7.6 and Autoresponder emails so this never got resolved. 
We use the SENDGRID API option for emails.

**Comment by snowbird-SC** [comment]
I am having the same problem.

## What Is The Unexpected Behaviour?
The autoresponder message does not show, for example, the bold tags applied. More importantly, there are no line breaks making the email unreadable.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?

Short Debug Information

    WordPress Version: 5.0.3PHP Version: 7.0.32MySQL Version: 5.6.34Caldera Forms Version: 1.7.6WP_DEBUG: 

Full Debug Information

WordPress Version: 5.0.3

PHP Version: 7.0.32

MySQL Version: 5.6.34

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    Redis: No

Object Cache:

    Apc: No
    Apcu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wp_hb97u4

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: Sparkling: 2.4.4

Plugins:

    Akismet Anti-Spam: 4.1 Active
    Atomic Blocks - Gutenberg Blocks Collection: 1.4.22 Not Active
    Caldera Forms: 1.7.6 Active
    Contact Form Builder for WordPress – Conversion Tools by HubSpot: 7.0.1 Not Active
    Duplicate Post: 3.2.2 Active
    Enable Media Replace: 3.2.7 Active
    Google Analytics Dashboard for WP (GADWP): 5.3.7 Active
    Hello Dolly: 1.7.1 Not Active
    Jetpack by WordPress.com: 6.9 Active
    Stackable - Gutenberg Blocks: 1.10 Active
    UpdraftPlus - Backup/Restore: 1.16.0 Active
    W3 Total Cache: 0.9.7 Active
    WP Dashboard Notes: 1.0.9 Active
    WP Mail SMTP: 1.4.1 Active
    Yoast SEO: 9.4 Active

**Comment by Bonitto** [comment]
I am also having this problem when I try to add img tags to my autoresponder it does not send.

WordPress Version: 5.2
PHP Version: 7.2.16
MySQL Version: 5.7.23
Caldera Forms Version: 1.8.4

**Comment by madpipe** [comment]
Love how bugs get marked resolved just because someone says "it worked for me". That's a fail.

**Comment by kazdal** [comment]
**Version:** 1.9.1 or newer
**Issue:** Autoresponder is sending plain text emails instead of HTML. Even if I add HTML tags like <br> or <p>, those are ignored. 
**Additional info:** Tried using SMTP or SendGrid, result didn't change.

This issue is marked as closed but it is **still there**.

**Comment by Teico88** [comment]
I also have this problem and I'm using Sendgrid. Added html tags are not visible in the email. Sending with the WP phpmail will fix this issue, but this isn't the solution I'm looking for...

**Comment by kazdal** [comment]
> I also have this problem and I'm using Sendgrid. Added html tags are not visible in the email. Sending with the WP phpmail will fix this issue, but this isn't the solution I'm looking for...

PHP Mail is not an option for me, and it should not be. If the plugin says it works with SendGrid, it should be working.
