### ISSUE TITLE
Feature Request List

### ISSUE THREAD

**Issue by tripflex** [CalderaWP/Caldera-Forms#13]
David, here's a few features that stand out to me while testing that would be beneficial to have.  I made two lists, one for things I think would be major improvements and minor.  If these are already available let me know as this is a list just from first glance.

Major features:
- [x] Ability to auto populate fields from custom meta or through function/filte, etc. Sort of like how GF you can put `{user.first_name}` to populate with user's first name if that meta key exists and the user is logged in, that way they dont have to type it
- [x] HTML editor for autoresponder emails
- [x] Allow using magic tags `%user_email%` in email fields (ie From Name, From Email) so you can set the email from name as the users name, or from email as users email.
- [x] User details processor (to create form for updating user details, password, etc)
- [x] Custom fields processor (to update custom post types, or fields, etc)
- [ ] Code editor in HTML field window

Minor features:
- [ ] Ability to use really simple captcha instead of google captcha
- [x] Use default from name and from email for auto responder
- [x] Show available variables to use in email, or small message that says how you can add template vars to email (from field, etc)
- [x] All fields magic tag to output default list in email of all fields submitted
- [ ] Show shortcode in form list on page

**Comment by bonnysitesdotcom** [comment]
This plugin seems to be what I really need! The only thing is, I cannot find any instructions on how to use it or explanation of what all the features do. Even the demos that are listed on the documentation pages are incomplete..

What I need to do is create a form to update entries to a custom post types from the front end, which is what I thought I could do with a form, only I cannot figure out how to do it, only to add entries, but not edit them.

Thanks for all your hard work!

**Comment by zoomwebstudio** [comment]
Hello!

I think the limiter field is already available for Caldera Forms. You may
find it on CalderaWP official site :
https://calderawp.com/downloads/caldera-forms-entry-limiter/

Check it out!

Cordialement et avec mes salutations distinguées
K. Adevou Fera N. EKPEH
------------------------------


Phone: +228 92 14 65 91
Skype: adevou
------------------------------
Behance: http://www.behance.net/adevouferaekpeh
LinkedIn: https://www.linkedin.com/in/adevoufera
Twitter: https://www.twitter.com/adevlordfera

"Believe! Life means possibilities. Focus only on creativity"


2015-04-10 21:01 GMT+00:00 bonnysitesdotcom <notifications@github.com>:

**Comment by bonnysitesdotcom** [comment]
I am not looking for an entry limiter, I need to make a form that allows a
user to edit entries from the website, not the admin area. Thanks.

On Sat, Apr 11, 2015 at 4:43 AM, Adevou Fera EKPEH <notifications@github.com

**Comment by zoomwebstudio** [comment]
Hi Desertsnowman/Calder,

I'd like to add you to my professional network on LinkedIn.

- Adevou Fera K. N.

Confirm that you know Adevou Fera K. N.: https://www.linkedin.com/e/v2?e=0-iocjz3aw-5j&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=VgS2ctxX&invitationId=6138602316590301184








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iocjz3aw-5j&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQE3mHfU6bWufgAAAVTCya334t5TBcrvK_DwlsTasJTE5JQjmBxSSUGR7cES6NtDCU-wNwTKFZwcgfrjbELVRbElqZ_qjEP-4x9JfM3yJ0n7hSAjRfK57001vsoVDLUfhWTg8pNkjHu6VZlv-IlTLPnSWSzAZTSButnEuo6vfyeIEplO59A7mDte2JAmDLWBlJ3J&eid=0-iocjz3aw-5j


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iocjz3aw-5j&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zoomwebstudio** [comment]
Adevou Fera K. N. EKPEH would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-stf3rb-iomlqm8w-ep&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=VgS2ctxX&invitationId=6138602316590301184

View Adevou Fera K. N. EKPEH&#39;s profile: https://www.linkedin.com/e/v2?e=-stf3rb-iomlqm8w-ep&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=VgS2ctxX&invitationId=6138602316590301184

Desertsnowman/Calder,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-stf3rb-iomlqm8w-ep&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-stf3rb-iomlqm8w-ep&loid=AQHba9wkTJNtlwAAAVToODGdez7eoCOvy06aQ-Pgm18WFCr1sQRdZoYNP118R-fJLwkzVUWmJZG-vRRPn_sICiaytWU7Mu5LnbseTWP7Qa5up8F6z858VA_-GUOn43SizGA03bp5Z9VyBEgjp0VsXDlrl0Em3BVxHbbdLrGcsAM721KfHNAnA_OGUc9DTRsM5qw7

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-stf3rb-iomlqm8w-ep&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Desertsnowman** [comment]
@zoomwebstudio - don't know why you posting linkedin links, but please try not too. It's not a network I actively use.

**Comment by zoomwebstudio** [comment]
Adevou Fera K. N. EKPEH would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=VgS2ctxX&invitationId=6138602316590301184&trk=eml-second_guest_reminder_01-hero-13-accept_text&trkEmail=eml-second_guest_reminder_01-hero-13-accept_text-null-%7Estf3rb%7Eiowujv8h%7Eiv

View Adevou Fera K. N. EKPEH&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=VgS2ctxX&invitationId=6138602316590301184&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Estf3rb%7Eiowujv8h%7Eiv

Desertsnowman/Calder,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-stf3rb-iowujv8h-iv&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-stf3rb-iowujv8h-iv&loid=AQGz4ONfi-PDSgAAAVUMtJ_djRDoWbQF9F6htSL-FuKuRpjiDVnWdwXEdIFxLnIqWZcoTYaZsYoAiBykMyIn8_jt43AbB3ROIqSpdB1AvYU2EGKvHl4DUaYN10w1iHMW3q2v3Lk94yCU1Lqvk0nCLoyo__S_q5cP0-J0eWXK-YkkGQjc9bnGIPWVHp87trk0Rw7Y

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-stf3rb-iowujv8h-iv&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
