### ISSUE TITLE
Forms not displaying form name content when titles hidden

### ISSUE THREAD

**Issue by cliqade** [CalderaWP/Caldera-Forms#1310]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.5.0.3

*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

WordPress Version: 4.7.2PHP Version: 5.6.22MySQL Version: 5.7.16Caldera Forms Version: 1.5.0.3WP_DEBUG:

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?

Nope. All plugins/themes switched off, but problem still persists.

## What Is The Unexpected Beahviour?

Before a recent update of the plugin, all forms were displaying their relevant field names in the field boxes (i.e. A field called 'Your Full Name', would add the text in the field box when show titles was set to hidden). But now, this is no longer displaying and the boxes remain empty.

## What PHP Errors Have You Logged While Reproducing This Bug?
Warning: file_exists(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP? in /var/sites/c/cliqifyskills.co.uk/public_html/wp-content/plugins/caldera-forms/classes/support.php on line 161

Warning: is_writable(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP? in /var/sites/c/cliqifyskills.co.uk/public_html/wp-content/plugins/caldera-forms/classes/support.php on line 162

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Uncaught TypeError: Cannot read property 'click' of null
    at (index):147
(anonymous) @ (index):147

**Comment by Shelob9** [comment]
@cliqade Thanks for the detailed bug report.


Close via 		d1283fb and	6f9186e
