### ISSUE TITLE
Scroll To Top On Submit doesn't scroll

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1316]
Here is a very long order form in Norwegian:
http://celias.no/bestilling/

In Form settings
I enabled: 
When form is submitted, scroll page to form message.

Filled out the form and expected the page to auto scroll up to the auto response message but it did not. I am using the latest update of WP and CF. Using Chrome. It is an existing form as in not newly created.

**Comment by Shelob9** [comment]
Close via 	038f511

**Comment by paaljoachim** [comment]
That was a quick fix Josh..:)
Awesome!
