### ISSUE TITLE
Edit entry issue: Text Area shows blank once editing data

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1327]
Entries correctly capturing data - however when you start to edit the entries the textarea shows up as empty even though in the view entry it had data.

Tested on version 1.5.0.4

**Comment by Vrhovc** [comment]
I have observed this issue also..
I populate form with caldera_forms_render_pre_get_entry filter, and all of the other fields get populated as they should, only textarea field does not, it stays empty. Checking the returned variable has value as it should.

**Comment by Shelob9** [comment]
Close via #1413
