### ISSUE TITLE
Field validation from remote json

### ISSUE THREAD

**Issue by Minisiteku** [CalderaWP/Caldera-Forms#1335]
Hi all.. i need help or tutorial how to validate field from remote json api..?
basically i have json url like hxxps://xxxxxx.xxx/myapi/file.json
json return with {"error": "Something went wrong"} if field not valid and {"user": {"requested...... } if valid.
try implementing like gravatar function.. after input email automatically show user image but not sure where they function. try searching on caldera website not found any tutorial about this.
thanks and sorry my bad english..

**Comment by Shelob9** [comment]
@Minisiteku  Thanks for using Caldera Forms. 

We have this tutorial on custom validation processors: https://calderaforms.com/doc/creating-custom-validation-processor-caldera-forms/

If you need help implementing this, please open a support request at https://CalderaForms.com/support
