### ISSUE TITLE
1.5.0.4 conditionals don't work

### ISSUE THREAD

**Issue by sportsnapper** [CalderaWP/Caldera-Forms#1337]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.2PHP Version: 5.6.30-0+deb8u1MySQL Version: 5.5.53Caldera Forms Version: 1.5.0.4WP_DEBUG: 1
## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes
## What Is The Unexpected Beahviour?
Conditionals just don't work eg yes no text in attached form
[conditional-test-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/813412/conditional-test-export.json.zip)
Existing forms don't work either

## What PHP Errors Have You Logged While Reproducing This Bug?
None shown

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none shown

**Comment by andrewlimaza** [comment]
I have tested your form export on my local environment and the condition is working as expected. I will create and test other edge cases to see if there are any issues with conditionals.

Here is a screenshot for reference - 

![say_something_test](https://cloud.githubusercontent.com/assets/12629136/23507122/32680cfe-ff54-11e6-9b1e-98a673625a54.png)

**Comment by sportsnapper** [comment]
My error - clash with autoptimise plugin
