### ISSUE TITLE
Parsley local language not showing on page

### ISSUE THREAD

**Issue by freveree** [CalderaWP/Caldera-Forms#1338]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.2PHP Version: 5.5.38MySQL Version: 5.7.12Caldera Forms Version: 1.5.0.4WP_DEBUG:

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
Local Parsley language doesn't show up on webpage. It's still in English, even though Wordpress is set in another language. The js with the translation is loaded in the source code (for example nl.js for Dutch)

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by netbussy** [comment]
Same problem here! 

WordPress Version: 4.7.2
PHP Version: 5.6.29
MySQL Version: 5.0.11
Caldera Forms Version: 1.5.0.4

**Comment by Shelob9** [comment]
Close via 	61b91da and 	ed01a1d

**Comment by Shelob9** [comment]
BTW workaround in 1.5.0.4 is adding this to functions.php or whatever:
`add_filter( 'caldera_forms_render_assets_minify', '__return_false' );`
