### ISSUE TITLE
Slug and label problem.

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#1341]
1.5.4 - XD. The slug + label appears on every field even if 'hide label' is ticked.

**Comment by Shelob9** [comment]
Correct. In 1.4.x and previous it didn't output a label element which is really bad for useablity and accessibility. Inputs without labels are terrible for those using screen readers.

So when I fixed the bug that wasn't adding the automatic placeholders, I also made is the label was outputted with .screen-reader-text class and added that CSS (#1314) which is how WordPress core handles this. Your theme must have a conflict causing that screen reader text label to show on the page.

You might need to apply your own .screen-reader-text rules to match your theme or switch to a theme that takes into account accessibility issues. 

https://make.wordpress.org/accessibility/2015/02/09/hiding-text-for-screen-readers-with-wordpress-core/
