### ISSUE TITLE
Form no longer displayed after updating to 1.5.0.4

### ISSUE THREAD

**Issue by tomygrenier** [CalderaWP/Caldera-Forms#1342]
Hi,
Since I updated to Caldera Forms 1.5.0.4, my forms aren't generated in HTML 
as if there was no shortcode added. Even if I copy and paste the shortcode from form itself in admin panel.

When I try to insert a form with the button in page edit mode, console shows this error : Uncaught TypeError: Cannot read property 'addMessages' of undefined  at fr.js?ver=1.5.0.4:3 (anonymous) @ fr.js?ver=1.5.0.4:3

And this warning : Accessing the method 'addValidator' through ParsleyValidator is deprecated. Simply call 'window.Parsley.addValidator(...)

Here's my short debug line : WordPress Version: 4.7.2PHP Version: 5.5.36MySQL Version: 5.7.9Caldera Forms Version: 1.5.0.4WP_DEBUG: 1

Any ideas what is going wrong?
Thanks,
Tomy

**Comment by Shelob9** [comment]
This is actually the same issue fixed in #1338

In 1.5.0.4 workaround is
`add_filter( 'caldera_forms_render_assets_minify', '__return_false' );`

**Comment by tomygrenier** [comment]
It works for langage issue on front-end. But not on admin panel.

And forms still don't show up without error in console or in PHP. 
Regardless of which method I use : button insert, do_shortcode, or php class.
