### ISSUE TITLE
Star rating fields don't have a default setting or respect default when rendered

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1345]
https://wordpress.org/support/topic/star-ratings-defaulting-to-2-stars/#post-8868429 - reported here, not replicated by me sorry

**Comment by beachgrrrl** [comment]
Having the same problem - WordPress 4.7.3, Caldera 1.5.0.6

**Comment by Shelob9** [comment]
Closing as dupe of #1520 - even though that's backwards, but that one has a PR.
