### ISSUE TITLE
%slug:label% doesn't show label.

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1347]
%slug:label% does not print out label for the slug field.

Tried displaying the %slug:label% inside any field returns blank - no errors.

**Comment by Shelob9** [comment]
@andrewlimaza Where are you using this magic tag? As a field default value, or in email notification, etc?

**Comment by Shelob9** [comment]
@andrewlimaza If it works in email, close this as not supported and edit magic tag docs to make that clear.

**Comment by andrewlimaza** [comment]
@Shelob9 this doesn't work. I added in %slug:label% to the email settings under 'Email Subject' and Email Message.

When using %slug:label% in email message it returns the value of that slug.

**Comment by Shelob9** [comment]
Close via 		0310bf0
