### ISSUE TITLE
Range Slider not saving

### ISSUE THREAD

**Issue by keeslina** [CalderaWP/Caldera-Forms#1361]
Hello,

Since I've installed the latest update of the plugin ( 1.5.0.4 ) , the range sliders are working like the should.
The input is not being saved. All my sliders are saved to ' 1 ' (default range), even though I slide to another value.

Kees

**Comment by shawnhooper** [comment]
@Shelob9 I just built a form with this slider using 1.5.0.6, and can confirm the correct values are being stored in the database.

**Comment by keeslina** [comment]
Thanks a lot !!

Op 21 mrt. 2017 6:20 p.m. schreef "Shawn Hooper" <notifications@github.com>:

**Comment by Shelob9** [comment]
@keeslina   Can you check against 1.5.0.6 please? This is working fine for me to. If it's a problem for you, it could be a site-specific error.

**Comment by keeslina** [comment]
Hi Josh,

I just found out the problem is still there.
Maybe it has something to do with multipage form?

See : http://wijzon.nl/zonnestroom-adviestraject/

The slides are on step 2. When you proceed to step 3 and than back to step
2, you can see the sliders are reset to position 1.
This is also the value that is stored when you finish the whole form and
send.


2017-03-21 19:23 GMT+01:00 Josh Pollock <notifications@github.com>:

**Comment by Marc-Moeller** [comment]
I can confirm that the issue is still there.
It has something to do with multipage form.
I created a multi page form and on the same page a single page form.

The multipage form does not send the range value via email (it sends the minimum, always)
The single page range slider works fine.

**Comment by keeslina** [comment]
Any news on this ?

**Comment by Shelob9** [comment]
Page change resets value, and only last page's slider gets sent.  Probably beacuse of 		9e08846 

Related #1230

**Comment by Shelob9** [comment]
6f0ccc0 makes them save, but back navigation is still wrong, so close beacuse they save now, but opening #1458 beacuse that is bad.
