### ISSUE TITLE
disables divi page editor

### ISSUE THREAD

**Issue by catxnc** [CalderaWP/Caldera-Forms#1363]
hello. fyi your plugin disables elegant theme's divi theme page editor on chrome browser. can you get with elegant themes and fix? I like using chrome to edit pages and I have a lot of divi sites. thanks.

**Comment by andrewlimaza** [comment]
Hey there,

Thanks for opening an issue regarding this.

We'd love to help but will need a bit more information.

Would you mind telling me the following:

What version of Divi, Divi Builder, Caldera Forms and WordPress are you currently using?

If you disable Caldera Forms does the Divi Builder work as expected?

If you could please log errors using the method described in this post -- https://calderaforms.com/2016/05/wordpress-debug-logging/ -- and show us the errors you found, then we could help you solve the issue causing this.

**Comment by catxnc** [comment]
howdy.  updating both divi and caldera forms, then clearing my browser cache did the trick – working again!

 

thanks!

 

John Hill

 <http://www.hil-tec.com/> HIL-TEC – Responsive Wordpress Websites
Oak Ridge, NC

336-508-4113

**Comment by andrewlimaza** [comment]
Glad to hear that it's working as expected! 

Please feel free to open a support thread on www.calderaforms.com should you require any further assistance.
