### ISSUE TITLE
Caldera form no longer displaying correctly

### ISSUE THREAD

**Issue by ClaireAPS** [CalderaWP/Caldera-Forms#1364]
Our forms are not displaying correctly and as a result customers are no longer able to complete them.

These forms were displaying correctly recently (approx 1 week) and no changes have been made to the forms or other plugins since:

![image](https://cloud.githubusercontent.com/assets/26250376/23657399/cce2f7be-0335-11e7-976c-8c57a6efe0ea.png)

Customers can't see the star ratings and customers can't select yes or no

Running Caldera 1.5.0.5

https://nirvanaspa.co.uk/feedback-form/

**Comment by Shelob9** [comment]
I am closing this as there is a open support request, and that's the correct venue for this.
