### ISSUE TITLE
calc value wrong from hidden fields in email summary + email summary format is off from 2 weeks ago... 

### ISSUE THREAD

**Issue by safewatch360** [CalderaWP/Caldera-Forms#1368]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
CF - Version 1.5.0.5
WP - 4.7.3
PHP - 7.0.12

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes, only running this plugin, and theme 2012.  

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.
I have a form since 0.x of CF.  I've enhanced it etc over time, but it has always performed well.  The {summary} email has been used to capture the info from the form.   Since a few releases ago, the summary started throwing in hidden fields used mostly for calculations.  

Product Type: Verizon Micro GPS - $169.95 Product Qty: 1
2GOBDprice: 69.95
2GHWprice: 59.95
2Gmicroprice: 139.95
VCprice: 169.95
regplan: 19.95
basicplan: 26.95
advplan: 32.95
proplan: 39.95
3GMprice: 169.95
30plan: 24.95
3GOBDprice: 159.95
3GHWprice: 169.95
3G OBD BupB Price: 179.95
counter: 13654
ltdactfee: 9.95
actfee: 9.95
sctax: 1.06
Select Your Service Plan: 10sec PRO PLAN @ $39.95/month
calc: 1434.20
SCttl: 1519.06
dollar_ysplit: 24.95
dollar_starter: 9.95
extbatt22: Extended Battery Kit with Case - $149.95
extbattqty22: 1
dollar_extbatt: 149.95
dollar_slim: 129.95
dollar_magcase: 29.95
dollar_magbox: 24.95
dollar_carchgr: 19.95

The totals are off.  They used to be accurate.  They are correct in the UI though.  
Above is an order for 2 products.  This is what it should look like.  

This is from 2/21/2017 where it was functioning properly.  Although the formatting was off for some reason that I could never figure out.  There was some release prior to this that caused the html tags to get thrown into the body of the email. 

<p>Product Type: Verizon Micro GPS - $139.95<br /> Product Qty: 1<br />
VCprice: 139.95<br />
proplan: 39.95<br />
actfee: 9.95<br />
sctax: 1.06<br />
Select Your Service Plan: 10sec PRO PLAN @ $39.95/month<br />
calc: 339.80<br />
extbatt22: Extended Battery Kit with Case - $149.95<br />
extbattqty22: 1<br />
dollar_extbatt: 149.95<br />

This is much easier to tell what's what!

email me if you need me to send you json file or anything.  

thanks, Brian

**Comment by Shelob9** [comment]
@safewatch360 Thanks for the bug report.

You didn't answer the question about errors. This is pretty essential. If you can please do PHP debug logging as the issue template describes and share what you found, that would be really helpful in understanding what the problem might be.

**Comment by safewatch360** [comment]
Not sure what errors to log on this to be honest.  Just let me know if you want me to try and catch logs.

**Comment by Shelob9** [comment]
@safewatch360  If you can take the steps that are suggested here, to help identify errors, that would be very helpful https://calderaforms.com/2016/05/wordpress-debug-logging/

**Comment by safewatch360** [comment]
Ok, I modified per recommendation.  I think filled out my form and submitted, 2 separate occasions.  I have no debug.log file however.  I’ve checked the entire subdirectory installation.  

 

 

/**

* For developers: WordPress debugging mode.

*

* Change this to true to enable the display of notices during development.

* It is strongly recommended that plugin and theme developers use WP_DEBUG

* in their development environments.

* define('WP_DEBUG', false);

*/

define('WP_DEBUG', true);

define('WP_DEBUG_DISPLAY', false);

define('WP_DEBUG_LOG', true);

 

 

Visit the site here if needed.  

 

https://order.safewatch360.com

https://shop.safewatch360.com 

 

Similar forms, just pricing is different.  

 

Let me know how else I can help you catch this.

**Comment by safewatch360** [comment]
@Shelob9 
I just rolled back to 1.4.8 and email summary is good, except for those html tags.  Only sends what was selected and the corresponding hidden fields, instead of every hidden field value. 

thanks

<p>Order 17659</p>
<p>Product Type: 2G Micro GPS - $99.95<br /> Product Qty: 1<br />
2Gmicroprice: 99.95<br />
proplan: 39.95<br />
counter: 17659<br />
actfee: 9.95<br />
sctax: 1.06<br />
Select Your Service Plan: 10sec PRO PLAN @ $39.95/month<br />
calc: 299.80<br />
extbatt22: Extended Battery Kit with Case - $149.95<br />
extbattqty22: 1<br />
dollar_extbatt: 149.95<br />

**Comment by Shelob9** [comment]
@safewatch360  This should be fixed in 1.5.0.6 via #1389 Please test on your staging site and let me know if this resolved it, if not, re-open this issue.

**Comment by safewatch360** [comment]
Looks perfect in staging!!!    Thank you very much!!!
