### ISSUE TITLE
Required Toggle Switches Don't Trigger Page Validation

### ISSUE THREAD

**Issue by raouflamari** [CalderaWP/Caldera-Forms#1369]
Pages with only a toogle field are not validated when advancing!

Wordpress 4.7.3
Caldera Forms 1.5.0.5

**Comment by Shelob9** [comment]
Problem here is that they are not inputs. Will get fixed as part of #1476

**Comment by Shelob9** [comment]
Good explanation here: https://wordpress.org/support/topic/required-not-working-properly-for-toggle-switches-on-multi-pages-form/
