### ISSUE TITLE
Wrong Timestamp while exporting entries

### ISSUE THREAD

**Issue by nishathahmed** [CalderaWP/Caldera-Forms#1370]
Hi There,
I tried to export my form entries to csv file with given option "Export all", unfortunately the submission time stamp seems to be on GMT based. I checked throughly across my environment viz. Wordpress time, Wordpress timezone, system time/zone, server time/zone and mysql time/zone. I set my time zone as IST (Indian Standard Time) which is +5:30 from GMT. Difference is exactly the same here.
![actual](https://cloud.githubusercontent.com/assets/18570361/23702880/3e1aea34-0423-11e7-8395-9d66304855ab.png)
Timestamp on CSV

  But when I view them on entry list it shows correctly. Need help.
![entries](https://cloud.githubusercontent.com/assets/18570361/23702881/3e1d116a-0423-11e7-9fbc-3f62e00fa1db.png)
Timestamp on Entries

What could be the issue. Please help.!

Thanks..!

**Comment by Shelob9** [comment]
Related #1344

**Comment by Shelob9** [comment]
Close via 		32a19c0
