### ISSUE TITLE
Additional option field presets

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1373]
1) US States
2) Canadian provinces
3) US States + Canadian Proviences

open to other ideas.

**Comment by andrewlimaza** [comment]
States/provinces for all countries depending on country selection. 

https://github.com/IshanDemon/List_Country_State

**Comment by Shelob9** [comment]
@andrewlimaza 
If you can add some presets (look at `Caldera_Forms_Admin::load_option_presets()`) that would be awesome :)

BTW Your comment is a separate feature, and a planned add-on :)

**Comment by Shelob9** [comment]
Close via ec0f83e
