### ISSUE TITLE
Number Field Validation Always Fails On Second Page

### ISSUE THREAD

**Issue by acosta07** [CalderaWP/Caldera-Forms#1376]
Hello Guys,

I think there's a bug with Number field.

Even if you type a valid number or interval, it returns an error saying it's invalid.

Caldera Forms version: 1.5.0.5
WP version: 4.7.3
PHP version: 7

**Comment by Shelob9** [comment]
@acosta07 Thanks for using Caldera Forms.

Can you clarify if this is a problem in the form editor or when filling out the actual form.

**Comment by acosta07** [comment]
Yes,

When I click on any type of button (Submit, Next/Prev Page), the validation
of Number type field retrieves this error:
This value seems to be invalid.

I try a pure WP installation with only Caldera Forms installed and got same
error.

When I change it to string field type, it works fine. So, I think the
problem is some validation with Number type.


2017-03-09 13:43 GMT-03:00 Josh Pollock <notifications@github.com>:

**Comment by Shelob9** [comment]
Possibly related #1299

**Comment by Shelob9** [comment]
I can reproduce this if number field is on page 2, works on a form with 1 page, and on page 1 of a multi-page form.

**Comment by Shelob9** [comment]
Only affects number fields, not text fields set with number type.

**Comment by acosta07** [comment]
Yes,

You're right.
Only number fields are affected.

I try only number field and Submit button and got same error (1 page only
tested).



2017-03-09 14:57 GMT-03:00 Josh Pollock <notifications@github.com>:

**Comment by acosta07** [comment]
Here's the screen with one page test:
![number-field-error-calderaforms](https://cloud.githubusercontent.com/assets/19167726/23764545/b7363f54-04dc-11e7-9cc5-4256403cceef.jpg)

**Comment by Shelob9** [comment]
Closing as #1405 is a better description of what is same issue.
