### ISSUE TITLE
processor magic tags not working

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1377]
If you use {paypal_express:name} inside email notification or Stripe magic tags it does not display the value but only the text as mentioned.

**Comment by Shelob9** [comment]
Close via 		71c76ad

**Comment by andrewlimaza** [comment]
@Shelob9 I think this is a gmail issue but the magic tag doesn't work on gmail but tested on iOS mail and works as expected (screenshot below) -

![image](https://cloud.githubusercontent.com/assets/12629136/23899899/c0944ae6-08bf-11e7-8c2d-a83540ae0fd2.png)

**Comment by andrewlimaza** [comment]
Here is iOS screenshot where magic tag is working - 
![image uploaded from ios](https://cloud.githubusercontent.com/assets/12629136/23899964/06aa7258-08c0-11e7-8b35-29af74657bf3.jpg)
