### ISSUE TITLE
Emails Notifications

### ISSUE THREAD

**Issue by SPWP17** [CalderaWP/Caldera-Forms#1378]
Hi, 
I'm new here and I start to use wordpress last year.

So, my problem is that i have configure Caldera Forms, but I'm not getting any emails notification.
I have tested sending forms and didn't get any email, as well the email notification. Although it is register in the plugin.

WordPress Version: 4.7.3
PHP Version: 5.6.27
Caldera Forms Version: 1.5.0.5

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I'm sorry you're having this issue. Email problems are either a sign of a bad form configuration, improperly setup server or a PHP error encountered during submissions. 

Here is our documentation on diagnosing email problems:
https://calderaforms.com/doc/improving-the-reliability-of-emails-sent-through-caldera-forms/

If you need help finding or fixing the issue, please open a support ticket at:
https://calderaforms.com/support

**Comment by SPWP17** [comment]
So I can't use this channel to get support?

**Comment by Shelob9** [comment]
Correct, this is an issue tracker for Caldera Forms development. Support tickets can be opened at https://calderaforms.com/support
