### ISSUE TITLE
PHP Fatal error:  Call to undefined function wp_get_upload_dir()

### ISSUE THREAD

**Issue by TheGreenArrow** [CalderaWP/Caldera-Forms#1379]
I have an upload form, if i try to submit it, a blank page appears and i got this error in my logs : 

`PHP Fatal error:  Call to undefined function wp_get_upload_dir() in /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/caldera-forms/classes/files.php on line 181`

**Comment by Shelob9** [comment]
What version of WordPress are you using? That function was added in WordPress 4.5

**Comment by TheGreenArrow** [comment]
WP 4.4
I can't upgrade WP for now.
Is there any solution ?

**Comment by Shelob9** [comment]
You can always copy the source of the function you're missing and put them into a mu-plugin or something, just be careful you don't break updates and you make sure you don't create new errors by calling other non-existant functions.

```
	if( ! function_exists( 'wp_get_upload_dir' ) ) {
		function wp_get_upload_dir(){
			return wp_upload_dir( null, false );
		}
	}
```

**Comment by TheGreenArrow** [comment]
It's working ! Thank you.
One last thing...
When i send a form, i receive it twice. Any idea why ?
