### ISSUE TITLE
Interaction between HTML fields, condition and magic tags

### ISSUE THREAD

**Issue by petrospapad** [CalderaWP/Caldera-Forms#1380]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3PHP Version: 7.0.16MySQL Version: 5.5.54Caldera Forms Version: 1.5.0.5WP_DEBUG:

## What Is The Unexpected Beahviour?
Basically i created a condition, that when a "Yes" option is selected from a toogle switch, some fields (number field type) were to be opened. 
Then i tried to handle the values of those fields via their magic tag in a HTML field, but i was unable.
In truth when i used as a default in the toogle switch option "Yes", my HTML field worked just fine.
However, when i switched to other options of the toogle switch my HTML field was gone completely in the front-end of my form.
Maybe, that is because an HTML field is updated live dynamically and the toogle switch justs removes the "hidden" fields from the form, so there is no value output from those fields (?).

I don't know if it is a bug or it's the intended use, but i think i should report it anyway..

**Comment by Shelob9** [comment]
Related (possibly dupe) #1404

**Comment by Shelob9** [comment]
@petrospapad This should be fixed after 	fbc4283 ? Can you please test against master branch and confirm?

**Comment by Shelob9** [comment]
Close via  fbc4283
