### ISSUE TITLE
Better Phone Number: regional mask doesn't work

### ISSUE THREAD

**Issue by TadashiCZ** [CalderaWP/Caldera-Forms#1381]
Hello. The new phone number allows more digits than are allowed regionally (for example CZ number use exactly 9 digits and region code. Form allows me to input more than 9 numbers but not less than 9. So it only works on one-side.

Enhancement part: Could there be spaces used as separators in numbers that would be inputed automatically? Czech are used to write numbers as +420 753 869 423 (not my number =D) for example, so it is easier for the user to check if he/she inputed the right number. Thanks.

**Comment by Shelob9** [comment]
@TadashiCZ I wonder if this is a bug in the JS library we're using.

It definitely validates properly for US numbers:
![screenshot from 2017-04-01 19-45-52](https://cloud.githubusercontent.com/assets/1994311/24583311/1cffad68-1714-11e7-8250-8ec53c1dae55.png)

I'm using your example and that's allowed, even if I add 3 numbers:

![screenshot from 2017-04-01 19-46-55](https://cloud.githubusercontent.com/assets/1994311/24583313/29ebe9c4-1714-11e7-837d-1e081f47d5cb.png)

If i add another it says too long:
![screenshot from 2017-04-01 19-47-05](https://cloud.githubusercontent.com/assets/1994311/24583317/36dbff16-1714-11e7-9c54-8667f620fcac.png)

It's not the spaces either, those are properly ignored:

![screenshot from 2017-04-01 19-47-17](https://cloud.githubusercontent.com/assets/1994311/24583319/4317c0da-1714-11e7-8b9f-6d9f350f4ead.png)

Not sure what to do, will keep digging.

**Comment by andrewlimaza** [comment]
This works.

**Comment by TadashiCZ** [comment]
http://www.instalacekotlu.cz/jarni-akce-buderus-logano-s181-e-za-34-999-kc/ Try it here. When I choose CZ I can input up to 12 numbers instead of 9. Can it be because of the country code which should be included in the count but isn't?
