### ISSUE TITLE
Calculation fields does not take conditionals into consideration

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1387]
I am busy testing all payment gateways and have come across an issue with the PayPal Express add-on.

Caldera: 1.5.0.5
PayPal Express: 1.1.6

**DESCRIPTION**

If you use a form with select boxes for conditional addition to the total amount, PayPal ignores the conditions and charges entire amount. For example -

if Field 1 is selected add $10 to the total.
if Field 2 is selected add $5 to the total. 

If none of these fields are selected don't add any amount to the total. 

Outcome = $15 every checkout regardless of input/selection.

**1) what your calculations is composed of.**
hidden field 1 + hidden field 2 = total

**2) what your conditional is**
If field 1 is 'yes' show hidden field 1 (value: 10)
If field 2 is 'yes' show hidden field 2 (value:5)

**3) what the calculation displayed in the front-end**
This displays correctly on the frontend. If field 1 is the only field selected $10 is shown. If both fields are selected $15 is shown (which is correct)

**4) what value was saved in the entry.**
150

**5) what happens when you do the same thing setup without a payment processor**
150

**Comment by andrewlimaza** [comment]
I am going to thoroughly check and test other payment gateways as Stripe shows $50 on front end but when you view in the entry viewer it is 150.00

**Comment by andrewlimaza** [comment]
@Shelob9 this seems working as expected now! :)

**Comment by Shelob9** [comment]
Close via #1389
