### ISSUE TITLE
Blank page after update 1.4.8 to 1.5.0.5

### ISSUE THREAD

**Issue by jjmortibus** [CalderaWP/Caldera-Forms#1388]
PHP 5.5
wordpress 4.7.3
Mysql 5.6 (utf8mb4)

Even i try to do an another form blank page when i use de shortcode, but i can see and change the form in the BO of wordpress

**Comment by Shelob9** [comment]
@jjmortibus Thanks for using Caldera Forms. A white screen sounds like you have a fatal error, but have suppressed error reporting. Th. If you could please log errors using the method described in this post -- https://calderaforms.com/2016/05/wordpress-debug-logging/ -- and show us the errors you found, that would help us understand what could be causing this conflict on your site and we can see if it is a bug with Caldera Forms or not.


Please keep in mind, this is not a support channel, if you need help troubleshooting, debugging or working through conflicts with plugins or themes, please open a support ticket at https://calderaforms.com/support
