### ISSUE TITLE
Add support for Radio and Checkbox in summary field

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1396]

**Comment by postali-eschumacher** [comment]
Yes, please... this would be a much appreciated update! I found this after spending a few hours testing everything to see if I had done something wrong on my form. Interestingly, they actually do appear in a summary field if you have any other sort of input after a radio / checkbox but before submit... typing anything in a text field will make your selections magically appear. Obviously having them update real time is preferred...

**Comment by Shelob9** [comment]
close via 		1ecfdba
