### ISSUE TITLE
Hide labels and Button field type not working

### ISSUE THREAD

**Issue by lmartins** [CalderaWP/Caldera-Forms#1398]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3PHP Version: 7.1.1MySQL Version: 5.5.5Caldera Forms Version: 1.5.0.5WP_DEBUG: 1

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
- For the labels, the selecting the hide label option the label is still being displayed on the front-end.
- For the buttons, the field type option does nothing and the button is always rendered as an `input type=button`

**Comment by Shelob9** [comment]
In regards to the issue of labels, are you disabling Caldera Forms styles? If so,you will need to use an accessibility ready theme or add the screen reader class to your theme.

See:
https://github.com/CalderaWP/Caldera-Forms/issues/1341#issuecomment-284030661

**Comment by Shelob9** [comment]
Also, i am unable to reproduce your button issue. I am seeing submit type for submits, button for next and previous and reset for reset.

**Comment by lmartins** [comment]
Hi @Shelob9 

On the labels ok, I'll look that up. I first though that would be the case but I don't see anything being generated on the markup that seems to be dedicated to hide them via CSS:
```
<div class="col-sm-6  first_col">
<div role="field" data-field-wrapper="fld_8768091" class="form-group">
<label id="fld_8768091Label" for="fld_8768091_1" class="control-label screen-reader-text">First name</label>
<div>
<input placeholder="First Name*" required="required" type="text" data-field="fld_8768091" id="fld_8768091_1" name="fld_8768091" value="" data-type="text" aria-required="true" aria-labelledby="fld_8768091Label" class=" form-control">
</div>
</div>
</div>
```

About the button, I was expecting the settings visible at https://cl.ly/2S123v0Z1E15 to output a `button` element of the type `submit`, not an `input` element of the type `submit`. From your info I realize I may have misinterpreted the UI and it will always output an input. 

Considering the info above, I'll close this for now.
