### ISSUE TITLE
Option to limit file size for adv file 2.0 and standard file fields

### ISSUE THREAD

**Issue by TheGreenArrow** [CalderaWP/Caldera-Forms#1399]
The file size control is working by file instead of the total files size.

![2017-03-14 11 31 06](https://cloud.githubusercontent.com/assets/21695752/23896511/fd257162-08a9-11e7-928f-55a6317bc8f7.jpg)

In this example, limit of file size uploading is 2Mo.

**Comment by Shelob9** [comment]
Correct, that is how this works. I'm going to retitled this as a feature request. As it would be a cool feature if it could do that.

**Comment by Shelob9** [comment]
Changing name to reflect that is will be implimented in standard file file fields and advanced file fields 2.0, not advanced file fields 1.0.

**Comment by Shelob9** [comment]
Close via 6e707fd #2823
