### ISSUE TITLE
If field is shown using conditions the magic tags display as blank

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1404]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3PHP Version: 5.5.24MySQL Version: 5.6.24Caldera Forms Version: 1.5.0.6WP_DEBUG: 1

## What Is The Unexpected Beahviour?
If you display a field using conditions and then try to use %slug% later down in the form to display the value of that field. It doesn't show any value and no errors occur.

The magic tag still shows blank once the hidden field is displayed using conditions.

So if you have a checkbox to show a field the %slug% never shows the value while the field is hidden (which is correct) or if it's shown. The value just stays blank.

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
Close via 	fbc4283
