### ISSUE TITLE
Checkboxes in emails are showing JSON not label

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1410]
I probably broke this in 71c76ad  or e9d6f6f

**Comment by Shelob9** [comment]
Most likely here: https://github.com/CalderaWP/Caldera-Forms/commit/71c76ad496ff99b29a7d2f7f93edceecd7ec46d3#diff-193f67224ef5db0b30425861c836e123R232

**Comment by johnalarcon** [comment]
Confirmed.  Email shows json for the options that were selected.

**Comment by Shelob9** [comment]
@johnalarcon I can't reproduce this at all, in 1.5.0.6 or against master. Can you please tell me which version you are using of Caldera Forms, WordPress and PHP?

**Comment by johnalarcon** [comment]
@Shelob9 
WordPress Version: 4.7.3
PHP Version: 7.0.14
MySQL Version: 5.6.28
Caldera Forms Version: 1.5.0.6

It worked on a brand new installation using twentyseventeen, but when I disabled all plugins and set twentyseventeen on the actual site I'm working on, the error persisted.  I also found that conditional inputs were not sending (or saving) their data, although the conditions did work on the front end.  Here's my console view before and after submission.  No errors are logged in debug.log.

[initial-pageload.txt](https://github.com/CalderaWP/Caldera-Forms/files/860025/initial-pageload.txt)
[after-submission.txt](https://github.com/CalderaWP/Caldera-Forms/files/860026/after-submission.txt)

**Comment by mfonville44** [comment]
I'm seeing this issue as well - since the latest update of the CF plugin.

Checkboxes that were showing labels or values and now are returning JSON - {"opt1729352":400}

WordPress Version: 4.7.3
PHP Version: 5.6.29
Caldera Forms Version: 1.5.0.6

No errors in debug.log.

**Comment by antoniostarace** [comment]
I've just tried with CF 1.4.9.1, I get the exact same results.

**Comment by Shelob9** [comment]
I've been assuming people were referring to the {summary} magic tag, which worked fine. Looks like problem is %field_slug% magic tags.

**Comment by Shelob9** [comment]
Closed via  d0aaea4
