### ISSUE TITLE
Date picker not working at all in Firefox and Safari browsers

### ISSUE THREAD

**Issue by Huuhkaja69** [CalderaWP/Caldera-Forms#1411]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by andrewlimaza** [comment]
I'm unable to replicate this issue, would you mind telling me what version of Caldera Forms you are using?

I came across this issue previously and the issue seemed to had been caching causing issues with Caldera Forms. If you are running a caching plugin, could you please temporarily disable it and see if the issue persists.

**Comment by Huuhkaja69** [comment]
Hi,
managed to get everything to work.  But unable to find out what was the reason. I just disabled all plugins and turned them on again and now everything works perfectly. Maybe it was cache issue, dont know.
Thanks.
