### ISSUE TITLE
Unable to view completed form entries

### ISSUE THREAD

**Issue by lerq** [CalderaWP/Caldera-Forms#1418]
## Do You Need Immediate Help?
* No, I have set up a processor to forward me all completed forms, but this isn't ideal.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.5.7
PHP Version: 5.3.3
MySQL Version: 5.1.73
Caldera Forms Version: 1.5.0.6

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Unable to try at the moment as site is being used and front end form functionality (ie ability to complete forms is still working)

## What Is The Unexpected Beahviour?
Clicking on "Entries" when in a form to view the entries now doesn't work. The spinner just spins. Prior to 1.5 this displayed a list of completed forms, and checking the release notes for 1.5.0.6 it looked to have been resolved.

## What PHP Errors Have You Logged While Reproducing This Bug?
not done

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Uncaught a {description: undefined, fileName: undefined, lineNumber: undefined, message: "You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined", name: "Error"…}
f @ wp-baldrick-full.min.js?ver=1.5.0.6:2
a.compile @ wp-baldrick-full.min.js?ver=1.5.0.6:2
filter @ wp-baldrick-full.min.js?ver=1.5.0.6:3
c @ wp-baldrick-full.min.js?ver=1.5.0.6:2
success @ wp-baldrick-full.min.js?ver=1.5.0.6:3
i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
fireWith @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
y @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:4
c @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:4

**Comment by Shelob9** [comment]
@lerq - Thanks for using Caldera Forms. The error you are showing almost always means that some PHP error happened while rendering the editor. You can probably will find something if you enable debug logging:
https://calderaforms.com/2016/05/wordpress-debug-logging/

If you need help troubleshooting, please open a support ticket at https://calderaforms.com/support

**Comment by lerq** [comment]
Thanks @Shelob9 for the feedback. I'll take a look, but this only started happening once I upgraded to a post 1.5 version of the plugin.

It didn't happen in 1.4.9, I then upgraded to 1.5.0.4 and first saw the issue, and it still happens in 1.5.0.6

No other plugins were updated at the same time, nor wordpress etc either.

So if there is a PHP error, could it be from the updated plugin?
