### ISSUE TITLE
$entryid instead $entry_id detected in classes\core.php (BUG?)

### ISSUE THREAD

**Issue by ESPONI** [CalderaWP/Caldera-Forms#1422]
near line 3061 in classes\core.php
$wpdb->insert( $wpdb->prefix . 'cf_form_entries', $new_entry );
**$entryid** = $wpdb->insert_id;

After that, $entry_id is used so NULL value is passed to all actions/filters.

**Comment by Shelob9** [comment]
@ESPONI Thanks for using Caldera Forms. Good catch! Can you please put in a pull request against the master branch for this?

**Comment by Shelob9** [comment]
close via 		0b55cb5
