### ISSUE TITLE
Need help to create a custom payment processor

### ISSUE THREAD

**Issue by zoomwebstudio** [CalderaWP/Caldera-Forms#1423]
Hello,

I want to create a Skrill payments processor (https://www.skrill.com/en/merchants/integration/) for caldera forms, but as a not experienced php developer, I am a little bit confused with the way I can use this abstract class with my processor : 

`/**
 * Base class that payment processor add-ons should use
 *
 * @package   Caldera_Forms
 * @author    Josh Pollock <Josh@CalderaWP.com>
 * @license   GPL-2.0+
 * @link
 * @copyright 2016 CalderaWP LLC
 */
abstract class Caldera_Forms_Processor_Payment extends Caldera_Forms_Processor_Processor implements Caldera_Forms_Processor_Interface_Payment  {

}

It might not be correct but I've search the calderaforms documentation but there seems to be no tutorial showing effectively how to make a payment with the processor and get back to form before saving it to the database.

Thanks

**Comment by Shelob9** [comment]
@zoomwebstudio Thanks for using Caldera Forms. I do appreciate it, but please keep in mind, this is not a support channel. This is a tracker for bugs and features. Support requests should go to https://calderaforms.com/support


https://calderaforms.com/doc/caldera-forms-processing-overview/

https://calderaforms.com/doc/creating-custom-validation-processor-caldera-forms/

https://calderaforms.com/doc/using-form-processors/

**Comment by zoomwebstudio** [comment]
Thanks @Shelob9
