### ISSUE TITLE
New "magic tag" for accessing query_vars (enhancement)

### ISSUE THREAD

**Issue by ESPONI** [CalderaWP/Caldera-Forms#1424]
Near line 162 of classes\magic\doer.php

(...)
add something like
		case 'getqv':
			$magic_tag = get_query_var($magic[ 1 ]);
			break;
(...)

**Comment by Shelob9** [comment]
@ESPONI Thanks for using Caldera Forms. This is a great idea. Can you please put in a pull request against the master branch for this?

**Comment by Shelob9** [comment]
Close via 	1dda915

New magic tag is `{query_var:*}` this is a wrapper for [get_query_var()](https://codex.wordpress.org/Function_Reference/get_query_var)
