### ISSUE TITLE
When "Use Country Code" option is checked required phone fields can be submitted empty

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1426]

**Comment by Shelob9** [comment]
Close via 3315eb5

**Comment by E31C** [comment]
@Shelob9 hi Josh, thanks for the update!

Im still getting the bug again. I do not know if this has something to do with the preferred country function that I pulled from github?

https://smartcanopy.co.za/contact/

`// Add Caldera Forms Country Code
// =============================================================================

add_filter( 'caldera_forms_phone_js_options', function( $options){
	//Use ISO_3166-1_alpha-2 formatted country code
	$options[ 'initialCountry' ] = 'ZA';
	return $options;
});

// End Caldera Forms Code
// =============================================================================`

**Comment by Shelob9** [comment]
@E31C To clarify, do you mean that in Caldera Forms 1.5.0.7 if you check "Use Country Code" for a field and check the required box, you can submit your form when that field is empty?

If so, is this field in a multi-page or single page form?

Also, does the issue persist if you remove that filter?

**Comment by E31C** [comment]
@Shelob9 yes that is correct, I have removed the function and reverted back to +1 but it still sends.

You can try this @ https://smartcanopy.co.za/contact/

Not to sure what I am doing wrong?
