### ISSUE TITLE
Submission weirdness - WP backend footer text pushed further up. -bug-

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1429]
In relation to the latest version:
![screen shot 2017-03-22 at 09 25 45](https://cloud.githubusercontent.com/assets/5323259/24188610/51c1c0ac-0ee2-11e7-9136-0dce6da18c74.png)

What can be seen in the submission screen is the Thank you for creating with WordPress (usually) footer text as well as version number.

Hopefully the submission screen is on its way to get a good cleanup.

**Comment by Shelob9** [comment]
Closing as duplicate of #1410
