### ISSUE TITLE
Magic Tags Not Processed in Paragraph Textareas

### ISSUE THREAD

**Issue by hostifynetworks** [CalderaWP/Caldera-Forms#1437]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3PHP Version: 7.0.17MySQL Version: 5.6.35Caldera Forms Version: 1.5.0.6WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes. Tried on fresh install.

## What Is The Unexpected Behavior?
Magic tags are not processed in paragraph textareas. The magic tag should not be printed to the screen. **The last release version in which this worked as expected is 1.4.9.1.**

Steps to reproduce:
1. Add a paragraph textarea to a form.
2. Set the default value to be a magic tag.
3. Preview the form.
4. The magic tag code will appear in place of the expected value.

In the attached screenshot I have setup a form that has "{get:blah}" set as the default value for the "Fullname" field as well as the "Comments/Messages" field. The magic tag is processed in the "Fullname" field but is untouched in the "Comments/Messages" field. Note that this occurs with other tags as well such as "{ip}"
![screen-shot-2017-03-27-at-2 58 34-pm](https://cloud.githubusercontent.com/assets/915523/24375695/dbf87bd8-12fe-11e7-9b18-3ecba2791aed.jpg)

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
@hostifynetworks This is only {get:*} magic tags right? %field_slug% type magic tags are working for you right?

**Comment by hostifynetworks** [comment]
This affects %field_slug% as well. Neither displays correctly on the form the end user sees when used in a paragraph textarea. The "{get:*}" style tags seem to display correctly in the resulting email while "%field_slug%" does not.

On a semi-related noted, it doesn't work as expected when you specify something like "{ip}/%email%" as the default value. I think the below screenshots will be better at explaining it. Perhaps this belongs in a separate issue? Seems like this is something that should throw an error when saving the form. At any rate, the behavior was different (but still "wrong") in 1.4.9.1.

I've setup the same form to test in 1.4.9.1 and 1.5.0.6 with various default values:

Here's an export of my test form along with screenshots to help with reproducing this in **1.5.0.6**: 
**{ip} set as default value:**
[test-export-ip-only.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/882512/test-export-ip-only.json.zip)
![screen-shot-2017-03-30-at-9 07 21-am](https://cloud.githubusercontent.com/assets/915523/24508284/8d500e52-1528-11e7-84a0-a448f454f866.jpg)
<img width="284" alt="screen shot 2017-03-30 at 9 37 34 am" src="https://cloud.githubusercontent.com/assets/915523/24509681/9c3efb40-152c-11e7-9dfa-585353716bb1.png">


**%email% set as default value:**
[test-export-email-only.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/882713/test-export-email-only.json.zip)
<img width="615" alt="screen shot 2017-03-30 at 9 24 55 am" src="https://cloud.githubusercontent.com/assets/915523/24509070/fbd607f8-152a-11e7-9b10-288661f3efde.png">
<img width="263" alt="screen shot 2017-03-30 at 9 25 57 am" src="https://cloud.githubusercontent.com/assets/915523/24509076/01b8865a-152b-11e7-8d67-a7a55d9fede4.png">



**{ip}/%email% set as default value:** 
[test-export-ip-and-email.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/882520/test-export-ip-and-email.json.zip)
![screen-shot-2017-03-30-at-9 06 01-am](https://cloud.githubusercontent.com/assets/915523/24508300/9ada5b68-1528-11e7-8306-014fd1408c4b.jpg)
<img width="273" alt="screen shot 2017-03-30 at 9 04 03 am" src="https://cloud.githubusercontent.com/assets/915523/24508301/9adcfbf2-1528-11e7-9105-39c3f3c030bf.png">

<hr />

Screenshots with the same setup in **1.4.9.1**:
**{ip} set as default value:**
<img width="617" alt="screen shot 2017-03-30 at 9 19 25 am" src="https://cloud.githubusercontent.com/assets/915523/24508737/003f2ab4-152a-11e7-98ea-95093b80e343.png">



**%email% set as default value:**
<img width="626" alt="screen shot 2017-03-30 at 9 33 14 am" src="https://cloud.githubusercontent.com/assets/915523/24509407/ed794098-152b-11e7-9015-b9f28929d2fc.png">



**{ip}/%email% set as default value:** 
<img width="627" alt="screen shot 2017-03-30 at 9 18 13 am" src="https://cloud.githubusercontent.com/assets/915523/24508689/dbb27a66-1529-11e7-82f8-e46d44d4ef11.png">

<hr />

Please let me know if I can be of any further assistance.

**Comment by Shelob9** [comment]
Close via  3b86fc1
