### ISSUE TITLE
Conditional recipient processor does not work

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1439]
Conditional recipient processor doesn't work even when conditions are met still sends to default email address found inside the email settings tab.

In the conditional recipient processor 'remove default' is selected.

**Comment by Shelob9** [comment]
Maybe related #1459

**Comment by Shelob9** [comment]
@andrewlimaza I can't reproduce. 

This is my test form: https://www.dropbox.com/home/Caldera%20Forms%20Test%20Forms?preview=conditional-recipients-export.json

It changes email if a field called email isn't empty. It successfully changes email to that input. Also tried with a hardcoded email. Also with and without remove default checked.'

Please test against master and tell me why I'm wrong or close.

**Comment by andrewlimaza** [comment]
This works! :)

**Comment by peter-at-houston-academy** [comment]
I am also experiencing this issue, while using SendGrid (API). There is no change from when "Remove Default?" is selected or not selected - it sends to both the default email address and the address in the conditional.
