### ISSUE TITLE
Page not found when trying to export entries from entry viewer page

### ISSUE THREAD

**Issue by rapafernando** [CalderaWP/Caldera-Forms#1443]
Hello.

I create a form and also a front end page to review the entries and also if needed export some of the entries, but no matter what security role I am using, including admin, from the front end I always get the page not found error.

However from the admin console of the Caldera forms I can export it correctly.

Also, it is anyway to edit an entry after submit it, I am planning to use the form as a workflow and it will be helpful to edit some field in each step.

Regards.

**Comment by Shelob9** [comment]
@rapafernando Am I right that you're using the classic entry viewer in the front-end? If so, I kind of doubt that's ever going to work, but we can look into.

https://calderaforms.com/doc/edit-caldera-forms-entries/

**Comment by Shelob9** [comment]
I am closing this as we have not heard back and I can't define what the issue is. @rapafernando Please reopen if you have new details using 1.5.0.9
