### ISSUE TITLE
files not sent in email when “Scroll To Top On Submit” enabled

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1444]
Reported here:
https://wordpress.org/support/topic/strange-bug-files-not-sent-in-email-when-scroll-to-top-on-submit-enabled/

I need to test.

**Comment by Shelob9** [comment]
I can't reporduce this, but while testing I ended up with a email with no message, which will not send, so I opened and fixed  #1456 

I'm going to close thison Tuesday unless someone can explain to me how to reproduce and convince me it's not just #1456

**Comment by andrewlimaza** [comment]
I'm unable to reproduce this issue... Images attach fine with back to top enabled & advanced file upload.
