### ISSUE TITLE
Attached files not saving to server

### ISSUE THREAD

**Issue by johnalarcon** [CalderaWP/Caldera-Forms#1451]
I created a form that has 3 advanced file inputs.  They seem to submit fine (progress indicators work), but the links to the files in the Entry view lead to 404s.  I checked the server - the directory and file aren't there at https://site.com/wp-content/uploads/randomStringOfChars/filename.pdf and I didn't find the file anywhere else.  Possibly related to #1444 

WordPress Version: 4.7.3
PHP Version: 7.0.14
MySQL Version: 5.6.28
Caldera Forms Version: 1.5.0.6
WP_DEBUG: 1

No errors logged.

Console shows:
ReferenceError: reference to undefined property a[(b.name + v(...))][Learn More]  parsley.min.js:2:28935
ReferenceError: reference to undefined property a[n.expando][Learn More]  jquery.js:3:1133
ReferenceError: reference to undefined property b[f][Learn More]  jquery-migrate.min.js:2:9487
ReferenceError: reference to undefined property j.opts.start[Learn More]  jquery.js:4:5212
ReferenceError: reference to undefined property l.headers[Learn More]  jquery.js:4:21662
ReferenceError: reference to undefined property b.username[Learn More]  jquery.js:4:26273
ReferenceError: reference to undefined property a[w.status][Learn More]  jquery.js:4:20474
ReferenceError: reference to undefined property e[d][Learn More]  jquery.js:3:1608
ReferenceError: reference to undefined property b.data.scroll[Learn More]  ajax-core.min.js:1:3587

**Comment by johnalarcon** [comment]
Replaced the advanced file upload field with the general file upload field.  Same results.

**Comment by Shelob9** [comment]
@johnalarcon Can you share what your settings are for this field?

It's impossible for me to understand if you're setting up the field wrong for your needs or experiencing a bug without knowing what your settings are.

**Comment by johnalarcon** [comment]
I tried both file upload inputs with the following settings:

Name: Custom Document
Slug: custom_document
Hide Label: true
Types: pdf,doc,zip

No other fields set.

**Comment by Shelob9** [comment]
@johnalarcon  So you didn't check "Upload To Media Library"? If so, the file will not save to your server. 
See: https://calderaforms.com/doc/how-caldera-forms-file-attachments-uploads-work/

**Comment by johnalarcon** [comment]
Thanks, @Shelob9 ... I did read the docs, but the way I interpreted them was that checking that box would upload files to the media gallery _in additional to_ wherever else it was saving.  So, you're right, the error occurred somewhere between my keyboard and my chair.  Appreciate your clarifying.  Thanks.

**Comment by Shelob9** [comment]
@johnalarcon Thank you for clarifying. Yes, it's a problem with your settings, not technically a bug, but you're *far* from the first person to be confused by the settings.

I'm going to think through how this could be more clear and am very open to suggestions. #1464

**Comment by johnalarcon** [comment]
I'll think on this as well.  I've got one suggestion and will add it to the #1464.  Thanks!

**Comment by regiside** [comment]
Hey, I know this is kind of an old topic, but I just ran into this issue as well. (tried accessing the images via the plugin only to find the directory didn't exist.) Personally I would like the ability to upload attachments to the sever without adding them to the media library. I use forms all the time to have people upload things I don't want cluttering up the media library, but will need to access via the form link.
