### ISSUE TITLE
Field sync doesn't work if field is intially hidden

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1452]
If a field is hidden on page load by conditional logic and it is synced to another field, when it is unhidden it is content is not synced and it doesn't update to synced field.

Possibly dupe or same root cause as #1404

**Comment by Shelob9** [comment]
Close via 	fbc4283

**Comment by vraja-ids** [comment]
Looks like this issue is still Open. @Shelob9 I am using version 1.5.6.2 and the problem was reproducible. It is critical feature for us since our registration may contain up to 8 people and we would like to sync a lot of fields like email, phone number etc.
