### ISSUE TITLE
MailChimp Processor field reset with every Caldera Forms Update

### ISSUE THREAD

**Issue by omniacode** [CalderaWP/Caldera-Forms#1475]
#### What Version Of Caldera Forms, WordPress and PHP Are You Using?
WP: 4.7.3 Multisite (Not Network Activated)
CF: 1.5.0.7 (every update since 1.5)
Addon: MailChimp
PHP: 5.6

This has happened that last few updates where if the MailChimp addon and processor are setup, the set fields are reset every time producing an error on the front-end. Once the fields are reconnected to the associated fields within the form, it goes back to working again.

**Comment by Shelob9** [comment]
@omniacode Can you please open a support request at https://CalderaForms.com/support and let us know what version of the MailChimp add-on you are using is? Also, I'll send you the newest version (not released yet) to test :)

**Comment by omniacode** [comment]
Sure thing Josh, currently using Version 1.2.1 - I will submit the ticket now. Thanks

**Comment by Shelob9** [comment]
No problem, just easier to handle in the right place. Also, yep, that's totally happens with 1.2.1. Shouldn't be a problem with 1.3.0 or later https://calderaforms.com/updates/caldera-forms-mailchimp-1-3-0/
