### ISSUE TITLE
Custom class is applied in two places

### ISSUE THREAD

**Issue by kevinwhoffman** [CalderaWP/Caldera-Forms#1491]
Custom class `form__item--name` is set in the GUI.

![image](https://cloud.githubusercontent.com/assets/1938671/24841183/e06e04d8-1d4b-11e7-8b00-ef08c35e5369.png)

Note how the custom class is applied to the control wrapper and to the input itself.

![image](https://cloud.githubusercontent.com/assets/1938671/24841210/68a64298-1d4c-11e7-8cb1-9c9611954342.png)

This is problematic because any styles that use this class selector will be applied to both the control wrapper and the input. I would expect the class to only be applied to the control wrapper, since the input could be targeted as a descendant of the selector if desired.

CF: 1.5.0.7
WP: 4.7.3
PHP: 7.1

**Comment by Shelob9** [comment]
@kevinwhoffman Correct, this is bad. I think that `remove_filter('caldera_forms_render_field_classes', 'cf_apply_field_classes', 10, 3);` is quick fix. Why that filter is even there doesn't make a lot of sense to me.

**Comment by kevinwhoffman** [comment]
@Shelob9 That would remove the custom class from the control wrapper, which leaves it only applied to the input. Is that your intention? If so, then is there another way to target the control wrapper?

Use case: I have custom layout styles and I'd like to apply a class to that field's control wrapper so that it is half-width. That's not possible if I can only apply a class to the input.

**Comment by Shelob9** [comment]
If it's working as it supposed to be, then you should be able to use caldera_forms_render_field_classes filter to target control wrapper and and input separately, look at the array that is passed into the filter here:

https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L3690-L3702

I'm going to make sure everything comes out of that as expected.

**Comment by kevinwhoffman** [comment]
Targeting the control wrapper and input separately works just fine when filtering the array. Some of the classes are not being filtered, but that's a separate issue described in #1490.

The issue I'm describing here is specific to classes that are entered in the Custom Class field of the GUI when building the form. Currrently these custom classes are being applied to both the control wrapper and the input.

What I'm looking for is a way to target specific control wrappers on a per field basis.

**Comment by Shelob9** [comment]
@kevinwhoffman 2nd arg is field, which has ID, so you can target based on field ID:
```
	add_filter( 'caldera_forms_render_field_classes', function( $classes, $field, $form ) {
		if( 'CF12233445' === $form[ 'ID' ] ){
			if( 'fld12' == $field[ 'ID' ] ){
				//
			}elseif (  'fld23' == $field[ 'ID' ] ){
				//
			}
		}
	
		return $classes;
	}, 10, 3 );
```

I'll fix the wrapper vs input bug today or tomorrow.

**Comment by Shelob9** [comment]
@kevinwhoffman I am testing with both 1.5.0.9 and 1.4.0 (to test if this was a bug in 1.5.x or traditional behaviour)

In 1.5.0.9 I get this:
![screenshot from 2017-04-12 19-09-22](https://cloud.githubusercontent.com/assets/1994311/24983198/9e53efa8-1fb3-11e7-9f82-1f1a137345f7.png)

Custom class is applied to wrapper and input for the text, but only to wrapper for the select.

In 1.4.0 I get this:
![screenshot from 2017-04-12 19-11-27](https://cloud.githubusercontent.com/assets/1994311/24983242/d95e8edc-1fb3-11e7-918b-5defcbe21820.png)

Custom class is applied to wrapper only for both.

Applying to wrapper make sense, as you can use `.custom-class input` and `.custom-class label`. Also, that's how it worked before I change how inputs (not selects) were generated in 1.5 (#945)

Therefore I declare bug to be "Inputs are getting custom class, which should only be applied to control wrapper"

**Comment by Shelob9** [comment]
Close via 		8d2e27b

**Comment by kevinwhoffman** [comment]
Strong agreement. Thanks.

**Comment by Shelob9** [comment]
Turns out exception to this rule was that hidden fields need custom class on input, since they don't have wrappers. #1564
