### ISSUE TITLE
Calculation rounding is wrong

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1493]
Hashtag epic fail.

Broken here when I created a single formatting method to reduce code reusse: 93b3cad0b8f89fddd678d4b2a99943656d10bdcc #1434

On the bright-side, I only need to fix one place now.

**Comment by Shelob9** [comment]
Close via 	1844bf3

Also @shelob9 is fired.

**Comment by andrewlimaza** [comment]
lol @ these comments.
