### ISSUE TITLE
Using shortcode to set default with multiple forms causes issues.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1499]
Default and conditionals are wrong
See: https://wordpress.org/support/topic/multiple-forms-placements-result-in-incorrect-applied-conditions/

**Comment by Shelob9** [comment]
Close via 		d719da6

**Comment by RichardGeorgeDavis** [comment]
Hi,

I’ve updated to the latest version today however the same error still persists. (Version 1.5.0.9)

> I’m using multiple instances of the shortcode on a single page, changing the default selection ie option1; option2; option3 etc
> 
> [caldera_form_modal id=”CF58e528e9d9513″ fld_1173319=”option1″ type=”button”]Build a Deal[/caldera_form_modal]
> 
> I’m experiencing the following two errors:
> 
> The shortcode’s conditions work perfectly in the very first form (or if the form ID is not duplicated) however on all consecutive forms that follow conditions are not being applied or fields are hidden which should be visible with default selection added to the shortcode, only appearing when changing a selection to another option and then changing the selection back.
> 
> And the first dropdown select now includes an empty option – not visible on the form setup, preview form or if the form ID isn’t duplicated on a page.

Here is the site I’m working on http://432.co.za/vw/11/

The conditions (from the same form) aren’t displaying correctly when multiple instances of the form are present.

On the above example, when each button is selected the deal options should show, but only the first form displays this – the others only show once a selection is made but this is not the way the conditioning should work for this form.

I've exported the form below:
[volkswagen-specials-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/975661/volkswagen-specials-export.json.zip)
