### ISSUE TITLE
Including "Add to media library" file URL magic tags in 1.5.8 replaces all other email content

### ISSUE THREAD

**Issue by andersnoren** [CalderaWP/Caldera-Forms#1502]
I spent a chunk of time this morning trying to find out why the URL for the file field, set to "Add to media library", replaced all other content in the Email Message. It was being replaced in the email sent off, and the "Preview Last Email" field, but all of the data is added correctly to the Entries for the form. I tried changing it to the Advanced File Uploader, I tried setting it to "Attach to Mailer" (in addition to "Add to media library"), I tried changing the allowed types and I tried creating a completely new form with the same fields (I had imported the one having issues, so I figured that might be a factor). Nothing helped. 

Finally, I realised that we have the same form on another WordPress installation, where the Email Message is including the file URL in the correct location (and not replacing the rest of the content). Both installations are on the same server. The installation where the form worked is running 1.5.0, whereas the one where the form wasn't working is running 1.5.8. I replaced Caldera Forms on the latter with the 1.5.0 version, and when I tried sending the form again, the file URL was included in the correct location, without replacing the other content.

I can attach an export of the form in question, if it would help.

**Short Debug Information:**
WordPress Version: 4.7.3
PHP Version: 5.6.29-0+deb8u1
MySQL Version: 5.5.54
Caldera Forms Version: 1.5.8 (note: now changed to 1.5.0)
WP_DEBUG: 1

**Comment by andersnoren** [comment]
I'm still having this issue in the latest version of the plugin (1.5.0.10).

**Comment by andersnoren** [comment]
Has this issue been fixed, or replicated by anyone? We have a client still on 1.5.0 since they need this functionality to work, but we're having issues with the entries view that seems to have been fixed in versions after 1.5.3, so we would really like to update them to the latest version.

**Comment by lyrixn** [comment]
I'm having this exact same issue with the latest build. Apparently they give f-all about bug reports.

**Comment by Shelob9** [comment]
This should be fixed via #2227 

https://calderaforms.com/updates/caldera-forms-1-5-9/
