### ISSUE TITLE
Conditional disable not working

### ISSUE THREAD

**Issue by Jerobie** [CalderaWP/Caldera-Forms#1509]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress 4.7.3 /  PHP 5.6.30

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Conditional disable of Caldera fields and buttons does nothing.  Conditional hide works perfectly with all other settings the same.

I've tried setting it up myself, and importing the .json file from this page: https://calderaforms.com/doc/repeat-email-confirm-using-conditionals/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None.

**Comment by Shelob9** [comment]
@Jerobie Thanks for reporting this bug. I just tested and it is in fact broken. I'll take a look this week.

**Comment by Jerobie** [comment]
Good stuff - thanks for the quick comment!

**Comment by Shelob9** [comment]
Close via 	e45865b
