### ISSUE TITLE
Action for when a Form is saved

### ISSUE THREAD

**Issue by lmartins** [CalderaWP/Caldera-Forms#151]
Hi, 

I've checked the documentation and this doesn't seem to exist at the moment. The use case here would be to force the caching plugin to clear cache, since im having serious issues with the combination of W3 Total Cache and Caldera Forms. Any change to a form causes the form to stop working, unless a cache clear is applied.

Have you considered having such hook available?

**Comment by Desertsnowman** [comment]
there is an action for this, but it wound help the current problem since the nonce is generated for each visitor. this problem should be solved in the current 1.2.x branch.

**Comment by lmartins** [comment]
Would you recommend to use this version directly with something like Github updated or should I wait for the .org release?

**Comment by Desertsnowman** [comment]
you can use the github version on branch 1.2.x this is a stable dev version

**Comment by Shelob9** [comment]
Closing as `caldera_forms_save_form` exists
