### ISSUE TITLE
The function setLocale in parsley js is not working

### ISSUE THREAD

**Issue by tshong1221** [CalderaWP/Caldera-Forms#1510]
What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3
PHP Version: 5.4.45
MySQL Version: 5.5.54
Caldera Forms Version: 1.5.0.8

Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

What Is The Unexpected Beahviour?
The console shows an Uncaught Error: zh_tw is not available in the catalog
    at p.setLocale (parsley.min.js:2)
    at j.d [as setLocale] (jquery.js:2)

**Comment by Shelob9** [comment]
@tshong1221  Is the file zh_tw.js being loaded? It should be at something like <your-content-directory>/plugins/Caldera-Forms/assets/build/js/i18n/zh_tw.js

**Comment by tshong1221** [comment]
No. It is not. But the translation of the validation can be shown correctly.
I have two websites, Both of them shows this error after I updated to 1.5.0.8.
There is a script like this added to my index:
<script> setTimeout(function(){window.Parsley.setLocale('zh_tw'); }, 2000 );</script>
but I cant find them anywhere in my files :(

**Comment by tshong1221** [comment]
Actually, I am not sure if zh_tw.js is being loaded or not.
The validation is in zh_tw but the console is showing this uncaught error. 
Btw, I found the script. It is added by the function : maybe_validator_i18n
which is located at  /plugins/caldera-forms/classes/render/assets.php.
I think the error may have something to do with this. Thank you.

**Comment by Shelob9** [comment]
@tshong1221 If you inspect the page source and search for zh_tw.js do you find that in a script tag?

**Comment by tshong1221** [comment]
Yes. There is a script tag like this:

<script type='text/javascript' src='https://www.mydomain.com.hk/wp-content/plugins/caldera-forms/assets/js/i18n/zh_tw.js?ver=1.5.0.8'></script>

And the console shows that the error is occur at this script tag:
<script> setTimeout(function(){window.Parsley.setLocale('zh_tw'); }, 2000 );</script>

**Comment by mrksdiehl** [comment]
I was struggling with this and now I feel stupid for how easy the solution is. Apparently Parsely likes the locale in a hyphen format. So renaming the zh**_**tw.js with underscore in assets/js/i18n/ to zh**-**tw.js with hyphen solves this problem. Same mistake probably applies to zh_cn and zh_cn.extra as well.

**Comment by tshong1221** [comment]
@mrksdiehl It works! Thank you.
