### ISSUE TITLE
Undefined index: "user" in classes\core.php

### ISSUE THREAD

**Issue by ESPONI** [CalderaWP/Caldera-Forms#1513]
v1.5.0.8
Undefined index: "user" in classes\core.php line: 3628
$data[ 'user' ] = apply_filters( 'caldera_forms_get_entry_user', $data[ 'user' ], $entry_id, $form );

'user' index could not exist in $data, when get_userdata does not find a user (for example deleted)

**Comment by Shelob9** [comment]
Before this https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L3636 need a check if `$data[ 'user' ]` is empty, if so, make it null before filter.

**Comment by Shelob9** [comment]
Close via 	8c8d2b6
