### ISSUE TITLE
use color to make autoresponder processor process more clear 

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1514]
from client's consultant --

One piece of feedback I'd like to offer is that the client couldn't figure out how to find the content in the Auto Responder email. He said since the Auto Responder button was gray in the 'Processors' section, it didn't look like actionable interface item.

-----

I feel like I've had this problem before too and using actionable colors to differentiate this would be the solution

**Comment by Shelob9** [comment]
Close via 		0ed769e
