### ISSUE TITLE
Checkboxes won't check.

### ISSUE THREAD

**Issue by ndehrman** [CalderaWP/Caldera-Forms#1517]
Caldera Forms Version 1.5.0.8
WordPress 4.7.3
PHP 7.0

Checkboxes themselves will not check. Checkbox label will check. This does not seem to be a problem for inline Checkboxes.
Terms & Conditions checkbox at checkout will not check at all.

**Comment by Shelob9** [comment]
@ndehrman Thanks for using Caldera Forms. We do appreciate it.

This is not the support form. Please use https://calderaforms.com/support
