### ISSUE TITLE
Paragraph Textarea and Star Rating Do Not Use Default Values When Editing Form Entries

### ISSUE THREAD

**Issue by jlangley** [CalderaWP/Caldera-Forms#1520]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3PHP Version: 5.6.30MySQL Version: 5.6.28Caldera Forms Version: 1.5.0.8WP_DEBUG:

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
I'm on a production build, so not able to easily test this. If you cannot replicate my issue, I'll stand up a sandbox and try.

## What Is The Unexpected Beahviour?
When attempting to edit a submitted form that has "paragraph textarea" and "star rating" controls, no default value is set on those controls. This makes editing the previously submitted forms impossible because the new (blank/standard) defaults will override the previously submitted values.

## What PHP Errors Have You Logged While Reproducing This Bug?
No Caldera Forms errors. When I turn on PHP Debug logging, I see this:

> Strict Standards: Non-static method OLT_Tab_Shortcode::add_shortcode() should not be called statically in /home/gardenth/public_html/wp-content/plugins/tabs-shortcode/tabs-shortcode.php on line 79
> 
> Strict Standards: Non-static method OLT_Tab_Shortcode::has_shortcode() should not be called statically in /home/gardenth/public_html/wp-content/plugins/tabs-shortcode/tabs-shortcode.php on line 67
> 
> Strict Standards: Non-static method OLT_Tab_Shortcode::add_shortcode() should not be called statically in /home/gardenth/public_html/wp-content/plugins/tabs-shortcode/tabs-shortcode.php on line 80
> 
> Strict Standards: Non-static method OLT_Tab_Shortcode::has_shortcode() should not be called statically in /home/gardenth/public_html/wp-content/plugins/tabs-shortcode/tabs-shortcode.php on line 67

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No javascript errors.

**Comment by Shelob9** [comment]
The paragraph field is now fixed via #1538

**Comment by Shelob9** [comment]
Close via  3b86fc1 (paragraph issue) and 		ececb0b (default for stars)
