### ISSUE TITLE
Paragraph field doesn't render magic tags or field slugs correctly on front-end.

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1525]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5.0.8, 4.7.3, 7.0.3

## What Is The Unexpected Behaviour?
When using magic tags for default value in paragraph fields, such as `{ip}` or `{user:user_login}` the following displays on the front-end:

<img width="669" alt="screen shot 2017-04-21 at 11 33 22 am" src="https://cloud.githubusercontent.com/assets/12629136/25272254/7a8c7646-2687-11e7-9d4a-8faf390c2a63.png">

When using field slugs for default value in paragraph fields, such as %first_name% in this example, it returns the Field ID:

<img width="642" alt="screen shot 2017-04-21 at 11 32 40 am" src="https://cloud.githubusercontent.com/assets/12629136/25272293/94a03004-2687-11e7-8326-8474682525c2.png">

**Comment by Shelob9** [comment]
Close via  3b86fc1
