### ISSUE TITLE
Condition values not loading on processors

### ISSUE THREAD

**Issue by juan-quiver** [CalderaWP/Caldera-Forms#1526]
I have 3 different kinds of processors (Run Action, Stripe and Auto Responder), all of which are conditional based on a Hidden field being greater than zero like:

![processors](https://cloud.githubusercontent.com/assets/19435349/25290519/0d999dae-2694-11e7-8e63-32f26e882b75.PNG)

This works well and the condition value is saved (I can tell because my form works as expected), but whenever I go back to the form, these values are not loaded back from the DB, hence if I'm not aware of setting them again to zero, make any other change to the form and save it, my processor conditions are lost and my form breaks.

![empty processor](https://cloud.githubusercontent.com/assets/19435349/25290628/7833c608-2694-11e7-9980-9e87d18f14a9.PNG)

WordPress Version: 4.7.4PHP Version: 5.6.30-1+wpengine8MySQL Version: 5.6.35Caldera Forms Version: 1.5.0.8WP_DEBUG: 1

**Comment by Shelob9** [comment]
@cicichirinos Please test this. Is this just beacuse the value is 0? Or does issue happen with value of 1 or 42 or "frogs". If so, the issue must be that somewhere the value isn't being saved beacuse `if( empty( 0 ) )` evaluates false, or it's not being displayed for the same reason.

**Comment by Shelob9** [comment]
Close via 	d834095
