### ISSUE TITLE
[documentation] Where to find the roles/users settings?

### ISSUE THREAD

**Issue by strarsis** [CalderaWP/Caldera-Forms#1527]
Related to: https://github.com/CalderaWP/Caldera-Forms/issues/1159

Where can I set up what roles/users can view the form entries?
I am not able to find anything roles/users related in the edit section of the form.

**Comment by Shelob9** [comment]
@strarsis This setting is in the Form Setting tab of the form editor. Enable the "Show Entry View Admin Page?" to reveal the user role settings.

**Comment by strarsis** [comment]
Thanks, I was able to find + enable it. 
The caption is a bit confusing though ("Show Entry View Admin Page?", "Create a sub-menu item of the Caldera Forms menu and a page to show entries for this form?") because it doesn't indicate this can be used for adding an admin item/access to other user roles.
