### ISSUE TITLE
make new conditional group more obviously actionable

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1532]
"add new conditional group" button in blank conditional group screen is not obviously an actionable item, should be obviously an actionable item by pulsing button when no conditionals present

related: #1514

**Comment by Shelob9** [comment]
@cicichirinos Keep the following in mind:

- This comment: https://github.com/CalderaWP/Caldera-Forms/commit/0ed769e6efd5c7af5f9ee6f3aad1a5a9e9c52bf0#diff-db9bdfee6f77ca16fb0c65548c281ff7R2361 (BTW Every other thing I'm about to explain makes this less of an issue, but still, the variable should be named more descriptively.)

- The HTML for the conditions panel and the JavaScript are generated in /ui/panels/conditions.php

- I <em>think</em> that clicking on the conditionals tab initializes the conditionals system. (yah everytime, which is insane) - look at L257 `$( document ).on('click', '#tab_conditions', function(){`. If I'm right, use that to start this maybe pulse/maybe add primary button class system. Also, #FML.

- L214 the closure starting with `$( document ).on('click', '[data-add-group]', function(){` is where the group is added, so you can stop the pulse, change the button class back there.
