### ISSUE TITLE
Issue with masking

### ISSUE THREAD

**Issue by dsn240** [CalderaWP/Caldera-Forms#1537]
Hello

Ok Im having this trouble with single line field
With a masking for phone  (i know is not the official way)
This is the masking
+52[9{10}]

This is how appear in summary and entries
![image](https://cloud.githubusercontent.com/assets/24656696/25314688/38fa963a-280e-11e7-9483-c33cf13506f6.png)

I make some testing in pc and phones
I was able to replicate with an android phone with Gboard active on chrome beta

I know there is a new field for phone  :) i'm happy with it and i'm happy with caldera, just sharing what i found out
bye!

**Comment by Shelob9** [comment]
Closing out this old issue as I'm updating masking and phone fields via #1118 which should resolve these issues.
