### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by bluelogicdigitalllp** [CalderaWP/Caldera-Forms#1541]
When we try to Export all Entries in one of our forms, we get the following error:

Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 65844969

System info:
WordPress Version: 4.7.3
PHP Version: 5.5.9-1ubuntu4.13
MySQL Version: 5.5.44
Server Software: Apache/2.4.7 (Ubuntu)
Caldera Forms version: 1.5.0.6

**Comment by bluelogicdigitalllp** [comment]
When we try to Export all Entries in one of our forms, we get the following error:

Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 65844969


**System info:**
WordPress Version: 4.7.3
PHP Version: 5.5.9-1ubuntu4.13
MySQL Version: 5.5.44
Server Software: Apache/2.4.7 (Ubuntu)
Caldera Forms version: 1.5.0.6

**Comment by Shelob9** [comment]
@bluelogicdigitalllp Thanks for using Caldera Forms. If you would like to report an issue, we really need the information we requested in the issue template.

We need to know if you were able to log any PHP errors.

Most importantly we need to know if this is happening with the latest version. IE do the fixes for similar issues int he last two releases solve your problem? 

Please upgrade to the latest version and re-test with PHP debug logging on, if you find the same problem please reopen this ticket. If you need support, please use https://calderaforms.com/support to open a ticket.
