### ISSUE TITLE
Parsley form:error firing multiple times

### ISSUE THREAD

**Issue by bishwadeepkc** [CalderaWP/Caldera-Forms#1549]
Hello,
I am using this plugin since 2015. This is an awesome plugin. Recently after updating the plugin to 1.5.0.6, I am having some issues with form validation. Previously, jQuery was used for form validation however, now Parsley is used for form validation. I have updated all the form validation functions accordingly.
The only issue I have now is that parsley’s form:error handle is called multiple times.
To be more specific, I have list of courses(http://studyselect.local/university-courses/) on this page. A form loads when the enquire online button is clicked. I am sending stats to Google analytics every time there is a form validation error. Its working fine when I load a form for first time. However, when I close the form and open another one, the event is fired 2 times and it adds up every time I open a new form.
I am using:
`window.Parsley.on('form:error', function() {
  //my code here
});`
Please let me know if you need more information.

Thank you,
BD

**Comment by Shelob9** [comment]
@bishwadeepkc Thanks for using Caldera Forms.

Your way of adding additional validation is one of the problems #1535 solves (the other being the unpredictable order the events will fire. Note that custom event is not in 1.5.0.8, only 1.5.0.9 (IE master branch here for now, on WordPress.org next week).

If you need help implementing the custom event, please open a support ticket at https://CalderaForms.com/support
