### ISSUE TITLE
"No lists or invalid API key" => CURLOPT_SSL_VERIFYPEER 

### ISSUE THREAD

**Issue by AlchemyUnited** [CalderaWP/Caldera-Forms#1555]
Latest version of CF. Latest version of CF's MailChimp add on. PHP 5.5.24.

Long to short I have having problems getting the API key to work. I kept getting the error: No lists or invalid API key. I knew the key was good. And I did have a list. I'm on a deadline - that has since passed :( -
 so I decided to poke around.

 I started with drewm's MailChimp API library (in vendor folder)  

The problem seems to be this:

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, $this->verify_ssl);

Your plugin has verify_ssl set to true. Since I'm not running SSL local (or - yet - on the client's site) MC returns an error. At least I presume that's what's happening, I'm no curl expert. 

If I change verify_ssl to false, I get a proper reply. 

Obviously, making this change in the add-on code itself is not practical. The solution needs to be make in the plugin. Perhaps this can be an option? 

Since fixing that, I've bumped into other issues (which I'll detail in another issue / ticket).

tia. i hope this helps.

**Comment by Shelob9** [comment]
@AlchemyUnited This repo is for Caldera Forms bugs, not add-ons. Use https://calderaforms.com/support to open a support ticket for Caldera Forms MailChimp and please let us know what version of Caldera Forms and the mailchimp add-on you are using. "latest" is not specific enough.

This sounds like it's an issue that should be opened here: https://github.com/drewm/mailchimp-api
