### ISSUE TITLE
MailChimp add-on => multiple bugs?

### ISSUE THREAD

**Issue by AlchemyUnited** [CalderaWP/Caldera-Forms#1556]
Once I got past the CURLOPT_SSL_VERIFYPEER issue (as mentioned in a different issue / ticket the add-on was able to communicate with MC. However...

My form in Caldera has 3 visible fields

- first name
- email
- interest (this is a select / drop down)

There are also some hidden fields that I want to pass to MailChimp. For example, post_id (of the form submission page), utm_* (e.g., utm_source as see in the URL).

=> Problem 1 - On the Form Processor page, I'm unable to map the hidden fields to their MC counterparts. In fact, the Caldera hiddens don't even show up in the selects / dropdowns. There no way - that I can see - where I can get "MC Field X = hidden CF Field Y." 

Note: If I switch a CF field from hidden to visible it's then in the selects / dropdowns. However, I don't want these marketing / tracking fields visible on my form. They are strictly for internal / analytics purposes. Maybe I'm supposed to use variables instead? 

=> Problem 2 - Once I submit the form, the entries captured in Caldera are there. The utm_* etc are captured. All good! 

However, the only thing that makes it into MailChimp is the email address. No errors, etc. From the frontend and backend of WP all seems like it should be fine - sans the previously mentioned mapping issue - but once the entry shows up in MailChimp the only data there is the email address. I've changed the CF slugs values to match their MC merge tags counterpart, but that didn't help either. 

So to clarify, Caldera captures everything, as expected, but nothing but the email address makes it into MailChimp. 

p.s. Any tips on debugging such issues would be a plus. Perhaps - at some point - CF / MC could have a debug mode. I'll do some more digging around today but the depth and extent of these bugs (?) seems significant in the sense I'm not so sure I'll be able to hack my way into getting this phase of this project completed on time :(

**Comment by Shelob9** [comment]
@AlchemyUnited This repo is for Caldera Forms bugs, not add-ons. Use https://calderaforms.com/support to open a support ticket for Caldera Forms MailChimp and please let us know what version of Caldera Forms and the mailchimp add-on you are using. "latest" is not specific enough.
