### ISSUE TITLE
MailChimp add-on => Subscriber Status goes MIA

### ISSUE THREAD

**Issue by AlchemyUnited** [CalderaWP/Caldera-Forms#1557]
This is two things in one, kinda.

First, it appears (i.e., I'm still testing / trying) that once there are updates / changes to a CF form the Processor (in this case MailChimp) needs to be deleted, and that processor setup needs to start over. From scratch. Sound about right? Maybe? 

That said, in doing so (twice now) the Subscriber Status option did not appear on the form. I didn't notice this, I saved the form and then tested it from the front end. That logged an error that basically comes down to $config[ 'status' ] in includes/functions.php not being set. Missing index or whatever the error is. 

That is, at some point $config[] gets initialized but not with any default values. 

Moi? When it makes sense, the pattern I prefer to follow is that I initialize my "config arrays" with "worst case" default values. In this case, I think status would be set to subscribed. This way, if something goes wrong, they'll always have to confirm their subscription. 

The other advantage of starting with key => value pairs is then you don't have to use isset() on the keys - which btw isn't happening now either. You always start with something, 

I'd go for a PR but I'm not sure what the initial / default values should be for that particular array. I'll leave that up to y'all but there's definitely something wonky with how this is working. 

thx again. 
mfs

**Comment by Shelob9** [comment]
@AlchemyUnited This repo is for Caldera Forms bugs, not add-ons. Use https://calderaforms.com/support to open a support ticket for Caldera Forms MailChimp and please let us know what version of Caldera Forms and the mailchimp add-on you are using. "latest" is not specific enough.

**Comment by AlchemyUnited** [comment]
"latest" is not specific enough."

You're joking, right? I take MY time to FYI about a bug in YOUR product...and now you're going to complain about it? The word you're looking for is "Thank you." 

Pardon me but...that's fucked up. 

AND - what's funny is - this actually traces back to core.php in the Caldera Forms main plugin. An array of args

	// set default config
	$config                   = array();

doesn't get a default value for status. It assumes something downstream will fill in that blank. Well, there's ANOTHER bug down stream so that assumption is a bad on. 

You're welcome. 

p.s. Just so you know,  I've been going back and forth with support@ and I'm 2 days in the deadline hole with trying to get resolution there. So this isn't the place either? Nice. I'll be sure to let my client know that - as if he f'in cares.
