### ISSUE TITLE
Conditional Logic still broken on 1.5.0.9

### ISSUE THREAD

**Issue by lmartins** [CalderaWP/Caldera-Forms#1559]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WP: 4.7.4
Caldera Forms 1.5.0.9

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Beahviour?
A few updates back, the logic for conditional fields was completely destroyed. Anything field that was hidden by conditionals stopped being hidden and it was always rendered. 
The last few updates changed this behaviour but it still didn't fixed it. If a field is initially hidden by a condition, once that condition is met, only the label is then shown, the field stays invisible.

The temporary workaround I've used so far was to disable the fields instead of hiding them. This works to some extend, far from ideal, but then I've faced another problem. Any field that is set as required, it will cause the form to fail validation on submit, even being disabled. This last part maybe not an error per si, but combined with the conditional errors and considering this was the only workaround possible it is quite unfortunate, render CF pretty much unusable at this point.
I love this plugin, have been heavily promoting it whenever I can, so yeah, a bit frustrating and disappointing that this problem has persisted for so long (has been like this for at least 2 months).

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No JS errors in console

**Comment by RalphGL** [comment]
Hi i am new to caldera forms and have created some forms with it in the last days. There are some problems, but i had **no** problem with conditional logic in WP: 4.7.4 and Caldera Forms 1.5.0.8. Have you exported the "problem form" and imported it at another (clean) WP install? Maybe i can test your form on my (test) installation to help.

**Comment by Shelob9** [comment]
@lmartins Thanks for the report. Sorry about the frustrating bug.

I can't reproduce this. Is this form a fair test? https://www.dropbox.com/s/f2br6m5tfg97s9c/conditional-first-export.json?dl=0

I've never seen label show, but not input. Have you tested with the default WordPress theme and any caching plugins disabled? Many themes or page builders add weird formatting to post content, which can make our targeting of fields with jQuery not work properly.

**Comment by lmartins** [comment]
@Shelob9 I'll test your config on the same site.
In the meantime, here's a screenshot of the DOM and UI being rendered onto the screen when the fields are set to be hidden depending on the first radio button:
https://cl.ly/0T2K3z373h1w
