### ISSUE TITLE
Toggle Switch Values Not Included In Calculation

### ISSUE THREAD

**Issue by marcellein** [CalderaWP/Caldera-Forms#1563]
Caldera version: 1.5.0.9
Wordpress: 4.7.4

There is a bug that came with the latest caldera version. I created a calculator which is based on some input numbers and variables. Today I checked the calc and nothing did work.
I tried to figure out the problem by deleting different parts of the calc. 
Without my day/month/year changer the calculations do work, but if it is integrated there is always 0.
Day=365; month=12; year=1 (values)
Everything should be setup correctly and I need to fix it asap. How about an older version of caldera?

The files for the english and german translator are uploaded via google drive here:

https://drive.google.com/open?id=0B_dxxi6GMIORSXF2V3dVQWRPNXc

**Comment by NedzadB** [comment]
First have to say that I love Caldera Forms, but I am having the same problem with toggle switch. Everything worked fine until update to 1.5.0.9.  I have following condition
Show=Subtotal
(If Toggle Switch = Yes AND User Input > 0)
When condition is met it does not show Subtotal .

**Comment by marcellein** [comment]
@NedzadB yeah, exactly that.

I changed from toggle switch to dropdown and everything is working again.
I recommend doing that, even though it isn't optimal.

**Comment by NedzadB** [comment]
I happened to have earlier version and rolled back and it works again just fine not sure if it will auto upgrade to new version again.

**Comment by Shelob9** [comment]
Probably caused by changes for #1484

Specifically, this the default in the switch statement does not handle toggle fields properly.


>Everything should be setup correctly and I need to fix it asap. How about an older version of caldera?
I recommend the plugin WP Rollback for that.

**Comment by Shelob9** [comment]
Close via 	135d6ac
