### ISSUE TITLE
Custom class not outputted in hidden field markup

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1564]
Reported here: https://wordpress.org/support/topic/custom-class-not-working-with-hidden-field/

**Comment by jayyogvihalkrupa** [comment]
any update ?

**Comment by jayyogvihalkrupa** [comment]
any update ?

**Comment by jayyogvihalkrupa** [comment]
any update ? @Shelob9 @cicichirinos @mgibbs189 @lynxlynxlynx @Desertsnowman 

Thanks

**Comment by Shelob9** [comment]
This was broken in 	8d2e27b

**Comment by Shelob9** [comment]
Close via 		96e6133

**Comment by jayyogvihalkrupa** [comment]
Where we add code and how?

**Comment by jayyogvihalkrupa** [comment]
have you fixed on plugin and launch as new version?

**Comment by jayyogvihalkrupa** [comment]
Any update?

**Comment by jayyogvihalkrupa** [comment]
Please check issue
It is Not Working.It is issue with LAtest version 
Don't send previous issues link

See screenshot and settings
[](http://prnt.sc/f4hh3n)
[](http://prnt.sc/f4hh78)
@Shelob9 @cicichirinos @mgibbs189 @lynxlynxlynx @Desertsnowman

**Comment by jayyogvihalkrupa** [comment]
http://prnt.sc/f7b272
@Shelob9 @cicichirinos  @mgibbs189  @lynxlynxlynx @Desertsnowman

**Comment by lynxlynxlynx** [comment]
Hey, stop with the spamming. Have you applied the patch? If not or you can't, wait for the next release.

**Comment by jayyogvihalkrupa** [comment]
Yes already did on plugin
