### ISSUE TITLE
caldera form width

### ISSUE THREAD

**Issue by estevecom** [CalderaWP/Caldera-Forms#1567]
Hi,

I have a simple question. testing caldera forms , i get a too small form : 
http://www.venezia-huissiers.com/demande-de-constat/

how to have it on 100% width?

thank you very much!
Pierre

**Comment by Shelob9** [comment]
Hi @estevecom  Thanks for using Caldera Forms.

The form should be 100% width, please try again using the default theme, as this looks like a site specific issue. 

I am closing this, since this is not a bug, if you need support please use CalderaForms.com/support
