### ISSUE TITLE
Using calculation magic tag inside HTML shows up blank

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1568]
Using %calculation_field% inside of an HTML field does not show the calculation total.

**Comment by Shelob9** [comment]
@andrewlimaza Can you please test this with the fix for #1563 to see if it is still an issue?

**Comment by andrewlimaza** [comment]
Tested this and still shows blank, the HTML field used %total% to display the total in the HTML field.

<img width="597" alt="screen shot 2017-05-09 at 7 18 35 pm" src="https://cloud.githubusercontent.com/assets/12629136/25863490/55e7647c-34ec-11e7-8eef-1cb02b6c8c9e.png">

**Comment by andrewlimaza** [comment]
<img width="403" alt="screen shot 2017-05-09 at 7 19 29 pm" src="https://cloud.githubusercontent.com/assets/12629136/25863531/76d6a47c-34ec-11e7-9b92-8b342d01a148.png">

**Comment by Shelob9** [comment]
close via 		1ecfdba
