### ISSUE TITLE
Conditionals based on calculation field values not using the correct value

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#1570]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5.0.9  and WP 4.7.4

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behavior?
Before this version I had a hidden button that would show only with a if 'greater than' > 0 condition for a calculation field. It doesn't work anymore for some reason after the latest update.

**Comment by Shelob9** [comment]
Possibly related #1526

**Comment by tshong1221** [comment]
I am having the same problem with version 1.5.0.9 and WP 4.7.4.
I set a condition: When X field is greater than 500, Y field will hide.
But nothing happen even X field is much greater than 500.
I tried on both single-page form and multi-page form. Nothing change.
After I downgrade Caldera Forms back to 1.5.0.6, it works.
And the problem I have in #1510 also disappeared in 1.5.0.6.

**Comment by Shelob9** [comment]
Close via 	a7398e4
