### ISSUE TITLE
Phone Field (Better) Still Submits Empty - If Required Is Selected

### ISSUE THREAD

**Issue by E31C** [CalderaWP/Caldera-Forms#1574]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

WordPress Version: 4.7.4PHP Version: 5.6.30MySQL Version: 5.6.35Caldera Forms Version: 1.5.0.9WP_DEBUG: 1

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?

Yes

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.

1.) Selected 'Required' for Phone Field (Better)
2.) If Submit Form is pressed require fields show up - except Phone Field (Better) - Green
3.) Can submit an empty phone field even though if required is selected backend

![screen shot 2017-05-10 at 6 47 39 am](https://cloud.githubusercontent.com/assets/26536264/25883690/feafb108-354c-11e7-8962-78bc7cae4546.png)
![screen shot 2017-05-10 at 6 47 58 am](https://cloud.githubusercontent.com/assets/26536264/25883691/feb36fa0-354c-11e7-9cc1-4048e06b531a.png)

**Comment by Shelob9** [comment]
@E31C Thanks for using Caldera Forms and for reporting this bug. Can you please add a screenshot of the form settings so I can make sure I'm reproducing this correctly?

**Comment by E31C** [comment]
@Shelob9  Hi Josh, thanks for taking this up.

Please find 2 screenshots attached.

![screen shot 2017-05-16 at 6 38 31 am](https://cloud.githubusercontent.com/assets/26536264/26090047/91725770-3a02-11e7-90dd-34d83d49a339.png)
![screen shot 2017-05-16 at 6 39 06 am](https://cloud.githubusercontent.com/assets/26536264/26090048/91735d50-3a02-11e7-8aba-3c09388f92d0.png)

**Comment by E31C** [comment]
@Shelob9 thanks for the update on this issue 👍  , were you able to replicate this on your side? I was forced to move to Contact Form 7 which is horrible, should I maybe try a fresh install and not change the country code? I'd like to move back to Caldera as soon as possible.

**Comment by Shelob9** [comment]
Close via 	b76ca60
