### ISSUE TITLE
Ajax submission fails in 404 when using a non simple permalink ...

### ISSUE THREAD

**Issue by vthoule** [CalderaWP/Caldera-Forms#1580]
Hi Caldera Team,

We are experiencing an issue similar as the one detailed in #404 ...
As soon as we have a non simple permalink (our current permalink is /index.php/%postname% ), the Ajax submission of form fails in 404.
Is there always a bug or do we miss some additional settings ?
Do we have some customization to append in header.php ?
... ?

We are using WP 4.7.4 with "Alcheme" theme and Caldera Forms 1.5.0.9
Thanks by advance
Vincent

**Comment by Shelob9** [comment]
@vthoule Thanks for using Caldera Forms.

This is a different issue than #638 which was about errors happening during AJAX submission, this is about our inability to support that kind of permalink for AJAX sumissions, which I am OK with, as having index.php in your permalinks is a bad idea.

You should contact your host to fix that. In the meantime, you will need to disable AJAX submissions.
