### ISSUE TITLE
Extra word

### ISSUE THREAD

**Issue by dedland58** [CalderaWP/Caldera-Forms#1581]
## What Is The Unexpected Beahviour?
The confirmation email sent to the form submitter contains an extra "get" as shown below:-
Hi **** .
 Thanks for your email.
 We'll get get back to you as soon as possible!
 Here's a summary of your message:

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms

You can change that message. See the documentation: https://calderaforms.com/doc/using-caldera-forms-auto-responder-processor/
