### ISSUE TITLE
Minor bug with range slider field and multipage forms

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1587]
Default value does not work on range slider on multipage form, any page number except the first page.

Here is screenshot (default value is set to 0, to show in the middle of the slider, - range is -100 to 100)

<img width="579" alt="screen shot 2017-05-16 at 11 52 01 am" src="https://cloud.githubusercontent.com/assets/12629136/26100613/af170efc-3a2e-11e7-99a4-33e97585cc5c.png">

PHP error, not sure if it's related - [16-May-2017 09:47:32 UTC] PHP Warning:  implode(): Invalid arguments passed in /app/public/wp-content/plugins/caldera-forms/processors/classes/ui.php on line 330

**Comment by Shelob9** [comment]
Helpscout #1884

**Comment by Shelob9** [comment]
Actual issue is that the onSlide method is called when field is initialized and if it's on page 2, that sets value to 0.

**Comment by Shelob9** [comment]
Close via 	a0e71c2
