### ISSUE TITLE
Using conditions on Calculations not working

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1588]
You are unable to show/hide fields with conditions on Calculation fields.

For example - show Field A, if subtotal is greater than 10.

**Comment by Shelob9** [comment]
@andrewlimaza Can you please test against master. This should be fixed.

**Comment by andrewlimaza** [comment]
@Shelob9 I have just tested this and this sort of works.

The total number flickers if you meet the minimum requirement of the total. For example, show discount field (hidden field) if the total amount is greater than 100. If you set the total amount to 110 it shows true but then the discount is applied to the amount (in this case $20 is the discount) which makes the total 90 so the condition is showing between true and false and the number flickers between 90 and 110 in an infinite loop (does not break the site). If the total amount including the discount is greater than 100 it works as intended (for example set total to 150 - 20 = 130, the condition is still true).

**Comment by Shelob9** [comment]
Closing as we discussed this an it was circular logic to blame.
