### ISSUE TITLE
How to send a HTTP POST with the form data to another URL

### ISSUE THREAD

**Issue by salian** [CalderaWP/Caldera-Forms#1589]
Perhaps this is mentioned in the documentation but I couldn't find it - how do I send the form data as an HTTP POST to an external URL where I can further deal with it myself?

This would be the equivalent of https://wordpress.org/plugins/forms-3rdparty-integration/

Is this supported already, or do I have to write some post-submission ajax js code to do this?

**Comment by Shelob9** [comment]
@salian There is a caldera_forms_submission_url filter for this. https://calderaforms.com/doc/caldera_forms_submission_url/

If you need help with this or have other support requests, please use our support form at https://calderaforms.com/support
