### ISSUE TITLE
Submit problem (loading at infinite)

### ISSUE THREAD

**Issue by LAlex14** [CalderaWP/Caldera-Forms#1590]
Hello, i use Caldera Forms 1.5.0.9

SOMETIMES my form will not be able to SUMBIT (or go to the NEXT page). SOMETIMES it will. When it can't submit, basically Its loading at infinite and form will not submit(Mail is not sent,It does not register in `entries)`

But  my form is long and I cannot have users reloading page any time there is an error.

THis error seems to occur about 20-25% of the time. It has occured in differenc browsers Chrome,  Firefox, and IE.

I thought perhaps it was a time out error because sometimes when I return to a form, it no longer works. But other times it doesn't work from the getgo.
Please help me!
![default](https://cloud.githubusercontent.com/assets/28743656/26133031/fcc580ec-3aac-11e7-91c1-2575e25b1de2.PNG)

**Comment by Shelob9** [comment]
@LAlex14  Thanks for using Caldera Forms. Please go to https://calderaforms.com/support and read the section `Please Read Before Requesting Caldera Forms Support`. That's the best advice I have to understand why this is happening on your site. If you need help troubleshooting your issue, please open a support ticket on our site.
