### ISSUE TITLE
Autotesting forms?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1594]
Because of various errors with Caldera Forms either inside of CF our from outside forces a client of mine is once a week testing the order form in various browsers to see if it works. It is cumbersome but needed because of earlier problematic experiences.

I am thinking that there could be somekind of automatic testing where one could get a summery that all the forms are working. Setting up an auto test to test daily that the forms are working as they should.

**Comment by Shelob9** [comment]
@paaljoachim Yes, I would love to have Selenium or similar to automate UI testing. Chris Weigman gave me a pretty strong pitch for it once.

This is way beyond our capabilities as an organization right now.
