### ISSUE TITLE
Magic tags showing up blank in Email Notification ( subject etc. )

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1595]
Inside the email notifications settings if you set the Subject to "Email from - %magic_tag_of_field%" the subject  shows "Email from - "

Tested with version 1.5.0.9

**Comment by Shelob9** [comment]
@andrewlimaza I am closing this. If you can reproduce against master, then reopen. Please don't open tickets without testing against master.
