### ISSUE TITLE
1.5.0.9 View of an entry with radio button select always displays the same value/label

### ISSUE THREAD

**Issue by vtad** [CalderaWP/Caldera-Forms#1598]
WP 4.7.5, php 5.6 CF 1.5.0.9

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The form contains 2 Select radio buttons with label "YES" and "NO", both with the value 0 for the "YES"
option.
The generated email has the correct seleted values.
Also the values in the DB (wp_CF_form_entry_values) are the correct ones.

But the "View" display of any entry shows always the "YES" selection.

**Comment by vtad** [comment]
Found a work around: Use a variable with value = 0 as value for the YES  option. The calculation still works ok.

**Comment by Shelob9** [comment]
@vtad Thanks for using Caldera Forms. Both options can't have the same value. It shouldn't have let you save the form.
