### ISSUE TITLE
FEATURE: Please add a new field for only text

### ISSUE THREAD

**Issue by Chris2011** [CalderaWP/Caldera-Forms#1600]
Caldera Form version: 1.5.0.9
WordPress version: 4.7.5

I was wondering, why it is not possible to create a simple label without having controls. So I decided to create a HTML field and added text to it, but this is only a workaround for me. It should be possible to add a simple textlabel/textblock without any other control.

Regards

Chris

**Comment by Shelob9** [comment]
@Chris2011  Thanks for using Caldera Forms. I think what you're asking for is a `<label>` element, with no input. That is not something I would not want to support for two reasons:

1. It is not semantic. This is a problem for screenreaders and other assistive technologies.
2. You can always use an HTML field to add non-field markup to your form.

**Comment by Chris2011** [comment]
Yes I used HTML but I thought for such thing a simple label or maybe a div which could have text should be possible out of the box. Because for me I was wondering where it is, how could I create such thing. After some minutes of searching the fields I decided to use HTML for this.
