### ISSUE TITLE
QUESTION: Possible to combine more than 1 control in 1 field?

### ISSUE THREAD

**Issue by Chris2011** [CalderaWP/Caldera-Forms#1601]
I was wondering, whether this is possible or not: 
![one-field](https://cloud.githubusercontent.com/assets/795658/26317068/8a1bb778-3f16-11e7-9c8d-e52912072e39.png)

Regards

Chris

**Comment by Chris2011** [comment]
So it means, that you have 1 field but with 2 controls inside of it. It could be possible with the HTML field, didn't test it yet, but seems like a workaround or?

**Comment by Shelob9** [comment]
@Chris2011 I think what you are asking for is a repeating field. This is a planned feature, that is not yet implemented.

Also, please keep in mind support is available at https://calderaforms.com/support

**Comment by Chris2011** [comment]
Thx for your answer.
