### ISSUE TITLE
Generic CSS style conflicts, how to disable on custom post types?

### ISSUE THREAD

**Issue by tripflex** [CalderaWP/Caldera-Forms#1604]
It seems that a bit of the admin CSS is very generic selectors, things like `.popover` ... which IMO should be more specific, like `.cwp.popover`, as it causes problems with my plugin styling on my custom post type pages.

How can I disable Caldera Forms from adding the media button and enqueuing styles/scripts on my custom post type pages?

Do I have to manually add code to my plugin to dequeue assets and remove the action associated with `media_buttons` for Caldera Forms, or is there a filter or some other way to prevent this from happening on specific custom post types?

**Comment by Shelob9** [comment]
Hi Miles :)

See this for removing shortcode button and its JavaScript:
https://gist.github.com/Shelob9/7dd652bfdda104926ceccde4556af0b7

To remove all JS/CSS use something like this, but conditionally:

`add_action( 'caldera_forms_includes_complete', function(){ remove_action( 'admin_enqueue_scripts', array( Caldera_Forms_Admin::get_instance(), 'enqueue_admin_stylescripts' ), 1 ); });`

**Comment by tripflex** [comment]
Awesome, thank you :)
