### ISSUE TITLE
Logging the issues reported earlier at wordpress.org

### ISSUE THREAD

**Issue by Mantukai** [CalderaWP/Caldera-Forms#1606]
Hello, Josh.

Being unfamiliar with the process I earlier reported the issues on wordpress.org (https://wordpress.org/support/topic/reporting-more-bugs-in-1-5-0-9/#post-9147231).  According to your email I am re-opening the ticket here.

I have the same form published on 2 different sites - one running 1.5.0.8 and the other 1.5.0.9.  I believe I can send you the URLs at contact@calderaforms.com so you can take a look?

I would like to connect personally to tell you more, I am out of LinkedIn credits and I can't disclose my email address here.  Can you send me a single message to a throwaway address here - 24f6f161@opayq.com?

Regards,

**Comment by Shelob9** [comment]
@Mantukai - I'm sorry about the confusion. This is a location for reporting bugs that are not unique to a site -- IE They can be reproduced with just the default theme. If you believe you have that kind of bug, please open a support ticket and fill out all of the sections in the issue template.

If you need support using Caldera Forms on your site, or working with a site-specific issue, please use CalderaForms.com/support to open a ticket if you own an add-on. if you do not own an add-on, you can purchase one or a priority support license at https://calderaforms.com/downloads/caldera-forms-priority-support/

**Comment by Mantukai** [comment]
@Shelob9 
This is a not a support issue, I don't need support.
1.5.0.8 works fine, 1.5.0.9 does not.  I just wanted to help you pinpoint a bug.
