### ISSUE TITLE
BCC list cannot have more than one email address

### ISSUE THREAD

**Issue by schungx** [CalderaWP/Caldera-Forms#1607]
Instructions of the BCC email address input box says:

> Comma separated list of email addresses to send a BCC to.

This is WRONG.  Comma-separated list of email addresses will make the mailer choke and never send out the notification emails.  The usual delimiter for email addresses is a semicolon, NOT a COMMA.

You probably confused it with the CSV download instruction on the same page, because CSV files have comma delimiters.

The correct instructions should be:

> Semicolon-separated list of email addresses to send a BCC to.

**Comment by schungx** [comment]
Well, it seems that the entire BCC line is take as ONE SINGLE email address.

Comma ==> Choke\
Semicolon ==> First email address in the list gets mail, the others no\
Space ==> First email address in the list gets mail, the others no

**Comment by schungx** [comment]
I'm using SendGrid by the way.

**Comment by schungx** [comment]
The reason for all these seem to be this line in `save.php`:

    $mail['headers'][] = Caldera_Forms::do_magic_tags( 'Bcc: ' . $form['mailer']['bcc_to'] );

`wp_mail` takes an array of headers, and each `Bcc:` header must only contain one email address.  Obviously, in order for this to work with multiple emails, `bcc_to` must be split by the delimiter character into an array and multiple `Bcc:` headers added, one for each.

**Comment by Shelob9** [comment]
@schungx  Thanks for using Caldera Forms and reporting this.

Are you using our SendGrid integration or the SendGrid plugin?

Also what version of Caldera Forms and PHP are you using?

**Comment by schungx** [comment]
Using SendGrid for WP plugin, so the Email setting is "WordPress" and not "SendGrid".

Caldera Forms 1.5.9.
