### ISSUE TITLE
 Fatal error: Call to undefined function rest_url() 

### ISSUE THREAD

**Issue by shawnhooper** [CalderaWP/Caldera-Forms#1613]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

WordPress 4.2.2
Caldera 1.5.1-b-1 
PHP 7.1.1 (cli) (built: Feb  8 2017 14:02:51) ( NTS )

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?

Yes

## What Is The Unexpected Beahviour?

When navigating to `/wp-admin/admin.php?page=caldera-forms` the following error appears in the browser: `Fatal error: Call to undefined function rest_url() in /Users/shawnhooper/www/caldera.dev/wp-content/plugins/Caldera-Forms/classes/api/util.php on line 35`

This is being caused because the version of WordPress does not support the REST API.

**Comment by Shelob9** [comment]
Closing as #1620 makes plugin not load on 4.6 or less. Better than the current status of stuff just breaking.
