### ISSUE TITLE
Expiration field shows div tags in the backend form

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1621]
I added in Creditcard, expiration and cvc fields.

The Expiration field shows this:

![screen shot 2017-05-25 at 09 10 55](https://cloud.githubusercontent.com/assets/5323259/26439882/3e739b4a-412a-11e7-86e9-09290f84bede.png)

**Comment by vtad** [comment]
Same problem with CF 1.5.1, also every time the form ist saved an adittional "> </div ..." is appended

**Comment by Shelob9** [comment]
Actual bug is that saving expiration field puts extra HTML in as placeholder setting's value. So the display of that extra HTML is technically correct...

**Comment by Shelob9** [comment]
Close via 		71f87b0
