### ISSUE TITLE
WP visual editor is not showing info after update 1.5.0.10

### ISSUE THREAD

**Issue by DoornAss** [CalderaWP/Caldera-Forms#1623]
After updating to Versie: 1.5.0.10 my WP visual editor is not gone but not showing any information. 
The html text tab is correct and complete. There are also no problems with publishing.
If I deactivate the Caldera Forms plugin the Visual-editor problem is solved.
Anyone the same problem or a solution?
[Support ‹ Doorneweerd — WordPress.pdf](https://github.com/CalderaWP/Caldera-Forms/files/1029764/Support.Doorneweerd.WordPress.pdf)

**Comment by Shelob9** [comment]
@DoornAss Thanks for using Caldera Forms and reporting this. It would be very helpful if you could open your JavaScript console and check for errors.

http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by DoornAss** [comment]
![screen shot 05-25-17 at 11 41 pm 001](https://cloud.githubusercontent.com/assets/28960242/26471887/f8f12248-41a3-11e7-899e-525903697269.PNG)
![screen shot 05-25-17 at 11 41 pm](https://cloud.githubusercontent.com/assets/28960242/26471888/f90c00e0-41a3-11e7-8674-f1a2b28b2388.PNG)

I am not familiar with this console but made some printscreens. I can't also not find any errors on  the other tabs in the console.
bytheway, the same visual editor error I find with IE.

**Comment by DoornAss** [comment]
And the error page (?)

![screen shot 05-25-17 at 11 49 pm](https://cloud.githubusercontent.com/assets/28960242/26472095/e44e883e-41a4-11e7-8c97-1f6650c2a1d0.PNG)

**Comment by DoornAss** [comment]
Is this enough information for you?

**Comment by DoornAss** [comment]
The problem is not solved after de-activating and/or delete and re-install. Have you other suggestions?

**Comment by DoornAss** [comment]
Caldera Forms colluded with the plugin "Forget About Shortcode Buttons". 
After de-activating this plugin the problem is solved.
