### ISSUE TITLE
Credit Card Number, Expiration Field, link disappears after saving

### ISSUE THREAD

**Issue by vtad** [CalderaWP/Caldera-Forms#1628]
CF 1.5.0.10, WP 4.7.5, Authorize.net for CF 2.1.1, PHP 5.6

## What Is The Unexpected Behaviour?
Editing the Credit Card Number field type ->Expiration Field offers the correct field (in my case Expires on [expires_on]) as the Link to the expiration field for validation, but seems to be not saved, since it doesn't show up when editing again. 
The cc payment test works correctly.

**Comment by Shelob9** [comment]
@vtad This is the correct behaviour for these fields. They are designed to be used with one of our payment processor add-ons. Using them to store credit card numbers in the WordPress database is a very bad idea. We pass the values to Authorize.net and they store them securely. If you were storing them in your database, and Authorize.net found out, they  would cancel your account.
