### ISSUE TITLE
"Reply To" Email: Ignored unless sent by Auto-Responder Processor

### ISSUE THREAD

**Issue by peter-at-houston-academy** [CalderaWP/Caldera-Forms#1629]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.5PHP Version: 7.1.5MySQL Version: 5.6.28Caldera Forms Version: 1.5.0.10

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
**My Situation**
I have a form with a default mailing setup in Email > Email Notification Settings, with "From" as a colleague's email, "Reply To Email" as %email_address%, and "Email Recipients" as my email. I have also added Auto-Responder Processors, to allow conditional recipients, etc, which is working very well (thanks, Caldera!). 

**Issue**
So far, when I receive an email as the default recipient (set up in "Email Notification Settings", not Auto-Responder), I receive the email as if from my colleague ("From") and not as if from %email_address% ("Reply To"). For what it's worth, this persists when Processors are disabled.

**Temporary Workaround**
However, I also set myself up as a recipient of an Auto-Responder Processor, and the emails I receive from the Auto-Responder come through as from %email_address% correctly. 

## What PHP Errors Have You Logged While Reproducing This Bug?
Enabled PHP error logs. No errors after submitting the form.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None in console when submitting the form.

**Comment by Shelob9** [comment]
Possibly related  #1607 and #1504

**Comment by Shelob9** [comment]
This should have been close via #1617
