### ISSUE TITLE
Star fields can be submitted if required and not entered

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1634]
https://wordpress.org/support/topic/required-field-14/

**Comment by texas2607** [comment]
Hi,
For me The star rating is from 1 to x (1 being the worst rating)
I would see a system like:
– If 0 then Required,
– If more than 0 then ok
– Finally, if the default value is set (and it is > 0) and the vote is changed, in all cases the value 0 can not be entered so there is no worry.

Regards,
Fred

(sorry for my English)

**Comment by Shelob9** [comment]
This is fixed in #1710

**Comment by kairey64** [comment]
Not fixed in 1.5.5 ?
