### ISSUE TITLE
Add user:roles as a magic tag

### ISSUE THREAD

**Issue by agileware** [CalderaWP/Caldera-Forms#1638]
It would be incredibly useful to have user:roles available as a magic tag in Caldera Forms. This can then be used:
1. in conditions to perform certain actions based on the user having one or more roles
2. store the user roles of the submitting user

**Comment by Shelob9** [comment]
@agileware The users add-on provides form and field visibility based on logged in state and role: https://calderaforms.com/downloads/caldera-forms-users-add/ It doesn't do a magic tag, but that should be added there: https://bitbucket.org/calderadev/cf-users/issues/3/add-user-role-magic-tag

**Comment by agileware** [comment]
@Shelob9 That's a bummer dude :( Would you reconsider this decision?

**Comment by Shelob9** [comment]
@agileware I can't take paid functionality and add it to the free plugin, that doesn't make sense. The Users add-on sells very well for us, if we don't sell add-ons then we don't have a business and then I can't keep making Caldera Forms and Caldera Forms related things. I like making Caldera Forms and Caldera Forms related things.
