### ISSUE TITLE
Email Notification "From Name" doesn't translate Magic Tags

### ISSUE THREAD

**Issue by peter-at-houston-academy** [CalderaWP/Caldera-Forms#1642]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.5
PHP Version: 7.1.5
MySQL Version: 5.6.28
Caldera Forms Version: 1.5.0.10

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When sending an email with the default Email Notification settings for a form, the Magic Tags %first_name% %last_name% are retained literally as the first and last names of the sender. This problem exists alongside the issue of "Reply To" not functioning properly (#1629), so perhaps one solution would return both to working. (Possibly related: #1524)

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
I'm not able to reproduce this. I used a magic tag for the `Reply To Email` setting and that was used. Maybe the issue is that the `From Email` setting does not accept magic tags and that isn't clear at all - #1652

**Comment by peter-at-houston-academy** [comment]
I'm sorry, I'm confused. Why did you use a magic tag for the `Reply To Email` for this issue? I was experiencing difficulty with the `From Name`. (I used a plain email address in `From Email`, so that is not related in my case.) 

Thanks for looking into this. I'm glad to be using such a good form builder with active support.
