### ISSUE TITLE
caldera form cf-api not found

### ISSUE THREAD

**Issue by Ataurr** [CalderaWP/Caldera-Forms#1646]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.5PHP Version: 7.0.17MySQL Version: 5.5.5Caldera Forms Version: 1.5.0.10WP_DEBUG:

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
When I  click the submit Button. it's stuck. If I check console I found a 404 error not found.
![aa](https://puu.sh/wec9a/6efd7c9fa4.png)

## What PHP Errors Have You Logged While Reproducing This Bug?
Nothing found

## What JavaScript Errors Have You Seen While Reproducing This Bug?
`POST http://www.example.com/cf-api/CF572710a7cd494 404 (Not Found)`

Please help me to solve this issue.

**Comment by Shelob9** [comment]
I replied to this question on WordPress.org

**Comment by pablo384** [comment]
> I replied to this question on WordPress.org

the link please, I have the same issue.

**Comment by tolarcible** [comment]
I have the same issue with connected caldera form !!!!! please help me

**Comment by Ataurr** [comment]
@tolarcible Reset your permalink from Settings-> permalink

**Comment by japalekhin** [comment]
I have a similar issue, but `403` instead of `404`.
Resetting (saving with or without changes) the permalink like @Shelob9 and @tolarcible suggested didn't do anything.

**Comment by imtiazShakil** [comment]
> @tolarcible Reset your permalink from Settings-> permalink

I had to change the settings-> permalink multiple times to make it work...
