### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#165]
Here atleast is needed some initial text to how to use this area. The text can then go away after having created the first variable....

Not sure how it works yet..

**Comment by JiveDig** [comment]
Agreed. This feature is the only one that I'm still unsure about after playing with CF for a couple days. I'm guessing it does some cool stuff, but not exactly sure what/how ;)

**Comment by Desertsnowman** [comment]
Think of them as hidden fields without having hidden fields in the form. .. but yes it does need more explaining.
