### ISSUE TITLE
No way to set default dropdown option using magic tags

### ISSUE THREAD

**Issue by bensteers** [CalderaWP/Caldera-Forms#1659]
I am using Caldera as essentially a profile editor. I need to set the form values using data pulled from my database via magic tags. For text fields, that is easy because I can just use a magic tag in the default value argument, but for dropdowns (and other selects) the default value can not be set using magic tags. I realize that the placeholder argument can take magic tags, but the value is set to be blank so that doesn't really help me.

One solution would be to add a text box to the Add Option section of the edit panel which could be matched against the values of the options. 

Another solution could be to just check the placeholder value against all of the option values and if it matches any of the option values, select that, otherwise use the existing functionality.

I can submit a pull request, but I was wondering which method would be preferred, or if I am missing anything. If neither, I can just patch it with hooks, but it would be more robust if it were part of the default functionality.

**Comment by bensteers** [comment]
I'm thinking the first option could be ideal, especially if it is added to all 'selects'. It would be great if I could specify a default US state from the state dropdown.

**Comment by Shelob9** [comment]
@bensteers Adding a default option, that was matched tag enabled makes a lot of sense. If you put in a pull request against master, I will merge it.

**Comment by Shelob9** [comment]
Close via #1660 etc.
