### ISSUE TITLE
illegal offset type in isset or empty in caldera-forms/fields/checkbox/field.php on line 26

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1664]
<img width="1239" alt="screen shot 2017-06-13 at 11 23 29 am" src="https://user-images.githubusercontent.com/9663875/27090435-2ddc553c-502b-11e7-9952-8d46b0cffc3c.png">

**Comment by Shelob9** [comment]
Close via 		ccfc6a4
