### ISSUE TITLE
Admin not receiving the e-mail sent by user.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1670]
My client contacted me letting me know that she was not receiving the order e-mails from her buyers. We have not changed the admin message. That means something has happened recently for the e-mails not to be sent through. They do show up in the submission area.

Success message works and so does the order confirmation to the client.

**Comment by Shelob9** [comment]
@paaljoachim This is not the right place to make support requests about issues on a specific site. Please use https://calderaforms.com/support.

**Comment by paaljoachim** [comment]
I figured it out.
