### ISSUE TITLE
Reopening issue - Submission still showing JSON and not entry.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1681]
An old issue is still showing up.
Under Option 1
![screen shot 2017-06-16 at 23 23 15](https://user-images.githubusercontent.com/5323259/27249765-dab70d58-52ea-11e7-8d88-dc9351e64299.png)

Test site is a local dev newly installed site using Twenty Seventeen and no plugins except Caldera Forms active. I am using the default Variable Pricing Form template.

Earlier issues:
https://github.com/CalderaWP/Caldera-Forms/issues/1410
https://github.com/CalderaWP/Caldera-Forms/issues/1428

**Comment by paaljoachim** [comment]
Here is another example from a live site.

![screen shot 2017-06-16 at 23 33 50](https://user-images.githubusercontent.com/5323259/27249866-036c80b4-52ed-11e7-8a51-086a7648c143.png)

**Comment by Shelob9** [comment]
Close via 	604f00e
