### ISSUE TITLE
Caldera Form Keygen not generating numbers

### ISSUE THREAD

**Issue by oduchris** [CalderaWP/Caldera-Forms#1682]
Hello there, please i use Caldera forms keygen to generate serial numbers for every form a user submits. But i have an issue. After the form is submitted i cannot use the number generated rather this is what i get {keygen:key}.

Is there a way to get around this? i will appreciate.

Thank you

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. Can you please provide all of the
information requested in the new issue template? It's impossible to know if
this is a bug or a site specific issue with out that information.

**Comment by oduchris** [comment]
Thank you for your swift response. Here is more information on the issue, Once I submit the form, I am able to see the generated reference number with ease, but I cannot see it in the form. If I use any field, it will just display {keygen: key} in the field. What I would like to do is have a number generated before the form is submitted, This is because i will like a number to be captured rather than {keygen: key} which is in the form field. 
Please let me know if you need more information on this.

Thank you

**Comment by Shelob9** [comment]
I need exactly the information that is asked for in the new issue template.
You can get that by clicking the new issue button.

**Comment by oduchris** [comment]
Hello, thanks for your response. Actually i am new here and dont know what you require of me. I have clicked the "New issue" button. it takes me to create another issue. What exactly am i expected to do?

Thank you

**Comment by Shelob9** [comment]
Please copy the issue template into a comment here, and answer all of the questions it asks. That information is not optional. I need it to determine if this is a bug, or a site-specific issue that would be better handled through our support system at https://calderaforms.com/support

**Comment by oduchris** [comment]
## Do You Need Immediate Help?
Not so urgent

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.


## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*Caldera form Version 1.3.5.3, WP4.4.2, PHP5.5.38

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes It still does.

## What Is The Unexpected Beahviour?
I use a caldera form Keygen, which is suppose to generate a unique number/code in form field. But what i noticed is that the number is only generated at submission and not before submission. Hence it gives me {keygen: key} in the field if i tried to capture the data globally. I think the caldera form keygen plugin needs to be adjusted, to fix this.

## What PHP Errors Have You Logged While Reproducing This Bug?
* none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* none

Will be hoping to hear from you soon. Thank you

**Comment by Shelob9** [comment]
You're using 1.3.5? That's 2 years out of date.

Does this issue presist if you update to the current version, which is
1.5.1?

**Comment by oduchris** [comment]
Yes the issue still persist even with 1.5.1. the issue seems to be in Caldera form keygen plugin, not really in Caldera form plugin it self (just my thoughts though) You can try from your end and see exactly what i mean.

I still use the old caldera form because that version seems stable for me, except that when i want to edit form it takes a while to load. I tried the new version sometime ago and had lots of issue that is why i had to revert back.

Thank you

**Comment by oduchris** [comment]
Hello Shelob9, any update for me yet? 

Thank you

**Comment by Shelob9** [comment]
@oduchris There is no update. I will update this issue if/when it is updated. Please keep in mind this is not a support channel.
