### ISSUE TITLE
Color picker field shows color code only

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#1683]
version 1.5.1

Is this how the color picker should render? I remember having a color preview on one of the sides beside the color hex code.

Using default theme and disabled all plugins.

![sketch](https://user-images.githubusercontent.com/20680030/27260262-79209b62-5430-11e7-8661-4f8c55527c24.png)

**Comment by Shelob9** [comment]
Yes, that is how it did work in CF 1.4

**Comment by Shelob9** [comment]
Funny thing is that the span to show it is there, and the CSS that should make it shown is there... We did change in 1.5.1 how it gets instantiated. Before [no settings](http://labs.abeautifulsite.net/jquery-minicolors/#settings) were passed, now all settings are passed as default and there is a filter, which is cool, but like would be cooler if it worked.

**Comment by 101010f** [comment]
The color picker seems to be dead for good with the latest update 1.6.3 Only shows a text input field

**Comment by hellohamzak** [comment]
is there any update on Color picker i find is not really working at all. on last couple of release with using only  twenty seventeen theme & plugin

**Comment by kjohnson** [comment]
@New0 `color_picker_init()` is targeting `.minicolor-picker`, which looks to be the class on the wrapper element. Instead, we should be targeting the `<input />` element directly.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/f68e48f49d06f502fd93012a73b69691f3f22eb4
