### ISSUE TITLE
{ip} magic tag not working in Email Message

### ISSUE THREAD

**Issue by djh361** [CalderaWP/Caldera-Forms#1684]
## Do You Need Immediate Help? 
No
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request? 
No
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using? 
WordPress Version: 4.8PHP Version: 5.2.17MySQL Version: 5.6.32Caldera Forms Version: 1.5.1WP_DEBUG: 1
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.

I am trying to use the {ip} magic tag in the Email Message, but whenever this tag is used in the Email Message, the email does not get sent. The user is informed that their form has been submitted. But the email has failed to be sent.

I have used other magic tags (e.g. {summary}, {ua}) in the Email Message and they work as expected. I have also used {ip} in the Email Subject and the user's IP address is being included in the Subject of the email that gets sent. So it seems that the inclusion of {ip} in the Email Message causes a problem.

The problem I am having sounds exactly the same as the problem described in issue #74. But that seems to have been fixed a couple of years ago.

## What PHP Errors Have You Logged While Reproducing This Bug?
None
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
@djh361 I just tested this in three ways:
1) Added a hidden field whose default is {ip} and put {summary} in email.
2) Added the {ip} magic tag ot the email.
3) Put the hidden field's magic tag in the email.

All three gave me the IP and the email sent. You might try, if you're using PHPmailer, to enable mailer debug to find exceptions.

**Comment by Shelob9** [comment]
No response, closing.
