### ISSUE TITLE
Hide breadcrumbs after submission

### ISSUE THREAD

**Issue by ictbeheer** [CalderaWP/Caldera-Forms#1702]
## Is This A Feature Request?
Yes

When a multi-page is submitted the breadcrumbs stay visible even when the form setting 'Hide Form' has been enabled.
I think it would make more sense if the breadcrumbs would also be hidden after submission.

![image](https://user-images.githubusercontent.com/14947039/27516336-59104d8a-59b8-11e7-9e13-2de232825bc1.png)

**Comment by Shelob9** [comment]
Make sure to only remove the breadcrumbs of from that submitted.

Get breadcrumbs as jQuery 	- https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/frontend-script-init.js#L124

Use `cf.form.submit`.

Something like this

```
$( document ).on( 'cf.form.submit', function(e,obj){
    var $form = obj.$form;

    var $breadBreadcrumbs = $form.child( '.breadcrumb' );

    $breadBreadcrumbs.hide().attr( 'aria-hidden', true ).css( 'visibility', 'hidden' );
    
});
```

**Comment by Shelob9** [comment]
Close via 
5c1e2ee PR #2155
