### ISSUE TITLE
Allow Multiple with simple File field not behaving as expected

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#1703]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

WordPress Version: 4.8
PHP Version: 5.6.25
MySQL Version: 5.7.14
Caldera Forms Version: 1.5.1
WP_DEBUG: 1

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?

Yes

## What Is The Unexpected Beahviour?

Using the File field type, when "Allow Multiple is checked, it adds a second button that opens file uploader and none of the two buttons allow the  selection of multiple files.

Here the normal File field without allow multiple 
![simple-file-field](https://user-images.githubusercontent.com/16348693/27534037-eb43a6e0-5a65-11e7-89aa-c4b5541ed738.png)

On the File field with allow multiple, a button is added above ( the black button saying add files)
![file-field-with-allow-multiple](https://user-images.githubusercontent.com/16348693/27534036-eb41b704-5a65-11e7-83dd-b35eb76dab08.png)

But none allow multiple files upload.

## What PHP Errors Have You Logged While Reproducing This Bug?
There is no error in the debug file

## What JavaScript Errors Have You Seen While Reproducing This Bug?
There is no error in the console

**Comment by Shelob9** [comment]
To clarify, if the desire here is a "add additional files" button to a basic file field, close the issue, that's not possible.
