### ISSUE TITLE
Email notification setting “From email” field not respecting value.

### ISSUE THREAD

**Issue by antoniostarace** [CalderaWP/Caldera-Forms#1709]
PHP 7
Wordpress 4.8
Calderaforms 1.5.1

Email notification setting “From email” field does not respect value. I fill in an email address that I want to be the "from" but it always returns wordpress default admin email.
Looks like a bug.

**Comment by Shelob9** [comment]
@antoniostarace Can you please open a new issue answering all of the questions that are in the template? That is neccasary for us to tell if this is a bug or a site-specific issue.
