### ISSUE TITLE
Mail body no more formatted

### ISSUE THREAD

**Issue by antoniostarace** [CalderaWP/Caldera-Forms#1711]
PHP 7
WP 4.8
Caldera 1.5.1

I had my mail body set to send a formatted html. I used inline styles and tables and it worked fine. With latest update of Calderaforms something happened because now my mails are sent without styles.

**Comment by Shelob9** [comment]
@antoniostarace Can you please open a new issue answering all of the questions that are in the template? That is neccasary for us to tell if this is a bug or a site-specific issue.
