### ISSUE TITLE
Forms not working correctly on Safari 8.0

### ISSUE THREAD

**Issue by tommifin** [CalderaWP/Caldera-Forms#1719]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

Short Debug Information

    WordPress Version: 4.7.5PHP Version: 7.0.18-1+deb.sury.org~trusty+1MySQL Version: 5.5.5Caldera Forms Version: 1.5.1WP_DEBUG: 

Full Debug Information

WordPress Version: 4.7.5

PHP Version: 7.0.18-1+deb.sury.org~trusty+1

MySQL Version: 5.5.5

Server Software: nginx/1.10.3

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:54.0) Gecko/20100101 Firefox/54.0

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    Redis: No

Object Cache:

    Apc: No
    Apcu: No
    Memcache: Yes
    Memcached: No
    Redis: Yes

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: UuteenSeelantiin: 1.0

Currently Active Plugins:

    Advanced Custom Fields PRO: 5.5.14
    Caldera Forms: 1.5.1
    Cookie Notice: 1.2.38
    Google Analytics Dashboard for WP: 4.9.6.2
    Maintenance: 3.4.1
    Redirection: 2.6.2
    Yoast SEO: 4.7.1

## What Is The Unexpected Beahviour?
Forms are working fien on Fir3efox and Chrome but not on Safari. The redirection doesn't work and the verification email to the form submitter is not triggered. Notification email to the site developer is sent.

## What PHP Errors Have You Logged While Reproducing This Bug?
-

## What JavaScript Errors Have You Seen While Reproducing This Bug?
FROM SAFARI:
[Log] JQMIGRATE: Migrate is installed, version 1.4.1 (jquery-migrate.min.js, line 2)
[Error] XMLHttpRequest cannot load https://uuteenseelantiin.fi/cf-api/CF594afcf77e268. Origin http://uuteenseelantiin.fi is not allowed by Access-Control-Allow-Origin. (yhteystiedot, line 0)
[Error] TypeError: undefined is not an object (evaluating 'b.jqxhr.responseJSON.data')
	error (ajax-core.min.js, line 1)
	request_error (jquery-baldrick.min.js, line 1)
	c (jquery-baldrick.min.js, line 1)
	error (jquery-baldrick.min.js, line 1)
	i (jquery-3.2.1.min.js, line 2)
	fireWith (jquery-3.2.1.min.js, line 2)
	A (jquery-3.2.1.min.js, line 4)
	(anonymous function) (jquery-3.2.1.min.js, line 4)

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. This line `[Error] XMLHttpRequest cannot load https://uuteenseelantiin.fi/cf-api/CF594afcf77e268. Origin http://uuteenseelantiin.fi is not allowed by Access-Control-Allow-Origin. (yhteystiedot, line 0)` indicates that you're loading the page on insecure HTTP but the submit URL is secure HTTPS. 

I suspect this will be a problem in Chrome as well.

You should work with your host to redirect all pages to their secure HTTPS urls.
