### ISSUE TITLE
Email notification setting “From email” field not respecting value in multi-site environment

### ISSUE THREAD

**Issue by localmedia** [CalderaWP/Caldera-Forms#1732]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8
PHP Version: 7.0.20
MySQL Version: 5.6.35
Caldera Forms Version: 1.5.2

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
The issue persists only in multi-site environments

## What Is The Unexpected Beahviour?
When sending the form, the "From email" value of the form settings is being ignored and overwritten by the email address in the General Wordpress settings.

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
@localmedia  

Thanks for using Caldera Forms. Can you please tell us what your settings are? When you say `When sending the form, the "From email" value of the form settings is being ignored and overwritten by the email address in the General Wordpress settings.` that makes me think that the email address you provide when passed to `is_email()` returns false, and therefore Caldera Forms resets the admin email to prevent an error.

**Comment by localmedia** [comment]
Thank you for your support! The problem was caused by a misconfiguration on our part in the admin settings and has been resolved.
