### ISSUE TITLE
Modal Overflowing Incorrectly on Desktop View

### ISSUE THREAD

**Issue by YenDiesel** [CalderaWP/Caldera-Forms#1733]
## Do You Need Immediate Help?

NO

## Is This A Feature Request?

NO

## What Version Of Caldera Forms, WordPress and PHP Are You Using?

Short Debug Information

WordPress Version: 4.8PHP Version: 7.0.19MySQL Version: 5.5.5Caldera Forms Version: 1.5.2.1WP_DEBUG:

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?

YES

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.

I have added a contact form to my [contact page](https://east-coast-it.co.uk/contact-us/) 

When you test the form & hit the contact button, the modal window opens but is overflowing across the entire page when using a browser.

Mobile & Tablet are both unaffected

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

NONE

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

NONE

**Comment by Shelob9** [comment]
@YenDiesel Thanks for using Caldera Forms and for pointing out this bug.

Looks like the solution is:
```
.caldera-modal-body 
.caldera-grid .row {
    max-width: 100%;
}

```

@New0 Can you test this one please? Do you see a better option?

**Comment by Shelob9** [comment]
Close via  11434bc
