### ISSUE TITLE
Question about creating ui processors 

### ISSUE THREAD

**Issue by AndrGelmini** [CalderaWP/Caldera-Forms#1734]
Hi and thanks for this great plugin.

With the latest changes it's really a great tool.

I come to the question immediately.

I'm trying to write a very simple processor that allows me to share with YetiForce CRM anyone compile a form.
To avoid writing a processor for each category of customer, collaborator, and vendor, I would like to "condition" the generation of certain fields following a select and a call to crm bees.

Something very similar to what you see in the video of your mailchimp plugin.

It is an idea that I came to mind not to have too many processors with the same plug. But so to have one very modularly.

And by a while I'm banging my head. I hope I was clear.

**Comment by Shelob9** [comment]
@AndrGelmini  - Thanks for using Caldera Forms.

This isn't a great place to discuss integrations. Can you send us a message using our contact form https://calderaforms.com/contact please? I don't answer those, but if you say Josh told you to use that form to get in touch, the ticket will get assigned to me.
