### ISSUE TITLE
HTML validation issues

### ISSUE THREAD

**Issue by haxtrujillo** [CalderaWP/Caldera-Forms#1750]
Caldera Forms v1.5.2.1 on WP v4.8 

Could you please fix html validation issues, I have attached a patch for review.  Here are the issues.

- "field" is not a valid value for the "role" attribute.
- "role" attribute with the value of "form" is not needed on a "form" element.
- When a label is hidden for a particular field, "labelledby" attribute is mislabeled. 

[caldera-forms.txt](https://github.com/CalderaWP/Caldera-Forms/files/1149285/caldera-forms.txt)

**Comment by Shelob9** [comment]
Ok, so sorry I did not fix this earlier. That was very wrong of me and I appologize.

Three issues stated here:
1. "field" is not a valid value for the "role" attribute.
2. "role" attribute with the value of "form" is not needed on a "form" element.
3. When a label is hidden for a particular field, "labelledby" attribute is mislabeled.

Looking at this screenshot, with latest `develop` branch, I see that issue 1 is not resolved, while issue 3 is resolved already, not sure where but its fixed. Issue 2 is not depicted, but is also totally valid. 

<img width="1045" alt="screen shot 2017-11-20 at 12 55 35 pm" src="https://user-images.githubusercontent.com/1994311/33033406-46c099d8-cdf2-11e7-8d9c-44f717bf7c12.png">

Give me a few more minutes please this is embarrassingly simple to fix.

**Comment by Shelob9** [comment]
With changes in PR #2091 -

<img width="994" alt="screen shot 2017-11-20 at 1 08 17 pm" src="https://user-images.githubusercontent.com/1994311/33033869-fa48c6e6-cdf3-11e7-95bc-8374d3e92302.png">

**Comment by Shelob9** [comment]
Close via #2091
