### ISSUE TITLE
cf_er=_cf_process_5964359a8605b

### ISSUE THREAD

**Issue by cbomkamp** [CalderaWP/Caldera-Forms#1751]
WordPress Version: 4.8
PHP Version: 7.0.16
MySQL Version: 5.5.51
Caldera Forms Version: 1.5.2.1
WP_DEBUG:

We just launched our new site a few days ago using Caldera Forms. So far, everything is going very well except I've noticed a handful of URLs showing up in Google Analytics with CF errors.

The URLs are the page with the form, with a query string parameter called "cf_er" appended, like this:

http://www.example.com/formpage?cf_er=_cf_process_5964359a8605b

The number on the end of the parameter value varies. I found a couple places in the CF source code where the cf_er field is set to something, but I don't really understand what's going on. What's worse is I can't reproduce this. It's happened about 20 times so far. Once in the Edge browser, and every other time in IE 11.

Can you shed any light on what this cf_process error could mean or suggestions on how I could troubleshoot further?

**Comment by Shelob9** [comment]
The cf_er query var is used when loading the form after validation errors
happened.

You will need to set Google Analytics to ignore that query var.
https://www.crazyegg.com/blog/remove-url-parameters-from-google-analytics-reports/
