### ISSUE TITLE
 Unexpected Beahviour with Add Custom Preset Options for Caldera Forms Select Fields

### ISSUE THREAD

**Issue by rdsivd** [CalderaWP/Caldera-Forms#1757]
WordPress Version: 4.8PHP Version: 7.1.1MySQL Version: 5.5.5Caldera Forms Version: 1.5.2.1WP_DEBUG: 

## What Is The Unexpected Beahviour?

i want to insert bulk preset options, created a txt bestand with following items

14-07-2017|<iframe width="100%" height="1200" src="http://vbl.be/messeranalyse.aspx?map=101017&file=uitslagtornooi170714VR.xml"/>

when copy paste this into bulk insertion it places the date not in the label field
![afbeelding](https://user-images.githubusercontent.com/30210198/28246552-de6ae16a-6a1c-11e7-881b-8f0d9374002b.png)

i try this with a list a typed directly into the bulk insert 

1|abc
2|abcd
3|abcde

copy paste this in the list and get the same result

![afbeelding](https://user-images.githubusercontent.com/30210198/28246561-24ffd7e8-6a1d-11e7-8da6-11e242135ac8.png)

![afbeelding](https://user-images.githubusercontent.com/30210198/28246564-3523634c-6a1d-11e7-91a7-d26a63a9fea4.png)

any idee how to fix this

Regards
Ronny

**Comment by Shelob9** [comment]
Close via 	72b2ff8
