### ISSUE TITLE
Range Slider not work properly.

### ISSUE THREAD

**Issue by novatendencia** [CalderaWP/Caldera-Forms#1758]
range slider, some times dont show value, get stuk, goes to zero.

I have tried it on several computers and in different browsers.

WordPress Version: 4.8PHP Version: 7.1.7MySQL Version: 5.5.5Caldera Forms Version: 1.5.2.1

http://registration.spanishlanguagec.com/

**Comment by logicalfantasy** [comment]
Also having this issue:

Wordpress 4.8, Caldera Forms 1.5.2.1

Range Slider shows correct colours and does slide, but the number preview stays at the default and does not change, precisely as the user above is experiencing.

**Comment by Shelob9** [comment]
Close via 		9ba9123

**Comment by novatendencia** [comment]
now show value at right but still "jumps" ... try to go 1 to 1 and suden jump to 40 or Zero
