### ISSUE TITLE
Total value 0 in emails

### ISSUE THREAD

**Issue by drelich** [CalderaWP/Caldera-Forms#1770]
**Caldera Forms version:** 1.5.2.1
**PHP version:** 7.0.21

Expected behaviour
---------------------
Total amount in email should show actual, non-zero, value.

Problem description
---------------------
My form has a set of checkboxes, all of which have their Label, Value and Calculation Value set. The Label and Value are text strings (service name). The Calculation Value is set to a number (price of the service).

Calculations on front-end work perfectly but when the form gets submited, I receive email, showing which service has been selected but shows Total as 0.

I use {summary} to display the form's content.

Changing the checkbox's Value in the form to the actual price solved the problem, and the Total did show a correct amount, but the service name in the email was replaced with the Value.

Ideally, I should see a service name (stored in Value) and the Total should show an actual amount based on the Calculation Values.

**Comment by Shelob9** [comment]
@drelich Thanks for using Caldera Forms. This is probably a symptom of the issue identified in #1776 If you still experience this issue after upgrading to 1.5.3, then please re-open this, but I doubt that will be needed as the fix for #1776 should solve this.

**Comment by drelich** [comment]
Thanks for response. Installed Cladera Forms via WP Plugin repository, which only offers the version I have installed already. I presume it'll take some time for the new version to pull through? Cheers.
