### ISSUE TITLE
502 Timeout when editing page

### ISSUE THREAD

**Issue by Cajs** [CalderaWP/Caldera-Forms#1772]
WordPress Version: 4.8
PHP Version: 5.6.30-1+wpengine8
MySQL Version: 5.6.36
Caldera Forms Version: 1.5.2.1
WP_DEBUG:

URL in question: https://ukfilm.wpengine.com/test-3/
As you can see, there is only 1 caldera form on the page, nothing else.

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
After creating quite a large form, it seems to exceed the 60 seconds processing time of my host when pressing edit page. So I receive a 502 error page.

## What PHP Errors Have You Logged While Reproducing This Bug?
None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None.

**Comment by Shelob9** [comment]
@Cajs Thanks for using Caldera Forms. This is really a support question/ site issue, not a bug. 

If your form takes longer than 60 seconds then either your form is way to complex and you should break it up into multiple forms using Connected Forms or something is happening on the server that causes it to take forever (an infinite loop, some really slow API integration, etc.)

If you need help tracking down what this is, please open a support ticket at https://calderaforms.com/support

**Comment by Cajs** [comment]
Thanks for feedback. Good idea with the connected forms!

Kind Regards
