### ISSUE TITLE
Range Slider not working with Conditions

### ISSUE THREAD

**Issue by renlo** [CalderaWP/Caldera-Forms#1775]
http://www.injoy-sound.com/%E8%A9%A2%E5%83%B9/#1476284105862-fa5108bb-e07f

if i set range slider with conditions, range slider not working. how can i fix it?

thank you.

**Comment by Shelob9** [comment]
@renlo  Thanks for using Caldera Forms. Sorry about this bug. It is already fixed for version 1.5.3 via #1758
