### ISSUE TITLE
Caldera Forms – Drop down bug

### ISSUE THREAD

**Issue by Levityz** [CalderaWP/Caldera-Forms#1778]
Hey guys,

Not sure what's going on here...
My form was working great until now. I am using Wordpress Version 4.8 and CForms 1.5.2.1

I am getting gibberish on my form when a drop down is selected.

It seems to only be happening on conditional fields...

Any ideas?

![screen shot 2017-07-25 at 3 19 41 pm](https://user-images.githubusercontent.com/30445692/28589579-bf60c9ec-714c-11e7-8679-8a27474ee09a.png)

**Comment by Levityz** [comment]
Nevermind, It was my fault. I was using a minify JS plugin that was causing the issue. Thanks guys

**Comment by Shelob9** [comment]
@Levityz Glad you got that fixed. If you're using a plugin to minify CSS or JS, you should use the caldera_forms_render_assets_minify filter to prevent Caldera Forms from enqueuing minified CSS and JS. Double-minification never ends well.

https://calderaforms.com/doc/caldera_forms_render_assets_minify/
