### ISSUE TITLE
Typos in /classes/admin.php, /ui/admin.php, /ui/admin_templates.php and readme.md

### ISSUE THREAD

**Issue by christophherr** [CalderaWP/Caldera-Forms#1785]
Hi,
I was going through untranslated strings on translate.wordpress.org and saw a few typos:

https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/admin.php#L1620
`Working with form revisions and drafrs` 
should be `Working with form revisions and drafts`

https://github.com/CalderaWP/Caldera-Forms/blob/master/ui/admin.php#L234
`we have support licneses` 
should be 
`we have support licenses`

I'm not sure if 
https://github.com/CalderaWP/Caldera-Forms/blob/master/ui/admin_templates.php#L161 
https://github.com/CalderaWP/Caldera-Forms/blob/master/ui/admin_templates.php#L181
https://github.com/CalderaWP/Caldera-Forms/blob/master/ui/admin_templates.php#L201
https://github.com/CalderaWP/Caldera-Forms/blob/master/ui/admin_templates.php#L222

should all say `Learn more about the free CSN and usage sharing.`  and if `CSN` should be `CDN`

Also noticed in the readme.md that the link to the Caldera Logo is broken and the link to open an issue doesn't work `[please open an issue]()https://github.com/CalderaWP/Caldera-Forms/issues/` 

If it's wanted/appropriate, I can submit a PR. 

Thanks for a great plugin!

**Comment by Shelob9** [comment]
@christophherr Thanks for pointing this out.  A pull request, referencing this issue would be greatly appreciated.

**Comment by christophherr** [comment]
@Shelob9 Looks like only the readme.md things aren't already covered by the latest additions to https://github.com/CalderaWP/Caldera-Forms/pull/1790
Maybe @pedro-mendonca can add them to his PR and this can be closed?
