### ISSUE TITLE
Forms exported form 1.5.3+ can't be imported in 1.5.3+

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1793]
I exported a form from CF version 1.5.3.1 to another site using the same version. Both are dev sites that are created in DesktopServer.

On import the new form title became CF5824b1cb3c757 and the form content was blank. Here is the contents of the json file:

{"_last_updated":"Tue, 25 Jul 2017 22:43:39 +0000","ID":"CF5824b1cb3c757","cf_version":"1.5.2.1","name":"Kontakt","scroll_top":0,"description":"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t","success":"Form has been successfully submitted. Thank you.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t","db_support":1,"pinned":0,"hide_form":1,"check_honey":1,"avatar_field":"fld_6009157","form_ajax":1,"custom_callback":"","layout_grid":{"fields":{"fld_8768091":"2:1","fld_9970286":"2:2","fld_6009157":"2:3","fld_3268432":"3:1","fld_6981453":"4:1","fld_3194078":"4:2","fld_6031368":"4:2","fld_8793679":"4:2","fld_1106026":"4:2","fld_3415406":"4:2","fld_7683514":"5:1","fld_7908577":"6:1"},"structure":"12|4:4:4|6:6|7:5|12|12"},"fields":{"fld_8768091":{"ID":"fld_8768091","type":"text","label":"Fornavn","slug":"fornavn","conditions":{"type":""},"required":1,"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","default":"","type_override":"text","mask":""}},"fld_9970286":{"ID":"fld_9970286","type":"text","label":"Etternavn","slug":"etternavn","conditions":{"type":""},"required":1,"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","default":"","type_override":"text","mask":""}},"fld_6009157":{"ID":"fld_6009157","type":"email","label":"Epost","slug":"epost","conditions":{"type":""},"required":1,"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","default":""}},"fld_3268432":{"ID":"fld_3268432","type":"text","label":"Telefon nummer","slug":"telefon","conditions":{"type":""},"required":1,"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","default":"","type_override":"text","mask":""}},"fld_6981453":{"ID":"fld_6981453","type":"checkbox","label":"Jeg har behov for:","slug":"jeg_trenger","conditions":{"type":""},"caption":"","entry_list":1,"config":{"custom_class":"","default_option":"","auto_type":"","taxonomy":"category","post_type":"post","value_field":"name","orderby_tax":"name","orderby_post":"name","order":"ASC","default":"","option":{"opt1404791":{"calc_value":"Ny nettside","value":"Ny nettside","label":"Ny nettside"},"opt1055597":{"calc_value":"Overf\u00f8re eksisterende nettside til WP","value":"Overf\u00f8re eksisterende nettside til WP","label":"Overf\u00f8re eksisterende nettside til WP"},"opt2011188":{"calc_value":"Justering av eksisterende nettside","value":"Justering av eksisterende nettside","label":"Justering av eksisterende nettside"},"opt2084074":{"calc_value":"WP kurs i bedriften","value":"WP kurs i bedriften","label":"WP kurs i bedriften"},"opt1884699":{"calc_value":"WP kurs for privatperson\/gruppe","value":"WP kurs for privatperson\/gruppe","label":"WP kurs for privatperson\/gruppe"},"opt1958788":{"calc_value":"Annen type hjelp","value":"Annen type hjelp","label":"Annen type hjelp"}}}},"fld_3194078":{"ID":"fld_3194078","type":"text","label":"Eksisterende nettside:","slug":"eksisterende_nettside","conditions":{"type":"con_6416143859021801"},"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","default":"","type_override":"text","mask":""}},"fld_6031368":{"ID":"fld_6031368","type":"radio","label":"Har du kj\u00f8pt domene og\/eller web hotell?","slug":"har_du_kjpt_domene_og_web_hotell","conditions":{"type":"con_1032371691690572"},"caption":"","entry_list":1,"config":{"custom_class":"","default_option":"","auto_type":"","taxonomy":"category","post_type":"post","value_field":"name","orderby_tax":"name","orderby_post":"name","order":"ASC","default":"","option":{"opt1138156":{"calc_value":"Ja","value":"Ja","label":"Ja"},"opt1076974":{"calc_value":"Nei","value":"Nei","label":"Nei"}}}},"fld_8793679":{"ID":"fld_8793679","type":"paragraph","label":"Hva heter domenet? Hvilket webhotell bruker du?","slug":"domene_webhotell","conditions":{"type":"con_8332161139784369"},"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","rows":4,"default":""}},"fld_1106026":{"ID":"fld_1106026","type":"paragraph","label":"Informasjon om hva slags kurs dere trenger:","slug":"informasjon_om_hva_slags_kurs_dere_trenger","conditions":{"type":"con_9387160521674623"},"caption":"","config":{"custom_class":"","placeholder":"","rows":4,"default":""}},"fld_3415406":{"ID":"fld_3415406","type":"dropdown","label":"Antall deltagere:","slug":"antal_deltagere","conditions":{"type":"con_9387160521674623"},"caption":"","config":{"custom_class":"","placeholder":"","default_option":"","auto_type":"","taxonomy":"category","post_type":"post","value_field":"name","orderby_tax":"name","orderby_post":"name","order":"ASC","default":"","option":{"opt1353802":{"calc_value":1,"value":1,"label":1},"opt1083633":{"calc_value":2,"value":2,"label":2},"opt1765942":{"calc_value":3,"value":3,"label":3},"opt1876690":{"calc_value":4,"value":4,"label":4},"opt1250466":{"calc_value":5,"value":5,"label":5},"opt1505466":{"calc_value":"6+","value":"6+","label":"6+"}}}},"fld_7683514":{"ID":"fld_7683514","type":"paragraph","label":"Melding","slug":"melding","conditions":{"type":""},"required":1,"caption":"","entry_list":1,"config":{"custom_class":"","placeholder":"","rows":5,"default":""}},"fld_7908577":{"ID":"fld_7908577","type":"button","label":"Send skjema","slug":"send","conditions":{"type":""},"caption":"","config":{"custom_class":"","type":"submit","class":"btn btn-default","target":""}}},"page_names":["Page 1"],"mailer":{"on_insert":1,"sender_name":"Caldera Forms Notification","sender_email":"paaljoachim@hotmail.com","reply_to":"","email_type":"html","recipients":"","bcc_to":"","email_subject":"Kontakt","email_message":"{summary}"},"processors":{"fp_17689566":{"ID":"fp_17689566","runtimes":{"insert":1},"type":"auto_responder","config":{"sender_name":"Site Admin","sender_email":"paaljoachim@hotmail.com","subject":"Contact auto-response","recipient_name":"%first_name% %last_name%","recipient_email":"%email_address%","message":"Hi %recipient_name%.\nThanks for your email.\nWe'll get get back to you as soon as possible!\nHere's a summary of your message:\n------------------------\n{summary}"},"conditions":{"type":""}}},"conditional_groups":{"conditions":{"con_6416143859021801":{"id":"con_6416143859021801","name":"nettside","type":"show","fields":{"cl7662310018773373":"fld_6981453","cl2633419779003537":"fld_6981453"},"group":{"rw8180776589838463":{"cl7662310018773373":{"parent":"rw8180776589838463","field":"fld_6981453","compare":"is","value":"opt2011188"}},"rw218729816981421":{"cl2633419779003537":{"parent":"rw218729816981421","field":"fld_6981453","compare":"is","value":"opt1055597"}}}},"con_1032371691690572":{"id":"con_1032371691690572","name":"domene-webhotell","type":"show","fields":{"cl2455698079650628":"fld_6981453"},"group":{"rw4910154512657481":{"cl2455698079650628":{"parent":"rw4910154512657481","field":"fld_6981453","compare":"is","value":"opt1404791"}}}},"con_8332161139784369":{"id":"con_8332161139784369","name":"kjopt","type":"show","fields":{"cl2428135424086394":"fld_6031368"},"group":{"rw9885686357257507":{"cl2428135424086394":{"parent":"rw9885686357257507","field":"fld_6031368","compare":"is","value":"opt1138156"}}}},"con_9387160521674623":{"id":"con_9387160521674623","name":"WP kurs","type":"show","fields":{"cl6625457430738779":"fld_6981453","cl95559553112275":"fld_6981453"},"group":{"rw7879038925059887":{"cl6625457430738779":{"parent":"rw7879038925059887","field":"fld_6981453","compare":"is","value":"opt2084074"}},"rw300693528892778":{"cl95559553112275":{"parent":"rw300693528892778","field":"fld_6981453","compare":"is","value":"opt1884699"}}}}}},"settings":{"responsive":{"break_point":"sm"}},"version":"1.5.2.1","db_id":"1","type":"primary"}

Link to the file:
https://www.dropbox.com/s/21t7454vo77m67i/cf-kontakt-export.json?dl=0

**Comment by Shelob9** [comment]
Works if form was created in CF 1.5.2 or less because db_id isn't in export. Same issue as #1786

**Comment by Shelob9** [comment]
Close via 	21fc2a7
