### ISSUE TITLE
Using the telephone field adding a default country.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1794]
I am creating a Norwegian contact form where I also am planning on using the telephone field.

![screen shot 2017-07-27 at 16 51 00](https://user-images.githubusercontent.com/5323259/28676760-cc26633a-72eb-11e7-82bd-2ba64e4d2ae9.png)

It would be great to add a default country code one wants to use:

![cf-telephone-field-new-wireframe](https://user-images.githubusercontent.com/5323259/28676916-4837150a-72ec-11e7-9aa5-fdd064ce0152.jpg)

As it is right now it becomes to cumbersome for the user to have to select Norway and then write the telephone number. So instead I am using just a regular text field.

**Comment by Shelob9** [comment]
You can do this with the caldera_forms_phone_js_options filter

https://calderaforms.com/doc/caldera_forms_phone_js_options/

**Comment by paaljoachim** [comment]
Ok good to know. It brings in another layer, so I'll just stick to using a regular text field.
