### ISSUE TITLE
1.5.3.1 upgrade breaks date format in export

### ISSUE THREAD

**Issue by cStuartHardwick** [CalderaWP/Caldera-Forms#1807]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.5.3.1
WP 4.7.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When exporting form entries, the date format has changed to be the same as the display format--unusable for scripts etc. that need to parse it. The format used to be ""2017-01-27 18:14:33" now it's "July 20, 2017 9:04 am" This cannot be parsed using standard DOS batch files because it contains a comma inside a field.

**Comment by Shelob9** [comment]
This happened in #1344 - wanted to make time localized.

I think this new behavior is a sensible default. Should probably add a filter to put it back to UTC, or localized timestring... 

 BTW A temporary workaround would be to use caldera_forms_admin_csv

See: https://calderaforms.com/doc/caldera_forms_admin_csv/

**Comment by Shelob9** [comment]
OK, so before  1.5.3.1 timestamp was used. But then I made it localized, which looks good, but makes it less useful in Excel. So I went back to original behaviour, and added a filter to localize time. Also, commas are now being stripped from dates.

Close via 0e28510

See: https://gist.github.com/Shelob9/fe26c6b722d6151c04f3b2f1fcbf7e8a
