### ISSUE TITLE
FEATURE REQUEST: Add BCC field to Auto Responder Processor

### ISSUE THREAD

**Issue by mathetos** [CalderaWP/Caldera-Forms#1815]
The Auto Responder is the best way to implement conditional email notifications (as far as I can tell). But in order for it to be as effective as the standard Email Notification, it should have at least the same features. Right now adding the BCC would be very helpful.

**Comment by JohannesDorn** [comment]
Hi,
This feature would be highly useful to us. As the necessary changes seem to have already been done on a separate branch, is there any ETA for this?

**Comment by Shelob9** [comment]
@JohannesDorn this will definitely get merged for 1.5.6, it needs more testing and also I might make some improvments to internal API for emails, and if so, will need to make sure this works with that.

**Comment by Shelob9** [comment]
Close via  #1905
