### ISSUE TITLE
Save form NOT working?

### ISSUE THREAD

**Issue by Simpleadmin1** [CalderaWP/Caldera-Forms#1821]
Hello, I'm trying to create a form, or edit the existing one, the save form button not working for me very often, I can't find the solution to the issue, creating new form, duplicating the old one don't help. anyone faced this issue?

**Comment by Simpleadmin1** [comment]
In my case, the updating to the beta version didn't resolve the issue, at the moment it looks like I have two forms trying to act like one, sometimes I have a form loading with sliders, some other times without, and nothing is matching the changes I do in the editor. It looks like there are two versions saved somewhere and the plugin is unsure what to load, I nearly had my form finished and then every time I was saving it more content was missing until I have been left with basic form, there is something not right. 👎

**Comment by M31W** [comment]
Came here to report the same thing, forms are not saving. =/

**Comment by mattstockdale** [comment]
Same here. Have deactivated all plugins except Caldera, switched to Twenty Seventeen theme, deleted and re-installed Caldera, tried the latest beta, and still form saves only work sometimes. Clicking save always results in a success message, but doesn't always actually save. I'm also having issues with calculation field %slugs% not displaying within html elements.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. Sorry about this issue.  You can rollback to 1.5.2 or update to 1.5.4-b-3 (coming shortly) to get the fix.

This is a duplicate of #1802 and therefore is being closed for housekeeping reasons.

**Comment by Shelob9** [comment]
1.5.4-b-3 is going to WordPress.org now, please update using WP Rollback see: https://calderaforms.com/updates/caldera-forms-1-5-4-beta/

**Comment by LogoLogics2** [comment]
Hi,

After recent updates I have this issue again, saving forms does not work, keeps spinning endlessly..
