### ISSUE TITLE
Submit button disabled and form is not submitted on media upload using advanced file upload.

### ISSUE THREAD

**Issue by sayma-siddiqui** [CalderaWP/Caldera-Forms#1823]
## Do You Need Immediate Help?
Yes

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3 PHP Version: 5.4.45 MySQL Version: 5.6.28 Caldera Forms Version: 1.5.0.6

## What Is The Unexpected Behaviour?
There is a Advanced File Uploader field in my form, I have enabled Attach to mailer, Allow Multiple and Add to Media Library options.
When I upload images the form gets submitted.
But when I upload a video of about 1MB in size, the submit button gets disabled, and the form isn't submitted. Same thing happens with images of larger size.

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors
 
Here is the link to the form:
[http://coolhandmovers.com/testform/](url)

There is no form processing, or page loading, it just seems that form has stuck.

![image](https://user-images.githubusercontent.com/30046001/28906541-d0607afe-7835-11e7-9cd8-fe43161ae7b5.png)

![image](https://user-images.githubusercontent.com/30046001/28907148-3a6d7e8e-783a-11e7-95a7-be7aab45e611.png)

**Comment by sayma-siddiqui** [comment]
I left the page to see if something happens, but nothing. Look at the time.

![image](https://user-images.githubusercontent.com/30046001/28909718-2f9689ee-7847-11e7-89ad-91c20027dd04.png)

**Comment by Shelob9** [comment]
@sayma-siddiqui - This could be happening because of an error or because the file size is so large it times out. I would not recommend using WordPress for large file uploads. Dropbox or s3 are better suited for that.

If you need help getting this working on your site, please open a support request at https://calderaforms.com/support
