### ISSUE TITLE
File type filter not working on Simple file uploads

### ISSUE THREAD

**Issue by imperyal** [CalderaWP/Caldera-Forms#1824]
The uploader doesn't restrict the type of files. On submit, if one file is the wrong type, nothing happens...

I'm using version 1.5.4-b-3

**Comment by Shelob9** [comment]
@imperyal I am closing this issue as you did not fill out the issue template. Please re-open the issue with all of the requested information. If you need immediate help, please open a support request at https://calderaforms.com/support
