### ISSUE TITLE
JQuery error - please see my website

### ISSUE THREAD

**Issue by instheheroes** [CalderaWP/Caldera-Forms#1826]
https://www.insuretheheroes.com/request-a-quote

# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature [Request?]([url]([url](url)))
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. This is not a support channel. This is for reporting bugs or making feature requests. If you would like to report a bug, not a site specific issue, please use the issue template.

 If you would like support, please use CalderaForms.com/support
