### ISSUE TITLE
Error in admin undefined function date_diff() in PHP 5.2

### ISSUE THREAD

**Issue by sebastiandorn** [CalderaWP/Caldera-Forms#1829]
Hello,

I updated the Caldera-Form to the current version. I opened the plugin site in the backend and click on update. I get the message 'Successful'. After it I want to change some forms. I get a error-message, I enabled the Wordpress debugging. When I try to open Caldera Forms --> Forms in the backend:
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /homepages/21/d245052193/htdocs/neu/wp-content/plugins/caldera-forms/classes/admin/pro.php on line 112

Fatal error: Call to undefined function date_diff() in /homepages/21/d245052193/htdocs/neu/wp-content/plugins/caldera-forms/classes/admin/clippy.php on line 243

I get no error-message, when I open addons, support and Caldera forms pro in the backend.
I can also open the page on the website with the caldera form in it (http://www.juppenwerkstatt.at/neu/sample-page/organisation-team/mitglied-werden/).

When I open the plugin site, I get this error message:
Warning:  Unexpected character in input:  '\' (ASCII=92) state=1 in /homepages/21/d245052193/htdocs/neu/wp-content/plugins/caldera-forms/classes/admin/pro.php on line 112

I tried to deactivate all plugins and activate them again. When I want to active the other plugins (RoyalSlider, Booking Calendar, ...), I get this error-message:
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /homepages/21/d245052193/htdocs/neu/wp-content/plugins/caldera-forms/classes/admin/pro.php on line 112

Warning: Cannot modify header information - headers already sent by (output started at /homepages/21/d245052193/htdocs/neu/wp-content/plugins/caldera-forms/classes/admin/pro.php:112) in /homepages/21/d245052193/htdocs/neu/wp-includes/pluggable.php on line 1210

Warning: Cannot modify header information - headers already sent by (output started at /homepages/21/d245052193/htdocs/neu/wp-content/plugins/caldera-forms/classes/admin/pro.php:112) in /homepages/21/d245052193/htdocs/neu/wp-includes/pluggable.php on line 1210

Debug-Information
WordPress Version: 4.8.1PHP Version: 5.2.17MySQL Version: 5.5.57Caldera Forms Version: 1.5.4WP_DEBUG: 1

Many thanks for your help!
Regards
Sebastian

**Comment by Shelob9** [comment]
Sebastian - Thanks for using Caldera Forms. Looks like that function date_diff was added in PHP 5.3 and you're using PHP 5.2. I apologize, I should have been backwards compatible, I'll fix this.

But, you really should contact your host right away and ask them to move you to a current version of PHP. Security support for PHP 5.2 ended in 2008.

**Comment by Shelob9** [comment]
Close via c70d65
