### ISSUE TITLE
Email settings screen is not showing

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1846]

**Comment by Shelob9** [comment]
Probably broken in #1822

**Comment by leewagner** [comment]
I Have the same issue did you manage to fix it and how?

**Comment by brandltd** [comment]
Same issue here. Please offer solution.

**Comment by Shelob9** [comment]
@brandltd @leewagner I'm sorry you are having this issue, please expect a fix shortly -- I have done the work but need to double test it.

**Comment by Shelob9** [comment]
Fixed via 

1761120
--
