### ISSUE TITLE
PHP Warning 'Illegal string offset' when including form via file

### ISSUE THREAD

**Issue by hallosascha** [CalderaWP/Caldera-Forms#1850]
Please see possible solution at the bottom.

## Do You Need Immediate Help?
No.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 7.1.7-1+ubuntu16.04.1+deb.sury.org+1MySQL Version: 5.5.5Caldera Forms Version: 1.5.4WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
not relevant

## What Is The Unexpected Behaviour?
I'm including a form via a file. And I get a warning. I do not expect a warning to occure.

## What PHP Errors Have You Logged While Reproducing This Bug?
PHP Warning:  Illegal string offset '_external_form' in .../plugins/caldera-forms/classes/forms.php on line 454

## What JavaScript Errors Have You Seen While Reproducing This Bug?
not relevant

## Possible solution
I looked at the code and I think, just the line 454 has to be changed. It says `$forms[ $form_id ][ '_external_form' ] = true;` but instead it should say `$valid_forms[ $form_id ][ '_external_form' ] = true;` since `$valid_forms` is the array, which actually contains the forms, whereas `$forms` just holds the form IDs.

**Comment by Shelob9** [comment]
Close via 515cc88 thanks to pull request from @ictbeheer
