### ISSUE TITLE
Caldera admin page is not working

### ISSUE THREAD

**Issue by smitharajmenon** [CalderaWP/Caldera-Forms#1852]
After installing Caldera forms on clicking Caldera - Forms - page opens, then tracking window with msg opens and after that the form page doesnt show at all. Pls help

**Comment by Shelob9** [comment]
@smitharajmenon Thanks for using Caldera Forms. We can not accept any issues that do not use the new issue template. Please create a new issue with all of the requested information.

**Comment by smitharajmenon** [comment]
how do i do that? pls help
