### ISSUE TITLE
Forms previously working are now returning 502: The page request was canceled because it took too long to complete

### ISSUE THREAD

**Issue by nortoncw** [CalderaWP/Caldera-Forms#1855]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
Yes, I purchased a Caldera Forms Pro but am in the 7 day trial period and it doesn't give me an option to submit a Support ticket.  However, I did submit a comment ticket already.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
WordPress Version: 4.8.1PHP Version: 5.6.30-1+wpengine8MySQL Version: 5.6.36Caldera Forms Version: 1.5.4WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
Forms previously working are now timing out returning error 502.  If I disable the Caldera Forms plug in, they quickly display the header and Caldera Forms ID.  Re-enabling the plugin returns 502 errors. 

## What PHP Errors Have You Logged While Reproducing This Bug?
[Mon Aug 14 22:23:09.795265 2017] [core:error] [pid 18959] [client 104.244.231.200:13753] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., 

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none.

## What I've done to troubleshoot this bug?
Updated all plugins
No change
Updated WordPress Engine
No change
Clear cache
No change
 
Disable all plugins, clear cache
The pages then pull up as they are basic, just the title and form ID.
Enable Caldera Forms plugin only
Back to returning 502 error
 
Exported all forms (no data) so they could be reimported later. 
 
Disabled and then deleted Caldera Forms plugin
Cleared cache
Installed Caldera Forms from a new installation
No change
 
Changed the activation from Network Activation to activating at the site Plugins area. 
No change 
 
Went into Edit each form, checking for errors and saving forms.
No change

**Comment by Shelob9** [comment]
Close via 26c20ac #1860
