### ISSUE TITLE
Validation filters do not work on paragraph fields

### ISSUE THREAD

**Issue by figassis** [CalderaWP/Caldera-Forms#1858]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1
PHP Version: 7.1.8
MySQL Version: 5.7.19
Caldera Forms Version: 1.5.4

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
I wrote the following validation filter, which never fires even though my form has a textarea field which I consistently input over 2000 words. The caldera_forms_validate_field_{$field_id} also does not work, even though they all work with all other field types.:

```
function validate_textarea( $entry, $field, $form ){
	if( str_word_count($entry) > 250){
	    	return new WP_Error( 'format_error','250 words max' );		
	    }
  		return $entry;
} 
         
        add_filter( "caldera_forms_validate_field_paragraph", 'validate_textarea', 10, 3 ); 
```

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by figassis** [comment]
After some testing I realized that was because the field was set to "not required" so caldera ignored all validation in classes/core.php line 2855. I think that's the wrong way to go about it. If a field is not required, user input might still need validation if its not empty.

So why not change the line to `if ( ! empty( $field[ 'required' ] ) || $entry !== null) {`

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms.

Your filter should be called "caldera_forms_validate_field_paragraph" as the technical name of the field type is "paragraph". Should be called "textarea" but that fix would be not backwards-compat.

I always make sure to look in the Caldera_Forms_Fields class, as the big array of field types there is keyed by the name of the field as used by these types of dynamicly named filters.

**Comment by figassis** [comment]
My filter is called "caldera_forms_validate_field_paragraph". Its the function that's called validate_textarea, and that was not the issue. Please see the comment right before yours.
