### ISSUE TITLE
Email Settings page in admin is blank

### ISSUE THREAD

**Issue by SalamaInsurance** [CalderaWP/Caldera-Forms#1859]
## Is This A Feature Request?
*Email Settings page is blank. Cant see any settings options.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 5.6.31MySQL Version: 5.5.56Caldera Forms Version: 1.5.4WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Cannot afford to do that.

## What Is The Unexpected Behaviour?
settings is blank to configure the email server.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by armandolas** [comment]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1 PHP Version: 5.5.38 Caldera Forms Version: 1.5.4

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes
## What Is The Unexpected Behaviour?
Its happening to me in two different WordPress installations. When i click " email settings" nothing shows up(we used to have those options to chosse WP vs sendgrid, etc)

## What PHP Errors Have You Logged While Reproducing This Bug?
not sure
## What JavaScript Errors Have You Seen While Reproducing This Bug?
not sure

**Comment by Shelob9** [comment]
This is a duplicated of #1846 - the fix is included in caldera Forms 1.5.5
