### ISSUE TITLE
Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type()

### ISSUE THREAD

**Issue by omniacode** [CalderaWP/Caldera-Forms#1864]
Hey -

Using Caldera Forms version 1.5.5, I tried to "resend" an entry to one of my forms and got the following error message:

> Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /home/website/www/www/wp-content/plugins/caldera-forms/classes/magic.php on line 46 and defined in /home/website/www/www/wp-content/plugins/caldera-forms/classes/field/util.php on line 361

Cleared cache and reloaded the page and tried a 2nd time and received the same error.

Thanks :)

**Comment by Shelob9** [comment]
Should be fixed via 09aeae2 

@omniacode Can you update to latest from Github to confirm? I wasn't 100% sure I could reproduce this properly so would appreciate confirmation that this is fixed.

**Comment by Shelob9** [comment]
Close via 7f4f810

**Comment by omniacode** [comment]
Sorry, we have been swamped and I never got around to testing the fix. Wasn't a huge deal and I am sure it will be fine in the next update 👍
