### ISSUE TITLE
Calculation script does not show on second page

### ISSUE THREAD

**Issue by Omeida** [CalderaWP/Caldera-Forms#1869]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
    WordPress Version: 4.8.1PHP Version: 5.6.14MySQL Version: 5.1.30Caldera Forms Version: 1.5.4WP_DEBUG: 

The Unexpected Behaviour:
I created a field that calculates the amount of money in RMB, USD, and EURO, on the first page of the form. This works successfully and outputs the information. Then I created a second page and I then want to "pull in" the same figures calculated money from the first page by using h3 tags. So I expect the figures to show up exactly as is on the first page, not calculated again but just simply copy the result and input it using the h3. Instead, I get three blanks H3 entries without the values and I can not understand why all the other info successfully shows from the first page but not my three calculated figures.

The link to the broken apply page (it is on the third step/form page 3): http://www.omeidachinese.com/summer-camp/
The link to how it should look: http://dev.omeidachinese.com/apply/comprehensive-courses/

JavaScript Errors:
The script for only that specific tag, is not being picked up by my site  
[missing script.pdf](https://github.com/CalderaWP/Caldera-Forms/files/1238584/missing.script.pdf)
<img width="1164" alt="screen shot 2017-08-21 at 6 50 04 pm" src="https://user-images.githubusercontent.com/31206587/29516436-e8df599e-86a2-11e7-9628-e31d52f17980.png">
<img width="635" alt="screen shot 2017-08-21 at 6 09 20 pm" src="https://user-images.githubusercontent.com/31206587/29516840-bfd240dc-86a4-11e7-81d5-1cfb6da58284.png">
<img width="955" alt="screen shot 2017-08-21 at 6 49 12 pm" src="https://user-images.githubusercontent.com/31206587/29516844-c3c6d270-86a4-11e7-864b-d855d3a69b02.png">
<img width="1439" alt="screen shot 2017-08-21 at 6 48 27 pm" src="https://user-images.githubusercontent.com/31206587/29516886-09433c6c-86a5-11e7-8e9f-0cc95e4fe53f.png">

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms.

This sounds like a site-specific issue. If you need help working through this, please open a support ticket at https://calderaforms.com/support

Please note, all issues that do not follow the issue template will be close.
