### ISSUE TITLE
ENHANCEMENT REQUEST: Order forms by name

### ISSUE THREAD

**Issue by bmheck** [CalderaWP/Caldera-Forms#1872]
When you have lot of forms (because you find Caldera Forms so useful that you can’t stop developing them), it becomes time consuming to search through the list of forms to find the one that you want. Currently the list seems to be ordered by form creation date, which is not very helpful. 

REQUEST: List the forms in alphabetical order, or at least providing the option to do so.

**Comment by Shelob9** [comment]
I think having a order alphabetically option would be a sensible option, leaving the default the same. Order by date modified would be cool to.

**Comment by Shelob9** [comment]
There is now a UI option to order forms by name  #1872

**Comment by bmheck** [comment]
Thanks Josh!

Bill Heck
Regional Director - Mississippi Flyway North
National Audubon Society
