### ISSUE TITLE
Submit button becomes unavailable

### ISSUE THREAD

**Issue by Joe-DM** [CalderaWP/Caldera-Forms#1875]
I am having an issue that causes the Submit button to become blank and unavailable (the form cannot be submitted). The issue doesn't happen a lot and reloading the page usually fixes it. 

It happened again today and I decided to check the code, I noticed a couple of changes in the HTML when the issue happens. The input has two properties that are not there when the button loads properly: "disabled" and "aria-disabled". 

I took screenshots of both the "blank" and working buttons. There are also screenshots of the code for both instances.

http://imgur.com/a/UMAHl

PHP Version: 5.3.29
WordPress Version: 4.8.1
Caldera Forms Version: 1.5.5
Theme: GeneratePress Premium (Version 1.4)

Thanks in advance,
Joe

**Comment by Shelob9** [comment]
@Joe-DM Thanks for using Caldera Forms.

This sounds like a site-specific issue. If you need help working through this, please open a support ticket at https://calderaforms.com/support

Please note, all issues that do not follow the issue template will be close.
