### ISSUE TITLE
Radio button style broken

### ISSUE THREAD

**Issue by dhaval47** [CalderaWP/Caldera-Forms#1884]
In my form I have one toggle switch, on change I use conditional logic of hide and show radio field type.

By default radio field is shown. on change of toggle switch radio field hide and again when I change toggle switch, radio button show but without icheck (with default css).

**How it should work** 
When checkbox or radio field show after toggle/change any kind of conditional field it should display with proper css (with icheck css)

WP version :  4.7.5
CF version : 1.5.0.10

**Comment by Shelob9** [comment]
@mgibbs189 thanks for using Caldera Forms. Can you please upgrade to the latest version and try again? This should be fixed already in 1.5.5

**Comment by dhaval47** [comment]
Hi @Shelob9 I checked with latest version and still I am facing this issue.

**Comment by dhaval47** [comment]
Hi @Shelob9 Yes it is working fine in latest version.

Thank you for awesome work :)
