### ISSUE TITLE
Not showing entries in form admin despite having entries

### ISSUE THREAD

**Issue by HThurm** [CalderaWP/Caldera-Forms#1893]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 5.5.37MySQL Version: 5.5.51Caldera Forms Version: 1.5.5WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When accessing the entries section of the form, it will show a loading icon, then not show any data, despite having entries on that form. If I click Trash, it will show "no entries yet", and if I click back to active, it will show "no entries yet." If I lower the count of entries per page, the navigation buttons disappear and the "no entries yet" message appears. This issue occurs will all of the forms I have. 

I also changed the <div class="caldera-entry-exporter" in the toolbar.php file and <div class="tablenav caldera-table-nav" in the pagination.php file to display="block" from "hidden", since before I did that, when I would click "entries" under any of the forms, the page would be blank and the loading icon would show for a second. Switching those divs back to hidden did not resolve the entries not showing problem.

## What PHP Errors Have You Logged While Reproducing This Bug?
There were no errors reported regarding the caldera plugin

## What JavaScript Errors Have You Seen While Reproducing This Bug?
/website/wp-content/plugins/caldera-forms/assets/js/caldera-clippy.js?ver=1.5.5:67 Uncaught TypeError: Cannot read property 'remove' of null
    at CalderaFormsAdminClippys2.remove (/website/wp-content/plugins/caldera-forms/assets/js/caldera-clippy.js?ver=1.5.5:67)
    at HTMLAnchorElement.<anonymous> (/website/wp-content/plugins/caldera-forms/assets/build/js/admin.min.js?ver=1.5.5:1)
    at HTMLAnchorElement.dispatch (load-scripts.php:3)
    at HTMLAnchorElement.r.handle (load-scripts.php:3)
    at Object.trigger (load-scripts.php:3)
    at Object.a.event.trigger (load-scripts.php:9)
    at HTMLAnchorElement.<anonymous> (load-scripts.php:3)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at a.fn.init.trigger (load-scripts.php:3)

**Comment by Shelob9** [comment]
Pretty sure this only happens if "clippy zone" - the 3 boxes on the right side of main admin don't load properly. Not 100% sure, but 0471d1f will protect against that not being a DOM element, as is the case in the error `Cannot read property 'remove' of null
at CalderaFormsAdminClippys2.remove (/website/wp-content/plugins/caldera-forms/assets/js/caldera-clippy.js?ver=1.5.5:67)` shown above.

**Comment by HThurm** [comment]
I made the changes to the files, the entries are still not showing up in the admin panel. Pulled up java dashboard and found this error:

parsley.min.js?ver=1.5.5:2 Accessing the method 'addValidator' through ParsleyValidator is deprecated. Simply call 'window.Parsley.addValidator(...)'
warn @ parsley.min.js?ver=1.5.5:2

**Comment by HThurm** [comment]
Just checked the Java console again, I am still receiving the same errors as in the original post. Additionally, I think I am starting to see where the problem may lie. Receiving a 403 error on loading the following scripts when I click "entries" under any of the forms (even though I am logged in as an admin):


POST http://prvteye.com/website/wp-admin/admin-ajax.php 403 load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-resizable,jquery-ui-button,jquery-ui-dialog,plupload&ver=4.8.1:4  (Forbidden) 
send @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-resizable,jquery-ui-button,jquery-ui-dialog,plupload&ver=4.8.1:4
ajax @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-resizable,jquery-ui-button,jquery-ui-dialog,plupload&ver=4.8.1:4
request @ wp-baldrick-full.min.js?ver=1.5.5:2
c @ wp-baldrick-full.min.js?ver=1.5.5:2
(anonymous) @ wp-baldrick-full.min.js?ver=1.5.5:3
dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-resizable,jquery-ui-button,jquery-ui-dialog,plupload&ver=4.8.1:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-resizable,jquery-ui-button,jquery-ui-dialog,plupload&ver=4.8.1:3
