### ISSUE TITLE
Layout is not working

### ISSUE THREAD

**Issue by rajmakhija** [CalderaWP/Caldera-Forms#1898]
![layout](https://user-images.githubusercontent.com/31541479/29971551-3dd73272-8f46-11e7-91bd-b4cfc2714178.PNG)
![form](https://user-images.githubusercontent.com/31541479/29971550-3dd6954c-8f46-11e7-8096-14c1834f9b92.PNG)

# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by rajmakhija** [comment]
I am really fed up with this issue.
Followed these Steps:
1. Installed Free Plugin
2. Created a form with dividing 2 columns
3. On preview mode, my layout is not column based it's in row format as shared screenshot above
4. Even tried on different website same issues

Please help with this matter
I hope you now understood what my pain area is.
