### ISSUE TITLE
Spacing & Alignment issue

### ISSUE THREAD

**Issue by tech1790** [CalderaWP/Caldera-Forms#1907]
Hello,
 I am facing a few issues with my form as discussed below:
1 .I designed a form layout in which I split a row into two columns containing two fields "Title" (dropdown) and "PassengerName"(singletext).
When I am previewing the form, the two fields are showing up to be vertically aligned though they should be horizontally placed next to each other.   

2. The vertical spacing between the two fields "Name" and "Email Address" is too wide compared to the other fields in the form.

Please find attached screenshot for the same.
Please help me in addressing the aforementioned issues as I am a novice when it comes to programming.
[caderla Issue.docx](https://github.com/CalderaWP/Caldera-Forms/files/1274551/caderla.Issue.docx)

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
