### ISSUE TITLE
Enhancement: Filter for for wpautop in autoresponder mail

### ISSUE THREAD

**Issue by ictbeheer** [CalderaWP/Caldera-Forms#1917]
## Is This A Feature Request?
For the regular mail a filter exists to remove wpautop (#1048), however for the autoresponder mail no such filter exists. It would be nice if it would be possible to remove wpautop from the autoresponder mail.

**Comment by Shelob9** [comment]
Great idea. Let's do this in 1.5.7!

**Comment by Shelob9** [comment]
Same as bc0aaecfe17da0b655956d6165ec05e8dfcce00a but for auto-responder.

**Comment by Shelob9** [comment]
close via fb260ee
