### ISSUE TITLE
GRID LAYOUT NOT WORKING

### ISSUE THREAD

**Issue by rajmakhija** [CalderaWP/Caldera-Forms#1922]
I am really fed up with this issue.
Followed these Steps:

Installed Free Plugin
Created a form with dividing 2 columns
On preview mode, my layout is not column based it's in row format as shared screenshot above
Even tried on different website same issues
Please help with this matter
I hope you now understood what my pain area is.
![output_no grid working](https://user-images.githubusercontent.com/31541479/30105648-df0fe728-9316-11e7-80ca-a70560240e3c.PNG)
![grid layout](https://user-images.githubusercontent.com/31541479/30105650-df3a44fa-9316-11e7-877b-07f4d6de17fe.PNG)

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
