### ISSUE TITLE
Mixed Content / This request has been blocked

### ISSUE THREAD

**Issue by strarsis** [CalderaWP/Caldera-Forms#1942]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 7.1.8-2+ubuntu16.04.1+deb.sury.org+4MySQL Version: 5.5.5Caldera Forms Version: 1.5.5WP_DEBUG:

## What Is The Unexpected Behaviour?
I see a little warning icon in Chrome when I visit the admin area. 
In JavaScript console, several warnings are logged that resources cannot be loaded.
The site got HTTPS (for HTTP2) support using a Let's Encrypt certificate.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
````
Mixed Content: The page at 'https://www.example.com/wp/wp-admin/admin.php?page=caldera-forms' was loaded over HTTPS, but requested an insecure stylesheet 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css?ver=1.9.0'. This request has been blocked; the content must be served over HTTPS.
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,jquery-ui-core,jquery-ui-mouse,jquery-ui-draggab&load[]=le,jquery-ui-sortable,zxcvbn-async,password-strength-meter&ver=4.8.1:9 JQMIGRATE: Migrate is installed, version 1.4.1
vue.min.js?ver=1.5.5:3 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
parsley.min.js?ver=1.5.5:2 Accessing the method 'addValidator' through ParsleyValidator is deprecated. Simply call 'window.Parsley.addValidator(...)'
warn @ parsley.min.js?ver=1.5.5:2
admin.php?page=caldera-forms:1 Mixed Content: The page at 'https://www.example.com/wp/wp-admin/admin.php?page=caldera-forms' was loaded over HTTPS, but requested an insecure stylesheet 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css?ver=1.9.0'. This request has been blocked; the content must be served over HTTPS.
````

**Comment by Shelob9** [comment]
@strarsis The script that is loaded incorrectly is `http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css?ver=1.9.0` That is not coming from Caldera Forms, you will need to find the plugin/theme that is loading that script with the wrong protocol and adjust it there.
