### ISSUE TITLE
Form page empty for non-admin users

### ISSUE THREAD

**Issue by strarsis** [CalderaWP/Caldera-Forms#1943]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 7.1.8-2+ubuntu16.04.1+deb.sury.org+4MySQL Version: 5.5.5Caldera Forms Version: 1.5.5WP_DEBUG:

## What Is The Unexpected Behaviour?
Form page is shown empty for non-admin users. 
Loading spinner appears and disappears.

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP errors.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
````
[Vue warn]: Cannot find element: #caldera-forms-clippy 
````

**Comment by Shelob9** [comment]
@strarsis By form page do you mean the entry viewer page or the page with the form shortcode?

**Comment by strarsis** [comment]
@Shelob9: The entry viewer page in admin backend (form-entries-viewer).

**Comment by strarsis** [comment]
@Shelob9: This still happens from time to time. How can I further help debugging?

**Comment by Shelob9** [comment]
Does your form have variables? If so, try again with 1.5.7.1.

If that doesn't work please use PHP erorr logging and your JavaScript
console to capture the error that it is causing it to be empty.

**Comment by strarsis** [comment]
No variables are used in the form - except for the mail settings (for sender email address + name).

**Comment by Shelob9** [comment]
This was fixed in 1.5.8
