### ISSUE TITLE
emails no longer sent after SendGrid upgrade

### ISSUE THREAD

**Issue by jpgoem** [CalderaWP/Caldera-Forms#1944]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
I have a fallback, by staying on the older version SendGrid 1.10.9.

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
No, it is an upgrade problem, when upgrading from SendGrid 1.10.9 to 1.11.7.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
WordPress Version: 4.8.1PHP Version: 7.0.14MySQL Version: 10.1.20Caldera Forms Version: 1.5.5WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
After upgrading the SendGrid plugin from 1.10.9 to 1.11.7, emails are no longer sent when submitting the contact forms.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/
no PHP errors.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
no JavaScript errors

**Comment by alrodgir** [comment]
I've the same error, I've supous it's a general bug :(

**Comment by jpgoem** [comment]
I tested again, and discovered that initially (last year) I was not taking into account the following note "If you are using the SendGrid Plugin, you should set email mode to WordPress, since that plugin takes over WordPress’ email system." 
The following was tested today and works fine for me : 
  1. SendGrid Plugin activated and email mode = WordPress
  2. SendGrid Plugin de-activated and email mode = SendGrid
