### ISSUE TITLE
Calculation field not working after updating

### ISSUE THREAD

**Issue by Jaska121** [CalderaWP/Caldera-Forms#1952]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 7.1.9MySQL Version: 5.5.5Caldera Forms Version: 1.5.6WP_DEBUG:

Form can be found on
https://www.Vaihdokki.com/myy

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Calculation field not calculating after update. Here you can see my formula. Is this a common problem or just me?

![nayttokuva 2017-09-14 kello 21 25 59](https://user-images.githubusercontent.com/30962889/30447272-39e533aa-9994-11e7-8aaa-22b122c91baf.png)

**Comment by Shelob9** [comment]
@Jaska121 Thanks for using Caldera Forms. Sorry about this issue? Do you have calculation value settings for these fields? If so, this is probably caused by #1953 which is about to get a fix.

**Comment by Jaska121** [comment]
Yeah, I do.
![nayttokuva 2017-09-14 kello 21 44 49](https://user-images.githubusercontent.com/30962889/30447930-05670674-9996-11e7-93fd-661a62c20178.png)

Great that it's been taken care of!

**Comment by Jaska121** [comment]
Apparently the calculation shows up correctly in the email summary.
