### ISSUE TITLE
CF_API_DATA is printed multiple times (sometimes, probably with multiple forms)

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1956]
only needed once.

**Comment by Shelob9** [comment]
Close via  07f264d

Complete https://app.asana.com/0/28975837849460/467784723296965

**Comment by Shelob9** [comment]
Close via 
07f264d

**Comment by keithpetrillo** [comment]
I'm running version 1.9.4 and seeing this issue again.
