### ISSUE TITLE
DatePicker - set only mondays available 

### ISSUE THREAD

**Issue by novatendencia** [CalderaWP/Caldera-Forms#1966]
Its posible to set only available mondays in date picker?

**Comment by Shelob9** [comment]
You can do this via the caldera_forms_field_attributes filter. https://calderaforms.com/doc/caldera_forms_field_attributes/

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
