### ISSUE TITLE
Compatibility with litespeed cache plugin (with solution inside)

### ISSUE THREAD

**Issue by hailite** [CalderaWP/Caldera-Forms#1968]
Please check this wiki for the compatibility improvement:

https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:lscwp:esi_sample

LSCWP v1.2.4+ will be released this week. If the compatibility issue can be fixed, we can add your plugin into our compatible plugin list.

**Comment by hailite** [comment]
I fixed it by https://github.com/CalderaWP/Caldera-Forms/pull/1971

Please check the pull request

**Comment by Shelob9** [comment]
@hailite I can't find your email address. I was wondering if I could ping you about an issue? I am Josh@CalderaWP.com

**Comment by hailite** [comment]
Yes I am here. About the nonce expiration issue, the temp solution is here:

If you want to set it on your side, you can change this part in render/nonce.php line 97:

```
		if ( ! $from_esi ) {
			if ( method_exists( 'LiteSpeed_Cache_API', 'esi_enabled' ) && LiteSpeed_Cache_API::esi_enabled() ) {
				if ( method_exists( 'LiteSpeed_Cache_API', 'v' ) && LiteSpeed_Cache_API::v( '1.2.4' ) ) {
					$params = array( 'form_id' => $form_id ) ;
					return LiteSpeed_Cache_API::esi_url( 'caldera_forms', 'Caldera Forms', $params ) ;
				}
			}
		}
```

to 

```
		if ( method_exists( 'LiteSpeed_Cache_API', 'esi_enabled' ) && LiteSpeed_Cache_API::esi_enabled() ) {
			if ( method_exists( 'LiteSpeed_Cache_API', 'v' ) && LiteSpeed_Cache_API::v( '1.2.4' ) ) {
				if ( ! $from_esi ) {
					$params = array( 'form_id' => $form_id ) ;
					return LiteSpeed_Cache_API::esi_url( 'caldera_forms', 'Caldera Forms', $params ) ;
				}
				else {
					LiteSpeed_Cache_API::set_cache_private() ;
					LiteSpeed_Cache_API::set_cache_no_vary() ;
				}
			}
		}
```

This will make the ESI block use private TTL setting which is 1800s by default. Should be able to fix this issue.

**Comment by hailite** [comment]
@Shelob9 Or if you would like to specify the TTL, you can change those two lines 
```
LiteSpeed_Cache_API::set_cache_private() ;
LiteSpeed_Cache_API::set_cache_no_vary() ;
```
to 
```
LiteSpeed_Cache_API::set_ttl( 600 ) ;
```
