### ISSUE TITLE
Caldera form entries error message "Page not found" when I try to download the uploaded file from completed form.

### ISSUE THREAD

**Issue by LeslieDev** [CalderaWP/Caldera-Forms#1973]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
Caldera Forms 1.5.5, Wordpress 4.8.2, Unsure of PHP 

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
What I did: I've created a form where users can upload a document.
What I expected to happen:  I expected to simply click and download the attached document from the form. 
What happened instead: When I look at the entries, all mandatory fields are completed but once I click on the attachment, the page "Page not found" appears. Please see screenshot below.

<img width="1436" alt="screen shot 2017-09-26 at 12 01 54 pm" src="https://user-images.githubusercontent.com/32295614/30854664-9d6cd19a-a2b2-11e7-8425-8deed08f034a.png">

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/ 
Unable to debug as website is in live environment.

**Comment by Shelob9** [comment]
@LeslieDev - Thanks for using Caldera Forms. Did you check the box to upload the file to the media library? If not they will not be saved.
