### ISSUE TITLE
Submit Button is Invisible, and CSS fix does not work. 

### ISSUE THREAD

**Issue by crackedv** [CalderaWP/Caldera-Forms#1981]
Prior to hovering, the "submit" button and the text that appears on it are the same color, and if the page is white, the entire business is the same color as the page, as well. I tried some fixes of my own, none of which worked, and used the code I found in your documentation:

/** Change Background color and text color **/
.caldera-grid .btn {
    background-color:blue;
    color:white;
}
This did not work either.  I am running WP 4.8.2 and PHP 5.6.30.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
