### ISSUE TITLE
401 Error on all pages with calera forms

### ISSUE THREAD

**Issue by jennafarr** [CalderaWP/Caldera-Forms#1984]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5.6.1 / 4.7.6 / 5.6

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Not sure...in production so I can't really do that 

## What Is The Unexpected Behaviour?
Just getting a 401 error on all pages with Caldera Forms:
"POST /wp-json/cf-api/v2/tokens/form HTTP/1.0" 401

**Comment by hahntech** [comment]
I have also been seeing these errors in my logs. When I test out the offending pages everything appears to be working correctly.... form loads, user submits form, I receive confirmation email. But why do we get these errors?

**Comment by Shelob9** [comment]
This is a minor bug. This could be related to your static html caching being set too long. Does this error go away when you load the page while logged in, which should bypass static html cache.

**Comment by hahntech** [comment]
Thanks for responding to my request.


All of my initial testing was done while logged in. I only tested it while logged out as part of the debug process. So whether I am logged in or not, the behavior does not change. I have even tested it on other people's devices.


Please let me know if there is anything I should try on my end to resolve the issue. This may be a minor bug, but it is preventing me from using these forms on my site until it is resolved.


Thanks for your time in resolving this matter.

--
Pete Hahn
Hahn-Tech, LLC
dryheat3@hahn-tech.com
www.hahn-tech.com

“Maximum Precision Through Intelligent Use of Minimal Resources”


________________________________

**Comment by jennafarr** [comment]
Yes, when we load the page logged in it shows a regular 200 code for POST /wp-json/cf-api/v2/tokens/form HTTP/1.0 but when a logged out users load the form we get a 401 POST /wp-json/cf-api/v2/tokens/form HTTP/1.0
