### ISSUE TITLE
Caldera forms not displaying correctly until I do a page refresh.

### ISSUE THREAD

**Issue by tjfeagin7** [CalderaWP/Caldera-Forms#1987]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
No
## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
Caldera - 1.5.6.1  Wordpress - 4.8.2  PHP - 7.0.24  Bridge Theme - 10.1.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
When I first view the form on the frontend of the website all the fields are in one column.  When I refresh the page the fields display correctly within different columns.  It then displays correctly until I open the website in a new instance.

![form-1](https://user-images.githubusercontent.com/32517093/31181002-cdc0cb92-a8e5-11e7-8d6d-24826866c023.JPG)
![form-2](https://user-images.githubusercontent.com/32517093/31181003-d0135068-a8e5-11e7-9f32-7ec36cc001a9.JPG)

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/
none
## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
none

**Comment by tjfeagin7** [comment]
This site is running under a temporary domain.  You will have to go to: https://hosts.cx/ and use the ip address with niewohnerbros.com to get the temp url and link for the site.  The form is under careers in the nav.  Thanks.

Tammy

**Comment by Shelob9** [comment]
Sounds like this is a performance issue. Our styles are probably being loaded in the footer and 

I would recommend updating to HTTPS right away, and then work on getting HTTP2.0 working as that would fix a lot of problems related to loading lots of scripts.
 
This is not a Caldera Forms issue itself, so I am closing this. If you need more help with your site, please open a support request.
