### ISSUE TITLE
Generated SQL does not contain all the conditions/parameters.

### ISSUE THREAD

**Issue by tberneman** [CalderaWP/Caldera-Forms#1988]
## Do You Need Immediate Help? No.
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request? No.
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using? WP v4.8.2, Caldera Forms v1.5.6.1, PHP v5.6.31, MySQL v5.6.23, Easy Queries v1.0.7

*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
Short Debug Information

WordPress Version: 4.8.2PHP Version: 5.6.31MySQL Version: 5.6.23Caldera Forms Version: 1.5.6.1WP_DEBUG:
Full Debug Information

WordPress Version: 4.8.2

PHP Version: 5.6.31

MySQL Version: 5.6.23

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36 OPR/48.0.2685.32

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: Yes
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 64M

Currently Active Theme: Unwind Child: 1.0.0

Plugins:

Admin Columns: 3.0.3 Not Active
Adminimize: 1.11.2 Not Active
Admin Menu Editor: 1.8 Not Active
Advanced Custom Fields: 4.4.12 Active
Advanced Custom Fields: Date and Time Picker: 2.1.5 Active
Advanced Text Widget: 2.0.10 Active
Akismet Anti-Spam: 4.0 Active
amr shortcode any widget: 3.6 Active
ARI Adminer: 1.1.5 Active
Better Font Awesome: 1.7.1 Active
Caldera Easy Queries: 1.0.7 Active
Caldera Forms: 1.5.6.1 Active
Caldera Forms - Run Action: 1.0.2 Active
CalderaWP License Manager: 1.2.9 Active
Contact Form 7: 4.9 Active
Custom Post Type UI: 1.5.5 Active
Duplicate Post: 3.2 Active
File Manager: 5.0.1 Active
Jetpack by WordPress.com: 5.4 Active
Livemesh SiteOrigin Widgets: 1.5.3 Active
ManageWP - Worker: 4.2.24 Not Active
Max Mega Menu: 2.3.8 Active
Page Builder by SiteOrigin: 2.5.13 Active
PHP Code Widget: 2.3 Active
SiteOrigin Installer: 0.1.3 Active
SiteOrigin Premium: 1.0.6 Active
SiteOrigin Widgets Bundle: 1.9.10 Active
Smart Slider 3 Pro: 3.2.8 Active
Widgets for SiteOrigin: 1.3.3 Active
WordPress Importer: 0.6.3 Not Active
WP Super Cache: 1.5.6 Not Active

## What Is The Unexpected Behaviour? Easy Queries SQL doesn't have all 3 of my conditions, just the first one. 

Website address: http://millersells2017.tryourweb.com/search/
Easy Queries setup screen:
FROM: Listings
Add Taxonomy Filter Group
WHERE CUSTOM FIELD   street_name   IN   {search:location}
OR
city   IN   {search:location}
OR
mls_number   IN   {search:location}

Here is the generated SQL:
SELECT 
  wp_posts.* 
FROM 
  wp_posts 
  INNER JOIN wp_postmeta ON (
    wp_posts.ID = wp_postmeta.post_id
  ) 
WHERE 
  1 = 1 
  AND (
    (
      wp_postmeta.meta_key = 'street_name' 
      AND wp_postmeta.meta_value IN ('batavia')
    )
  ) 
  AND wp_posts.post_type = 'listings' 
  AND (
    (wp_posts.post_status = 'publish')
  ) 
GROUP BY 
  wp_posts.ID 
ORDER BY 
  wp_posts.post_date DESC

As you can see it has the first condition in the generated SQL but not the 2nd or 3rd condition.

* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug? None.
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug? None.
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
Is this a question about our plugin Easy Queries? If so, please open a support request at https://CalderaForms.com/support -- Paying customers are entitled to support for Easy Queries there.
