### ISSUE TITLE
The caldera_forms_entry_viewer shortcode is not using output buffering

### ISSUE THREAD

**Issue by mathetos** [CalderaWP/Caldera-Forms#1992]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 4.8.2
* PHP Version: 7.0.24
* MySQL Version: 5.6.36 
* Caldera Forms Version: 1.5.6.1
* WP_DEBUG: False

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Haven't tested yet, but the issue is a common issue with shortcodes and has a simple fix.

## What Is The EXPECTED Behavior?
When you use the Front-end submissions shortcode, the output should appear in the body copy where the shortcode was inserted.

## What is the UNEXPECTED Behavior?
Instead, the output is forced to the top of the body content regardless of where the shortcode is inserted. 

Note this is only with the version 2 viewer. Adding `type="classic" with_toolbar="true"` results in having the output put in the correct place in the content.

This is because it's not being output with `ob_get_contents()` or similar. Here's a good reference:
https://stackoverflow.com/questions/42586566/shortcode-output-always-showing-at-top-of-custom-template

**Comment by Shelob9** [comment]
https://wordpress.org/support/topic/bug-in-entry-viewer-diplay-function/

**Comment by Shelob9** [comment]
Close via 
2a36bb5
