### ISSUE TITLE
json_decode produces warning with code using get_entries for certain types of entries

### ISSUE THREAD

**Issue by mathetos** [CalderaWP/Caldera-Forms#1996]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 4.8.2
* PHP Version: 7.0.24
* MySQL Version: 5.6.36
* Caldera Forms Version: 1.5.6.1
* WP_DEBUG: false

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Using [this code](https://calderaforms.com/doc/get-entries-from-a-form/) in Docs produces a PHP warning:
`json_decode() expects parameter 1 to be string` on this line: 
https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/admin.php#L966

It doesn't happen for all forms/entries. It works fine for some and not for others. The only difference I can tell is that the forms it's not working for have entries that are showing some custom fields in the entries table whereas others are just showing the default fields in the entries table.

## Potential Fix
Switching the line above from `json_decode` to `maybe_unserialize` seems to resolve the issue but would need further testing.

**Comment by Shelob9** [comment]
@New0 I'm assigning to you. I assume in some cases on L963 checkbox fields that are stored as JSON are already parsed back to an array (or object).  So wrapping `json_decode` in `is_string()` is needed, but make sure that checkboxes and non-multi select fields display in emails and entry viewer properly.

**Comment by Shelob9** [comment]
Close via 90a7bd4
