### ISSUE TITLE
Delete Entries Option

### ISSUE THREAD

**Issue by paulca55** [CalderaWP/Caldera-Forms#2005]
## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

I set "Capture Entries" to disabled (for GDPR reasons) and there were already some entries saved. It's not necessarily a problem but when Capture Entries is enabled again the previous entries were still there. This could catch some people out as information from the form is still in the database which could mean the website is not compliant. Is it possible to have the option to clear the entries as you disable Capture Entries?

**Comment by Shelob9** [comment]
Please see: #2108

**Comment by Shelob9** [comment]
@New0 
Steps:
- [ ] Add  button to form settings tab to delete all entries
- [ ] Add ability to bulk delete entries via REST API (There is `Caldera_Forms_API_Entries::delete_item()`, add a similar one to delete all entries of a form. `Caldera_Forms_Entry_Bulk::bulk_delete()` can do bulk deletes. #2498 will give us capability to find all by entry ID.

**Comment by Shelob9** [comment]
```
 $entries = \calderawp\CalderaFormsQueries\CalderaFormsQueries()->selectByFormId( 'CF5afb00e97d698', false );
        $entryIds = [];
        foreach( array_column( $entries, 'entry' ) as $entry ){
            $entryIds[] = $entry->id;
        }
        Caldera_Forms_Entry_Bulk::delete_entries($entryIds);
```

**Comment by Shelob9** [comment]
This is no longer blocked.

**Comment by Shelob9** [comment]
Close via #2509
