### ISSUE TITLE
website error

### ISSUE THREAD

**Issue by mickartz** [CalderaWP/Caldera-Forms#2016]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by mickartz** [comment]
There seems to be an issue with the website whereby once I log into the pro site there is a dropdown "choose subscription" which is unpopulated. A whopping great orange "choose" button but nothing else. I paid for this subscription 2 days ago when I had some time to set up some membership application forms for our local surf club and have been unable to progress since then.
The worst part is that the supporet ticket options for "immediate answers" for subscribers is hidden behind the same subscription choice screen, so that the ticket I submitted via the "everyone else" option still hasnt been answered. Im typing this here in the hope that some one may read my dilemma

![image](https://user-images.githubusercontent.com/392905/31574412-0808a198-b11b-11e7-8d35-bad3ea4f82c0.png)

**Comment by Shelob9** [comment]
Thanks for your purchase. We appreciate it. Looks like your API keys need
regenerated. Send us a message at https://calderaforms.com/contact and tell
us the email you used to sign up and we'll reset them for you.

**Comment by mickartz** [comment]
Thanks, I've done that and still waiting…but re-submitted

 

The email address is secretary@warrnamboolslsc.org.au

**Comment by mickartz** [comment]
Wow tried to submit and I get submission rejected, token invalid…there’s something critical with your website!

**Comment by Shelob9** [comment]
I'll take a look right now.

**Comment by mickartz** [comment]
Went through that time…shortened the message.

 

On the website I used a different email address on the original install (this one) but I'm pretty sure that was just for newsletter signups?

 

Your help appreciated thanks!

**Comment by Shelob9** [comment]
I just fixed your API keys and responded. Sorry, again, bad timing, Friday night. I'm actually working on the bug on our site that caused this right now.

**Comment by mickartz** [comment]
Brilliant and again appreciate the attention.. doing this as a hobby (creating the membership workflow/logic) for our local lifesaving club, so have to use my allotted time efficiently.  It’s a great product, just working up the learning curve!
