### ISSUE TITLE
Email notification report different (and wrong) value

### ISSUE THREAD

**Issue by cesqo** [CalderaWP/Caldera-Forms#2018]
Hi guys

I've got a really strange error in my caldera form installation on WP.

The email report (with the  {summary} tag) send me a different value, while in the entries on wordpress the value is another (and correct)....

I update the plugin at last version:
![mail-notification](https://user-images.githubusercontent.com/10668902/31586151-80e102f6-b1cd-11e7-9b42-c8cb9c3e0573.png)
![entry](https://user-images.githubusercontent.com/10668902/31586152-8104dbcc-b1cd-11e7-805f-8dc90b10535a.png)

Thank you
Francesco

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.6PHP Version: 5.4.45MySQL Version: 5.5.55Caldera Forms Version: 1.5.6.2WP_DEBUG:

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
