### ISSUE TITLE
Acces Denied

### ISSUE THREAD

**Issue by labuse974** [CalderaWP/Caldera-Forms#2020]
Hello,

I have a problem with the caldera form input already entered by the user. The forms are only displayed for "administrator" accounts. customers have the message "acces denied". Even by changing the rights of the "All" form in the admin does not change anything.

Thinks.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
