### ISSUE TITLE
Advanced file field required option doesn't block users to click and go to next page

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2021]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.2
PHP Version: 7.0.20-2~ubuntu14.04.1+deb.sury.org+1
MySQL Version: 5.5.5
Caldera Forms Version: 1.5.6.1

## What Is The Unexpected Behaviour?
On a multi page form, the advanced fiel field required option doesn't block users to click and go to next page, when I get to the submit button the form is not sent but no errors are thrown ( no console error or debug.log error)

**Comment by Shelob9** [comment]
@New0 Let's look at this one together. Get your brain ticking on how per page (tab really) validation should work vs how it works :)

**Comment by Shelob9** [comment]
Probably related: #1765

Probably relevant: https://stackoverflow.com/questions/24246098/parsley-custom-validator-is-not-working-for-javascript-installation

**Comment by Shelob9** [comment]
Ok, this was way less bad then it I thaught it was. We were echoing the wrong variable to output required. 

79e9e02 fixes this, but for some reason, and probably the same reason this only broke on multi-page, it validates on multi-page forms, but prints double errors.

**Comment by Shelob9** [comment]
close via #2098
