### ISSUE TITLE
Can't edit Caldera form; all fields blank in back end but visible on page

### ISSUE THREAD

**Issue by DAWHub** [CalderaWP/Caldera-Forms#2047]
# Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*WordPress Version: 4.8.3
PHP Version: 5.4.45
MySQL Version: 5.5.57
Caldera Forms Version: 1.5.6.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes, tried it on a brand new install on a subdomain, same issue

## What Is The Unexpected Behaviour?
* When trying to edit a Caldera form in WordPress backend, all the fields are blank and clicking the edit button next to each form doesn't do anything. In the front end the form appears to be working, I just can't edit it, it's almost like it's 'locked'. When attempting to click any of the form tabs ('Pages', 'Email', 'Processors' etc) nothing happens, I can't open those tabs.

When first creating a form, all seems to work. But save and close the form and then reopen and the blank un-editable status appears.

## What PHP Errors Have You Logged While Reproducing This Bug?
* Debug set to true on sudbdomain with Caldera installed; no PHP errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* None

**Comment by DAWHub** [comment]
I seem to have found a potential source of the bug. Whenever I enter HTML in the name field for a checkbox, the moment I save the form, exit then re-enter the form, the above behaviour occurs, i.e. the fields are all blank (although disabling CSS on the page shows they're still there)

Here's one of the filed names I put in the name for a checkbox field type:
<p style="text-align: left;color: #006AB3; background-color: #dbe9ee;padding: 20px;border-radius: 5px;overflow: hidden;">Support from representative  <span style="color: #FF0000;>*</span></p>
The slug I change to be a simple name, in the case above just "rep"

However when I just hide the label for the checkbox, remove the HTML in the field name, then the bug does not happen.

**# Conclusion:**

Your checkbox field type, and possible others, really don't like HTML in the field name and the form locks up. The reason I was putting html in the name is that it saves my having to add another HTML field. 

However I can work around it by adding the html field, but please guys can you look at this?

**Comment by Shelob9** [comment]
@DAWHub Thanks for using Caldera Forms. I'm sorry you're having this issue. Without any debug information, it's impossible to say if this is a site-specific error or a bug. I'm going to close this ticket as there is nothing actionable here.

I do agree that you you should not use HTML for the field name.
