### ISSUE TITLE
Small Syntax issue found formobject.js & Custom Callback

### ISSUE THREAD

**Issue by robwilde** [CalderaWP/Caldera-Forms#2051]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.3PHP Version: 7.0.25-1+ubuntu16.04.1+deb.sury.org+1MySQL Version: 5.5.5Caldera Forms Version: 1.5.6.2WP_DEBUG: 1

clean test environment with minimal plugins

- caldera-forms
- caldera-forms-run-action
- debug-bar-extender
- developer
- nginx-helper
- pep-shipping-calculator
- query-monitor
- wp-migrate-db-pro
- wps
- wp-migrate-db-pro-compatibility

## What Is The Unexpected Behaviour?
@Shelob9 as we discussed I am having trouble getting Custom Callback to fire either from Form Settings or from custom button. _Submission my JS Fu maybe not as strong as it should be_

**My Goal**
Fill in form details and Click button 1 _"Quote"_ which makes API request to external source (configured in back-end) and returns data. Data used to complete second query _"Order"_

I have used the following JS for testing and get event to fire but obj.data is undefined

```
;(function ($, window, document, undefined) {

    function pep_shipping_quote(obj) {
        console.log('formObj: ', obj);
    }

    $('#fld_2833393_1').onclick(pep_shipping_quote);

})(jQuery, window, document);
```

doing some reverse engineering, I so love this code ;), I found a slight oversight in formobjects.js line 71
`wp-content/plugins/caldera-forms/assets/js/formobject.js`

```
  /* new button handler */
  $('.caldera_forms_form').on('click','.cf-form-trigger', function( ev ){
    var clicked = $(this);
        form = clicked.closest('form.caldera_forms_form'),
        form_id = form.prop('id'),
        calderaforms = window[ form_id ],
        data = form.formJSON(),
        fields = {},
        target = clicked.data('target');
```

**_should be , after $(this) and not ;_**

The only doc I can find realting to Callback is [/custom-processing-of-caldera-forms-submissions/](https://calderaforms.com/doc/custom-processing-of-caldera-forms-submissions/)

Another item I am working on is to create a repeating section in a form i.e. adding multiple items. 
Any examples of callback usage would be so helpful.

**Comment by robwilde** [comment]
FYI: @Jojaba I am on poststatus.slack.com @mrwilde

**Comment by Shelob9** [comment]
Yes, that's a syntax error, but also, that code isn't used for custom callback as documented in that link.

I set the custom callback function setting for a form to "foons" and then I added this:

```
add_filter( 'wp_footer', function(){
	?>
	<script>
		function foons( obj ){
			console.log(obj);
		}
	</script>
	<?php
});
```

When I submitted my form, using a normal submit button, it console logged the submission as expected.

So, question for you, what are you doing, expecting this callback function specified in the form settings for this form? I am aware of no other ways to get it to run then submitting the form, but it's totally possible that you're talking about a feature I don't know about in my own plugin, which totally happens from time to time. Not often, but if this conversation is about how something I don't know exists is broken, I'm going to LOL and then I might be able to understand better :)

**Comment by Shelob9** [comment]
Also, what is this  `create a repeating section in a form i.e. adding multiple items.` you speak of? I'm super curious about that.

**Comment by robwilde** [comment]
I think we actually joked about this on twitter the other day but very early this morning, as I was reading back what I had written above I realized that if the form was dynamically using the callback based on the name provided then encapsulating the callback in an IFEI would cause a problem with scope.
So I added the callback at root level and OMG never guess what happened, it worked (:-.

However, I could not guess to work when using a custom button with a callback name. Does that work the same way? The current form design I am building needs to submit all the form data first, pre-process, then return a result, an estimate, then the user can place the order. Using variables to pass back data is cumbersome. 
When I realised the error I had made, regarding scope using the callback function in Form Settings, I had the idea to use the _submit button_ and the inhibit _notice function_. That will get me around that issue but still interested to know about the custom button callback.

**Comment by Shelob9** [comment]
Close via 3c14e92 

@robwilde  Feel free to keep discussing, I'm just closing since fixed.

**Comment by robwilde** [comment]
**Repeating Section** 
I am working on 2 projects, both of which have a need for repeating data. One is a loan application with several, possible, applicants and the other being a shipping calculator with an unspecified number of items to deliver. 
I am tinkering with a method of creating a form section, using a BS panel or well in a modal, made up of fields that can be extended from the front end and increment the slug field with each addition. So you can click a button and add User1; User2; User3 etc.
Now that I have two use cases I am working it into a separate plugin as an add-on of sorts. Is this feature in the pipeline?

**Comment by robwilde** [comment]
Does the custom button _Click Target_ callback work the same as the Form Settings _Callback Function_? 
it says under the field_name _"Selector or the callback function to push form values on click."_ but not sure if it is referring to JS or a WP Hook.
This will not fire like the Form Settings callback :(

**Comment by Shelob9** [comment]
OK, so right. `custom button callback.` I don't know what that's supposed to do, I didn't put it there, not sure it's ever done anything, I should remove it.

Different story.

I think coming at this discussion backwards -- https://meta.stackexchange.com/a/66378 -- Asking about how to get the callback function to run on the button custom callback, which I'm pretty isn't what it does, since the custom callback is sending data from a form submission, which doesn't exist before submission...

Is it possible, that what you're asking is how to make a field from a previous form in a sequence show up -- not the value, but the same field that edits the same value of the same entry? Right? If so, I think it's possible actually, but please confirm. Would be cool AF to do.

Re, is this in the pipeline, I mean I experience similar thoughts when I think about what I will do when I rewrite Connected Forms from scratch. I enjoy those thoughts but there are some road map items before that, so we're probably talking mid next year. If you want to make something to do this, and sell it on our site, that would be really cool and we can figure out how to do that so we're not competing with each other and we get some of the things in the core plugin that would make this a lot easier done.

**Comment by robwilde** [comment]
I have actually thought about using connected forms, seeing if I can get it to go from form1 to form2 and then back to form1 then to form3 or form2. Hope that is making sense, most of the time things in my head don't make sense to me without whiteboarding & Coffee. 
Glad I actually helped find a bug, so to speak, and not take up your time. 
Love the Idea "make something to do this, sell it on your site", will see what I can get working. Very much prefer building apps then client sites. Thanks for the help Josh.

**Comment by Shelob9** [comment]
So here's the thing about connected forms that is going to hurt you here -- {prev:*} magic tags are getting value of an earlier entry, then lets you set it as default of a different field. What you want is the same field.

This is totally doable, theoretically. There is a filter that controls form root element type. It defaults to `form`, but you can make it `div`. That way you could embed forms (or parts of forms, by filtering out unneeded forms) inside of other forms without ending up with `<form><form></form></form>` which is not valid HTML.

Making them of them edit the same entry, not sure of that one, but totally doable.

**Comment by Tofandel** [comment]
About this so called "custom button callback",
I want to change the email recipient (with the preprocessors) depending on wich button is clicked on a form page, this clicked button should also make it go to the next form page.

But I have no idea what the "Click target" field on the button is supposed to do and how to use it, and I cannot use the Next page button in the preprocessors or as a value (the next page doesn't submit a value :disappointed: )
Is it a javascript function ? An ID of the HTML element (like a hidden next page button) ?
I tried several things and none of them worked.

A bit of documentation on this button callback would be really appreciated, thanks.

@robwilde That's funny I need the exact same thing for this project as well, where can I find your add-on please ?

**Comment by elvinaliyev** [comment]
> FYI: @Jojaba I am on poststatus.slack.com @mrwilde

Hi, 

Were you able to develop a solution to repeating section problem in Caldera? I am trying to find at least some solutions. Cant find anything yet. 

Help will be appreciated
