### ISSUE TITLE
Submit button no longer submits anything

### ISSUE THREAD

**Issue by Jeantalus** [CalderaWP/Caldera-Forms#2054]
Hy and thank you for helping !

## Do You Need Immediate Help?
Yes

## Is This A Feature Request?
sorry, but i don't understand the question. English is not my language :(

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera : 1.5.6.2, worpress : 4.8.3–fr_FR 

## What Is The Unexpected Behaviour?
I've installed caldera forms yesterday and I am working on my first form. I was making tests by filling the form and sending it by clicking on the submit button. It worked well at the begining (I've recieved my five or six first attempts) but since this morning, the submit button no longer submits anything. (and I have no error reported). It means that I can click on the button, but nothing happens (no "your message has been successfully submitted" and no error message).
I've tried cleaning the cache and with other browser and stille have the same problem.

Here is the url for the test page with the form :

http://clesdesoi.com/index.php/test-3/

## What PHP Errors Have You Logged While Reproducing This Bug?
no php errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
no javascript errors

Thank you for considering my request,
Best regards,
David

**Comment by Shelob9** [comment]
David - Thanks for using Caldera Forms. I really appreciate it. That said, this is not a support channel, we can't help with site-specific issues here, this for organizing development.

Our support page is https://calderaforms.com/support

**Comment by Shelob9** [comment]
David - Thanks for using Caldera Forms. I really appreciate it. That said, this is not a support channel, we can't help with site-specific issues here, this for organizing development.

Our support page is https://calderaforms.com/support

**Comment by Shelob9** [comment]
David - Thanks for using Caldera Forms. I really appreciate it. That said, this is not a support channel, we can't help with site-specific issues here, this for organizing development.

Our support page is https://calderaforms.com/support
