### ISSUE TITLE
Calculation not working with Summary

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#2063]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5.7 / WordPress 4.8.3

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Calculation fields are always 0 if a summary field is added to the form
![capture](https://user-images.githubusercontent.com/20680030/32606607-9fe62b8c-c55e-11e7-851b-7388a4d8999c.PNG)

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
`1979 CALCULATIONS CREATED@1.5.5 DEV@1.5.6.2` Is the test that we were relying on for this. It's totally working too -- http://dev-cf-testing.pantheonsite.io/1979-calculations-created1-5-5-dev1-5-6-2/

That form has lots of conditionals -- exposes how they were breaking summaries and calculations in some cases before. I made a new test with no conditionals -- `2063 Calculations create@1.6.2.2 dev@1.5.7.1` ISSUE REPRODUCED - http://dev-cf-testing.pantheonsite.io/2063-caluclations-create1-6-2-2-dev1-5-7-1/

**Comment by Shelob9** [comment]
This doesn't work in 1.5.6.2 or 1.5.5 or 1.5.4 http://r-154-cf-testing.pantheonsite.io/2063-caluclations-create1-6-2-2-dev1-5-7-1/

**Comment by Shelob9** [comment]
Test 5a0486d1d5628e428b3399f1 is for this. I faked the baseline, failing on 1.5.7, which is good.

**Comment by Shelob9** [comment]
Test 5a0486d1d5628e428b3399f1 is also for this, passes on 1.5.6.2, failing on 1.5.7, which is good.

**Comment by Shelob9** [comment]
This is actually the same issue as #2082 and is fixed and tests are passing after #2143
