### ISSUE TITLE
If form has variables, error when showing entry viewer

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2069]
`Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /app/web/wp-content/plugins/caldera-forms/classes/magic.php on line 46`

Problem is global $form isn't set. Fucking globals.

**Comment by Shelob9** [comment]
close via 
3acee76

**Comment by Tofandel** [comment]
Reoccuring in 1.8.4
`Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /httpdocs/wp-content/plugins/caldera-forms/classes/magic.php on line 45 and defined in /httpdocs/wp-content/plugins/caldera-forms/classes/field/util.php:375`
