### ISSUE TITLE
Field Sync does not work if field was hidden due to Conditional Logic

### ISSUE THREAD

**Issue by vraja-ids** [CalderaWP/Caldera-Forms#2075]
## Do You Need Immediate Help?
Yes.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.6.5.2
WordPress 4.8.1 running Enfold theme.
PHP 5.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
In the registration form, add Field Sync for fields with Two People or Three People from first person info by adding %slug% in the default value for the fields.

## What PHP Errors Have You Logged While Reproducing This Bug?
None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None.

**Comment by Shelob9** [comment]
My fixes works, but it also causes values to reset in some situations. I'm punting this to 1.5.9

**Comment by Shelob9** [comment]
I am moving to 1.6.0 milestone as PR #2345 will fix this.

**Comment by Shelob9** [comment]
close via 6fba27c  #2345

**Comment by Shelob9** [comment]
I added the test `2075 Sync Multi-page create@1.60` to cover sync across pages in 64abc57
