### ISSUE TITLE
Calendar issue

### ISSUE THREAD

**Issue by naxiand** [CalderaWP/Caldera-Forms#2077]
The calendar doesnt apear for firefox . Latest version for everything. It works for chrome and edge though.
https://cl.ly/2M1E0R0M0L2g

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
