### ISSUE TITLE
Entry Viewer shows checkboxes as JSON encoded data

### ISSUE THREAD

**Issue by cargeo** [CalderaWP/Caldera-Forms#2078]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.3
PHP Version: 7.0.20-nmm1
MySQL Version: 5.7.15
Caldera Forms Version: 1.5.7.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
No

## What Is The Unexpected Behaviour?
In the CSV file and in the the Admin View all checkbox options contain JSON-like data, e.g. if the option is "yes" it shows {"opt1649190":"yes"}

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
Close via #2078 Thanks @New0
