### ISSUE TITLE
Check box and radio button labels dont display in Internet Explorer 11

### ISSUE THREAD

**Issue by YuppSirup** [CalderaWP/Caldera-Forms#2080]
Check box and radio button labels dont display in Internet Explorer 11 (works in Chrome and Firefox))

- Caldera Version: 1.5.7.1

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
