### ISSUE TITLE
Default value of select fields only handled with calculation value

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2082]
Reproducible issue at :
- https://secure.helpscout.net/conversation/430142856/5136/

When a select field value is involved in a calculation, it always need to be set manually. Otherwise a default value that remain unchanged won't be taken into account by the calculation

**Comment by New0** [comment]
Default value of select fields only handled with calculation value when manually set select field with empty calculation field and a value field work

**Comment by Shelob9** [comment]
@New0 I'm assigning this to you.

**Comment by Shelob9** [comment]
Related #2090

**Comment by Shelob9** [comment]
Also probably related  ##2076

**Comment by Shelob9** [comment]
Reassigning to me

**Comment by Shelob9** [comment]
Test "2082 Calculations created@1.5.7.1 dev@1.5.8" now exists for this issue.

**Comment by Shelob9** [comment]
b0ba255 fixes #2090 This issue is not yet fixed.

**Comment by Shelob9** [comment]
Test "2082 Calculations created@1.5.7.1 dev@1.5.8" covers this.

**Comment by Shelob9** [comment]
Close via  #2143
