### ISSUE TITLE
Caldera Form not displaying properly

### ISSUE THREAD

**Issue by kslingsby** [CalderaWP/Caldera-Forms#2085]
Using WP 4.8.3 & Caldera Forms 1.5.7.1 & PHP 5.6
Theme Exodus

I have created a form with 3 fields across one column, so they should appear next to each other across the page. However, the whole form occupies just about one third of the available width, with the fields underneath one another. In the 2017 theme, the full width is used, but the fields are still underneath one another instead of side by side.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
