### ISSUE TITLE
Form does not display properly

### ISSUE THREAD

**Issue by kc015** [CalderaWP/Caldera-Forms#2086]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
@kc015 Thanks for using Caldera Forms. Here is the docs that explain this message: https://calderaforms.com/doc/getting-submission-url-current-url-protocols-not-match-warning-caldera-forms/

If you need help getting this fixed on your site, please open a support request at https://calderaforms.com/support
