### ISSUE TITLE
Section break are exported

### ISSUE THREAD

**Issue by koko-ng** [CalderaWP/Caldera-Forms#2089]
WordPress Version: 4.8.3 PHP Version: 7.0.20 MySQL Version: 5.6.35 Caldera Forms Version: 1.5.6.2

When entries are exported, CSV file has a column for the section break, which obviously is empty. I think a way to avoid these fields from being exported would be a more intuitive behavior. Maybe an empty column could also be good.

**Comment by Shelob9** [comment]
Technically speaking, the problem is either section break is registered without not_supports set properly or that setting isn't respected.

**Comment by Shelob9** [comment]
@New0 Look at how button fields work re: not saving

**Comment by Shelob9** [comment]
Close via 
01d761e
