### ISSUE TITLE
Add aria-label for form

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2093]
@bamadesigner pointed out while discussing #2091 that we need a label for the form. I suggest we use `$form[ 'name' ]` and by default hide it using the `sr-only` class so we don't mess with any existing layouts. Need a filter to pull that out.

https://github.com/CalderaWP/Caldera-Forms/pull/2091#issuecomment-346166619

**Comment by bamadesigner** [comment]
You wont' have to hide anything. Just do: `<form aria-label="<?php echo $form[ 'name' ] . '"...>`.

**Comment by Shelob9** [comment]
Fixed via 
ffdd1a1 

#thanksRachel
