### ISSUE TITLE
Manually trigger calculation?

### ISSUE THREAD

**Issue by marianssen** [CalderaWP/Caldera-Forms#2096]
I've built a day counter using two of your bootstrap datepickers. The result is a number of days inserted into Caldera field, which should then be used in calculation in another field using caldera calculation. However, since the number of days is inserted outside Caldera, it does not trigger the calculation function.

Could you please suggest, how can I run the caldera calculation inside my function? Or change the trigger event on the input field, where I'm importing the number of days?

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We really appreciate it. Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

I would use a hidden field and set the number of days in there, using the CFState object stored in window.cfstate or use jQuery.val()

**Comment by Shelob9** [comment]
BTW If you don't see the value of the calculation change after updating the hidden field. Try `jQuery( document ).trigger( 'cf.add' );`
