### ISSUE TITLE
caldera form "Advanced File Uploader" vs "File"

### ISSUE THREAD

**Issue by mohamed-talha** [CalderaWP/Caldera-Forms#2097]
I have a contact form and i use Caldera form.

Users can attach a file to their message so I used the "Advanced File Uploader". When a test nothing happens. But by using the simple "File" uploader it works fine.

Can you help me please ?

Thanks

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
