### ISSUE TITLE
File doesn't attach, plus email content borked

### ISSUE THREAD

**Issue by ManaUser** [CalderaWP/Caldera-Forms#2101]
## Do You Need Immediate Help?
No.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9
PHP Version: 7.0.25
MySQL Version: 5.5.5
Caldera Forms Version: 1.5.7.1
WP_DEBUG: 1
(This is the free version of Caldera Forms.)

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
I am using the simple file uploader with a single file.

First of all, in no case does the file actually get attached to email the form sends out.

Additionally, in some cases the URL for the uploaded file replaces the ENTIRE contents of the email.

## What PHP Errors Have You Logged While Reproducing This Bug?
Apparently none. I followed your directions, and the debug.log file was not created.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
I'm not an expert at using the console but, I did not see anything marked as an error.

## Full Details
Again, no matter what I do, the file is not actually attached to the email.

Depending on other settings, the second problem may or may not occur. The closest I can get to a good result is when I have "add to media library" checked, and use the default {summary} format for the mail. In this case I get a crudely formatted email contain all the information including a link to the file. Not terrible, but far from good.

If my email template includes %file% (i.e. the slug for my file filed) and "add to media library" is turned on, then the email contains NOTHING but the URL of the file. If %file% is not present, other content displays correctly, but obviously I don't get a link to the file. If %file% is present but "add to media library" is off, all content displays correctly, but the file URL doesn't actually work, because of course the file didn't get saved.

**Comment by Shelob9** [comment]
Semi-related #2021

**Comment by Shelob9** [comment]
Close via #2106
