### ISSUE TITLE
Credit card fields validate on wrong page of mutli-page forms

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2107]

**Comment by Shelob9** [comment]
The form in the test sheet 2107 Credit Card created@? dev@1.5.8 reproduces this.

**Comment by blunket** [comment]
Glad to see this is being worked on! Feel free to close #2095 now (I opened that one about this same issue).

**Comment by Shelob9** [comment]
@blunket Yep, I'm just describing it different here. Removing that function isn't a long-term solution, as it's supposed to disable advance if field is invalid __and it's on the current page__.

**Comment by Shelob9** [comment]
Note to future self, and others like me: you can determine what page a field is on, like this:
https://gist.github.com/Shelob9/ee38f435b9739f7821ab542af551be64

**Comment by Shelob9** [comment]
Should be fixed via 
7f2f6b2

Test "2107 Credit Card created@? dev@1.5.8" is defined in sheet, but not yet recored, will record tomorrow.

**Comment by Shelob9** [comment]
Test "2107 Credit Card created@? dev@1.5.8" is now created and passing on this PR.

**Comment by Shelob9** [comment]
Close via #2139
