### ISSUE TITLE
caldera form email notification not working

### ISSUE THREAD

**Issue by rbtviga** [CalderaWP/Caldera-Forms#2114]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
Caldera Forms 1.5.7.1
WordPress 4.9.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The email notification isnt working
So, Ive set it up so that i should be getting an email notification when someone submits a form 
and it simply isnt working 
I followed the instructions to the letter as indicated on this page
https://calderaforms.com/doc/setting-caldera-forms-email-notification/
and it still doesnt work

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I'm sorry you are having trouble with Caldera Forms. This does not sound like a bug, it sounds like a site-specific issue. To be handled here it would have to be an issue with Caldera Forms' code, which I don't see anything in your report to indicate.

Emails are very hard to debug, but it is something we are happy to help with via support - please open a ticket if you have a support subscription https://calderaforms.com

Please note, this is not a support channel.
