### ISSUE TITLE
GitHub Updater not working if plugin installed via w.org

### ISSUE THREAD

**Issue by afragen** [CalderaWP/Caldera-Forms#2115]
When installing Caldera Forms from w.org the plugin slug and directory name is `caldera-forms`. When installing from GitHub or via GitHub Updater the plugin slug and directory name is `Caldera-Forms`. At some point these may have been equivalent, but they aren't any longer.

What this means is that updates will come from the location of user installation.

If the user installed Caldera Forms from w.org the slug is `caldera-forms` and GHU will not see the GitHub repo as matching. That means GHU won't work.

If the user installs from GitHub the slug will be `Caldera-Forms` and all updates will come from GitHub and never from w.org.

The solution, if you want to take advantage of GHU, is to rename the GitHub repo to the same slug as in w.org.

If the user is on the `master` branch, all updates will come from w.org. It is no longer necessary to specify a `GitHub Branch` header as GHU will correctly store it if the plugin was installed via GitHub Updater or branch switching was used at any time.

For the screenshots below I made certain that the slug was `Caldera-Forms`.

With branch switching enabled.
![screenshot_02](https://user-images.githubusercontent.com/1296790/33535538-0bb9ff20-d863-11e7-86ae-d70786fdfa51.png)

With the branch switching dropdown selected.
![screenshot_01](https://user-images.githubusercontent.com/1296790/33535542-178cc3aa-d863-11e7-87e3-f99b477895b8.png)

When the branch was switched to something else.
![screenshot_03](https://user-images.githubusercontent.com/1296790/33535614-71d18594-d863-11e7-902d-6076d3a8e921.png)

BTW, this is all @royboy789's fault. #HiRoy

**Comment by afragen** [comment]
Hmm, I think w.org is case-insensitive. I just did the update above and the download installed from w.org. I guess that's better. Just need to make sure anyone wanting to use GHU changes the directory slug to `Caldera-Forms`.

**Comment by afragen** [comment]
So in DM with Josh it seems simply changing the from 
`GitHub Plugin URI: https://github.com/CalderaWP/Caldera-Forms`
to
`GitHub Plugin URI: https://github.com/CalderaWP/caldera-forms`
might solve the issue.

This would need to be done in all used branches. The `GitHub Branch` headers can be removed too. No longer needed.

**Comment by Shelob9** [comment]
Close via 67bcd67

Thanks Andy!

**Comment by afragen** [comment]
No problem Josh. Just remember you will need to make this change in all branches you think someone might switch to for testing and eventually in the branch that gets pushed to dot org.
