### ISSUE TITLE
Error 500 when the pulg-in is actived

### ISSUE THREAD

**Issue by peantoine** [CalderaWP/Caldera-Forms#2116]
Hello the team,

# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
I try to install it on WP  4.9.1 / PHP 5.6 / Last version 1.5.7.1 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
I have a probleme with wpml because you change the .httaccess

## What Is The Unexpected Behaviour?
I try to activate the plugin, but when it's activated, all my website return a 500 error

Regards,
peantoine

**Comment by peantoine** [comment]
I found a solution, I replaced the httaccess modified and changed my index.php
But the visualization of the form isn't possible but the form work well in production.
Regards

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. Please note we do not edit the .htacess file in anyway.

If you need support for site specific issues, please open a support ticket at https://calderaforms.com/support
