### ISSUE TITLE
CSV option on email not working

### ISSUE THREAD

**Issue by samkarpluk** [CalderaWP/Caldera-Forms#2123]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.1PHP Version: 7.0.26-1+ubuntu16.04.1+deb.sury.org+1MySQL Version: 5.5.5Caldera Forms Version: 1.5.7.1WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
I've activated the csv download on the form email tab, but not getting a csv attachment.

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors are being generated.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No js errors.

**Comment by New0** [comment]
I cannot reproduce this issue, @Shelob9 did you experienced it ?

**Comment by Shelob9** [comment]
@samkarpluk I see you're using  1.5.7.1, we are testing with 1.5.9.1 and can't reproduce this. Have you tried upgrading?

Sounds like #1978 BTW
