### ISSUE TITLE
Pods 2.7 problem if Caldera Forms 1.5.7.1 is installed

### ISSUE THREAD

**Issue by pierluigiabramo** [CalderaWP/Caldera-Forms#2124]
Hi developers! i have a problem with Caldera Forms 1.5.7.1 and Pods 2.7.. is better if you read the issue https://github.com/pods-framework/pods/issues/4589 Thanks!

**Comment by 0xLBF** [comment]
I think this might be the same issue as https://github.com/CalderaWP/Caldera-Forms/issues/1752

**Comment by 0xLBF** [comment]
I can also confirm that https://github.com/neilgilmour/Caldera-Forms/commit/5d95da451f08fa408a0b6019eeec9704161ec070 (along with editing the shortcode-insert.min.js as well of course) seems to fix the issue.

**Comment by hgordon-whoi** [comment]
I have both Caldera Forms 1.5.7.1 and Easy Pods 1.1.10 on a site with Pods 2.7.1. I have the same issues with the Pods Template editor not sizing or having the nice color coding anymore. I am using a Caldera Easy Pod with a Caldera Search Form to allow searching and displaying the pod.

**Comment by Shelob9** [comment]
#2150 
a3ade9d close via
