### ISSUE TITLE
CalderaForms interference with WooCommerce

### ISSUE THREAD

**Issue by webstr4711** [CalderaWP/Caldera-Forms#2129]
Hello,

When calderaForms is activated, I cant edit Orders in WooCommerce.
I get this error:

https://www.7visuals.com/download/wperror.png

WordPress Version: 4.9.1PHP Version: 5.6.31MySQL Version: 5.7.15Caldera Forms Version: 1.5.7.1WP_DEBUG: 1

Thanks for helping.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by dariovar** [comment]
I have the same problem… it's not related with the template, but with the WooCommerce…

**Comment by dariovar** [comment]
https://github.com/CalderaWP/Caldera-Forms/issues/2031
