### ISSUE TITLE
Button centered

### ISSUE THREAD

**Issue by ComputingFroggy** [CalderaWP/Caldera-Forms#2130]
Hello,

I am using Caldera with OceanWP theme and Elementor.
_WordPress Version: 4.9.1PHP Version: 5.6.31MySQL Version: 5.5.55Caldera Forms Version: 1.5.7.1WP_DEBUG:_ 

I’ve been trying to modify the display of the button using CSS as described in many web pages (for instance https://divinotes.com/styling-caldera-forms-submit-button/).

However, if the centering works the colour change does not work as the caldera style defined in caldera-forms-front.min.css is loaded last at the end of the document.

As a workaround I managed to style the button using the CSS id but this is not ideal.
Would you consider not loading the CSS style at the end of the page but in the header with the rest of the CSS style.

Cheers,
L@u

**Comment by New0** [comment]
Hello @ComputingFroggy,

Thank you for using Caldera Forms.

You will find documentation about the styles loading process and how to manage that at -- https://calderaforms.com/doc/caldera_forms_force_enqueue_styles_early/ --

Let us know at -- https://calderaforms.com/support/ -- if you need further help with that.

Kind regards,
