### ISSUE TITLE
Variable pricing (tshirts) template form item is ambiguous.

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#2134]
"Two Large" is supposed to be "too large," "two small" is supposed to be "too big"

entirely possible the answer here is "no, it's supposed to be 'one' and then 'two-small'," to which I would say: a user complained about this, and also when using the form myself I thought the same thing before I thought through why it  may not be a typo

**Comment by New0** [comment]
If I understood correctly... The field names Two big and Two small were a reference to Option 2 -> Big and Option 2 -> small.
In that case, too big and too small wouldn't have the correct meaning so I changed it to Value Big and Value small, does that work ?

**Comment by cicichirinos** [comment]
Perfect. 

I just want to eliminate possibilities of poor first impressions. 

Christie Chirinos
