### ISSUE TITLE
Email Notification does not work with a single form

### ISSUE THREAD

**Issue by afsps** [CalderaWP/Caldera-Forms#2136]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.1PHP Version: 7.0.25-1+ubuntu14.04.1+deb.sury.org+1MySQL Version: 5.6.33Caldera Forms Version: 1.5.7.1WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The Email notification does not work for a certain form (even the Resend button delivers no Email), all other 4 forms work but only deliver a message when I push the Resend button. 

## What PHP Errors Have You Logged While Reproducing This Bug?
Nothing

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Nothing

**Comment by Shelob9** [comment]
Closing this as it is Helpscout ticket 6519
