### ISSUE TITLE
Permanent delete of trashed entries in the entry pages

### ISSUE THREAD

**Issue by mdorchain** [CalderaWP/Caldera-Forms#2153]
Hi,

When browsing entry admin pages, there's no option to delete permanently the trash or to restore the entries. The only bulk options available are "Export entries" and "Move to Trash".
Shouldn't be the "Move to Trash" option removed and, "Restore" and "Delete Permanently" added for trashed elements ?

This bulk options are already working perfectly when the entries are accessed from the form, but not from the entry pages.

Thanks

Michael

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
