### ISSUE TITLE
Conditional forms not working anymore

### ISSUE THREAD

**Issue by abcwebsites** [CalderaWP/Caldera-Forms#2154]
The forms on my site have stopped working. E.g. on this page: https://abcsandbox.nl/vrijwilligers/, there are 2 buttons ('ja' and 'nee') which are supposed to open up text fields, but nothing is happening anymore. It used to work beautifully, not sure when it stopped working.

WP, theme and plugins are all uptodate.

**Comment by New0** [comment]
This issue was caused by a theme loading an outdated jQuery version ( 1.7.1 )
