### ISSUE TITLE
500: Internal server error

### ISSUE THREAD

**Issue by engonsi** [CalderaWP/Caldera-Forms#2190]
Hi ..
i am receiving this error as soon as i activate the plugin
------------------------------------------------------------------------
500: Internal server error

This error is generated when a script running on the server could not be implemented or permissions are incorrectly assigned for files or directories

Troubleshooting suggestions:

Temporarily disable any rewrite rules by renaming your .htaccess file if it exists.

Ensure that any CGI or Perl scripts have at least .755. permissions.

If trying to run PHP and you get this error, you may have an invalid php.ini in your /cgi-bin, or may be missing your php.dat file in this folder.
---------------------------------------------------------------------------------------

**Comment by Shelob9** [comment]
@engonsi Thanks for using Caldera Forms.

I apologize you are having this problem on your site. It looks like you need support for a site-specific issue. Please see: https://calderaforms.com/support if you need helpo.

This is an issue tracker for development. If you have a bug that you can reproduce with only Caldera Forms 1.5.8.2 and the default theme, please open a new issue with all items requested in the template. We will address the bug and add it to a milestone if valid. Please note, this will not lead to a quick resolution for your issue. If you need help with your site, please use our support channel.
