### ISSUE TITLE
Problem using a frontend edition form, with custom taxonomies

### ISSUE THREAD

**Issue by Dj4y** [CalderaWP/Caldera-Forms#2191]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera forms : 1.5.8.2 - Wordpress : 4.9.1 - PHP : 7.1.7

## What Is The Unexpected Behaviour?
It seems that cutom taxonomies in checkboxes or radio buttons doesn't work on frontend edition : values are not kept, nothing is checked. (it works with a manual list, but not with an autopopulated list of custom taxonomies)

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. Can you please open an issue in the repo for the custom fields add-on? This issue tracker is for core bugs only.

https://github.com/CalderaWP/caldera-custom-fields

**Comment by Dj4y** [comment]
oups, sorry ! done, thanks!
