### ISSUE TITLE
When conditions are set, in the fronteend appears "/*" bevor and "/*]]>*/" after the field, that was conditioned.

### ISSUE THREAD

**Issue by schmittfee** [CalderaWP/Caldera-Forms#2203]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
# #[https://intelligente-stadt.com/dienstleister-der-intelligenten-stadt/#cf-modal-CF5a4f4b655dbf05a4fad4780a2d](url)

**Comment by schmittfee** [comment]
![bug](https://user-images.githubusercontent.com/33862923/34619367-2d194042-f242-11e7-94b3-06bacbdecc51.jpg)

**Comment by schmittfee** [comment]
![bug](https://user-images.githubusercontent.com/33862923/34619389-435af3a0-f242-11e7-9825-58a56cf70641.jpg)

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. Please keep in mind, this is not a support channel. It's a tracker for bugs that need fixed and features that need added. This issue, which we see often is a plugin or theme conflict, not a bug.

If you need help debuging this site-specific issue -- BTW when this happens its either a theme/ page builder that applies WordPress formatting in the wrong order to post content or a caching plugin -- we can help, it's why we sell priority support through Caldera Forms Pro.
