### ISSUE TITLE
Auto Responder

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#221]
Hey

What about an option in the drop box in  to select to include all fields that were filled out.
I like getting a confirmation and the message I sent through a form to my own e-mail address.
I have a feeling that I am missing something here....and might addon with additional comments...

**Comment by soumyabg** [comment]
I think %summary% does the same

**Comment by paaljoachim** [comment]
Confirmation to user
Confirmation to admin
Auto responder

All of these have to do with showing a message or sending a message about the sent contact form. 
I will check out the logic on how these sections are in relation to each other. I believe there was something about the logic of it that threw me off.

**Comment by paaljoachim** [comment]
Processors:
We have the Auto Responder.
I notice no %summary% code easily available there. 
It could be the first choice in the code list.
Basically go through the list and check to see which shortcodes needs to be added. For instance %recipient_name% is not in the list but it is mentioned in the message. If one deletes the info in this box one also needs a way to get the %recipient_name% back again.

One of the more difficult parts can be to remember to set the various e-mail parts.
Success message, confirmation to user and to admin. So these need to be easily to get to. Perhaps some kind of reminder needs to be set.Perhaps in the All form. Have somekind of connection with info that need to be added to a form. 
Hmm not sure what a good way would be for this right now.

**Comment by Shelob9** [comment]
@paaljoachim I'm confused by `What about an option in the drop box in to select to include all fields that were filled out.` why not just use `{summary}` magic tag? That's what it does.

**Comment by paaljoachim** [comment]
Summery/All fields = first option in the drop down. Just have it clickable/available to choose in the drop down.
Then the various individual fields below this in the same drop down.
