### ISSUE TITLE
Auto Responder not working

### ISSUE THREAD

**Issue by customfit** [CalderaWP/Caldera-Forms#2211]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Form Version 1.5.8.2
Wordpress Version 4.9.1
PHP Version 7.0.15

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes, doesn't work with the default theme, disabled plugins either.

## What Is The Unexpected Behaviour?
Hello, after updating Caldera form to Version 1.5.8.2 , I noticed the Auto Responder stopped working. Email comes correctly to the email for the admin of the contact form, but the sender never receives an email. I tested it with a name an email I have an access to, and the email never came. I noticed new fields on the Auto Responder page such as: Reply to, CC and BCC, but I don’t think those fields would’ve affected the processor. It worked fine before the update. Any suggestions? Thanks

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by kathrynprice6** [comment]
Im having the same problem.

**Comment by customfit** [comment]
My issue got resolved, Nico from Caldera noticed that  the magic tags used to retrieve the email address field value were misspelled. Once fixed, the responder started working perfectly! 
The magic tag to retrieve a field's value need the actual slug of the field. Let me know if you need more help.
