### ISSUE TITLE
Removes LifterLMS "Courses" menu item from WP Admin screen on activation

### ISSUE THREAD

**Issue by bph** [CalderaWP/Caldera-Forms#2223]
When I activate Caldera forms plugin,  LifterLMS' menu item "Courses" is replaced by "Caldera Forms" menu item. Here is the screen recording: http://g.recordit.co/rvFhl8zVIB.gif
It also happens when Caldera Forms is activated before LifterLMS. 

WordPress Version: 4.9.1
PHP Version: 5.6.99-hhvm
MySQL Version: 5.5.5
Server Software: nginx/1.13.5

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP errors recorded

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No Javascript errors recorded

**Comment by bph** [comment]
For others having this problem: LifterLMS published a work around in their knowledge base in September 2017 https://nptp.us/2FxPvy5

**Comment by Shelob9** [comment]
[Apparently](https://twitter.com/chriscct7/status/952425966688600064) when @chriscct7 [fixed this in core](https://core.trac.wordpress.org/changeset/35477) he did it in a way that makes me wrong. Well played Chris.

Also, we need to remove at least two digits from our priority.

**Comment by chriscct7** [comment]
Actually you've just simply always been wrong in this regard. $position per
docs has always required an int. Though there was previous guidance there
that suggested doubles to avoid conflicts, it did so explicitly stating
they should cast to a string, ie '50.222' not 50.222 in the $position
parameter.

<?php
$arr   = array();
$arr[50] = 'test';
$chris = '50.22';
$josh  = 50.22;

echo isset( $arr[$josh] ) ? 'Josh is wrong. 50.222 is not the same  as
"50"' . PHP_EOL : 'Josh is right. 50.222 is not the same  as "50"' .
PHP_EOL;
$arr[$josh] =  "Overrode old value 'test'";

echo isset( $arr[$chris] ) ? 'Chris is wrong. 50.222 is not the same  as
"50"' . PHP_EOL : 'Chris is right. 50.222 is not the same  as "50"'.
PHP_EOL;
$arr[$chris] = "Works just fine";

print_r( $arr );

**Comment by chriscct7** [comment]
Thus all you need to do is change it to 50 (int) for WP 4.4+ support or
'50.22' (string) for all WP.

**Comment by Shelob9** [comment]
Close via 
cebef3f
