### ISSUE TITLE
Email notification not adhering to the "From Email" setting

### ISSUE THREAD

**Issue by Shane-C5** [CalderaWP/Caldera-Forms#2226]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
No

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
WordPress Version: 4.9.1PHP Version: 5.6.30MySQL Version: 5.6.32Caldera Forms Version: 1.5.8.2WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
Email Notifications started being emailed from no-reply@calderaformspro.net (rather than the settings in the From Email field) after I installed the Caldera Forms version 1.5.8.2 update.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shane-C5** [comment]
Hi

Is anyone else experiencing this issue?  

Thanks

**Comment by Shelob9** [comment]
@Shane-C5 This is the correct way it should work when using Caldera Forms Pro. I now this is confusing. We are making the labels more clear. #2304 

The reply to will be set correctly, but having it this way ensures that the sender domain is verified. It it were not, the emails would likely be flagged as spam or phishing.
