### ISSUE TITLE
Getting a fatal error when I want to activate Caldera forms plugin

### ISSUE THREAD

**Issue by ndcreativity** [CalderaWP/Caldera-Forms#2237]
## Do You Need Immediate Help?
* No, my problem is not that urgent.

## Is This A Feature Request?
* No, it's not a feature request.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* PHP Version: | 7.1.13
* WordPress Version: | 4.9.2
* Caldera Version 1.5.8.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* I'm using Semplice https://www.semplice.com/ as a theme

## What Is The Unexpected Behaviour?
* After installing I wanted to activate, but I can't.

## What PHP Errors Have You Logged While Reproducing This Bug?
* 
Warning: include_once(/var/www/wptbox/wp-content/plugins/caldera-forms/includes/plugin-page-banner.php): failed to open stream: No such file or directory in /var/www/wptbox/wp-content/plugins/caldera-forms/caldera-core.php on line 95

Warning: include_once(): Failed opening '/var/www/wptbox/wp-content/plugins/caldera-forms/includes/plugin-page-banner.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/wptbox/wp-content/plugins/caldera-forms/caldera-core.php on line 95

Warning: include_once(/var/www/wptbox/wp-content/plugins/caldera-forms/includes/updater.php): failed to open stream: No such file or directory in /var/www/wptbox/wp-content/plugins/caldera-forms/classes/core.php on line 449

Warning: include_once(): Failed opening '/var/www/wptbox/wp-content/plugins/caldera-forms/includes/updater.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/wptbox/wp-content/plugins/caldera-forms/classes/core.php on line 449

Fatal error: Uncaught Error: Call to undefined function caldera_forms_get_last_update_version() in /var/www/wptbox/wp-content/plugins/caldera-forms/classes/core.php:450 Stack trace: #0 /var/www/wptbox/wp-includes/class-wp-hook.php(286): Caldera_Forms::activate_caldera_forms('') #1 /var/www/wptbox/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /var/www/wptbox/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /var/www/wptbox/wp-admin/plugins.php(174): do_action('activate_calder...') #4 {main} thrown in /var/www/wptbox/wp-content/plugins/caldera-forms/classes/core.php on line 450

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* Idk

**Comment by Shelob9** [comment]
@ndcreativity Thanks for using Caldera Forms, I'm sorry you ahd this issue. It sounds like a bad download from WordPress.org The file it can't include is here: https://plugins.svn.wordpress.org/caldera-forms/tags/1.5.8.2/includes/updater.php

Can you try erasing the plugin and reinstalling please?

**Comment by Shelob9** [comment]
Closing, no response in 28 days.
