### ISSUE TITLE
Numeric field should keep the number part even if there are non numeric characters

### ISSUE THREAD

**Issue by CoolWind** [CalderaWP/Caldera-Forms#2241]
When using a numeric field, if the user enters an alphanumeric character, the whole field is then ignored.
For example, if the user enters 
12345 €
the "€" makes the field to become invalid.

In my opinion, what your plugin should do is remove the non numeric characters and keep just the number.

Wordpress 4.9.2
Caldera Forms 1.5.8.2 

Thank you.

**Comment by Shelob9** [comment]
@CoolWind Thanks for using Caldera Forms.

The number field is using the HTML type of "number" which according to the specification, does not allow non-numeric fields, so this is not possible.
