### ISSUE TITLE
Forms exported to PHP don't show up in wp-admin

### ISSUE THREAD

**Issue by iandunn** [CalderaWP/Caldera-Forms#2243]
The generated PHP code registers a callback for `caldera_forms_get_forms`, but is missing one for `caldera_forms_admin_forms`.

Related #262

WordPress Version: 4.9.2
PHP Version: 7.1.12
MySQL Version: 5.7.19
Caldera Forms Version: 1.5.8.2
WP_DEBUG: 1

**Comment by Shelob9** [comment]
I am reopening, I just tested this again. First time with one external form, this time with two, which caused a fatal error as both files added function `caldera_forms_register_forms` I'm going to make the function name include the form ID (`/^[A-Za-z0-9_]+$/`)

**Comment by Shelob9** [comment]
Should have been closed by 262bb5d 

Now close via 7b85555

**Comment by iandunn** [comment]
Doh! I should have thought of that, sorry about that :(
