### ISSUE TITLE
Forms exported to PHP are editable

### ISSUE THREAD

**Issue by iandunn** [CalderaWP/Caldera-Forms#2245]
Steps to reproduce:

1. Setup a form in the database
1. Exported it to PHP code
1. Modify the PHP code so that the form shows up in wp-admin (related: #2243 )
1. Click on the form's "Edit" link
1. Click Save

There's now a duplicate copy of the form in the database, but if you try to edit it again, you'll see the original external form, instead of the copy that was created. 

Adding the `_external_form` directive to the config during export would fix that.

WordPress Version: 4.9.2
PHP Version: 7.1.12
MySQL Version: 5.7.19
Caldera Forms Version: 1.5.8.2
WP_DEBUG: 1

**Comment by Shelob9** [comment]
Close via 
7c150ea
