### ISSUE TITLE
Caldera Form sends hidden copy of attached pdf-files 

### ISSUE THREAD

**Issue by Pausecomm** [CalderaWP/Caldera-Forms#2251]
Hi,
our client reports that sometimes when form is submitted they receive attached pdf-files from other forms that have been submitted earlier.

Also if BCC checkbox is checked this form is send back to person who fills that form.
(%send-copy-of-this-email-to-sender%) - and that person also got pdf-files from forms submitted earlier.
Not good because this form was used as a recruiting form.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Versio: 1.5.8.2 and PHP 7.0

**Comment by Shelob9** [comment]
@Pausecomm This is a troubling bug. Thanks for reporting it. Are you talking about the PDF of the entry attached by Caldera Forms Pro? If so, can you open a support ticket please - https://calderaforms.com/support ? We can more easily dig in and also get you the fast priority support if we go through there and have all of your account info and logs handy.

**Comment by Pausecomm** [comment]
Hi, no this was not Pro version but version available from WordPress Plugins directory.
We had to remove that plugin because of those weird pdf attacments.

**Comment by Shelob9** [comment]
@Pausecomm I'd really like to know what caused this problem for you. Is there anyway you can send me an export file of your form and a description of how to reproduce the issue? Right now, I'm not sure exactly what you're describing, but would like to be see this myself so I could see if it is a bug or an issue with your site/ form config.

My email is josh@calderawp.com
