### ISSUE TITLE
Help with Star Rating

### ISSUE THREAD

**Issue by ahinerfeld** [CalderaWP/Caldera-Forms#2256]
I have attached a copy of the form's json export file

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.2
PHP Version: 5.6.17-pl0-gentoo

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Unknown

## What Is The Unexpected Behaviour?
When I go to fill in the form and try to use the star rating to open a conditional filed for comments when I try and complete the Paragraph entry field the Star Rating changes and this closes the paragraph filed.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?

* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

[volunteer-hours-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/1658013/volunteer-hours-export.zip)

**Comment by Shelob9** [comment]
@ahinerfeld Thanks for reporting this. That should work, we'll look into why.

@New0 Please test the export form and make a test form/ acceptance test out of it.
