### ISSUE TITLE
With your new release on Caldera form nothing works anymore. 

### ISSUE THREAD

**Issue by pascale2018** [CalderaWP/Caldera-Forms#2262]
I made the update of Caldera form today. Now nothing works anymore, when I access Caldera form on my dashboard, 

Short Debug Information
WordPress Version: 4.9.2PHP Version: 7.0.10MySQL Version: 5.5.56Caldera Forms Version: 1.5.9.1WP_DEBUG: 
Full Debug Information
WordPress Version: 4.9.2
PHP Version: 7.0.10
MySQL Version: 5.5.56
Server Software: Apache
Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
Session Save Path: /var/opt/rh/rh-php70/lib/php/session
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache: 
Apc: No
Memcached: No
Redis: No
Object Cache: 
Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: f5l4y2nk_
WP Multisite Mode: No
WP Memory Limit: 40M
Currently Active Theme: U-Design Child: 

![image](https://user-images.githubusercontent.com/35871330/35473357-b478895a-037f-11e8-9566-72857418dfec.png)
![image](https://user-images.githubusercontent.com/35871330/35473387-21f28a9e-0380-11e8-82b8-034e70f59818.png)
![image](https://user-images.githubusercontent.com/35871330/35473438-04352c40-0381-11e8-87d1-4c21860abdfa.png)

**Comment by pascale2018** [comment]
Can someone from Caldera help me please?

**Comment by pascale2018** [comment]
I made a rollback but the same problems appear :(

**Comment by pascale2018** [comment]
Please I need support!!!!

**Comment by Shelob9** [comment]
@pascale2018 Sorry you're having these issues. Either some files are not loading or a PHP error is happening when you load the form editor. I can't tell with out looking at error logs or your JavaScript console.

It looks like you have purchased add-ons. This entitles you to priority support - https://calderaforms.com/support we can work with you to help you troubleshoot this.

**Comment by paaljoachim** [comment]
Hey @pascale2018 

NB! you can also use this plugin for now: https://wordpress.org/plugins/wp-rollback/ and roll back the plugin to the last working version for you.

**Comment by pascale2018** [comment]
Thank you for your great support! Everything works fine again.
