### ISSUE TITLE
Hi, French get mix in my English form...

### ISSUE THREAD

**Issue by paintyourfrstgraffiti** [CalderaWP/Caldera-Forms#2265]
Hi

I m using the Caldera Forms 1.5.9.1, that one that allow peoples to contact me through my website ( www.paintyourfirstgraffiti.com )

Everything is perfectly working except of the sending files button:

It is in French, when all the rest is in English...How could i change that please?

Thx a lot for your help!

Greets

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. The basic file field is a native HTML5 input. We don't have control over that message, it's set by the browser.

We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. 


Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by paintyourfrstgraffiti** [comment]
I'm not sure that i get it, that this a HTML5 input or not it is a problem
on your caldera form, a setting that you offer.

Whatever i m gonna change to another contact form



2018-01-29 21:01 GMT+01:00 Josh Pollock <notifications@github.com>:
