### ISSUE TITLE
Caldera form field creation is blocked

### ISSUE THREAD

**Issue by cperrin1967** [CalderaWP/Caldera-Forms#2277]
I use Caldera Form and it's work well until this morning.

Now I can't modify a existing field, the right window to define parameters of field is blocked to the first field and do not allow to switch to another one.

Or when I create a new field after drag and drop to add a new field, the right window to define parameters do not appears...

Thanks for your help :-)

![capture](https://user-images.githubusercontent.com/36067629/35723374-5bf7d9be-07fa-11e8-80b9-b6c72b4e6de8.PNG)

**Comment by New0** [comment]
Hello @cperrin1967 could you document this issue please ?

Could you report errors that show in the browser's console and share the debug.log file if generated after turning WP_DEBUG on ?

- How to check your JavaScript console in any browser - http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

- How to use the WordPress debug log to find hidden errors - https://calderaforms.com/2016/05/wordpress-debug-logging/

**Comment by Shelob9** [comment]
@cperrin1967 We have not heard back from you, so we are closing this ticket. 

Please feel free to open a new ticket, make sure to follow the template.

If you need immediate help, please use https://calderaforms.com/support

**Comment by New0** [comment]
As @Shelob9 said, feel free to open a new ticket, make sure to follow the template.

If you need immediate help, please use https://calderaforms.com/support
