### ISSUE TITLE
Wrong capability in example code in documentation

### ISSUE THREAD

**Issue by Aetles** [CalderaWP/Caldera-Forms#2281]
The documentation and examples [provided here](https://calderaforms.com/doc/caldera_forms_manage_cap/) contains this example code:

```php
/**
Allow users with the editor role to use the Caldera Forms admin screen
*/
add_filter( 'caldera_forms_manage_cap', function( $cap, $context ) {
	if( 'admin' == $context ) {
		return 'create_posts';
	}
	return $cap;
}, 10, 2 );
```

This does not work. Unless I'm mistaken there is no [capability](https://codex.wordpress.org/Roles_and_Capabilities) called `create_posts`. 

If you want to use a capability for the editor role I suggest `edit_pages` instead, like this:

```php
/**
Allow users with the editor role to use the Caldera Forms admin screen
*/
add_filter( 'caldera_forms_manage_cap', function( $cap, $context ) {
	if( 'admin' == $context ) {
		return 'edit_pages';
	}
	return $cap;
}, 10, 2 );
```

**Comment by Shelob9** [comment]
@Aetles Good catch. Thanks. I fixed it.
