### ISSUE TITLE
Page does not advance if number fields are empty

### ISSUE THREAD

**Issue by bostiq** [CalderaWP/Caldera-Forms#2282]
WordPress Version: 4.9.2PHP Version: 7.0.27MySQL Version: 5.6.36Caldera Forms Version: 1.5.9.1WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?

Yes

## What Is The Unexpected Behaviour?

I Simply created the *next* button at bottom of the page on a 3 page form and I'm not able to brows through pages.. not even with the *breadcrumbs*.

## What PHP Errors Have You Logged While Reproducing This Bug?

`[05-Feb-2018 10:56:22 UTC] PHP Notice:  Undefined variable: has_hero in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/settings/post-customizer/post-custom-styles-settings.php on line 102`

`[05-Feb-2018 10:56:22 UTC] PHP Notice:  Undefined variable: has_backimg in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/settings/post-customizer/post-custom-styles-settings.php on line 219`

`[05-Feb-2018 10:56:22 UTC] PHP Notice:  Kirki::add_field was called <strong>incorrectly</strong>. Do not use &quot;alpha&quot; as an argument in color controls. Use &quot;choices[alpha]&quot; instead. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.0.10.) in /home/indexweb/public_html/nira.com.au/wp-includes/functions.php on line 4147`

`[05-Feb-2018 10:56:22 UTC] PHP Notice:  Undefined variable: has_spacer in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/settings/post-customizer/post-custom-styles-settings.php on line 905`

`[05-Feb-2018 10:56:22 UTC] PHP Notice:  Undefined variable: custom_selector in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/settings/custom-modules/hide-custom-settings.php on line 42`

`[05-Feb-2018 10:56:25 UTC] PHP Notice:  Undefined variable: dce_output in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/output.php on line 59`

`[05-Feb-2018 10:56:25 UTC] PHP Notice:  Undefined variable: title_background in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/output/post-customizer/post-custom-styles-output.php on line 42`

`[05-Feb-2018 10:56:25 UTC] PHP Notice:  Undefined variable: title_padding in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/output/post-customizer/post-custom-styles-output.php on line 42`

`[05-Feb-2018 10:56:25 UTC] PHP Notice:  Undefined variable: meta_background in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/output/post-customizer/post-custom-styles-output.php on line 55`

`[05-Feb-2018 10:56:25 UTC] PHP Notice:  Undefined variable: meta_padding in /home/indexweb/public_html/nira.com.au/wp-content/themes/index-niri-divi_child/divi-children-engine/dce-customizer/output/post-customizer/post-custom-styles-output.php on line 55`

## What JavaScript Errors Have You Seen While Reproducing This Bug?
`[Violation] Forced reflow while executing JavaScript took 68ms`
`621:29:47.400 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='organization', confirm at <URL>) `
`621:29:47.400 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='name', confirm at <URL>) `
`1221:29:30.113 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='tel', confirm at <URL>) `
`621:29:47.402 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='email', confirm at <URL>) `
`1221:29:30.114 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='address-line1', confirm at <URL>) `
`621:29:47.402 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='postal-code', confirm at <URL>) `
`621:29:47.402 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='address-level1', confirm at <URL>) `
`621:29:47.402 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='address-line2', confirm at <URL>) `
`621:29:47.402 [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='address-level2', confirm at <URL>) `

Thanks for any help

**Comment by Shelob9** [comment]
@bostiq Thanks for reporting this. if you remove the plugins or themes that are making those warnings, does it resolve this issue?

Can you confirm that this is an issue with just TwentySeventeen, WordPress 4.9.4 and Caldera Forms 1.5.10-beta1? If so, it's probably a bug, we can look into it for the next release. It would be very helpful to have your form export. Can you send that please?

If you need help with an immediate work around or that kind of testing, please open a support ticket https://calderaforms.com/support

**Comment by bostiq** [comment]
Hi there, thanks for replying.
the behavior still the same
- with WP 4.9.4
-  with 2017 theme activated
- all other plug-ins deactivated
- caldera Version 1.5.9.1 NOT 1.5.10-beta ...no update available (as stated at the beginning of this thread)
- the log file is clean from any warnings or errors

Here the export of file
[nira-assessment-tool-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/1705195/nira-assessment-tool-export.json.zip)

Cheers.

**Comment by Shelob9** [comment]
@bostiq Thanks for that. I see the same issue in your form and in another form I'm testing

@robwilde See https://secure.helpscout.net/conversation/515243947/7376/ different user, with same issue.

The test form `2282 CF Feature: Multi-page create@x dev@1.6.0` reproduces this error.

**Comment by Shelob9** [comment]
FYI I made the name of this issue `Page does not advance if number fields are empty` because the actual problem is that a number field without any value is considered invalid by multi-page invalidation.

**Comment by bostiq** [comment]
@Shelob9 Yeah that seems better fitting. can't view that conversation though.. google credential won't let me in, and don't wanna have yet another account on some service, unless you deem it necessary to solve the issue.

Please, let me know if there's any breakthrough with this as eventually I'll need to create a prototype to show to client. which will lead to purchasing few extensions since it's already on the quote I gave them.

Also, perhaps you guys need to change the label of this issue as is still `Needs Feedback From User`.

Cheers!

**Comment by robwilde** [comment]
Received info after posting an issue on the Parsley repo, the issue is related to a controversial bug that `''` does not technically validate to an email or number when using `isValid({force: true})`.
They have posted an update to rectify parsley.js code base
[Parsley Commit](https://github.com/guillaumepotier/Parsley.js/commit/af2f99e77b54d4b70684caac9bf409c1e19184a7)

working on final testing and submission

**Comment by Shelob9** [comment]
Upgrade it

**Comment by bostiq** [comment]
Thank you! I will let you know after testing.

**Comment by Shelob9** [comment]
@bostiq My comment was aimed @robwilde he's going to update an internal dependency. 

Happy to have you test, nothing to test yet though. Please keep in mind this isn't our support system, this where we track development, since we're open source, you can follow and also help us, as you have done. 

Just keep in mind the messages you're getting here are technical discussions about developing the fix. I know that's weird and might feel like bad customer support, but this is not our support channel, feel free to follow along,it's open source.

**Comment by bostiq** [comment]
@Shelob9 Thanks for clarifying that.. I fully understand the process and the medium, I just misinterpreted the message ( or had wishful thinking!).  Also, I'm very happy to keep helping as tester if it's useful, when needed.

**Comment by Shelob9** [comment]
PR #2346 should resolve this

Acceptance test `2282 CF Feature: Multi-page create@1.6.0 dev@1.6.0` is updated to cover this.

**Comment by Shelob9** [comment]
Close via 5525abf #2346
