### ISSUE TITLE
Front End Post Creation bug

### ISSUE THREAD

**Issue by ahinerfeld** [CalderaWP/Caldera-Forms#2303]
I have created a Front End Post Generation form and I can generate the post and it processes but the web page form never clears and I just get a busy indication that never clears.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
