### ISSUE TITLE
Fields are cleared in Caldera Connected if back navigation is used

### ISSUE THREAD

**Issue by EmilyHazlehurst** [CalderaWP/Caldera-Forms#2305]
## Do You Need Immediate Help?
No
## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera 1.5.9.1
Connected Caldera 1.2.10
Wordpress 4.9.4
PHP  5.4.45

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
We have a 7 page form in Caldera Connected that has back and forward navigation between the pages. I would expect the form to display the user's field entries however many times the previous and next buttons are clicked, thus allowing them to make changes before submitting the form.

When navigating backwards and forwards a few times, eventually (after a seemingly random number of previous/next clicks) the form clears the data from the previous pages. If the form is submitted, the email summary still shows the original entries and they continue to appear in the database. 

Uploaded files never persist between form pages but do still get sent out with the mailer.

I've recreated the issue in a very simple 3 page form:

![caldera test](https://user-images.githubusercontent.com/24455584/36107411-d60722c2-1011-11e8-8960-2a56ad718f79.gif)

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
@EmilyHazlehurst Thanks for using Caldera Forms. I see you have an open ticket in our support waiting for a response from @New0 who is ready to help. We can help you there or if you want to create a new ticket please use https://calderaforms.com/support
