### ISSUE TITLE
Conditional Logic bug - special characters appearing out of nowhere

### ISSUE THREAD

**Issue by leolaurettimusic** [CalderaWP/Caldera-Forms#2310]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

Short Debug Information
WordPress Version: 4.9.4PHP Version: 7.0.27MySQL Version: 5.6.23Caldera Forms Version: 1.5.9.1WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
even if it did, if that persits, that's a no go

## What Is The Unexpected Behaviour?
I'm seeing some annoying special characters in the form that I'm creating whenever it activate a conditional logic

Example:
Subject *

**/***Topic*

**/*]]>*//***Track Link

Please, insert a Dropbox (or Soundcloud) URL
**/*]]>*/**

How can I fix this?

**Comment by Shelob9** [comment]
We see this mainly with caching plugins, w3tc especially. Try adding a cache exemption on the page with the form.

If you need help troubleshooting this on your site, please open a support ticket https://calderforms.com/support
