### ISSUE TITLE
Ajax form submission causes duplication of form

### ISSUE THREAD

**Issue by francisbarton** [CalderaWP/Caldera-Forms#2312]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.4
PHP Version: 5.6.32
MySQL Version: 5.6.38
Caldera Forms Version: 1.5.9.1
WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Not tried (site is live)

## What Is The Unexpected Behaviour?
When I complete the form and click Submit, a duplicate form appears below the original form and it is not clear if the form has submitted successfully. This only happens when Ajax Submissions is turned on in Form Settings.
If I turn Ajax off then the form works but the page reloads to the top leaving the submission confirmation message back at the bottom of the page where the form was, so the user will not see it.
See https://www.citizensonline.org.uk/contact-us/ for an example.

## What PHP Errors Have You Logged While Reproducing This Bug?
No relevant errors visible

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No relevant errors visible on console

**Comment by Shelob9** [comment]
This is a site-specific issue. It would indicate that you're getting an error during submission.

We can help you find this site specific error via support -- https://calderaforms.com/support
