### ISSUE TITLE
Warning illegal offset type thrown when custom field processor is used by the Form

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2318]
PHP Warning: Illegal offset type in isset or empty in /caldera-forms/classes/magic/doer.php on line 501 / 518 / 522

An array is passed as the key of an array in the magic_tag_meta_prepare() function.

**Comment by Shelob9** [comment]
Maybe related: #2295 
https://github.com/CalderaWP/Caldera-Forms/issues/2295#issuecomment-363984893 ?

**Comment by Shelob9** [comment]
Close via bc4c6e8   #2319
