### ISSUE TITLE
Translate press plugin translates some fields in contact form, except phone and your message.

### ISSUE THREAD

**Issue by stefanwebdevity** [CalderaWP/Caldera-Forms#2339]
Hi there!

I installed Translate press plugin for translating this website: http://cmplaw.ro

everything is great except two small issues: on the contact page, i have a contact form from you guys, and translate press can translate all the fields, except the phone and your message.

Please advise!

Best regards,
Stefan Caldare

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
