### ISSUE TITLE
cannot switch to the next page when email fields are not required and created as required at first

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#2344]
See: https://wordpress.org/support/topic/multi-page-not-working-good-with-email-fields/ 

Nico says it seems related with the creation of the field. He created a multi page form with an email field that was already created on the first page and that led to the email field being always required. If we delete the field and create a new one and the field works as expected.

**Comment by Wilfried1954** [comment]
I tryed to delete the field and create a new one. But it is still required. I attach a simple demo. If you leave the email empty you can not go to page 2. Rgds, Wilfried
[test-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/1792183/test-export.json.zip)

**Comment by Shelob9** [comment]
@Wilfried1954 This is probably the same bug, different symptom, as #2282 which I am working on now.

**Comment by Shelob9** [comment]
PR #2346 should resolve this

Acceptance test `2344 CF Feature: Multi-page create@1.6.0 dev@1.6.0` is created to cover this.

**Comment by Shelob9** [comment]
Close via 5525abf #2346
