### ISSUE TITLE
Form Processors Disapearing

### ISSUE THREAD

**Issue by npilk94** [CalderaWP/Caldera-Forms#2354]
I am having an issue to were the Form Processors will just disappear after saving and leaving Caldera Forms no matter what I do. I tried adding them back, but once I leave Caldera Forms and go back in, the Form Processors are all gone. All I see in the Form Processors the "Add Processor" button fading in and out. I have tried removing and adding back Caldera Forms, but no effect.

Thanks for any help on this.

**Short Debug Information:**
_WordPress Version: 4.9.4
PHP Version: 5.6.30
MySQL Version: 5.5.51
Caldera Forms Version: 1.5.9.1
Elementor Verision 1.9.7_

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
