### ISSUE TITLE
1 of 2 calculation fields, which are copies of 2 dropdown select fields, is incorrectly stored in the database

### ISSUE THREAD

**Issue by jpgoem** [CalderaWP/Caldera-Forms#2355]
## Do You Need Immediate Help?
No.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.4PHP Version: 7.1.10MySQL Version: 5.5.5Caldera Forms Version: 1.5.9.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
2 calculation fields, which are copies of 2 dropdown select fields, are correctly shown on the screen, but one of them is incorrectly stored in the database. In the attached example, copy1 is a copy of dropdown1 and shows the value 1, copy2 is a copy of dropdown2 and shows the value 2. In the database however, copy2 is zero ! 
![testform](https://user-images.githubusercontent.com/31822130/37258842-21e95ea4-257e-11e8-9642-2b2252841302.png)
![testform-database](https://user-images.githubusercontent.com/31822130/37258845-2e6c49c0-257e-11e8-80ef-650733f12c74.png)

[testform-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/1800922/testform-export.zip)

## What PHP Errors Have You Logged While Reproducing This Bug?
None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None.

**Comment by Shelob9** [comment]
@jpgoem  Thanks for using Caldera Forms and for attaching the form export. The big detail that this added is that you are setting field values using a variable. _That's not going to work_.

![screen shot 2018-03-12 at 12 43 40 pm](https://user-images.githubusercontent.com/1994311/37297075-2bb25a74-25f3-11e8-85c4-61715898e1b9.png)

There are many ways to set select fields dynamically that will work as alternatives:  https://calderaforms.com/doc/select-options/
