### ISSUE TITLE
Stripe and Connected Forms add ons compatability

### ISSUE THREAD

**Issue by Matthewnie** [CalderaWP/Caldera-Forms#2364]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.4
PHP Version: 7.0.27-1+ubuntu14.04.1+deb.sury.org+1
MySQL Version: 5.6.36
Caldera Forms Version: 1.5.9.1
Caldera Forms Stripe: 1.4.6
Connected Caldera Forms: 1.2.2

## What Is The Unexpected Behaviour?
I am trying to use Connected Forms with Stripe and am running into a few issues along the way.

1. I currently have a 2 part form, the stripe payment is on form 2, when filling out form 1 and loading form 2 I get a continual loading graphic because of a JS error for StripeCheckout `Uncaught ReferenceError: StripeCheckout is not defined`
2. I can then refresh the page and get the 2nd form to load and I have the back button option enabled, when I click the back button I get the stripe payment form, I do not get taken back to the previous form.  

## What JavaScript Errors Have You Seen While Reproducing This Bug?
`Uncaught ReferenceError: StripeCheckout is not defined`

**Comment by Shelob9** [comment]
@Matthewnie This looks like a question about a premium add-on. can you please open a support ticket at https://calderaforms.com/support ?
