### ISSUE TITLE
Save button not working

### ISSUE THREAD

**Issue by cjmiam** [CalderaWP/Caldera-Forms#2375]
v. 1.5.9.1

When trying to update the form, the save button does not work. Ie, any changes made to the form are not saved. I tried creating a new form and it saved it, but I am not able to make changes to it once it's created. 

Thanks. Chris

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
