### ISSUE TITLE
Editing multiple forms Mailer settings causes blocked IP address

### ISSUE THREAD

**Issue by lroyal** [CalderaWP/Caldera-Forms#2383]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.4PHP Version: 5.6.34MySQL Version: 10.0.34Caldera Forms Version: 1.5.9.1WP_DEBUG:

## What Is The Unexpected Behaviour?
Often when changing settings between multiple forms in the back end, in this case changing the email field in the 'Mailer' settings, it causes my IP address to be blocked from the hosting provider.
Steps:
1. Open Caldera forms tab in WP backend (with multiple forms set up)
2. Edit Mailer settings on Form 1 + save settings
3. Go back to all forms, and edit mailer settings on another form
4. Click 'Save Form' - nothing happens
5. Refresh - get redirected to page from hosting company saying my IP has been blocked.

Apologies there's not much more info to it, might just be me but it's happened almost every time I used Caldera forms.

**Comment by Shelob9** [comment]
@lroyal Thanks for using Caldera Forms. This is something you will need to contact your host about, I'm sorry but there is nothing we can do from our end.
