### ISSUE TITLE
More useful view for when Caldera Forms Pro is not connected

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2391]
This is what we have:
![screen shot 2018-03-26 at 5 43 34 pm](https://user-images.githubusercontent.com/1994311/37934757-4562a6ec-311d-11e8-9953-7c7a8c210040.png)

It does not:
* Explain what Caldera Forms Pro is and what it's value is.
* Explain how to start your free trial of Caldera Forms Pro.
* Help you install the add-ons .

It does have links for form settings and other things you don't need, which is not helpful. I'd like to have a nice on-boarding screen, that has a big "I'm Ready To Put In My API Keys" button, that then reveals the component to input API keys.

**Comment by Shelob9** [comment]
We may want to use @cicichirinos new video here when not connected. Related #2392

**Comment by amamlin** [comment]
Here is a different version of the tabs from the image provided. An orange box indicates that the corresponding option has been selected: 

![account](https://user-images.githubusercontent.com/38040370/38250025-a938817e-371b-11e8-8f30-87966d1439d4.jpg)
![cf-pro](https://user-images.githubusercontent.com/38040370/38250034-acd88c48-371b-11e8-9949-0d0ae2272cc3.jpg)
![free-trial](https://user-images.githubusercontent.com/38040370/38250042-b0bf37c6-371b-11e8-85e3-307a5951bae4.jpg)

**Comment by amamlin** [comment]
I think the current colors work well. The bright orange does a good job of indicating which tab's info the user is currently viewing.

**Comment by Shelob9** [comment]
@New0 I'm assigning this one to you. If you have time after GDPR or while blocked on GDPR, please work on this. Pro UI is now created in clients/pro
