### ISSUE TITLE
Calculation satisfaction

### ISSUE THREAD

**Issue by Bobo637** [CalderaWP/Caldera-Forms#2398]
round([%arena_length%+%arena_width%+%sand_to_fiber_rate04%+%divided_by_bale_weight%] /3 ,2) In php that formula work , but when i use in static forms is show me in round number white out decimals? I am limited because whit out "round" show 15 decimals.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
