### ISSUE TITLE
Cleaning up telephone number fields

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#2399]
Adding a phone number basic field adds:
(___)___-____ or other visible markers.
Removing the markers in custom makes the phone number field also use letters. Making it into a standard single line text field.

Adding a phone number better field shows the local field in the frontend if it is clicked or not. As I use US English in the backend for most of my Norwegian client sites it will show the local US field on the frontend. So this might just contain a bug as it will always show the local field on the frontend.

Adding a number field adds in the frontend an incremental drop down. (Please add a check box to turn it off.)

What I need is a plain number field to where the user can add their telephone number. None of the above really provides in a good way what is needed. On one site I have used the number field but having the incremental drop down just looks out of place.

**Comment by Shelob9** [comment]
@paaljoachim Sounds like you should either set the default country to Norway, or use a standard text field with input masking.

**Comment by paaljoachim** [comment]
Ahh...input masking works really well. I have not used it before since I did not know what it did do.
Now I know that Input Masking is a way to select what kind of input can be used. Thanks Josh!
