### ISSUE TITLE
PHP warning from entries API

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#2400]
PHP Warning: Invalid argument supplied for foreach() in /home/mccirmoc/public_html/dev/wp-content/plugins/caldera-forms/classes/api/entries.php on line 118

Reported on https://wordpress.org/support/topic/error-log-message-5/

**Comment by Colinsp** [comment]
This is in Wordpress v4.9.4 using the Suffusion v4.5.4 theme and php v7

**Comment by Shelob9** [comment]
@Colinsp What version of Caldera Forms are you using?

**Comment by Colinsp** [comment]
v1.6.0 (free)

**Comment by Shelob9** [comment]
Close via #2410 2da2485
