### ISSUE TITLE
Fatal error on PHP 5.2, due to namespace Caldera_FormsL1034

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2406]
`Parse error: syntax error, unexpected T_STRING in /home2/(REDACTED)/plugins/caldera-forms/classes/core.php on line 1034`

Support for PHP 5.2 should be kept in 1.5, also we should be wrapping that line in a check to see if pro is active, which doesn't fix core issue.

* Relevant code: https://github.com/CalderaWP/Caldera-Forms/blob/develop/classes/core.php#L1034

* Reported: https://wordpress.org/support/topic/upgraded-to-new-version-fatal-error/

**Comment by Soulfuric** [comment]
I updated to PHP 7.0 and still get the same error

**Comment by Shelob9** [comment]
You can easily go back to an older version of Caldera Forms using WP Rollback: https://wordpress.org/plugins/wp-rollback/

**Comment by Soulfuric** [comment]
Thank you, I'll give that a try.

**Comment by Soulfuric** [comment]
This worked. For now I'll just stick with the old version. My advice, if it ain't broke, don't fix it. haha

**Comment by Shelob9** [comment]
d2aa118 should fix it :)

**Comment by Shelob9** [comment]
Close via 7661a6c

**Comment by Shelob9** [comment]
@Soulfuric Can you please try using WP Rollback to update to 1.6.1.beta.1 please? I'd appreciate if you can let us know if that resolved your issue.

https://calderaforms.com/updates/caldera-forms-1-6-1-beta-1/
