### ISSUE TITLE
UI for marking fields as personally identifying

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2427]
Since there is no concept of which field is _The_ email field, we need a way to mark fields as personally identifying (#2426) and a screen or tab for marking a field as being an email field or name field that will need reported/deleted/exported.

**Comment by Shelob9** [comment]
0f241ac adds a setting to fields that get stored in the database -- not buttons -- to mark them as personally identifiable as expected by the functions created in #2426 to identify a field as personally identifiable. 

UI needs text optimization
![screen shot 2018-04-14 at 2 37 08 pm](https://user-images.githubusercontent.com/1994311/38771430-5d357cc6-3ff1-11e8-9394-836273fde688.png)

Currently the label is "Personally Identifying" and the description is "Does this field collect personally identifying information, as defined in the EU in the GPDR standard?", which needs work.

**Comment by thequicksilver** [comment]
Perhaps provide a link in the descriptive text to the actual standard, or to Caldera documentation that gives an overview? Could do something like "How can I tell?" or "What is personally identifying?" Most folks probably don't know that IPs are considered PII in the EU, for instance.

**Comment by mywebink** [comment]
Maybe something like:

"Personally Identifying Information"

"Does this field collect information that could be considered personally identifying as defined by the [General Data Protection Rules](https://gdpr-info.eu/) within the European Union?"

**Comment by johnalarcon** [comment]
I'd try to keep the texts as slim as possible...

For a label, `Personally Identifying Information (PII)`.

For description, `This field contains PII. What is PII?` where the second sentence is linked (or tooltip'd) with a quick reference.

**Comment by Shelob9** [comment]
Thanks for the feedback everyone. Here is what it looks like after a2d9826

![screen shot 2018-04-17 at 2 42 00 pm](https://user-images.githubusercontent.com/1994311/38889736-8f3e2e8a-424d-11e8-9454-7dd2cf067342.png)

Close via 33cedf8

Docs: https://calderaforms.com/doc/gdpr-api/#pii

**Comment by thequicksilver** [comment]
Awesome! I think that'll be great.
