### ISSUE TITLE
Provide data to GDPR export/delete/annoymize requests from core

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2429]
Filters: 
* `wp_privacy_personal_data_exporters`

https://danieliser.com/practical-guide-to-gdpr-compliance-for-wordpress-plugin-and-theme-developers/

- [x] Data Exporter: https://gist.github.com/danieliser/5ae69ed33491a43ddd62fe05efb6d4c0#file-plugin-privacy-user-data-exporter-php
- [x] Eraser : https://gist.github.com/danieliser/b6d2a57b795349af4e5127d9081dc1c2#file-plugin-privacy-user-data-eraser-php

**Comment by nicomollet** [comment]
Very much appreciated. Gravity Forms, Ninja Forms and Formidable Forms don't seem to care about this tool.

**Comment by Shelob9** [comment]
Close via 656bdd8
