### ISSUE TITLE
 Permanent delete of trashed entries in the entry pages

### ISSUE THREAD

**Issue by jpgoem** [CalderaWP/Caldera-Forms#2435]
## Do You Need Immediate Help?
No.

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
YES.  I would like to re-open the issue opened by mdorchain  on Dec 15, 2017 (issue #2153 :
 Permanent delete of trashed entries in the entry pages.  ) and have it considered as a Feature Request.
Here is a copy/paste of his description :  
When browsing entry admin pages, there's no option to delete permanently the trash or to restore the entries. The only bulk options available are "Export entries" and "Move to Trash".
Shouldn't be the "Move to Trash" option removed and, "Restore" and "Delete Permanently" added for trashed elements ? This bulk options are already working perfectly when the entries are accessed from the form, but not from the entry pages.

**Comment by nerdworker** [comment]
Is there really no option to permanently delete these trashed messages? I can't find one. This seems like an obvious requirement.

**Comment by New0** [comment]
Thanks for opening the feature request @jpgoem and for detailing the solution @nerdworker 

The Submenu entry viewer is meant to display entries to non-admin users, the delete permanently option is only accessible via the menu reserved for admins.
