### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined 

### ISSUE THREAD

**Issue by naugustijr** [CalderaWP/Caldera-Forms#2448]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Short Debug Information
WordPress Version: 4.9.5PHP Version: 5.6.35MySQL Version: 5.6.36Caldera Forms Version: 1.6.0WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
There seems to be a conflict with the Pods plugin (I have version 2.7.1). When I deactivate Pods, the javascript error disappears. I also have Caldera Easy Pods installed (version 1.1.8), Caldera Forms version 1.6.0.

## What Is The Unexpected Behaviour?
I filled out the form and clicked Submit. Nothing happened.

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP errors or notices related to this.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
The error below is from the Chrome console. The error comes up when entering a text in one of the form fields. 

Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.error (ajax-core.min.js?ver=1.6.0:1)
    at Object.request_error (jquery-baldrick.min.js?ver=1.6.0:1)
    at c (jquery-baldrick.min.js?ver=1.6.0:1)
    at Object.error (jquery-baldrick.min.js?ver=1.6.0:1)
    at i (jquery.js:2)
    at Object.fireWith [as rejectWith] (jquery.js:2)
    at y (jquery.js:4)
    at Object.abort (jquery.js:4)
    at Object.request (jquery-baldrick.min.js?ver=1.6.0:1)
    at c (jquery-baldrick.min.js?ver=1.6.0:1)

**Comment by naugustijr** [comment]
I deactivated Caldera Easy Pods (installed version 1.1.8) and the error was gone, but I lost the functionality of the page!

**Comment by naugustijr** [comment]
Error on Firefox:

TypeError: b.jqxhr.responseJSON is undefined[Learn More]
ajax-core.min.js:1:2228
error
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/ajax-core.min.js:1:2228
request_error
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:1692
c
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:2048
error
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:9877
i
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:27444
fireWith
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:28213
y
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:4:22744
abort
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:4:20559
request
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:1372
c
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:2048
a.fn.baldrick/</<
http://parisnaamerica.org/wp-content/plugins/caldera-forms/assets/build/js/jquery-baldrick.min.js:1:10191
dispatch
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:12392
add/r.handle
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:9156
trigger
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:11571
a.event.trigger
http://parisnaamerica.org/wp-includes/js/jquery/jquery-migrate.min.js:2:8273
trigger/<
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:18983
each
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:2879
each
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:2:844
trigger
http://parisnaamerica.org/wp-includes/js/jquery/jquery.js:3:18962
init_search<
http://parisnaamerica.org/search/:461:8

**Comment by naugustijr** [comment]
https://github.com/CalderaWP/Caldera-Forms/issues/1157

**Comment by naugustijr** [comment]
https://github.com/CalderaWP/Caldera-Forms/issues/2369

**Comment by naugustijr** [comment]
I try https://wordpress.org/support/topic/issue-processing-caldera-forms-possible-js-minification-issue/ but it did not work.

**Comment by naugustijr** [comment]
I have update Caldera Forms to version 1.6.1 and the error persists.

**Comment by 0xLBF** [comment]
I had similar JavaScript errors, but in the Pods Template editor, not when submitting forms. So I'm not sure if the referenced patch fixes this.

**Comment by naugustijr** [comment]
I'll try and return the result

**Comment by creabrain** [comment]
Is WP_DEBUG true? Cause when you get ajax reponse of submitted form and there are notices or warnings in response the json data is not parsable and so data object will be undefined.

**Comment by Shelob9** [comment]
I am going to close this in favor of #2820 which will address the root issue.

**Comment by Shelob9** [comment]
Will be fixed via #2822
