### ISSUE TITLE
Caldera Compatibility issues with WooCommerce 3.3.5

### ISSUE THREAD

**Issue by steveconnerton** [CalderaWP/Caldera-Forms#2453]
Caldera has compatibility issues with WooCommerce v3.3.5. I was getting the Submission Rejected; invalid Token error, so immediately thought it was my caching, but was able to verify that it wasn't. So I dug deeper and was able to find this:

Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php on line 284

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api/class-wp-rest-server.php on line 1248

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api.php on line 544

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api.php on line 545

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api.php on line 546

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php:284) in /var/www/html/wp-includes/rest-api.php on line 547
{"nonce":"88f9edba06"}

Hope this is helpful. I am going to reach out to Woo as well.

Thanks,
Steve 

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
I'm going to close this as this is related to a feature -- token check -- that is no longer in use.
