### ISSUE TITLE
Add File doesn't work with iphone 

### ISSUE THREAD

**Issue by SmartAutoRepairs** [CalderaWP/Caldera-Forms#2468]
Hi My website is www.kitchencabinetspraying.co.uk  we've just discovered that the form does not submit on iphone or mac when you have the add file field on the form. If you remove this field it works fine.

hort Debug Information
WordPress Version: 4.9.5PHP Version: 5.6.22MySQL Version: 5.7.16Caldera Forms Version: 1.6.1.1WP_DEBUG:
Full Debug Information

Warning: file_exists(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP? in /var/sites/k/kitchencabinetspraying.co.uk/public_html/wp-content/plugins/caldera-forms/classes/support.php on line 172

Warning: is_writable(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP? in /var/sites/k/kitchencabinetspraying.co.uk/public_html/wp-content/plugins/caldera-forms/classes/support.php on line 173
WordPress Version: 4.9.5

PHP Version: 5.6.22

MySQL Version: 5.7.16

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Session Save Path: tcp://10.168.1.55:11211?persistent=0&weight=1&timeout=5&retry_interval=15

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 14400

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: Yes
Memcached: Yes
Redis: No
WPDB Prefix: clij_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: Avada: 5.5

Plugins:

Akismet Anti-Spam: 4.0.3 Not Active
Caldera Forms: 1.6.1.1 Active
Defender Pro: 1.8 Active
EWWW Image Optimizer: 4.1.3 Active
Fusion Builder: 1.5 Active
Fusion Builder Before/After Element: 1.4.0 Active
Fusion Core: 3.5 Active
Hello Dolly: 1.6 Not Active
Hummingbird Pro: 1.8.2 Active
Limit Login Attempts: 1.7.1 Active
Snapshot Pro: 3.1.7 Active
WordPress Importer: 0.6.4 Active
WP Fastest Cache: 0.8.7.9 Active
WPMU DEV Dashboard: 4.5.2 Active
WP Smush: 2.7.8 Not Active
WP Smush Pro: 2.7.8 Active
Yoast SEO: Local: 7.4 Active
Yoast SEO Premium: 7.3 Active

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
