### ISSUE TITLE
Caldera dosent send emails to outlook.

### ISSUE THREAD

**Issue by IdanYekutiel** [CalderaWP/Caldera-Forms#2473]
When i try to send emails to outlook ( office 365 ) it dosent work. It works with email and other but not with outlook. Can someone help me?

**Comment by martin-neumann-at** [comment]
You does not give much infos, but I would check in your case whether this is not a blacklisting problem. If you send the same address from the email client does it work? If you send an email from another Wordpress plugin to that address does it work? Do you use wordpress to submit the caldera form or another emailing option?

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
