### ISSUE TITLE
Anti Spam Settings not saved

### ISSUE THREAD

**Issue by Anchaal05** [CalderaWP/Caldera-Forms#2489]
Deactivate “anti-spam honeypot” in the Anti-Spam settings of the form, click on “Save Form” and then edit this form again later, the settings are not saved, the “anti-spam honeypot” is activated again. The same applies to the honeypot Settings in the “Form Settings”.
The settings are only saved when I deactivate or activate BOTH settings and then click on “Save Form”.

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by New0** [comment]
@Shelob9 I could reproduce this behavior. The option for the honeypot under the anti-spam tab is not "linked"(immediate state) to the option for the honeypot under the Form settings tab.
That means that when the option is saved in one place via ajax, the other is not refreshed with the new state. That leads to save again the opposite state if we edit the form again before refreshing the page.

I propose two solutions 
1) we bound the two options kind of how I bounded the emails settings to the pro enhanced delivery state
2) we remove the option from Form settings tab as Anti spam has its own tab now

**Comment by Shelob9** [comment]
I like option 2. Pretty sure that was my intent.

**Comment by Shelob9** [comment]
Fixed in #2577 2a151be
