### ISSUE TITLE
Can't Add New Field 1.6.2

### ISSUE THREAD

**Issue by sfraise** [CalderaWP/Caldera-Forms#2494]
## Do You Need Immediate Help?
* No, we rolled back to V6.1.1

## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* Caldera V6.2, WP V4.9.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Tried on 2 completely different sites on 2 totally different servers and 2 totally different themes, same issue.

## What Is The Unexpected Behaviour?
* Try to add a new field, all you get is a blank field.  The modal window does not appear to select field type and no settings options on the right, essentially you can't add anything at all.

## What PHP Errors Have You Logged While Reproducing This Bug?
* No PHP errors and no Javascript errors in the console.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* No errors at all in the console

**Comment by Shelob9** [comment]
Thanks for reporting.

The root bug is that when new fields are added, the element with the field editor is not given an ID attribute, so it can't be unhidden when selecting the field.

**Comment by Shelob9** [comment]
Pretty sure this was broken in 71fc30b0fc3b95ccaba3ee8851b043cce56c95b3

**Comment by Shelob9** [comment]
should be fixed via 197f31e

**Comment by Shelob9** [comment]
close via  251716f
