### ISSUE TITLE
Date Picker locale folder is missing in the new update 1.6.3

### ISSUE THREAD

**Issue by Anchaal05** [CalderaWP/Caldera-Forms#2513]
In the upgrade to version [1.6.3,] the complete translation of the bootstrap date picker is missing! The folder /plugins/caldera-forms/fields/date_picker/ is missing the complete /js/ folder (containing the all i18n files). Now the date picker is only in English.  
https://wordpress.org/support/topic/date-picker-locale-folder-is-missing/

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by neovinter** [comment]
I have the same issue with 1.6.3
Clean installation WP 4.9.6, PHP 7.2.4, MySQL 5.7.21

**Comment by StonehengeCreations** [comment]
Jeperzzzzz 13 days ago I made a comment on WordPress support forum WITH the solution included: Add the missing js folder. That solves the problem. No, the support thread is marked as "solved", while it is not and the problem still persists! Creating this Github  item took more time than adding the missing folder and files and putting it up on the WP repository.

**Comment by StonehengeCreations** [comment]
VERY EASY to solve... I've uploaded my js folder from the previous release. 
Download it from https://www.stonehengecreations.nl/js.zip. Unzip it and upload it through FTP to /wp-content/plugins/caldera-forms/fields/date_picker/. 
That's all, folks :-)

**Comment by Shelob9** [comment]
This got lost in b317fced75128ba5af3df1f2d5e34c574652e4c1

**Comment by Shelob9** [comment]
Close via 
5a4c828

![screen shot 2018-05-30 at 1 44 17 pm](https://user-images.githubusercontent.com/1994311/40737758-afb2ffc2-640f-11e8-8785-c7f4466ffd24.png)
