### ISSUE TITLE
Woocommerce add new order bug

### ISSUE THREAD

**Issue by ck-iridium** [CalderaWP/Caldera-Forms#2517]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
**WordPress Version: 4.9.6PHP Version: 7.1.17MySQL Version: 10.1.31Caldera Forms Version: 1.6.3WP_DEBUG:** 
## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
**Yes, the problem was when CalderaF is active**
## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
**If Caldera Forms is active, i cant create manually an ORDER into Woocommerce. Some is bugged, cant sellect a customer and cant add new products**
## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by ck-iridium** [comment]
If Caldera Forms is active, i cant create manually an ORDER into Woocommerce. Some is bugged, cant sellect a customer and cant add new products

**Comment by Shelob9** [comment]
This will be resolved via #2527 in version 1.7. See this comment for an immediate workaround:
https://github.com/CalderaWP/Caldera-Forms/issues/2527#issuecomment-390653283

**Comment by Shelob9** [comment]
Fixed in #2527 see: https://github.com/CalderaWP/Caldera-Forms/issues/2527#issuecomment-391488156
