### ISSUE TITLE
Save FORM not working

### ISSUE THREAD

**Issue by jpvoigt** [CalderaWP/Caldera-Forms#2519]
WordPress Version: 4.9.6 PHP Version: 7.1.17 MySQL Version: 5.6.39 Caldera Forms Version: 1.6.3 WP_DEBUG: true

When I press the save button there is a little indicator showing up, but no success message is displayed and no changes are saved.
*mydomain.example* *myip.example* - - [18/May/2018:15:19:30 +0200] "POST /wp-admin/admin.php?page=caldera-forms HTTP/1.1" 503 299 "https://*mydomain.example*/wp-admin/admin.php?edit=CF5aeaae4f27d09&page=caldera-forms" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
There are no php errors logged.

**Comment by jpvoigt** [comment]
Disabling all other plugins does not make any difference. Once I was able to save the form, but it seems not possible to make any important changes now.
Maybe this is related to issue #1821 ?

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
