### ISSUE TITLE
Don't ask for slug or name for certain field types

### ISSUE THREAD

**Issue by iamntz** [CalderaWP/Caldera-Forms#2524]
Some fields asks for an slug and name even they aren't useful in that context: separator and HTML content being the culprits.

I understand that in some cases the slug can be useful (e.g. to show/hide based on a condition), but i guess these values can be pre-populated with an `uniqid()` or something similar.

**Comment by Shelob9** [comment]
Close via 6b6ad4a  Thanks @iamntz
