### ISSUE TITLE
Remove form inserter button on all WooCommerce related pages.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2527]
#2239
#2517
#2239
#2526

**Comment by Shelob9** [comment]
Note to those looking for immediate fix:

This is a conflict between WooCommerce's JavaScript and the JavaScript our form insert button. I'm going to prevent that button from loading on WooCommerce screens -- you can still cut and paste the shortcode in.

That's basically what is documented here: https://calderaforms.com/doc/remove-caldera-forms-shortcode-button-post-editor/ In Caldera Forms 1.6.3 or lower, the solution is to do what that doc says.

**Comment by Shelob9** [comment]
Close via 
c4362f5 and 
2815191

**Comment by marlonbrum** [comment]
The is_woocommerce_page() function is returning true even on non woocommerce pages, like the Page editor.  this is making the Caldera forms insert button not appearing.
