### ISSUE TITLE
form submission is completed and with out click the validation link

### ISSUE THREAD

**Issue by arisss1** [CalderaWP/Caldera-Forms#2543]
I have wordpress 4.9.6 and caldera version 1.6.3 , my php is 7

i have a problem with caldera verify,
 if someone doesn't click the validation link, submission email is completed again

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by arisss1** [comment]
thank you about your quick replay, could you help me in caldera verify plugin, 

where can i change-rename the final messege alert of the verify link "Form has been successfully submitted. Thank you."

thanks a lot
