### ISSUE TITLE
Uncaught ReferenceError: ceil is not defined

### ISSUE THREAD

**Issue by SilvorMike** [CalderaWP/Caldera-Forms#2555]
Hiya

I have found that a manual calculation of
`ceil(%field_1%/%field_2%)`

Does not work, with error
> Uncaught ReferenceError: ceil is not defined
    at do_calc_fld_3399490_1 (?page_id=1572&preview=1&cf_preview=CF5b07c6fa6d387:1020)
    at g (VM8807 caldera-forms-front.min.js:1)
    at VM8807 caldera-forms-front.min.js:1
    at g (VM8807 caldera-forms-front.min.js:1)

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.6PHP Version: 7.0.30MySQL Version: 10.1.33Caldera Forms Version: 1.7.0WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Calculation using ceil (Math.ceil) doesn't appear to work like other Math functions

## What PHP Errors Have You Logged While Reproducing This Bug?
N/A

## What JavaScript Errors Have You Seen While Reproducing This Bug?
> Uncaught ReferenceError: ceil is not defined
    at do_calc_fld_3399490_1 (?page_id=1572&preview=1&cf_preview=CF5b07c6fa6d387:1020)
    at g (VM8807 caldera-forms-front.min.js:1)
    at VM8807 caldera-forms-front.min.js:1
    at g (VM8807 caldera-forms-front.min.js:1)

**Comment by SilvorMike** [comment]
Hello, is it possible that I can fix this as I can't figure out why it isn't working properly?

**Comment by SilvorMike** [comment]
Updated with support/bug template

**Comment by SilvorMike** [comment]
To confirm, doesn't work in 1.7.2 either

**Comment by Shelob9** [comment]
The issue here is that the function name is spelled wrong in the list of functions, which we use to prepare the calculation -- ceil() and tan() are not  functions Math.ceil() and Math.tan() are.

Quick fix, modify this line and change the spelling. Will fix it for CF 1.8.0.

https://github.com/CalderaWP/Caldera-Forms/blob/2cdb95b7f258b6567f0b570da526ab4bd6d58ec3/classes/field/util.php#L223

**Comment by Shelob9** [comment]
closee via fea9bd7
