### ISSUE TITLE
Receiving Unfilled Messages from Caldera Forms Notification

### ISSUE THREAD

**Issue by camanicnack** [CalderaWP/Caldera-Forms#2557]
My company is currently using Caldera Forms for our contact page. Currently we have the form hidden until they check the “Request More Information” checkbox. Once that is check our contact form pops up.
As of late, we have been receiving blank email notification messages. No name, phone, e-mail, address, city, zip, description or topics where chosen. Each text box shows up blank.
Example –

from , has requested more information about your company.
Name:
Phone:
E-Mail:
Address:
City: State: Zip Code:
Topics Selected:
Message:

We have put the required tag on most of the items such as name, phone, email, city, zip and topics so no matter what, the user has to enter the information in within the textboxes. Tried going over our conditions. We even tried to duplicate the issue by entering spaces and etc, but we cannot duplicate this issue and do not know why we are receiving these blank email notifications. When we tried to test it out, everything works fine and emails are being sent. We even tried every scenario to try to crash it, but it still seems to work properly. We even received some emails from clients, but still not sure why blank emails are popping up.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
