### ISSUE TITLE
Bugfix: filter caldera_forms_update_field inside a wrong if statement

### ISSUE THREAD

**Issue by leogermani** [CalderaWP/Caldera-Forms#2559]
Hi,

Im not sure if this is the intention, but I believe not. In the core.php class, the `caldera_forms_update_field` filter is beeing called inside an `if` statement checking the existence of another filter. I believe this is a mistake. Here is the snippet: 

```

		if (has_filter('caldera_forms_save_field')) {
			$new_data = apply_filters('caldera_forms_update_field', $new_data, $field, $form);
		}

		if (has_filter('caldera_forms_save_field_' . $field['type'])) {
			$new_data = apply_filters('caldera_forms_update_field_' . $field['type'], $new_data, $field, $form);
		}
```

I am preparing a simple pull request to fix this, if it is the case to be fixed.

Thanks

**Comment by Shelob9** [comment]
Good catch. Thanks for the fix!

**Comment by Shelob9** [comment]
close via 37648b0
