### ISSUE TITLE
User reporting fatal error after 1.7 update 

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#2572]
see https://prnt.sc/jpuwlh

ticket ref https://secure.helpscout.net/conversation/593221209/10125?folderId=832038

**Comment by patthai74** [comment]
Thank you. I am that user ;-) This error happens with the Entrada theme.

I just did the upgrade for a site with the Avada theme and got the following error: http://prntscr.com/jqafgu

**Comment by Shelob9** [comment]
Closing as duplicate of #2574
