### ISSUE TITLE
Request: Change inline javascript to allow jquery inclusion in footer

### ISSUE THREAD

**Issue by eli-g** [CalderaWP/Caldera-Forms#259]
In your fields templates you often have inline javascript such as the button field:

jQuery( function($){

		$(document).on('click dblclick', '#<?php echo $field_id; ?>', function( e ){
			$('#<?php echo $field_id; ?>_btn').val( e.type ).trigger('change');
		});

	});
To maximise our page speed insights score we need to load our javascript in the footer of our website, which makes this code break, as jQuery is not loaded yet when this attempts to execute. To fix this I change the code to:

window.onload = function(){

		$(document).on('click dblclick', '#<?php echo $field_id; ?>', function( e ){
			$('#<?php echo $field_id; ?>_btn').val( e.type ).trigger('change');
		});

	}
Is there a chance this change (or something similar) could be incorporated into your plugin please?

Thanks,
Ellie

**Comment by Desertsnowman** [comment]
The script is supposed to be captured then outputted at the end. but I think this is even missing the call.

I'll add your suggestion in the next update (which is very soon)

**Comment by Desertsnowman** [comment]
Matter of interest, assigning to the Global Event Handler for load is not a good idea as it redefines it. any other call that was assigned before wont be fired.
it would be better to place an event listener instead.
```javascript
window.addEventListener("load", function(){
	// your code here
});
```

**Comment by alexandergryth** [comment]
Any news on this issue? Seems like it's still necessary to load jQuery in the header instead of footer to avoid errors.

**Comment by eli-g** [comment]
I've just done a pull request which includes the fixes I have been applying to my websites when Caldera Forms is updated.
