### ISSUE TITLE
Form settings changes not saved

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2595]
Because of #2581

**Comment by Shelob9** [comment]
https://github.com/CalderaWP/Caldera-Forms/commit/43c5d0955192bd03236525c0c411b5b53bf32880#diff-9f9968437cfc01236a148f223bb2d071R1567

**Comment by Shelob9** [comment]
Close via eb15935

**Comment by randyvogl** [comment]
I just update to 1.7.1.2 and I am still encountering the same bug. Error I get on submission is Fatal error: Class 'Caldera_Forms_API_Privacy' not found in ****/public_html/wp-content/plugins/caldera-forms/classes/admin.php on line 1567

**Comment by meganrofl** [comment]
I've updated to version 1.7.1.2 after reading about this major bug but cannot successfully save any changes using "Save Form".

**Comment by caratolo** [comment]
Same problem here. Using version 1.7.1.2.

**Comment by randyvogl** [comment]
As it appears as though other are having this same issue I am @Shelob9 I am using PHP 5.6 Caldera 1.7.1.2 I also received the error with 1.7.1.1 I believe. I can reproduce the error by going into any one of my existing forms, making a change and clicking Save Form. If I record the network traffic during the Save operation I get a response from {URL}/wp-admin/admin.php?page=caldera-forms with a response Fatal error: Class 'Caldera_Forms_API_Privacy' not found in ***/public_html/wp-content/plugins/caldera-forms/classes/admin.php on line 1567 please let me know if I can help provide any additional information on this issue.

**Comment by mforti** [comment]
Same problem here using version 1.7.1.2. I cannot save any changes in my forms in button "Save Form".

**Comment by Shelob9** [comment]
This is fixed in 1.7.1.3+
