### ISSUE TITLE
Privacy Setting and Consent Fields not work

### ISSUE THREAD

**Issue by worksfather** [CalderaWP/Caldera-Forms#2597]
WordPress Version: 4.9.6
PHP Version: 7.2.6
MySQL Version: 10.1.33
Caldera Forms Version: 1.7.1.2

I just installed Caldera Form 1.7.1.2 update. And after installation, I noticed that "Consent Field" disappeared from my form on the site. When I checked on the dashboard, I noticed that the row is still there but without the field. While it worked well before the update. 

Also, the Private setting tab does not work. Already, it didn't work in the 1.7.0 version I had installed.

**Comment by Shelob9** [comment]
Thanks for reporting. This was an issue with how 1.7.1/1.7.1.2 was pushed to WP.org 

1.7.1.3 includes the missing files
