### ISSUE TITLE
More useful message in privacy screen than "No route was found matching the URL and request method"

### ISSUE THREAD

**Issue by andersgj54** [CalderaWP/Caldera-Forms#2598]
WordPress Version: 4.9.6PHP Version: 7.0.30MySQL Version: 5.5.60Caldera Forms Version: 1.7.1.3WP_DEBUG:

I was used to seeing PII options on forms and noticed that this is no longer the case so I assume that the Privacy Settings option has to be used to set them.

When I try to set the privacy settings for any form using the privacy settings option a red line with
"No route was found matching the URL and request method" is displayed.

I am therefore unable to set the privacy options for forms.

**Comment by Shelob9** [comment]
This generally happens when you do not have pretty permalinks enabled -- IE ?p=21 instead of /about

I need to make this message more useful. It's currently showing the actual server error, which isn't useful.

**Comment by andersgj54** [comment]
I have changed the permalinks setting to /%postname%/ on my website as suggested and this enabled me to use the Privacy settings page

**Comment by Shelob9** [comment]
Close via 
db38953
