### ISSUE TITLE
Are not the notification mail

### ISSUE THREAD

**Issue by Anthonyy75** [CalderaWP/Caldera-Forms#2606]
Hello,

I wish you reassembled this problem.

After the update I found Caldera forms, but on 4 forms I receive the notification only on 2 forms. The notification email (gmail) are neither in the inbox, nor in spam) what to do?

Looking forward to your return,

Regards,

**Comment by Alexchef** [comment]
Hi,
i have the same random problem too. I use Godaddy as mailer sender, but during my test , where i send email to my gmail or yahoo email, some email arrive and some no.
But in the db all messages are coorected stored :( 
Somebody suggested me to try with mailgun....
Thanks

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
