### ISSUE TITLE
uploaded and activated plugin. Nothing. And cannot login to the caldera account doesnt recognize my email, but sent me everything to it, repeated password recover says user doesnt exist

### ISSUE THREAD

**Issue by tjshepherd2** [CalderaWP/Caldera-Forms#2607]
## Do You Need Immediate Help?
Yes, and since I cannot login, because you fail to recognize the email to which you sent my files... I cannot create a support ticket about inability to login... [great process] * If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
NO 

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
NO version since it isn't working to install. and can't get to account to find out whatever the issue may be since the get started guide was faulty. 
## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
I am not doing that. If that is needed to work, refund me.

## What Is The Unexpected Behaviour?
It is unexpected to have nothing work and not to be able to login to the caldera account and be told my account username email doesn't exist, despite all of the password recoveries being sent to it, and the order confirm came to this email. * Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I replied to what I believe was your support ticket. I am closing this out as it is a support request.
