### ISSUE TITLE
CF Pro Api keys do not appear to save.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2608]

**Comment by Shelob9** [comment]
This is the workaround to save CF Pro API keys until a fix for this bug is released:

1) Enter the keys.
2) Click save.
3) Refresh the page.

**Comment by maritzar** [comment]
Enter the Keys, saving and refreshing is not working for us

**Comment by Shelob9** [comment]
Close via 147ec93
