### ISSUE TITLE
Forms disappear

### ISSUE THREAD

**Issue by linkolus** [CalderaWP/Caldera-Forms#2610]
Hello,

I allow myself to contact you because I have a problem with your tool. Indeed, the forms I created no longer appear. Even when I create a new form, it is not displayed. I always have the phrase: "You have no form".

Can you help me ?

Thank you in advance for your response.

**Comment by diegojaimo** [comment]
Same problem here

**Comment by linkolus** [comment]
Update :
We tried to replace the existing folder with a one-week archive of the plugin folder. Without success, it still does not work ... Thank you for your return

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
