### ISSUE TITLE
Caldera Forms Gutenberg Block using removed InspectorControls 

### ISSUE THREAD

**Issue by telizarose** [CalderaWP/Caldera-Forms#2618]
## Do You Need Immediate Help?
* Nope. This is an experiment for a blog post.

## Is This A Feature Request?
* No, but if you make it work, I will feature it in my next post!

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*Caldera: 1.7.1.4 | WordPress: 4.9.6 Gutenberg: 3.0.1 PHP: ?? Honestly I don't know. 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
* The block does not appear on the front end. It seems to work just fine on the back end. 

## What PHP Errors Have You Logged While Reproducing This Bug?
I don't know.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
I don't see any.

**Comment by Shelob9** [comment]
We are using wp.blocks.InspectorControls which was deprecated and is removed from Gutenberg in 3.1. Should be using wp.editor.InspectorControls instead.

**Comment by Shelob9** [comment]
Close via 
bcd0e94
