### ISSUE TITLE
Form not work in safari

### ISSUE THREAD

**Issue by GH974** [CalderaWP/Caldera-Forms#2624]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
caldera => 1.7.1.4
wordpress => 4.9.6

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes

## What Is The Unexpected Behaviour?
I added caldera redirection after submit form, it's work in google chrome or in safari v11.1. i get a error

## What JavaScript Errors Have You Seen While Reproducing This Bug?
![capture d ecran 2018-06-19 a 11 51 23](https://user-images.githubusercontent.com/11731125/41584296-fe03faf2-73b7-11e8-88ba-cb61331c681d.png)

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
