### ISSUE TITLE
Syntax errors from WPE code sniffs

### ISSUE THREAD

**Issue by colorful-tones** [CalderaWP/Caldera-Forms#2625]
Caldera Forms Version: 1.7.1.4
PHP: 7.1.6

Receiving the following errors in CircleCI when trying to deploy to WPEngine:

```
remote: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in - on line 139        
remote:   - warning:(B syntax Error Found in wp-content/plugins/caldera-forms/vendor/calderawp/caldera-forms-query/Tests/Traits/HasFactories.php ... 

remote: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in - on line 43        
remote:   - warning:(B syntax Error Found in wp-content/plugins/caldera-forms/vendor/calderawp/caldera-forms-query/src/CanCollectResults.php ...   
```

I'm rolling back to 1.6.3 for now.

**Comment by Shelob9** [comment]
@colorful-tones We do not follow WordPress code style. I am working on adding a linter here: #2362 If you'd like to help finish that, would be great.

That's actually coming from the tests of the Caldera Forms Query tool - https://github.com/CalderaWP/caldera-forms-query Which does have a linter which does not follow WordPress code style: https://github.com/CalderaWP/caldera-forms-query/blob/master/phpcs.xml.dist

**Comment by colorful-tones** [comment]
@Shelob9 totally makes sense. Thanks for clarifying. 👍🏻
