### ISSUE TITLE
Can't skip pages in form without filling them out (no obligatory fields active)

### ISSUE THREAD

**Issue by bannann** [CalderaWP/Caldera-Forms#2628]
WordPress Version: 4.9.6 PHP Version: 7.1.17 MySQL Version: 5.6.40 Caldera Forms Version: 1.5.9.1WP_DEBUG:

I have created a multi-page form and implemented it on our webpage. Most of our costumers like to skip through the pages before they start filling them out. It is impossible to skip the second page so most costumers just leave. I have already checked all the fields and none is set to "obligatory".

Are some of the fields broken?How can I fix this problem?

https://www.stylique.de/design-service-anfrage/

**Comment by Shelob9** [comment]
https://github.com/CalderaWP/Caldera-Forms/issues/2634#issuecomment-400124172

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms.

I am trying to reproduce this issue with just the default WordPress theme and just Caldera Forms and was unable to reproduce the problem. http://dev-caldera-testing.pantheonsite.io/multi-page-advanced-file-field-on-page-two/ I can not. This likely means it is a site specific issue **or I am missing a key instruction on how to reproduce this issue**

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by Shelob9** [comment]
Possibly it is this issue: https://github.com/CalderaWP/Caldera-Forms/issues/2644
