### ISSUE TITLE
Caldera Forms Not Attaching PDF or Attachments

### ISSUE THREAD

**Issue by reginaldparks** [CalderaWP/Caldera-Forms#2637]
**Site in question:** https://realitymarketinggroup.com/clients/vycelogistics/careers/

**## Do You Need Immediate Help?**
I would ideally like to solve this issue quickly as I have other sites having the issue as well

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
4.9.6

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
We have not tried to deactivate all plugins, though there seemingly is not a single plugin that is causing this issue.

## What Is The Unexpected Behaviour?
Entire submission is not being sent when there is an attachment

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
