### ISSUE TITLE
Custom validation error message filter doesn't work for checkboxes

### ISSUE THREAD

**Issue by amsgator** [CalderaWP/Caldera-Forms#2649]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.6
PHP Version: 7.2.6
MySQL Version: 10.1.31
Caldera Forms Version: 1.7.1.4
WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?

Using this filter: https://gist.github.com/Shelob9/869d0ebb94b017ca690ed70c5aa7431a

Checkbox fields are not accepting `data-parsley-error-message` as an attribute in the filter. Even with the filter it's still rendering `<span class="parsley-required">This value is required.</span>`.

## What PHP Errors Have You Logged While Reproducing This Bug?

None

## What JavaScript Errors Have You Seen While Reproducing This Bug?

None

**Comment by Shelob9** [comment]
Correct, the checkbox fields do not use that filter. https://github.com/CalderaWP/Caldera-Forms/blob/master/fields/radio/field.php

**Comment by amsgator** [comment]
I'm guessing the correct link I should be looking at is https://github.com/CalderaWP/Caldera-Forms/blob/master/fields/checkbox/field.php

Do you have a gist somewhere on how to change the validation error message for checkboxes?
