### ISSUE TITLE
Error submitting form

### ISSUE THREAD

**Issue by ypantig** [CalderaWP/Caldera-Forms#2650]
## Do You Need Immediate Help?
No, but it would be great if I can get an answer soon.

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms >= 1.5.2.1
WordPress >= 4.9.6
PHP >= 5.6

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The form is not submitting when using Safari. Firefox and Chrome are both OK.

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
- TypeError: undefined is not an object (evaluating 'b.jqxhr.responseJSON.data') (http://ace.test/wp-content/plugins/caldera-forms/assets/build/js/ajax-core.min.js?ver=1.5.2.1)
- Failed to load resource: The network connection was lost. (http://ace.test/cf-api/CF5955f653710a5)

==

Note: This is happening both on my local install of the site, as well as in our live site. Please also note that I have tried disabling all plugins and moving back to Twenty Twelve Theme, and still the same result.

Here is a link to the form on the live site: http://co-op.bc.ca/post-a-co-op-job/ 
*NOTE: Please note that submissions on this form goes to a lot of different people, not just the admin.*

<img width="757" alt="screen shot 2018-06-28 at 6 43 39 pm" src="https://user-images.githubusercontent.com/8999926/42068905-79f1e21c-7b03-11e8-9cd6-06309c5eec29.png">

**Comment by Shelob9** [comment]
@ypantig Thanks for using Caldera Forms.

This is not a support channel and this is a site-specific issue, so I am closing.

This sounds like a time out or error server-side. I would recommend updating to the last version and checking for PHP errors during submission
