### ISSUE TITLE
Losing validation of Phone Better field in conditional logic 

### ISSUE THREAD

**Issue by salihkulangara** [CalderaWP/Caldera-Forms#2652]
When we use the Phone Number(Better) field in a conditional logic, first time when the field show up it will have all the validation and country flags and all, but if we switch between the conditions, lose the validations and county flags, to better explain please see the attached gif.

![caldera-issue](https://user-images.githubusercontent.com/6852780/42073102-1d314764-7b82-11e8-9cb4-377d75bcde81.gif)

The Phone Number(Basic) also had the issue - losing the field masking and validations, still version Version 1.7.1.4, but in Version 1.7.2, it seems fixed, For Phone Number(Better) field issue still exists.

Wordpress:  4.9.6
Caldera Forms: 1.7.2
PHP: 5.6.31

**Comment by Shelob9** [comment]
@salihkulangara Thanks for reporting this. 

Notes:
- This likely has the same solution as  #2612
- The handler function for phone_better fields is here - https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/field-config.js#L383
- That file is contacted into caldera-forms-front.min.js

**Comment by Shelob9** [comment]
New test 2652 CF Field: Phone Better created@1.7.3 proves this is a real issue.

The init function *is* running after the field is unhidden, but it still doesn't reload the functionality of this field type. Confused now, I will look further.

**Comment by mecachisenros** [comment]
@Shelob9 this should be fixed via #2711, I've added a brief explanation in the PR.

### Demo
![phone_init_validation](https://user-images.githubusercontent.com/3038096/44633855-73e78800-a988-11e8-98dc-17cd9c63358c.gif)

**Comment by Shelob9** [comment]
Fixed via #2711

**Comment by salihkulangara** [comment]
Great
