### ISSUE TITLE
Content of html forms and other missing parts in Translation plugin

### ISSUE THREAD

**Issue by davidecornacchini** [CalderaWP/Caldera-Forms#2655]
Hello
i installed the translation plugin and updated it.

The placeholder of a dropdown select module does not appear in the english language, so i see it in the original language because it cannot get translated

The content of html sections also does not appear in the plugin, so i cannot translate it. I used this field to add a little Title and Subtitle before the following field, but i cannot translate it

Can you help about this?

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by davidecornacchini** [comment]
What? your multilingual plugin has some missing parts and this is clearly explained in my message

if you want users to pay for having it works just say it clearly, without going too much around it
