### ISSUE TITLE
Hello, I have been having problems with the Caldera Forms plugin. The forms have stopped working on our website, in particular, the buttons no longer function. I had a Wordkeeper agent assist me. He suggested undoing the recent update that was done over the weekend, however, this did not work. He believes there may be a bug in your updated code and suggested I contact you directly. You can see one example of the broken Caldera Forms here: https://www.sunwize.com/mount-guide/. Thanks in advance for the assistance.

### ISSUE THREAD

**Issue by KJlassi** [CalderaWP/Caldera-Forms#2656]
Hello, I have been having problems with the Caldera Forms plugin. The forms have stopped working on our website, in particular, the buttons no longer function. I had a Wordkeeper agent assist me. He suggested undoing the recent update that was done over the weekend, however, this did not work. He believes there may be a bug in your updated code and suggested I contact you directly. You can see one example of the broken Caldera Forms here: https://www.sunwize.com/mount-guide/. Thanks in advance for the assistance.

**Comment by cicichirinos** [comment]
@KJlassi if you believe you have found a bug, please open an issue that follows the New Issue template and a form export of the form at the link you have shared above https://calderaforms.com/doc/exporting-caldera-forms/. We need your Caldera Forms, PHP, WordPress etc versions to be able to recreate your issue and fix the bug. Thanks!

**Comment by KJlassi** [comment]
Alright, is this what you are looking for? I am not a programmer and I do not understand any of this. I was particularly looking to have some sort of assistance solving the problems with this plugin, but there are no service options for those not paying for the plugin. I appreciate the help and hope this document is what you need. 
[php.docx](https://github.com/CalderaWP/Caldera-Forms/files/2160936/php.docx)
