### ISSUE TITLE
Can't select Form in Gutenberg

### ISSUE THREAD

**Issue by marcusig** [CalderaWP/Caldera-Forms#2660]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.7
PHP Version: 7.1.17
MySQL Version: 5.5.55
Caldera Forms Version: 1.7.2

**Tested on Chrome and Firefox.**

## What Is The Unexpected Behaviour?
When inserting a Caldera form block In Gutenberg, if I only have 1 form I can't select it.

![image](https://user-images.githubusercontent.com/11990914/42502343-0f3f509e-8436-11e8-8142-9f1011a51451.png)

When there's only 1 form present in the list, the `onChange` event can't be triggered, thus the inability to select the form. A `-- Select a form --` option would solve that.

Also if a form is disabled, it still appears in the list. IMO it shouldn't be the case.

**Comment by Shelob9** [comment]
Should be fixes via #2745

**Comment by Shelob9** [comment]
Close via #2745 and 
0836606
