### ISSUE TITLE
Dollar sign is not localizable in includes/cf-pro-client/classes/admin/scripts.php#L89 

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#2661]
in https://plugins.trac.wordpress.org/browser/caldera-forms/trunk/includes/cf-pro-client/classes/admin/scripts.php#L89 you’ve got an interesting thing name this string:
Ready to try Caldera Forms Pro? Plans start at just 14.99/ month with a 7 day free trial.

WordPress is used all over the world. It may be obvious for you what currency you’re referring to here, but for a big chunk of the world, it’s not.
So: Please add a currency marker, USD

requested here: https://wordpress.org/support/topic/a-note-from-a-translator/

**Comment by Shelob9** [comment]
Close via 01c4b2d
