### ISSUE TITLE
Checkbox values can not be gotten with jQuery val()

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#267]
I want to be able to grab value of an arbitrary field which maybe be a select or checkbox and send that  in a GET request. Using .val() works for selects but not checkboxes. Not sure if this is a sign of a CF issue, Josh issue, or a just a thing we should make possible, but don't.

**Comment by Desertsnowman** [comment]
checkboxes have different id's since you cant have the same ID for each option. instead you need to use the data-field attribute and specify the checked one like so:
```
$('[data-field="fld_5407331_1"]:checked').val();
```

**Comment by Shelob9** [comment]
Closing as @shelob9 is Jon Snow
