### ISSUE TITLE
Calder Forms not loading table css

### ISSUE THREAD

**Issue by Guevarabrik** [CalderaWP/Caldera-Forms#2675]
Hi,

Short Debug Information
WordPress Version: 4.9.7PHP Version: 7.0.30MySQL Version: 5.5.60Caldera Forms Version: 1.7.2WP_DEBUG:

I am having a problem with caldera forms loading my css for the table I created inside an html element. Before the update it worked well, but now its unable to load the css.

In the backend the style is working well, but in the frontend its not being loaded.
I could show you my html code and my css. i can also show you my backend and my frontend.

Is there any solution for this problem?

Thx.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
