### ISSUE TITLE
Freemius optin uses MangeWP's name if ManageWP Worker is active

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2686]
To reproduce this I install the managewp worker plugin and the Caldera Forms plugin on a fresh install. Do not dismiss either plugin's Freemius optin.

![022](https://user-images.githubusercontent.com/1994311/43327727-2d448670-918a-11e8-82bd-002fabd83add.png)

**Comment by damian-gora** [comment]
Here is a similar case - https://wordpress.org/support/topic/admin-notice-pulling-other-plugin-names/#post-10722269
Maybe there is a bug in the method `get_plugin_name()` of the `Freemius` class. 
Finally I can't reproduce it too.

**Comment by Shelob9** [comment]
Close via b3dde2b #2865
