### ISSUE TITLE
[Feature Suggestion] Honeypot Improvement

### ISSUE THREAD

**Issue by black-eye** [CalderaWP/Caldera-Forms#2696]
I'm receiving a lot of spam on several of my sites lately. Even when the honeypot is activated. 

After some investigation of the code I found out that the honeypot field and it's surrounding are hidden by `class="hide"` and even backed up by `style="display:none; overflow:hidden;height:0;width:0;"`.

I'm not a big programmer or antispam specialist, but would't it be more effective, if the honeypot hiding was less obvious? 

Just my two cents idea, maybe I'm wrong... ;)

**Comment by Shelob9** [comment]
@black-eye You can try it, but I don't think it would help. If it does, reopen this issue. 

Honey pots are less effective than they used to be. If I were you, I'd be looking at how bots are getting to your sites. A good web application firewall should block the malicious traffic.
