### ISSUE TITLE
Feature: 'cf.bind' / 'cf.unbind' events

### ISSUE THREAD

**Issue by 0xLBF** [CalderaWP/Caldera-Forms#2697]
Code intended to initialize a field generally needs to run once when the form is loaded, then once every time the field becomes visible if it's a conditional field. While this behavior can already be implemented with the cf.add/remove events or through window.cfstate[..].events.subscribe/detach, they require additional logic to make sure the init code is not called more often than necessary. As CFState's bindField/unbind already seem to be called at the right time for this feature, they could be exposed as cf.bind / cf.unbind events.

**Comment by Shelob9** [comment]
Close via #2691
