### ISSUE TITLE
Forms crashed

### ISSUE THREAD

**Issue by piranhafear** [CalderaWP/Caldera-Forms#2699]
Warning: get_current_user() has been disabled for security reasons in /home2/dentelit/esteliteglobal.com/wp-content/plugins/caldera-forms/includes/freemius/includes/class-fs-logger.php on line 89
I see this kind of error when activate the plugin
Please help 
Thanks

**Comment by Shelob9** [comment]
@piranhafear I apologize you are having this issue. I'm not sure what on your site is causing this. We can not support a site that disables core WordPress functions. I would recommend disabling this feature.
