### ISSUE TITLE
Uploaded IMages in Form dont appear in E-mail as attached

### ISSUE THREAD

**Issue by haimi23** [CalderaWP/Caldera-Forms#2700]
Hello i am using the newest version of caldera and WP. I use caldera for the following form here: http://hostessenfrankfurt.de/?page_id=5288

The form works great but the uploaded image dont appear in my media browser or attasched in my e-mails. in my e-mails it just shows ", , , , "
i marked every checkbox (upload to libary, attach image to mail, multiple files allowed)

Thank you very much for your help

Kind regards
Haimi

**Comment by vitalijm** [comment]
Same problem

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
