### ISSUE TITLE
Phone (better) field displaying 'Not a number' error message

### ISSUE THREAD

**Issue by mecachisenros** [CalderaWP/Caldera-Forms#2703]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8
PHP Version: 7.0.31
MySQL Version: 5.5.5
Caldera Forms Version: 1.7.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The Phone (better) field displays a `Not a number` error message when the field is empty, with both _Use Country Code_ setting enabled or disabled.

If you click on the field or navigate with tab key and leave the field empty you get a `Not a number` validation message, the validation is performed on `change`, `blur/focus`, and `submit` events, so even if don't _touch_ the field, the error displays briefly on form submission as well.

I would expect no validation error if the field is empty. 

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP errors.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No JS errors.

I propose to change the [validation function](https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/caldera-forms-front.js#L6054) to handle both cases, empty field, and empty field with country code (_Use Country Code_ enabled).
```
 var validation = function () {
     reset();
     var valid;
     var value = $.trim($field.val()); // field value
     if (value) {
         if ($field.intlTelInput("isValidNumber")) {
             valid = true;
         } else {
             valid = false;
         }
     }

     var message;
     var errorCode = $field.intlTelInput("getValidationError");
     var selectedCountryData = $field.intlTelInput("getSelectedCountryData"); // selected country data

     if (0 == errorCode) {
         valid = true;
         message = '';
     } else if ( value ==  "+" + selectedCountryData.dialCode ) { // Use Country Code enabled (this settings fills in the dial code as value)
         	valid = true;
         	message = '';
     } else if ( ! value ) { // empty value
         	valid = true;
         	message = '';
     } else {
         if ('undefined' != field.messages[errorCode]) {
             message = field.messages[errorCode]
         } else {
             message = field.messages.generic;
         }
     }


     handleValidationMarkup(valid, $field, message, 'help-block-phone_better');
     return valid;
 };
```

### Before
**Use Country Code setting disabled, initial state**
![country_code_disabled_initial](https://user-images.githubusercontent.com/3038096/44314034-5b68f200-a40b-11e8-8dfe-786560c3adf6.png)

**Use Country Code setting disabled, after** `change/blur/focus/submit` **events**
![country_code_disabled_event](https://user-images.githubusercontent.com/3038096/44314053-ae42a980-a40b-11e8-8718-9202c37ad213.png)

**Use Country Code setting enabled, initial state**
![country_code_enabled_initial](https://user-images.githubusercontent.com/3038096/44314066-e5b15600-a40b-11e8-9beb-10bd5360fcf1.png)

**Use Country Code setting enabled, after** `change/blur/focus/submit` **events**
![country_code_enabled_events](https://user-images.githubusercontent.com/3038096/44314075-fd88da00-a40b-11e8-9473-18f7b0567e41.png)

### After
After proposed changes, no 'Not a number' validation error.

**Comment by Shelob9** [comment]
Related #2652

**Comment by Shelob9** [comment]
Close via 760c33d #2704
