### ISSUE TITLE
Caldera forms is not calculating hidden fields

### ISSUE THREAD

**Issue by MendesMartini** [CalderaWP/Caldera-Forms#2708]
Hello,

I created two hidden fields:

subtotal, with value {post:subtotal}
taxas, with value {post:taxas}

`<input type="hidden" data-field="fld_3406989" class=" form-control" id="fld_3406989_1" name="fld_3406989" value="214.0000" data-type="hidden">
<input type="hidden" data-field="fld_4754951" class=" form-control" id="fld_4754951_1" name="fld_4754951" value="25.4100" data-type="hidden">`

No problem here at all.

So, I created a calculation field with value %subtotal%+%taxas% but the result was zero.

Opening Javascript Console, I can see only this:

`jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
parsley.min.js?ver=1.7.2:2 Accessing the method 'addValidator' through Validator is deprecated. Simply call 'window.Parsley.addValidator(...)'`

When I create variables and do the calculation using this variables, then the calculation fields work normally, BUT when I try to send the form, I get an error 500:

`Parse error: syntax error, unexpected '{' in /home/santosma/www/forms/wp-content/plugins/caldera-forms/classes/core.php(1437) : ru`

Any ideas? :/

Just in time:

`[root@vps0693 ~]# php -v
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies`

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
