### ISSUE TITLE
Switching between toggle <-> radio, options disappear

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#2709]
When add options to radio buttons and then go to try out the toggle the options disappear. I add them again and then decide I want to go back to the radio buttons and the options disappear again.

I am using the newest Caldera Forms. 
Chrome
Desktop Server. 

Plugins
Autoptimize - activated
Gutenberg - not activated

Theme from Beans Framework. I am creating a Norwegian signup for a trip form for a client and noticing a few things along the way.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
