### ISSUE TITLE
Exporting and importing iframe embed stripped from html code

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#2710]
I added this code to the html field box:

```
<iframe width="420" height="315"
src="https://www.youtube.com/embed/fAJs2SiJNfk">
</iframe>
```

Exporting the form and then importing the form the iframe was stripped out. I had to manually add it back in again.

**Comment by Shelob9** [comment]
You can not put an <iframe> element inside of a <form> element. It is not allowed by HTML.

**Comment by paaljoachim** [comment]
Ok good to know.
Have a continued great day Josh!
