### ISSUE TITLE
Retrieve newly created post id in action 'caldera_forms_submit_post_process'

### ISSUE THREAD

**Issue by vitalijm** [CalderaWP/Caldera-Forms#2714]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
Maybe.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera forms 1.7.2 
Wordpress 4.9.8

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
I want retrieve new created post id, after form was submitted in action 'caldera_forms_submit_post_process'

I am using processor 'Save as post type'.
I need this id because wanna change submitted data in new post.

## What PHP Errors Have You Logged While Reproducing This Bug?
7

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
@vitalijm I am closing this as it is a support request. If you need support, pleaser use https://calderaforms.com

BTW That hook exposes entry_id, when the custom fields processor is being used, that is the post ID.
