### ISSUE TITLE
Minify assets based on WordPress Constant SCRIPT_DEBUG

### ISSUE THREAD

**Issue by pascalknecht** [CalderaWP/Caldera-Forms#2717]
Feature Request:
It would be great if Caldera would honor the WordPress SCRIPT_DEBUG constant to decide whether to load minified assets or not. See blog post here: https://pippinsplugins.com/use-script_debug-enable-non-minified-asset-files/

**Comment by Shelob9** [comment]
@pascalknecht I'm not inclined to support this, because of the other things that SCRIPT_DEBUG does. Also, you can easily impliment this yourself if you want:

https://gist.github.com/Shelob9/69e749750307207db952705f59ef90b9#file-script_debug-php
