### ISSUE TITLE
Conditional processors problem

### ISSUE THREAD

**Issue by pszerf** [CalderaWP/Caldera-Forms#2718]
## Do You Need Immediate Help?
no

## Is This A Feature Request?
no

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WP 4.9.8 Caldera Forms 1.7.2 PHP 7.0.27

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes
## What Is The Unexpected Behaviour?
After adding new processor (redirect on submission) with a simple conditional logic it only works till I try editing a form, so if I set it up and save, it will work as long as I get back to dashboard and click edit form, on that moment the conditional logic gets reseted and if I save form even without making any changes to it the redirection will no longer work, to make it work again I need to go to processors tab and set the conditional logic again ( processor itself it's still there but conditional logic box gets empty )

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none
![caldera](https://user-images.githubusercontent.com/17258614/45121890-b8320f80-b162-11e8-8dd7-70ecfdff96c6.png)

**Comment by takkaria** [comment]
Also seeing this with the same version of WordPress, PHP and and Caldera

**Comment by pszerf** [comment]
Anyone got any solutions ?

**Comment by mrsnightskyre** [comment]
<img width="871" alt="cf_conditions_blank" src="https://user-images.githubusercontent.com/43246489/45500943-e52b8700-b74d-11e8-9c04-4bcfaa09c957.png">

I installed version 1.7.2 of Caldera - without making any other changes, my conditionals all went blank.

**Comment by mrsnightskyre** [comment]
I downgraded back to version 1.6.3 of Caldera Forms and am still seeing this problem, even though I didn't have it before the upgrade.

**Comment by DeanBu** [comment]
HelpScout Ticket Ref: https://secure.helpscout.net/conversation/667257514/12712?folderId=2136818
----
**What Version Of Caldera Forms, WordPress and PHP Are You Using?**

WordPress Version: 4.9.8
PHP Version: 7.0.30
Caldera Forms Version: 1.6.3

**Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?**
Yes (replicated on staging)

**What Is The Unexpected Behaviour?**
The form has HTML fields, drop-down fields and a submit button.

The form uses 'Conditional Recipient' and 'Conditional Groups' - these conditions are being used to hide and show fields depending on what the user selects previously. 

When you set the conditions in the conditional groups or the conditional recipient and then save, refresh the form and the conditions are now empty.

**Comment by New0** [comment]
This should be fixed by #2753
