### ISSUE TITLE
Braintree SDK conflict with PayPal for WooCommerce plugin

### ISSUE THREAD

**Issue by dear-leader** [CalderaWP/Caldera-Forms#2720]
I'm running the latest version of Wordpress core and all plugins. Short debug line:
`WordPress Version: 4.9.8PHP Version: 7.2.7-1+ubuntu16.04.1+deb.sury.org+1MySQL Version: 5.5.5Caldera Forms Version: 1.7.2WP_DEBUG:`.

The Braintree credit card form does not load on the WooCommerce checkout page as soon as the Caldera Forms Braintree add-on is activated. I haven't actually tried any of the functionality of the Caldera Braintree add-on yet, because of the incompatibility. 

Here's the PHP error:
`Uncaught Error: Call to undefined method Braintree_MerchantAccountGateway::all() in /www/beetstech_608/public/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-braintree-angelleye.php:2021`

I found issue #2681 which references a similar problem with a different Braintree related plugin, and tried the quick fix code mentioned in one of the comments. It required some modification for the PayPal for WooCommerce plugin, and then still didn't work but threw a slightly different error referencing a different line:

`Uncaught Error: Call to undefined method Braintree_MerchantAccountGateway::all() in /www/02_932/public/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-braintree-angelleye.php:1750`

Then I realized I should have began by checking which version of the SDK each plugin was using and sure enough, they're different. Caldera Forms is using 3.2 and [PayPal for WooCommerce is using 3.34](https://github.com/angelleye/paypal-woocommerce/blob/release/classes/lib/lib/Braintree/Version.php).

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. This is an issue tracker for Caldera Forms, not a support system. Please use https://calderaforms.com/support to request support for Caldera Forms add-ons.
