### ISSUE TITLE
load jQuery as dependency for JS files.

### ISSUE THREAD

**Issue by Nikschavan** [CalderaWP/Caldera-Forms#2722]
## Do You Need Immediate Help?
No.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
`develop` branch

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
No.

## What Is The Unexpected Behaviour?
`parsely.min.js` depends on jQuery but it is not added in the dependency array when registering the script.
With the themes that don't require jQuery themselves (like [Astra](https://github.com/brainstormforce/astra)) this throws JS errors since jQuery loads after the `parsley.min.js`

## What JavaScript Errors Have You Seen While Reproducing This Bug?
![image](https://user-images.githubusercontent.com/2931091/45354122-898cbc80-b5da-11e8-980f-e6188225d591.png)

**Comment by pascalknecht** [comment]
I second this. Would be great to have no dependency on jQuery in body.

**Comment by Shelob9** [comment]
#2805 is a PR for this.

**Comment by Shelob9** [comment]
Close via #2805
