### ISSUE TITLE
Pbs with the Stripe addon : wrong amount and error message "invalid positive integer" 

### ISSUE THREAD

**Issue by jpfiliatre** [CalderaWP/Caldera-Forms#2732]
WordPress Version: 4.9.8PHP Version: 7.0.30-1~dotdeb+8.1MySQL Version: 5.5.60Caldera Forms Version: 1.7.2WP_DEBUG: 

Two different problems with the Stripe Addon (in test mode)

The form contains a calculated field (whose results are OK); this field is used in the Stripe processor as the "amount" file. It is the addition of three different values collected in other fields in the form, depending on the answers of the customer.

When clicking on the last button of the form (transmit or whatever you call it in english), the payment form appears with the right amount.

BUT

in some cases, the payment is processed but the amount that can be read in the "payment" page when viewing the Stripe account is wrong; it seems that the amount supposed to be paid is the first term of the addition (?!) though in the form itself and later in the payment form the amount was right, ie the sum of the three values as indicated above.

in some other cases, the payment is not processed and an error message appears : Invalid positive integer

**Comment by Shelob9** [comment]
@jpfiliatre Thanks for using Caldera Forms. I really appreciate it. Support for paid add-ons can be requested here: https://CalderaForms.com/support this is an issue tracker for Caldera Forms core development. We'd be happy to help if you open a support ticket.
