### ISSUE TITLE
Consider add a comment about PII string to help translators

### ISSUE THREAD

**Issue by Rahmon** [CalderaWP/Caldera-Forms#2735]
It's not easy to translators know what "PII" meaning so I think it's a good idea add a comment. 

https://github.com/CalderaWP/Caldera-Forms/blob/2cdb95b7f258b6567f0b570da526ab4bd6d58ec3/classes/admin/privacy.php#L78

**Comment by Shelob9** [comment]
Fixed via #2746  c175c2c

Thanks for the patch.
