### ISSUE TITLE
Caldera bug "Warning: in_array() expects parameter 2 to be array, null given in ...." 

### ISSUE THREAD

**Issue by Zajeccc** [CalderaWP/Caldera-Forms#2736]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
Yes

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera 1.7.2, PHP 7.2.10

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Just I want to delete this issue "Warning: in_array() expects parameter 2 to be array, null given in /home/platne/serwer17387/public_html/boguslaw/wp-content/plugins/caldera-forms/classes/forms.php on line 725

Warning: in_array() expects parameter 2 to be array, null given in /home/platne/serwer17387/public_html/boguslaw/wp-content/plugins/caldera-forms/classes/forms.php on line 725"

What I should to do, to switch off this bug from my website ?

**Comment by Deaner666** [comment]
Same problem for me... I also see this error message at the same time:

Notice: Undefined index: name in /nas/content/live/sitename/wp-content/plugins/caldera-forms/classes/core.php on line 4214

**Comment by Shelob9** [comment]
Related  #2569

**Comment by Shelob9** [comment]
This line is here - https://github.com/CalderaWP/Caldera-Forms/blob/25b2cc800d3ddfb570889f62022be7a8a23045be/classes/forms.php#L727

the `get_stored_forms()` method is not guaranteed to return an array. If you have no saved forms, then its going to return null in some cases.

**Comment by Shelob9** [comment]
Close via ef2a721
