### ISSUE TITLE
Note to confirm email in Gutenberg partially covered by sidebar

### ISSUE THREAD

**Issue by bph** [CalderaWP/Caldera-Forms#2740]
WordPress Version: 4.9.8PHP Version: 7.0.32-0ubuntu0.16.04.1MySQL Version: 5.7.23 Caldera Forms Version: 1.7.2WP_DEBUG: 1 Gutenberg 3.9

## What Is The Unexpected Behaviour?
After activation, the request to confirm the email  shown in the Guteberg editor, but partially covered when "Settings" sidebar is visible. 
![screen shot 2018-09-28 at 9 37 31 am](https://user-images.githubusercontent.com/39980/46211950-d1158700-c302-11e8-8b9d-c95b065bac9d.png)
![screen shot 2018-09-28 at 9 37 17 am](https://user-images.githubusercontent.com/39980/46211951-d1158700-c302-11e8-80e3-30918d570316.png)

**Comment by Shelob9** [comment]
I'm going to leave this open, for now, though it will need to fixed upstream https://github.com/Freemius/wordpress-sdk/issues/265

**Comment by Shelob9** [comment]
We will resolve this in 1.7.4 by removing Freemius integration  #2865

**Comment by Shelob9** [comment]
Close via b3dde2b #2865
