### ISSUE TITLE
Disabled Form still shows up in drop down on Block

### ISSUE THREAD

**Issue by bph** [CalderaWP/Caldera-Forms#2742]
WordPress Version: 4.9.8PHP Version: 7.0.32-0ubuntu0.16.04.1MySQL Version: 5.7.23Caldera Forms Version: 1.7.2WP_DEBUG: 1

After I disabled a form, it still would show up in the Block as a choice. 
http://recordit.co/MyMOcW6fuv

**Comment by Shelob9** [comment]
PR #2806 should resolve this.

**Comment by Shelob9** [comment]
Close via #2806
