### ISSUE TITLE
With a single form, drop-down doesn't 'select' form 

### ISSUE THREAD

**Issue by bph** [CalderaWP/Caldera-Forms#2743]
WordPress Version: 4.9.8 PHP Version: 7.0.32-0ubuntu0.16.04.1 MySQL Version: 5.7.23 Caldera Forms Version: 1.7.2WP_DEBUG: 1 - Gutenberg 3.9 Chrome 69

If I have only one form in Caldera Forms, I am not able to add it as Gutenberg block as the drop-down doesn't trigger the action to pull in the form on the first item. AFter I created a second, bogus form, I was able to trigger the desired from for my page. 

Here is a video: http://recordit.co/DvPYtetsLW

Cheerio:-)

**Comment by Shelob9** [comment]
Closing as duplicate of #2660
Should be fixed via #2745

**Comment by Shelob9** [comment]
Fixed via #2745 and  0836606
