### ISSUE TITLE
Run JS unit tests in Travis 

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2765]
Only needs to run on one test run, not all test runs.

See readme, but:
`npm install`
`npm run test:once`

**Comment by Shelob9** [comment]
Related #2764

**Comment by New0** [comment]
First attempt returned
- Failed tests all because of " Cannot find module 'React' from 'setupJest.js'" ( clients/tests/setupJest.js )
- Then ended with "The command "npm run test:once" exited with 1."

**Comment by Shelob9** [comment]
Two theories:
* Import is bad
* React doesn't exist

**Comment by Shelob9** [comment]
Close via 296e6bc #2767
