### ISSUE TITLE
Form cloning issue

### ISSUE THREAD

**Issue by mlee390** [CalderaWP/Caldera-Forms#2768]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8PHP Version: 7.1.22MySQL Version: 5.6.41Caldera Forms Version: 1.7.3

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Y
## What Is The Unexpected Behaviour?
When 'cloning' a form, the original form is gone.

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by Shelob9** [comment]
Close via 0b76d08 #2770

**Comment by jrglaber** [comment]
Which Season of version 1.7.4 will be released with this update?

**Comment by Shelob9** [comment]
https://calderaforms.com/updates/caldera-forms-1-7-4/
