### ISSUE TITLE
My save form ( button on click not saving the data) not working,

### ISSUE THREAD

**Issue by tiapreetha** [CalderaWP/Caldera-Forms#2777]
Hi Frnds,
           I am using caldera form in my project.Its really a nice plugin. I am writing some conditional logic codes for my project ....suddenly my save form button not working.Its not saving my data. The (uploaded successfully ) msg is not coming, I am not able to complete my project due to this issue ...plz help me caldera form team....anyone plz help me 
My caldera form Version: 1.7.3 (latest one)
Thanks in advance....

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
