### ISSUE TITLE
Calculation value of field options is always zero after import

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2778]
IF I have a field with calc values:
![screen shot 2018-10-20 at 12 44 06 pm](https://user-images.githubusercontent.com/1994311/47258207-e1360780-d465-11e8-8b0d-f49d42b17847.png)

After it imports the calc_values are 1.
![screen shot 2018-10-20 at 12 44 40 pm](https://user-images.githubusercontent.com/1994311/47258211-f27f1400-d465-11e8-9fbf-94e6e10314db.png)

This is bad and also blocking #2772 because none of my caluculations tests pass for stupid reasons.

**Comment by Shelob9** [comment]
Should be fixed via 8c18fdb

**Comment by tiapreetha** [comment]
Hi Shelob9 ,
          hello sir, greetings ...i am using caldera form in my project ....i am almost to finish ...my save form button not working........plz help me.......i am meeting my project deadlines.......waiting for your reply....
Thanks in advance
issue no : #2777

**Comment by Shelob9** [comment]
Close via #2779
