### ISSUE TITLE
Not obvious how to add licence if process skipped at first activation

### ISSUE THREAD

**Issue by JonBarrett** [CalderaWP/Caldera-Forms#280]
After installing and activating the Users plugin a message in the plugins screen asked me to add the licence. I skipped the task at that stage. 

Now I wish to add the licence there does not appear to be any way to do so. When I select Extend in the menu a licence tab appears for a few seconds then disappears.

**Comment by Shelob9** [comment]
Closing as license manager v2 will handle this.
