### ISSUE TITLE
Caldera Forms not working - not receiving email and not going to the Thank You page

### ISSUE THREAD

**Issue by rinlp** [CalderaWP/Caldera-Forms#2811]
I am using Caldera forms 1.7.4 for my website (hosted on WordPress) and it was working well for a few months. However yesterday when I decided to do a random test on the form nothing happens when I click "Send Request". Usually it will go to a thank you page, and I will get an email sent to the email address I have linked to the form. Can someone help?

Would appreciate help asap as we are running a business and we typically get requests a few times a week, and last I check, we have not received a request for over a week. Thanks.

Irene

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
