### ISSUE TITLE
How to remove Deprecated Functionality mail message?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#2816]
## Do You Need Immediate Help?
No.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8PHP Version: 7.1.23MySQL Version: 10.1.36Caldera Forms Version: 1.7.3WP_DEBUG:

How would one go about removing the Deprecated Functionality mail message?
There is no X to click.

![screen shot 2018-11-21 at 13 10 40](https://user-images.githubusercontent.com/5323259/48840440-e8b33e00-ed8e-11e8-9700-eccc759ffbe7.png)

**Comment by Shelob9** [comment]
This is the correct behaviour. We will remove those settings when we refresh the admin page.
