### ISSUE TITLE
Easy Pods 1.1.10 TypeError: wp.mce is undefined

### ISSUE THREAD

**Issue by n9yty** [CalderaWP/Caldera-Forms#2835]
This problem *may* be related to:

[Pods 2.7 problem if Caldera Forms 1.5.7.1 is installed #2124](https://github.com/CalderaWP/Caldera-Forms/issues/2124)

Version information:

WordPress Version: 4.9.8PHP Version: 7.1.21MySQL Version: 5.7.23Caldera Forms Version: 1.7.4WP_DEBUG: 

Although the problem is with Caldera Easy Pods: 1.1.10, but I was directed here to report the issue.

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?

Yes, except for those required to show the problem... WooComnmerce and the Shipment Tracking plugin.  Plus PODS, as Easy Pods requires it.

## What Is The Unexpected Behaviour?

When viewing an order page, the following javascript error is thrown, and it causes elements on the page to not respond properly, like the one to add shipment tracking information provided by the plugin mentioned above.

shortcode-insert.js:52:5

```
TypeError: wp.mce is undefined

<anonymous>
https:/siteurl/wp-content/plugins/caldera-easy-pods//assets/js/shortcode-insert.js:52:5
i
https://siteurl/wp-admin/load-scripts.php:2:27444
fireWith
https://siteurl/wp-admin/load-scripts.php:2:28213
ready
https://siteurl/wp-admin/load-scripts.php:2:30004
K
https://siteurl/wp-admin/load-scripts.php:2:30366
```
I was able to modify shortcode-insert.js file on line 49 to test for wp.mce as well, that made the error go away. Similarly, as the above ticket mentioned in a secondary point, changing wp.mce.views to wp.media.View also made the error go away. However, I have not tested if this breaks the plugin functionality or not. The referenced ticket mentioned a problem with Caldera Forms, and was closed, but in the report the issue with Easy Pods was mentioned and I don't know that it was ever addressed. It may not be the same problem anyway, but mentioning it as a reference.

**Comment by Shelob9** [comment]
@n9yty  Thanks for using Easy Pods. If you have an active license for Easy Pods, you can open a support request here: https://calderaforms.com/support and someone can help you out. We can not offer support via Github.

**Comment by n9yty** [comment]
Ok, I was trying to document a bug for your benefit.  I have modifed our site to work, so if you don't want to modify the main code that is your choice.

Thanks.
