### ISSUE TITLE
 For a Form with one Advance File field version2 ,form not getting submitted on Microsoft Edge browser

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2838]
## Do You Need Immediate Help?
* No

## Is This A Feature Request?
* NO

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 4.9.8PHP Version: 7.1.24MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1
Using CF from develop branch on 30th Nov 2018

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
 * Yes
## What Is The Unexpected Behaviour?
* In my form with one advance file field v2, when I attach a file in the field and click on submit button in my form, the form is not getting submitted even after clicking submit button multiple times on Microsoft edge browser

## What PHP Errors Have You Logged While Reproducing This Bug?
* None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
*  HTTP403: FORBIDDEN - The server understood the request but is refusing to fulfill it.
(Fetch)POST - https://testsite.lndo.site/wp-json/cf-api/v3/file

**Comment by Shelob9** [comment]
@New0 This is one that needs checked once we're ready for QA again on adv file fields v2

**Comment by swapnilmanjrekar** [comment]
@Shelob9 @New0 I was not able to reproduce this issue on Microsoft Edge, Mozilla Firefox  & Chrome browser. I did not see any JS or PHP Errors when I checked the Console of my browsers and debug.log file of my local WordPress test site.



  WordPress Version: 5.0.3PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0-beta.1WP_DEBUG: 1

**Comment by New0** [comment]
Thank you @swapnilmanjrekar probably fixed after render/index.js refactor

**Comment by cymode** [comment]
This issue still exists with the advanced file uploader V2 using the latest version of Caldera Forms. Sadly the developer have no clue or time how to fix this. Been having this issue across all our domains now for a few months. Very disappointing.
