### ISSUE TITLE
Can not remove file from adv file v2 field in Firefox and Edge

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2839]
## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*WordPress Version: 4.9.8PHP Version: 7.1.24MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

Using CF from develop branch on 30th Nov, 2018

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
*Yes

## What Is The Unexpected Behaviour?
* For a form with 1 advance required file field with the required option checked, when I attach a file in the field and remove it and try to submit the form submit button is not working as I expected to see the"file is required" warning on my form.

## What PHP Errors Have You Logged While Reproducing This Bug?
* None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* I did not see any JS errors on my console in Mozilla & Edge browser.

**Comment by Shelob9** [comment]
@swapnilmanjrekar Good catch. Did you test this in Chrome. I've never seen this in Chrome but want to make sure that I'm understanding you clearly that this is an Edge + Firefox issue only.

@New0 When you get back into file fields, please look into this. I'm not sure how to test it, will think. I've been testing doing manual testing with Chrome + Safari. Cypress only runs in Chrome. We have a clear gap here.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 I tested this in Chrome today and I am facing this issue on Chrome also. So this is a Chrome + Firefox + Edge Issue.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 I was not able to reproduce the issue as I was able to import my previously created file field form and after Importing the form it was properly displaying File field in the form. Also, I did not see any JS or PHP errors when I checked the console of my browsers ie.Chrome,Edge & Firefox and debug.log file of my local WordPress test site.

WordPress Version: 5.0.3PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0-beta.1WP_DEBUG: 1

**Comment by swapnilmanjrekar** [comment]
@Shelob9 @New0 I am still able to reproduce this issue on Mozilla Firefox, Chrome & Edge Browser. 

**JavaScript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.

**PHP Errors:**

- When I checked the debug.log file of my WordPress test site it gave me following PHP warning : 
 "PHP Notice:  Undefined index: name in /app/wp-content/plugins/1.8.0-beta.1/classes/core.php on line 
 4238"


WordPress Version: 5.0.3PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0-beta.1WP_DEBUG: 1

**Comment by New0** [comment]
Thank you @swapnilmanjrekar I also see that the Field is required error message is not triggered when the File field is set a file and then removed that file, the form is just stuck and doesn't submit either.

We have a PR for server side errors in progress that could fix that at #2933

**Comment by Shelob9** [comment]
Closed. No longer an issue.
