### ISSUE TITLE
403 error on request to upload file in adv file v2 field

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2842]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
** WordPress Version: 4.9.8PHP Version: 7.1.24MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1

Using CF from develop branch on 3rd December, 2018

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
 Yes

## What Is The Unexpected Behaviour?
* For a form with 3 Adv File Fields v2 when  I attach files in field 1 & field 2  and click submit button, the spinner keeps going round and round on and does not displays "Form has been successfully submitted" which I expected to see when I click submit button but on the back end, the form was successfully submitted and I received the attached files in my email.

## What PHP Errors Have You Logged While Reproducing This Bug?
* None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* When I checked the console of my Chrome & Mozilla browser it showed me following error:
" **TypeError: "b.jqxhr.responseJSON is undefined**"
And For Edge it showed following error:
"**[object Object]: {code: "rest_cookie_invalid_nonce", data: Object, message: "Cookie nonce is invalid"}
HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.
(Fetch)POST - https://testsite.lndo.site/wp-json/cf-api/v3/file**"

**Comment by cymode** [comment]
This issue still exists with the advanced file uploader V2 using the latest version of Caldera Forms. Sadly the developer have no clue or time how to fix this. Been having this issue across all our domains now for a few months. Very disappointing. The issue has been around now for nearly 2 years for some. For me it's been since June.
