### ISSUE TITLE
Custom autopopulated checkboxes are not calculated by Calculation field

### ISSUE THREAD

**Issue by mecachisenros** [CalderaWP/Caldera-Forms#2849]
## Do You Need Immediate Help?
Nope

## Is This A Feature Request?
More of a fix and feature request.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8
PHP Version: 7.1.24
MySQL Version: 5.7.24
Caldera Forms Version: 1.7.4

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes :)
## What Is The Unexpected Behaviour?
When using `caldera_forms_field_option_presets` and `caldera_forms_render_get_field` hooks for autopopulate/bulk insert presets options, is common practice to use some unique ID (an `integer`) for the populated data.

When using those unique IDs and also using the field for autopopulation, Checkbox fields are ignored because `Caldera_Forms_Field_Util::get_option_calculation_value()` checks very early for `is_string()` [here](https://github.com/CalderaWP/Caldera-Forms/blob/2cdb95b7f258b6567f0b570da526ab4bd6d58ec3/classes/field/util.php#L523) and `caldera_forms_get_option_calculation_value` hook never kicks in because of the [early return](https://github.com/CalderaWP/Caldera-Forms/blob/2cdb95b7f258b6567f0b570da526ab4bd6d58ec3/classes/field/util.php#L530) that evaluates the calculated value to `0`. `is_string()` makes sense for Caldera Forms' implementation of options as those get an ID in the form of `optXXXX`, but for custom implementation I think it would be appropriate to also accept an integer as the option ID.

So that early check could also check for `is_int()` or `is_numeric()` or both, thoughts?
```
...
if ( is_array( $option ) || is_int( $option ) ) {
...
```
Happy to submit a PR if agreed.

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors to reproduce.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors to reproduce.

**Comment by Shelob9** [comment]
Thanks for reporting. Your idea for how to fix this makes sense.

Am I correct that this happens because you've chosen to make the option IDs the same integer as the value when loading the forms via JSON export or the filter for file system-based forms? Makes logical sense to do that, we're just trying to make sure we understand root of the bug.

**Comment by mecachisenros** [comment]
@Shelob9 yes, you are correct, this use case is for a [plugin](https://github.com/mecachisenros/caldera-forms-civicrm) that integrates Caldera Forms with [CiviCRM](https://civicrm.org) where the integers where needed.

**Comment by New0** [comment]
Closed by [`de77a31`](/CalderaWP/Caldera-Forms/commit/de77a3110290be2f0e98d8e02d34e9534381e3de)
