### ISSUE TITLE
Placeholders don't work for dropdown fields. (maybe theme related)

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#285]

**Comment by Shelob9** [comment]
Works fine for me in TwentyFifteen, but reporting user's form does not show placeholders, shows empty option as default...

**Comment by zanematthew** [comment]
The issue with placeholders in dropdowns/selects is that when you are using them with the option to auto-populate the form you have no way of "unselecting" an already selected value.

1. Site load – Form, with initial results below
2. User selects value from dropdown, results update
3. User has now has no way to get back to his initial results without reloading the page, as he/she cannot select the "placeholder value" hence retrieving the initial results.

**Comment by Desertsnowman** [comment]
Truth is that placeholders are not supported by select fields. everything we do is more of a hack to make it kind of work.
I am looking at alternate ways of making it work better.

**Comment by zanematthew** [comment]
@Desertsnowman see above, easy as removing `disabled`?

**Comment by Desertsnowman** [comment]
sort of. that will make it work, but wont have the same appearance as a placeholder. I will indeed experiment with this more.

**Comment by zanematthew** [comment]
True, granted we can always target the "placeholder" via CSS and style it that way. Additionally, concise text can be used. "Please select a value", even though its not grayed out users will be able to understand.

This is the fix/hack I'm using currently.

`$('.calderawp-placeholder-fix option:first').prop('disabled', false );`

FYI, great work.

**Comment by Shelob9** [comment]
This has been fixed in 1.4.4
