### ISSUE TITLE
*Bug* Caldera Forms loops on freemius integration page

### ISSUE THREAD

**Issue by VizeyeBasvur** [CalderaWP/Caldera-Forms#2853]
Hi,

I have been using Caldera forms for a long time and it is great. Since yesterday I am stucked at freemius.com integration offer page.

I have tried deactivating, removing, clear cache and browser cookies, updated wordpress 5.0 but still it's the same. Did this happen to anyone of you?

UPDATE
I have installed plug-in to another worpress site, works fine. Tried to install older version to my site but still same.

Here are the sample links when I try to skip or activate

mysite.com/wp-admin/admin.php?error&page=caldera-forms
mysite.com/wp-admin/admin.php?error&page=caldera-forms
mysite.com/wp-admin/admin.php?fs_action=caldera-forms_skip_activation&page=caldera-forms&_wpnonce=68abac091e

Whatever I do I get the same screen. 

Here is a screenshot:
https://prnt.sc/lre8iq

I don't want to debug this. If you know, can you please explain how to fresh install the plug-in without losing the forms that I created before?

Thanks in advance!

**Comment by swapnilmanjrekar** [comment]
**I checked this bug using the following steps:**

- I created a WordPress test site on my desktop locally using Lando.
- I Installed WordPress 5.0.2 on my local test site
- I installed CF plugin on my test site.
- After CF plugin was installed, I Clicked on Activate CF Plugin and on wordrpess+CF+ freemius popup I was successfully able to skip it by clicking skip option.


**Javascript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.

 **PHP Errors:**

- When I checked the debug.log file of my WordPress test site I did not see any PHP errors.

**So according to my testing & findings, I think this is not a bug as I was successfully able to skip the popup of WordPress+CF+Freemius.**

WordPress Version: 5.0.1PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.7.4WP_DEBUG: 1

**Comment by Shelob9** [comment]
We will resolve this in 1.7.4 by removing Freemius integration  #2865

**Comment by Shelob9** [comment]
BTW The "Skip" option works, not the continue option.

**Comment by Shelob9** [comment]
Close via b3dde2b #2865

**Comment by VizeyeBasvur** [comment]
Thank you for your concern!

**Comment by VizeyeBasvur** [comment]
By the way I have to say that I found an overlap with YASR plugin. They are also making integration with Freemius. When I deactivated YASR, I was able to see my forms at caldera but when they are both active they behave the same. On the YASR side, it's still an issue. Thank you again.
