### ISSUE TITLE
Entries of previously created forms in WordPress 4.9 not showing in WordPress 5.0.1 

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2858]
## Do You Need Immediate Help?
* Yes

## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.0.1PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.7.4WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is The Unexpected Behaviour?
* When I try to import my forms created previously in WordPress 4.9 I was not able to see my entries which I expected to See.

## What PHP Errors Have You Logged While Reproducing This Bug?
* " PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /app/wp-content/plugins/caldera-forms/classes/forms.php on line 274 "

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* None

**Comment by Shelob9** [comment]
This is not a bug, form import does not import form entries.
