### ISSUE TITLE
404 error on request to upload file in adv file field v1

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2863]
## Is This A Feature Request?
* No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.0.1PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.7.4WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is The Unexpected Behaviour?
* For a form with Adv. File field, when I attach multiple files of image & doc type, it is not getting uploaded and submit button gets unresponsive as I expected the files to be uploaded and form getting submitted successfully.

## What PHP Errors Have You Logged While Reproducing This Bug?
* None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* When opened the console of my browser it showed me the following errors:
  "Failed to load resource: the server responded with a status of 404 ()"
   "Uncaught ReferenceError: buttons is not defined"

**Comment by Shelob9** [comment]
I am closing this as this field type will be deprecated in 1.8
