### ISSUE TITLE
403 error on request to upload file in adv file fields v1

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2867]
## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.0.1PHP Version: 7.1.24MySQL Version: 5.7.24Caldera Forms Version: 1.8.0-alpha.1WP_DEBUG: 1
 Using CF from dev branch on 17th DEC 2018

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is The Unexpected Behaviour?
* For a CF with adv file field v1, when I attach one file in file field and click on submit button, the file is not getting uploaded as I expected to see the file uploaded and form has been successfully submitted message.

## What PHP Errors Have You Logged While Reproducing This Bug?
* None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* When I check the console of my browser, it gave me the following error:
"index.min.js?ver=1.8.0-alpha.1:30 POST https://testsite.lndo.site/wp-json/cf-api/v3/file 403"
"{code: "rest_forbidden", message: "Sorry, you are not allowed to do that.", data: {…}}"

**Comment by Shelob9** [comment]
I am closing this as the field type will be deprecated in 1.8.0

**Comment by cymode** [comment]
This issue still exists with the file uploader V2 using the latest version of Caldera Forms.  Sadly the developer have no clue or time how to fix this. Been having this issue across all our domains now for a few months.  Very disapointing.
