### ISSUE TITLE
Forms can no longer be saved

### ISSUE THREAD

**Issue by reserna** [CalderaWP/Caldera-Forms#2884]
Forms can no longer be saved

I have inserted masks for text fields in 2 of my forms. Since then, I can no longer edit any of my forms and the changes are no longer saved. I also can't remove the corresponding masks or delete the field. Even if I create a new form, the form will still appear, but none of the created fields are included.
What can I do? I'm not a Pro customer and I'm desperate.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
