### ISSUE TITLE
CF2 File field is not set in Gutenberg preview form

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2887]
The Gutenberg block shows a preview of the form once set on the edition view of the post/page. This preview of the form is not showing the new cf2 File field yet.

**Comment by Shelob9** [comment]
This is because my preview loader is not loading the render client. I think instead of fixing this, it would be better to replace my form preview loader with the ServerSideRender component that Gutenberg provides for this. I have example code for how to do that.

**Comment by Shelob9** [comment]
Close via #2920
