### ISSUE TITLE
HTTP Referrer Ability

### ISSUE THREAD

**Issue by richgar07** [CalderaWP/Caldera-Forms#2894]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

Please create an HTTP Referrer ability. Example: _Customer clicks on a link in a Facebook post that takes them to a page that has a Caldera Form, they fill it out, then in the email the website admin receives is the url the customer lead came from_. This provides a ton of value to the clients and helps Agency's with Caldera Forms stand out. This is a pretty standard feature for wp contact forms (contactform7, gravity form) so I think it would be pretty easy feature to quickly add.

**Comment by richgar07** [comment]
Hi Josh, Thanks for your response. 

I have contacted your support and they mentioned that they don't have this capability and directed me to here. I'm looking for the referring website like Google Analytics uses to figure out Acquisitions. So yes there is the ability to see what page the customer came from on the website but that wouldn't be a referral because the site is mine/clients. I am looking for the url from the site that the customer was referred from. As an example, ContactForm7 does it well with their plugin https://wordpress.org/plugins/referrer-input-for-contact-form-7/. The ability to grab the HTTP Referrer.

**Comment by richgar07** [comment]
I'm glad you brought up the magic tags because that would be a cool way for users to easily use or maybe it has to be a free add on to make it work. Either way it would be very beneficial to website owners so that they can easily see what channels are actually converting on the website and then becoming a customer. Finding out what sites convert the best is a bit easier for e-commerce when using Google Analytics but for service based businesses this is a game changer. It helps see where marketing dollars should go towards. Can be beneficial for all websites though.

**Comment by Shelob9** [comment]
Thanks for the extra details. That helps me understand the problem your trying to solve.

I'm curious if using a utm_referrer argument in the URL, tracking it in Caldera Forms with the UTM field, so it shows up in the email, and the you cam reports that to Google Analytics as well works for you? I'm asking because if that solves your problem, this is a document issue that we can solve.

**Comment by richgar07** [comment]
Totally true! We currently do that for clients that have a higher marketing budget. This is more work for us and the client since they/us would have to change url they created across the web or setup tag manager to auto fill. Agency's aren't looking to add more work on their end but create repeatable systems. The http referrer is very easy to setup and repeatable. I'm also not really looking to loose a feature switching to Cladera Forms. Do you have any other suggestions on creating the HTTP Referrer ability? Support made it sound like there is no way to do it on our end it would have to be on your end. Is that true or can I create hooks or a plugin that integrates with Caldera Forms? I have seen in every Wordpress wp-includes there is the following code but I'm not sure if tapping into this would do what the same thing the other premium forms do? You probably would.

Here is what is already in Wordpress includes functions:
/**
* Retrieve URL with nonce added to URL query.
*
* @since 2.0.4
*
* @param string $actionurl URL to add nonce action.
* @param int|string $action Optional. Nonce action name. Default -1.
* @param string $name Optional. Nonce name. Default '_wpnonce'.
* @return string Escaped URL with nonce action added.
*/
function wp_nonce_url( $actionurl, $action = -1, $name = '_wpnonce' ) {
$actionurl = str_replace( '&', '&', $actionurl );
return esc_html( add_query_arg( $name, wp_create_nonce( $action ), $actionurl ) );
}

/**
* Retrieve or display nonce hidden field for forms.
*
* The nonce field is used to validate that the contents of the form came from
* the location on the current site and not somewhere else. The nonce does not
* offer absolute protection, but should protect against most cases. It is very
* important to use nonce field in forms.
*
* The $action and $name are optional, but if you want to have better security,
* it is strongly suggested to set those two parameters. It is easier to just
* call the function without any parameters, because validation of the nonce
* doesn't require any parameters, but since crackers know what the default is
* it won't be difficult for them to find a way around your nonce and cause
* damage.
*
* The input name will be whatever $name value you gave. The input value will be
* the nonce creation value.
*
* @since 2.0.4
*
* @param int|string $action Optional. Action name. Default -1.
* @param string $name Optional. Nonce name. Default '_wpnonce'.
* @param bool $referer Optional. Whether to set the referer field for validation. Default true.
* @param bool $echo Optional. Whether to display or return hidden form field. Default true.
* @return string Nonce field HTML markup.
*/
function wp_nonce_field( $action = -1, $name = "_wpnonce", $referer = true , $echo = true ) {
$name = esc_attr( $name );
$nonce_field = '';

if ( $referer )
$nonce_field .= wp_referer_field( false );

if ( $echo )
echo $nonce_field;

return $nonce_field;
}

/**
* Retrieve or display referer hidden field for forms.
*
* The referer link is the current Request URI from the server super global. The
* input name is '_wp_http_referer', in case you wanted to check manually.
*
* @since 2.0.4
*
* @param bool $echo Optional. Whether to echo or return the referer field. Default true.
* @return string Referer field HTML markup.
*/
function wp_referer_field( $echo = true ) {
$referer_field = '';

if ( $echo )
echo $referer_field;
return $referer_field;
}

/**
* Retrieve or display original referer hidden field for forms.
*
* The input name is '_wp_original_http_referer' and will be either the same
* value of wp_referer_field(), if that was posted already or it will be the
* current page, if it doesn't exist.
*
* @since 2.0.4
*
* @param bool $echo Optional. Whether to echo the original http referer. Default true.
* @param string $jump_back_to Optional. Can be 'previous' or page you want to jump back to.
* Default 'current'.
* @return string Original referer field.
*/
function wp_original_referer_field( $echo = true, $jump_back_to = 'current' ) {
if ( ! $ref = wp_get_original_referer() ) {
$ref = 'previous' == $jump_back_to ? wp_get_referer() : wp_unslash( $_SERVER['REQUEST_URI'] );
}
$orig_referer_field = '';
if ( $echo )
echo $orig_referer_field;
return $orig_referer_field;
}

/**
* Retrieve referer from '_wp_http_referer' or HTTP referer.
*
* If it's the same as the current request URL, will return false.
*
* @since 2.0.4
*
* @return false|string False on failure. Referer URL on success.
*/
function wp_get_referer() {
if ( ! function_exists( 'wp_validate_redirect' ) ) {
return false;
}

$ref = wp_get_raw_referer();

if ( $ref && $ref !== wp_unslash( $_SERVER['REQUEST_URI'] ) && $ref !== home_url() . wp_unslash( $_SERVER['REQUEST_URI'] ) ) {
return wp_validate_redirect( $ref, false );
}

return false;
}

/**
* Retrieves unvalidated referer from '_wp_http_referer' or HTTP referer.
*
* Do not use for redirects, use wp_get_referer() instead.
*
* @since 4.5.0
*
* @return string|false Referer URL on success, false on failure.
*/
function wp_get_raw_referer() {
if ( ! empty( $_REQUEST['_wp_http_referer'] ) ) {
return wp_unslash( $_REQUEST['_wp_http_referer'] );
} else if ( ! empty( $_SERVER['HTTP_REFERER'] ) ) {
return wp_unslash( $_SERVER['HTTP_REFERER'] );
}

return false;
}

/**
* Retrieve original referer that was posted, if it exists.
*
* @since 2.0.4
*
* @return string|false False if no original referer or original referer if set.
*/
function wp_get_original_referer() {
if ( ! empty( $_REQUEST['_wp_original_http_referer'] ) && function_exists( 'wp_validate_redirect' ) )
return wp_validate_redirect( wp_unslash( $_REQUEST['_wp_original_http_referer'] ), false );
return false;
}

**Comment by tmdesigned** [comment]
#2936

**Comment by richgar07** [comment]
Hi Taylor, Looks like you figured out a way. What is the process to set it up? I have tried:
Hidden Feild > Name: Get Referrer, Slug: get_referrer, Value: {get:referrer_url}
Hidden Feild > Name: Get Referrer, Slug: get_referrer, Value: {referrer_url}
Hidden Feild > Name: Get Referrer, Slug: get_referrer, Value: referrer_url
UTM Feild > Name: Get referral url, Slug: get_referral_url, Value: referrer_url

**Comment by richgar07** [comment]
Thank you so much for putting that request in!

**Comment by Shelob9** [comment]
The PR looks good. We have put this on the 1.8.1 branch and will do final test/ merge after 1.8.0 issues are cleared.

**Comment by richgar07** [comment]
Fantastic! You guys rock! If it works I think this will be a great simple addition.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/d5d9a6255b09fda05c663f7e7b0dd1285c310baf
