### ISSUE TITLE
CSV exported from entry viewer has JSON encoded options for checkbox fields

### ISSUE THREAD

**Issue by evolluti0n** [CalderaWP/Caldera-Forms#2895]
## Do You Need Immediate Help?
Ticket opened:
https://secure.helpscout.net/conversation/747675939/17690?folderId=2372292

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version 5.0.2-de_DE
PHP Version 7.3
Caldera Forms Version 1.7.5.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
I have a checkbox type field in a form. The field is exported as a coma separated list which is then repreated with {"opt ....}. See this example:

Winterball am 26.12.2019, 1 .Skitag fÃ¼r Frauen am 5.01.2019, Curling fÃ¼r Erwachsene am 12.01.2019, 1. Skitag fÃ¼r MÃ¤nner am 19.01.2019, 1. Gleitschirm-Tandemflug-Tag am 26.01.2018, Renntraining fÃ¼r Erwachsene am 2.02.2019, Clubabend am 9.02.2019, {"opt2017242":"Winterball am 26.12.2019","opt1302036":"1 .Skitag f\u00fcr Frauen am 5.01.2019","opt1156424":"Curling f\u00fcr Erwachsene am 12.01.2019","opt2001886":"1. Skitag f\u00fcr M\u00e4nner am 19.01.2019","opt1430941":"1. Gleitschirm-Tandemflug-Tag am 26.01.2018","opt1087773":"Renntraining f\u00fcr Erwachsene am 2.02.2019","opt1102332":"Clubabend am 9.02.2019"}

Is this a bug or is a normal behavior?

**Comment by Shelob9** [comment]
@New0 I am adding this to 1.8.0 as I know what's wrong and its important to get fixed.

**Comment by Shelob9** [comment]
Related(ish) #1032 #2078 #374 #173

**Comment by Shelob9** [comment]
Should be resolved via 
6fb6bc8 when #2919 is merged

**Comment by Shelob9** [comment]
I updated the title to avoid the confusion noted here: https://github.com/CalderaWP/Caldera-Forms/issues/2895

**Comment by New0** [comment]
Closed via [`27e20f2`](/CalderaWP/Caldera-Forms/commit/27e20f20399d31d7dfc240478e24e5d432691d11)
