### ISSUE TITLE
Add 'disabled' attribute for Checkbox, Dropdown, and Autocomplete field types

### ISSUE THREAD

**Issue by mecachisenros** [CalderaWP/Caldera-Forms#2904]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
Yes.

The Radio field type has the very useful `disabled` attribute which allows options to be disabled through Caldera Forms filter hooks like `caldera_forms_render_get_field`, the Checkbox, Dropdown, and Autocomplete field types lack the `disabled` attribute.

This is a request to add the `disabled` attribute to the mentioned field types.

### Example and use case
Both options for the Radio field **Event 1** are disabled (filtered through `caldera_forms_render_get_field` ) based on an external condition (in this case is an Event registration integrated with CiviCRM), the Option 2 option for the Event 2 fields (Checkbox, Autocomplete, and Dropdown) are disabled based on an external condition (in this case that option is Sold out).

#### Before
There's no possibility to achieve this with Checkbox, Dropdown, and Autocomplete field types.

#### After
It is possible to disable field options for the mentioned field types.

![disable_field_options](https://user-images.githubusercontent.com/3038096/51115818-371a1180-1801-11e9-9619-32e91a63f99a.gif)

**Comment by Shelob9** [comment]
PR #2905 should resolve this.

**Comment by New0** [comment]
Closed via 
 [`46141dc`](/CalderaWP/Caldera-Forms/commit/46141dc3329ad755f0583de968bf87878eff1b16)
