### ISSUE TITLE
CF2 File Field sets a static CSS ID for cf2-list-files

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2906]
This is an issue when there are multiple file fields on the form or page.

I think it was set to answer to the aria-controls attribute of the button element.

I suggest making it variable by adding the field ID to the UL ID ( like cf2-listfile-{field-id} )

**Comment by Shelob9** [comment]
@New0 The the component should have `fieldIdAttr` as a prop or something like that, so `cf2-listfile-${fieldIdAttr}`

**Comment by Shelob9** [comment]
close via 

6258d32 #2937
