### ISSUE TITLE
Show in Entry List on by default?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#291]
Hey

Most of the fields will be added to the entry list.
To me it seems more natural to have it checked (on) by default. 
For the fields one does not need an entry to then one can uncheck (turn it off). 
There can also be some logic built in for specific fields that are more likely not be be added to the entry list. Then it can be off by default.

**Comment by paaljoachim** [comment]
I am bumping this issue. It is too easy for customers to forget to click the add to entry list checkbox. It would be natural to have it already turned on.

**Comment by Desertsnowman** [comment]
I disagree with this. On the other side, if someone makes a form with a few hundred fields and doesn't look to uncheck the option, the entry list will be impossible to manage. Then have to unchecked each one.

**Comment by paaljoachim** [comment]
This means...
If we look at this from the view point of a customer having a form with lets say max 10 fields.
Then it seems natural to have it on.

Then look at it from the view point of a big company having a form that has 50-60 fields.
Then it seems natural to have it off.

Perhaps this means creating a settings page that effect all the forms and entries. Where one can turn on and off certain default aspects. Leaving it up to the user to define how they want it.
