### ISSUE TITLE
When advancing pages via breadcrumbs - empty fields are validated, preventing advancing

### ISSUE THREAD

**Issue by jeroenrotty** [CalderaWP/Caldera-Forms#2911]
## Do You Need Immediate Help? 
**no**

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Latest and latest 7.2, tried through Local by Flywheel too.

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
**Yes.**

## What Is The Unexpected Behaviour?
Can't click to next page when clicking on the **breadcrumbs** link, does work when clicking on a 'next page' button.

**Comment by Shelob9** [comment]
@swapnilmanjrekar Can you please test this with a multi-page form? If you can reproduce the issue, please send me the form export you created.

**Comment by swapnilmanjrekar** [comment]
**I checked this bug using the following steps:**

- I created a  WordPress test site on my desktop locally using Lando.
- I installed CF plugin on my test site.
- Using the CF plugin, I created a blank form.
- I added a Name Field, Phone number field & Email field & Next button on first page.
- I added one more page to my form with Message (Text) Field & Added Next button.


- I added one more page to my form with a star rating field and submit button.
- In the Pages setting section of my form, I checked Progress Bar with Show Breadcrumbs option.
- I saved and loaded the created form.
- I clicked on the next page button it was going on 2nd page .
- Similarly, when I clicked the next page button on the 2nd page it was going to 3rd Page.
- But When I tried to click on the Breadcrumbs option of 2/3, I was not able to go to next page even after clicking multiple times which I expected to go to 2nd or 3rd page on clicking 2 & 3 option.


**Javascript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.


**PHP Errors:**

- When I checked the debug.log file of my WordPress test site I did not see any PHP errors.



- **So according to my testing & findings, I think this is  a bug as I was not able to go to the next page through even after clicking the 2nd &3rd Page.**


WordPress Version: 5.0.3PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.7.6WP_DEBUG: 1

[multipage-form-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/2784331/multipage-form-export.json.zip)

**Comment by Shelob9** [comment]
@swapnilmanjrekar  I can not unzip that form. Can you send it the JSON to me in Slack please?

I tried the form that @Wilfried1954 posted. 

Correct behaviour with this form would be:
* If email field is not filled in, you can not advance to page 2.
* If email field is filled in with valid email, and the other fields are empty, you can advance to page 2.

If I fill in all three fields with valid values, then I can advance to page 2. If I only fill in the email field, which is required  and click page 2, I see validation errors under the other 2 pages.

I am renaming the issue to reflect the root cause: empty fields are being evaluated when advancing via breadcrumbs.

**Comment by Shelob9** [comment]
PR #2928 should resolve this in 1.8.0

**Comment by New0** [comment]
> 
> 
> PR #2928 should resolve this in 1.8.0

Test created at https://app.ghostinspector.com/tests/5c4882684f812d73c7834e29

**Comment by Shelob9** [comment]
Close via 542d02e #2928

BTW @New0 it was my intent to have you fix this because I want to talk about refactoring multi-page form navigation in 1.9, or 1.10, but then I saw the quick fix. Let's make sure to discuss when we talk conditionals refactoe for 1.9.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 I am not able to reproduce this issue as I successfully able navigate through breadcrumbs and also tested for the following scenarios which were as per my expectations:

-   Empty, non-required fields do not validate.
-   Empty, required fields do validate.
-   Non-empty fields do validate.
- Validation errors blocks submission.

WordPress Version: 5.0.3PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0-beta.1WP_DEBUG: 1
