### ISSUE TITLE
Radio type field default value (i.e. checked) gets overridden when disabling its options  

### ISSUE THREAD

**Issue by mecachisenros** [CalderaWP/Caldera-Forms#2913]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
Yes.

When disabling (setting 'disabled' attribute value to `true`) on a Radio field's options (via `caldera_forms_render_get_field` or other filters), its default value (`checked` attribute) is forced to `false`. This can cause various issues when viewing or editing an entry, or when providing a default value, and other fields have conditionals based on the Radio field's value.

Disabled fields/options are [never submitted](https://www.w3.org/TR/html401/interact/forms.html#disabled) in a form so for me it doesn’t make sense to force its value.

My suggestion is to remove the forced `checked` value.

**Comment by New0** [comment]
Closed via 
[`ff2a14d`](/CalderaWP/Caldera-Forms/commit/ff2a14d2214239bc80782125d88181ae7a2b7504)
