### ISSUE TITLE
[WORKAROUND IN COMMENTS] PDFs are not attaching to emails sent via pro with 1.7.6

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2917]
Reported here: https://secure.helpscout.net/conversation/755755867/17945/

**Comment by Shelob9** [comment]
I tested with build from master on a live site and I did not get a PDF attached to the email.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 I am able to receive emails with pdf attached on CF 1.7.5.1 with Caldera Forms Pro active when Tested on pantheon sandbox site.
