### ISSUE TITLE
Caldera Forms Plugin Blocking WP-Admin Login, HTTP 500 Error

### ISSUE THREAD

**Issue by laurenmb** [CalderaWP/Caldera-Forms#2918]
For the last few days, the Caldera Forms plugin has been blocking me from logging into our company Wordpress website. I can get to the login page but after entering my credentials and submitting, it displays an HTTP 500 error page.

I reached out to Flywheel who hosts our site, and after their troubleshooting they found it was the Caldera Forms plugin causing the problem. Here is what they said in their email back to me:

"Thanks for reaching out, happy to help with this one.
The login page is working after disabling the caldera-forms plugin. It's strange that it's not giving a PHP error.
The site is currently on PHP 5.6 and WordPress 4.9.9. You can try reaching out to the plugin developer and find out if there's a resolution.
Hope this helps. Please let us know if you have more questions."

I can't leave the plugin disabled as our main contact form is built on it, so I have had to enable it again and sacrifice being able to log into our site for now.

**Comment by Shelob9** [comment]
Please see: #2896
