### ISSUE TITLE
Wide entry list bug

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#292]
Having a lot of entry list fields then scrolling to the right pushes the left Form column under the black left sidebar. It also pushes the left sidebar links to the left out of the screen. Actually a pretty interesting bug. It also goes past the white space box on the right side.

![skjermbilde 2015-10-22 kl 11 09 53 p m](https://cloud.githubusercontent.com/assets/5323259/10683665/6ba5f428-7912-11e5-86c3-6865729166c1.png)

![skjermbilde 2015-10-22 kl 11 15 38 p m](https://cloud.githubusercontent.com/assets/5323259/10683717/decadc3e-7912-11e5-93e0-587d5758c30f.png)

**Comment by Shelob9** [comment]
Fixed via #627
