### ISSUE TITLE
Grunt concatenation and minification seems incomplete

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2922]
PRs #2916 and #2921 show that Grunt process breaks CF2 conditional result.

**Comment by New0** [comment]
Concatenating ajax-core and conditionals into caldera-forms-front.js fixes the issue.

This means when $should_minify os True we enqueue only caldera-forms-front.min.js instead of the three files ( caldera-forms-front.min.js, ajax-core.min.js and conditionals.min.js ).

**Comment by Shelob9** [comment]
Close via 23dc378   #2923
