### ISSUE TITLE
Country drop down?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#293]
It would be nice to add in a country drop down field.

**Comment by gmedhouse** [comment]
I would love this too please

**Comment by web506** [comment]
I agree, very much needed Josh, please!

**Comment by paaljoachim** [comment]
@Shelob9 Can you assign this to one of the milestones?

**Comment by web506** [comment]
Wait, I found it @paaljoachim 

![image](https://cloud.githubusercontent.com/assets/3137216/26752873/9263dd88-4827-11e7-8b68-fa09af77ec9c.png)

Go to select, the click the bulk button option

**Comment by paaljoachim** [comment]
That is great! We can then close this issue.

**Comment by quakeboy** [comment]
Guys, unbelievable that the developers thought about adding this.
But its in the wrong place. I wouldn't have figured it out unless I googled and found this page.

Caldera Forms needs to be marketed better, your product is a class above other ones.
