### ISSUE TITLE
Errors for too large of a file are insufficent

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2932]
File size limitation is added in #2823 to fix #1399 

A file that is too large should be rejected in the client when its added.

It is already rejected server side resulting in an error response here -- https://github.com/CalderaWP/Caldera-Forms/blob/develop/cf2/RestApi/File/CreateFile.php#L126-L134

Let's make sure that if a file is added to a field that is too large -- an error is shown on the field and the offending item in the list is highlighted in red and the form can't be submitted until its removed. It's tempting to say it should just not add that file, but then a user might add a file, see it didn't get added, add it again, see it didn't get added and get annoyed. They should see what is wrong clearly.

Let's make sure if file upload fails, it opens that notice and stops form submission -- second part is already covered. 
https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/ajax-core.js#L82

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/a3cd7f6ef69534db8b2ddca1107bb8bf065f4ade
