### ISSUE TITLE
Files not getting attached in File Fields v2.0 when using with Caldera Forms Pro

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2942]
## Do You Need Immediate Help?
* No

## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.0.3PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0-beta.1WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is The Unexpected Behaviour?
* For a form with one 1 file field v2.0 when I attach a file in the field and click on submit button, the form is not getting submitted and also I didn't receive an email in my MailHog mailbox. Currently, I tested this only on Chrome & Firefox Browsers.

## What PHP Errors Have You Logged While Reproducing This Bug?
*  None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* When I checked the console of my browser it gave me the following error: "caldera-forms-front.min.js?ver=1.8.0-beta.1:1 Uncaught TypeError: Cannot read property 'data' of undefined”

**Comment by Shelob9** [comment]
@swapnilmanjrekar Thank you for the report -

>`When I checked the console of my browser it gave me the following error: "caldera-forms-front.min.js?ver=1.8.0-beta.1:1 Uncaught TypeError: Cannot read property 'data' of undefined”`
This would indicate that the returned HTTP response was malformed. Can you please test again with the network inspector open and show us what the results for uploading file and submitting form are?

> the form is not getting submitted and also I didn't receive an email in my MailHog mailbox.
When testing with CF Pro, you should NOT expect for MailHog to have a record of the email. If you have CF Pro and the email shows up in MailHog, that would be a bug. The email will be sent via CF Pro, send it to your work email to test.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 Removing MailHog from the lando.yml file of my local WordPress site solved this issue but my emails are not working. So I am opening an issue for it.

**Comment by Shelob9** [comment]
@swapnilmanjrekar what is the difference between this issue and  #2942 ?

>Removing MailHog from the lando.yml file of my local WordPress site solved this issue 
What issue did this solve?

I would recommend leaving mailhog in your lando.yml config BTW. You need that for testing emails without CF Pro and having it installed as no effect on CF Pro functionality.

**Comment by swapnilmanjrekar** [comment]
@Shelob9 Files were not getting attached in File Fields v2.0 when using with Caldera Forms Pro for this issue and after removing MailHog from the lando.yml file, the file was getting uploaded, the form was getting successfully submitted and the attached file was also uploaded to media library but I was not receiving info for my submitted form. So I opened a separate Issue for it as #2943
