### ISSUE TITLE
The file list under advanced file field v2 is VERY different from v1

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2950]
I have reviewed the file fields more throughly and I think that there are too many difference in v1 vs v2 fields and the differences are likely to cause confusion, so I am considering this issue to be a blocker.

This is a v1 and a v2 file field next to each other:
![screen shot 2019-01-29 at 2 53 18 pm](https://user-images.githubusercontent.com/1994311/51936211-a84aee80-23d5-11e9-9888-de67b887713a.png)

I think the one on the right looks better. The markup we have now is more semantic, but it does not look as good. Let's keep the same HTML markup if possible.

- [ ] Make the list of files in the field use the same typography and font/icon sizes as v1. 

 This screenshot I enabled image preview for the v2 field on the right, after adding a file to the v1 field on the right, I used the inspector to replace the name of the file with the image preview. Looks better. 

![screen shot 2019-01-29 at 2 57 24 pm](https://user-images.githubusercontent.com/1994311/51936621-9ddd2480-23d6-11e9-9b9e-2a5c7a6d5ac3.png)

- [ ] When using image preview, replace image name with image preview.

Also, v1 file fields list file size in kB, MB or GB. v2 fields are using bytes, which is confusing.

- [ ] File size should be listed in kB, MB or GB.

When you submit a form with a v1 file in it, you get a little progress bar that indicates that something is happening. With v2 there is no visual indication. This is likely to lead to multiple submissions as people will just click submit until it looks like something happened.

- [ ] File fields should show a progress indicator when uploading.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/a27a239bb1854e80711705f624460a1df265c73c
