### ISSUE TITLE
Civicrm in create same record are marge

### ISSUE THREAD

**Issue by Rohansystem** [CalderaWP/Caldera-Forms#2961]
We are using CiviCRM to create a new contact and generate a case. http://prntscr.com/mfjt7e

We have submitted the caldera form after we have got two entries, one for caldera form and second for CiviCRM. But in which the CiviCRM get that issue for the same email ID's two entry. http://prntscr.com/mfjvzn   

1)You can see the case and contact. http://prntscr.com/mfk7hx
2)User register. http://prntscr.com/mfk7xh

May I know How to marge that same email ID's record? Please answer as much as earlier possible.
Thank You.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We are not the authors of the Caldera Forms CiviCRM add-on.  Please open an issue https://github.com/mecachisenros/caldera-forms-civicrm/issues if you have an issue.
