### ISSUE TITLE
Unhide cf2 field creates error

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2964]
Ghost inspector test https://app.ghostinspector.com/tests/5c3882b70b45715fbf380071 is failing after showing `"Warning: Failed prop type: Invalid prop `field.fieldValue` supplied to `CalderaFormsFieldRender`.\n in CalderaFormsFieldRender (created by CalderaFormsRender)\n in CalderaFormsRender"`

**Comment by Shelob9** [comment]
Close via f5c5a8f #2965
