### ISSUE TITLE
When two same forms are inserted in a page, the cf2 fields rendered have duplicated behavior

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2972]
In the case that we insert twice the same form in a page, same CF2 field are rendered twice and their state are mixed.
The value and the error messages will be shared.

**Comment by Shelob9** [comment]
I can not reproduce this  🤷‍♂️ 

Two of the same form field allows multiples and only png.

I added one file, I have the state for the form that does not have the fiel field in it open:
![screen shot 2019-02-07 at 5 24 26 pm](https://user-images.githubusercontent.com/1994311/52447011-9667fa80-2afd-11e9-9af3-1fe1002bb6a1.png)

I added an invalid file type to the top form, bottom form state shows that field was never focused:
![screen shot 2019-02-07 at 5 25 04 pm](https://user-images.githubusercontent.com/1994311/52447079-bbf50400-2afd-11e9-8a82-a02e3f72a274.png)

Then I added a file to bottom form and it was in that form's state and not the other one:
![screen shot 2019-02-07 at 5 25 28 pm](https://user-images.githubusercontent.com/1994311/52447108-d4651e80-2afd-11e9-9e81-4f49a47d2394.png)

**Comment by New0** [comment]
Thank you for the research. I realized this happened during Submission. For example insert twice the same form that has a required CF2 File field, click the submit button of one form without loading a fie and the error message appears in both forms.
Your research allowed me to open a PR to fix that ->#2974

**Comment by New0** [comment]
Closed via [`7e3ac08`](/CalderaWP/Caldera-Forms/commit/7e3ac08c12b436e12a648208ad92d999d876fd65)
