### ISSUE TITLE
How to export all caldera forms data in a efficient way?

### ISSUE THREAD

**Issue by lucashfreitas** [CalderaWP/Caldera-Forms#2977]
Hello,

I have more than 8 forms on my WordPress website using caldera forms. I want to keep all these forms in wordpress but also I want to export all forms data to an external database, where I will be able to generate some statistics and collect some information. 

How can I export all form information to an external database? Caldera forms allow us to export form entries in wp-admin console, but this is not quite efficient,  because I will have to access every form and then export each data individually and then read all the data from CSV files and import that to the database. 

 I've tried some solutions: 

**1 - Post form data to external API changing submission URL:** I could do that, but this will not solve my problem as I want to form data be also stored in wordress as well. **Q:** How can I post form data for 2 different URLS? 

**2- Read form information from database**: I tried to get all form entries from database but I have another issue. All forms entries are stored in mysql database, in tables: **ms_cf_form_entries** and **ms_cf_form_entries_values**. But I can not get the information about forms because they are stored using **transients** as I read in the code. 

Anyone know any alternative that I can try?

**Comment by ahinerfeld** [comment]
I use a plugin called [WPDataTables](https://wpdatatables.com/) to present the data in a very usable format.  The plugin pulls the data from the database and allow you so filter and sort the data anyway that you would like.  The one thing that I find that is difficult is that all entries from CalderaForms is stored within a single data table.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I'm going to close this out as it is a support request, not an issue related to development. You can request support here: https://calderaforms.com/support

If you want to create a WPDataTables integration I would start by reading these pages:
* https://calderaforms.com/doc/get-entries-from-a-form/
* https://calderaforms.com/doc/using-caldera-forms-paginated-queries/
