### ISSUE TITLE
No option to change CSV delimiter/separator

### ISSUE THREAD

**Issue by stblink** [CalderaWP/Caldera-Forms#2983]
I've searched and can't find way to change the CSV delimiter.
Currently is set to a comma (,).

How can i change to a pipe or ;?

I'm asking this because i have an html field where users can insert a comma. When converting text to columns in Excel setting the comma as separator, all breaks.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I think this is an issue with your site as having commas in a column value of a CSV works just fine, if encoding is correct. I suspect you have the wrong character encoding set.

Take a look at the caldera_forms_csv_character_encoding and if you're need help, open a support ticket. I'm sure the support team can help!
