### ISSUE TITLE
Translating Success Message via Filter

### ISSUE THREAD

**Issue by black-eye** [CalderaWP/Caldera-Forms#2984]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.9PHP Version: 7.2.8-1+0~20180725113345.2+jessie~1.gbp571e56MySQL Version: 5.5.60Caldera Forms Version: 1.7.6WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Havent try, but I suppose so

## What Is The Unexpected Behaviour?
I have tried to translate the success message via filter `caldera_forms_get_form`, but it doesn't seem to work. The message stays the same and when I echo `$language` it shows the default language.

The similar approach on translating the form fields via `caldera_forms_render_get_field` works just fine.

Am I missing something? Here is my code:

`add_filter( 'caldera_forms_get_form', function( $form, $id  )  {

	if ( 'CF5c6490cb852cf' == $id ) {
		$language = pll_current_language();

		if ( $language == 'en' ) {
			$form[ 'success' ] = 'Your RE-PORT is on the way!';
		}
	}
    return $form;
}, 10, 2);`

Thanks

## What PHP Errors Have You Logged While Reproducing This Bug?
No

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
@black-eye that is not the correct filter to modify form configuration. I think caldera_forms_render_get_form or something similar -- check the docs or open a support ticket if you need more specific advice.

I'm going to close this as it is not related to any bugs/ features.

**Comment by black-eye** [comment]
@Shelob9 thanks for your reply. Yes, `caldera_forms_render_get_form` seems to be a better choice. 

But I'm affraid I might come across some kind of bug...

Here is the test page: 
http://demo.remedical.cz/en/what-we-offer/legislation-monitoring/medical-devices/

Here is my code:

```
add_filter( 'caldera_forms_render_get_form', function( $form  )  {
	$language = pll_current_language();
	if ( $language == 'en' ) {
		$form[ 'success' ] = 'Your RE-PORT is on the way!';
		print_r($form[ 'success' ]);
	}
    return $form;
}, 10, 1);
```
Here is the success message:
![obrazek](https://user-images.githubusercontent.com/5634870/52856371-85823f00-3124-11e9-8330-dffb322dfd5d.png)

I echoed the content of `$form[ 'success' ]` and it seems to be updated correctly. But unfortunatelly is not taken into account when outputing the success message. Or am I using the wrong variable? It doesn't seem so, before the change it showed the original success message.

Thanks again
