### ISSUE TITLE
GI tests for 1.8.0 failures in calculations suite

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2998]
Three tests are failing in suite https://app.ghostinspector.com/suites/59d8091baea70072f47c435b

No logs in the failing tests or the debug.log file.

My first manual test on form 1962-calculations-created1-5-5-dev1-5-6-2 shows that when I replace the form that creates the formula by a manual formula, the calculation works.

**Comment by Shelob9** [comment]
Close via #3007
