### ISSUE TITLE
Adv File Field v1 do not upload

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3000]
If a form has the version 1 advanced file field, the file upload does not route correctly and form submission does not complete.

class `Caldera_Forms` L3571, it returns for reasons I don't get. I think that is the issue.

<img width="1154" alt="screen shot 2019-02-19 at 8 46 56 pm" src="https://user-images.githubusercontent.com/1994311/53060183-8cdc7c00-3487-11e9-91e1-11aaf11702c1.png">

**Comment by New0** [comment]
Closed via #3001
