### ISSUE TITLE
On upgrade Clear old CRON jobs from transients API

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3004]
Select all options LIKE `cftransdata_`.

Then for each. get the id and clear hook with that argument 
https://developer.wordpress.org/reference/functions/wp_clear_scheduled_hook/

**Comment by New0** [comment]
Closed via [`87c3873`](/CalderaWP/Caldera-Forms/commit/87c38730fadadd2660fdafaf3261770aede70d3c)
