### ISSUE TITLE
Cannot See Image Preview after Attaching image in Advanced File Fields Version 2.0

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#3013]
## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.0.3PHP Version: 7.2.15MySQL Version: 5.5.5Caldera Forms Version: 1.8.0-rc.1WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is Unexpected Behaviour?
*  Steps to Reproduce this bug are as follow:

* I created a  WordPress test site on my desktop locally using Lando.
* I installed CF plugin on my test site.
* I upgraded my CF plugin from 1.7.6 to CF 1.8.0 beta 2
* I created a contact form from the available form templates.
* In my contact form I added an Advanced File Field v2.0 Field.
* Then for the added Advanced File Field v2.0, I checked the image preview option in the field setting.
* I then saved and loaded my created form.
* I attached an image in my advanced file field v2.0 and I expected to see the image in my advance file field version 2.0 
* I was not able to see the preview of the image attached in Advanced File Field V2.0 of my form and it was not as per expectations as I checked the image preview option in my advance file field v2.0 field setting.
* Now in the Advanced File Field V2.0 setting of my form, under the image preview I set Image preview width as "48" and Height as "48" and saved my form.
* I loaded my saved form.
* I again attached an image in my advance file field v2.0 field of my form and I was not able to see to preview the image as I expected to see it.

## What PHP Errors Have You Logged While Reproducing This Bug?
* When I checked the debug.log file for my WordPress Test Site, I didn't see any PHP errors.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* When I checked the console of my browser I didn't see any JavaScript errors.

**Comment by st3phan76** [comment]
Hi, 
if I'm right, there is no preview in this field-type ...

**Comment by Shelob9** [comment]
@st3phan76 this related to the new file fields in Caldera Forms 1.8.0, which do support this.

**Comment by Shelob9** [comment]
I was unable to reproduce this issue. @swapnilmanjrekar Please include steps to reproduce.

I created a form with a file field and enabled image preview:
![screen shot 2019-02-22 at 11 13 55 am](https://user-images.githubusercontent.com/1994311/53255106-ff6d7780-3692-11e9-8d93-f49ab52e8b7e.png)

When I add a PNG file, I see the image preview.

**Comment by New0** [comment]
@swapnilmanjrekar The preview is only for image type of files, was the test loading image files ? ( .png, .jpg...)

@Shelob9 This could be a point worth mentioning on the option, preview being for images file types only

**Comment by swapnilmanjrekar** [comment]
@Shelob9  @New0 I am not able to reproduce this issue now.
  * I created a  WordPress test site on my desktop locally using Lando.
* I installed CF plugin on my test site.
* I upgraded my CF plugin from 1.7.6 to CF 1.8.0-rc.2
* I created a contact form from the available form templates.
* In my contact form I added an Advanced File Field v2.0 Field.
* Then for the added Advanced File Field v2.0, I checked the image preview option in the field setting.
* I then saved and loaded my created form.
* I attached an image in my advanced file field v2.0 and I expected to see the image in my advance file field version 2.0 
* I was able to see the preview of the image attached in Advanced File Field V2.0 of my form and it was as per my expectations as I checked the image preview option in my advance file field v2.0 field setting.
* Now in the Advanced File Field V2.0 setting of my form, under the image preview I set Image preview width as "48" and Height as "48" and saved my form.
* I loaded my saved form.
* I again attached an image in my advance file field v2.0 field of my form and I was  able to see to preview the image as I expected to see it.
![a form with new advance file fields version 2 0 field with image preview option checked in field setting](https://user-images.githubusercontent.com/43219826/53421017-e292b600-39aa-11e9-820d-c3f90c59f478.PNG)

* When I checked the debug.log file of my local WordPress Lando Test Site I didn't see any PHP errors.
* Similarly When I checked the console of my browser I didn't see any JavaScript errors.





WordPress Version: 5.1PHP Version: 7.2.15MySQL Version: 5.5.5Caldera Forms Version: 1.8.0-rc.2WP_DEBUG:

**Comment by New0** [comment]
Thank you @swapnilmanjrekar
