### ISSUE TITLE
Render client is loaded on forms without cf2 fields

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3016]
This is an extra HTTP request/ opportunity for things to go wrong that we do not need.

**Comment by Shelob9** [comment]
@New0  I think we should close this without fixing for two reasons.

1) I did and that prevents it from loading when not needed, but it also breaks submission, because window.cf2 is not set. So I started messing with ajax-core.js, but that's touching the hardest to test part of what we did and that makes no sense to do last minute. This is how stupid bugs happen.
2) I want to get rid of ajax-core/state.js/conditionals.js ASAP and add more cf2 fields. So, this file is always going to be needed and caldera-forms-front.js is going to shrink.

Please either disagree with me or close this issue.

**Comment by New0** [comment]
@Shelob9 I agree to close the issue
