### ISSUE TITLE
Editing entires in Number Field with value of 0 returns a blank field

### ISSUE THREAD

**Issue by stonge85** [CalderaWP/Caldera-Forms#3024]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by stonge85** [comment]
When editing a number field entry that is set to 0, the entry form does not populate; meaning the field is blank.  If this is a required field, the entry will not save until the field is repopulated.

**Comment by stonge85** [comment]
This issue has been open for over a year.  How do we get this on the roadmap to get it resolved.

**Comment by Shelob9** [comment]
Added tests in  f692ea7

Bug is most likely introduced here: https://github.com/CalderaWP/Caldera-Forms/commit/f14ec7412a9ca79db0e52c1a10ea535e2ad7ef00#diff-f81f3dff36bf04b7a070d642c858e883

**Comment by Shelob9** [comment]
Here, we're checking if saved value is empty, whioch `'0'` and `0` are.

https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/field/input.php#L21

**Comment by Shelob9** [comment]
Should be fixed via #3471

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/d19d7d9f38352468e2f612c9d26f48f34ebbd31d -
