### ISSUE TITLE
Range Slider field displays Field Id Attr instead of value

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3043]
Since update to 1.8.0 the Range slider field seems to display the Field Id Attr when it should display the Value, this does not have consequences on calculations

![screenshot_2019-03-04 form - dev](https://user-images.githubusercontent.com/16348693/53731262-77e5ec80-3e7a-11e9-99e4-4eadbace6ed1.png)

**Comment by Shelob9** [comment]
Probably a duplicate. See: https://github.com/CalderaWP/Caldera-Forms/issues/3040#issuecomment-470183962
