### ISSUE TITLE
Check Title attribute in Consent field

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3044]
Hello @iamntz , thank you for opening that PR #3041 , could we make sure it addresses your issue ?

The condition you edited ( l11 of fields/gdpr/field.php ) works as expected for me. We display the title attribute set in the field options if it is set, otherwise we display a preset string of text as title attribute for the link.
Could you share the php warning you mentioned in the PR ?

**Comment by iamntz** [comment]
Is a php notice of undefined title...

The gdpr field didn't always had the option of a custom Title => forms saved before this custom title will don't have this field available => notice is thrown.

The title was added in july, but all forms saved pre-july will have this issue

https://github.com/CalderaWP/Caldera-Forms/commit/994b225adf34f9f2c77e6363763cf4ed9d47b5e0#diff-92e43c2d984669a28cd468d081414406

**Comment by New0** [comment]
Thank you for the details, we'll merge the PR in 1.8.2

**Comment by New0** [comment]
Closed via abc515b
