### ISSUE TITLE
File upload V2 not working

### ISSUE THREAD

**Issue by WimSchol** [CalderaWP/Caldera-Forms#3046]
## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template. No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

Korte debug informatie

    WordPress Version: 5.1PHP Version: 7.2.15MySQL Version: 5.5.5Caldera Forms Version: 1.8.1WP_DEBUG: 

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

If one file selected in the form this is uploaded and send attatched in the mail, if more then one files are selected mail is send but without any attached files...

## What PHP Errors Have You Logged While Reproducing This Bug? 
There are no PHP errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No JavaScript errors

**Comment by New0** [comment]
Hello @WimSchol , thank you for opening that issue. Just to be more specific, can you confirm thatthe uploads to the media library are working and the issue is related to email attachments ? 

I could reproduce an issue with email attachments, when one file is loaded via the field, it is attached but none are attached when multiple files are loaded.
The files upload to the media library worked as expected during my tests.

**Comment by WimSchol** [comment]
Hi Nicolas
I confirm that in all cases files are stored in the media libary. In case of zending one file andere in case of sending multiple. In case of multiple the files are not attached to the mail.
Greetz Wim

Op 6 mrt. 2019 16:27 schreef Nicolas Figueira <notifications@github.com>:

Hello @WimSchol<https://github.com/WimSchol> , thank you for opening that issue. Just to be more specific, can you confirm thatthe uploads to the media library are working and the issue is related to email attachments ?

I could reproduce an issue with email attachments, when one file is loaded via the field, it is attached but none are attached when multiple files are loaded.
The files upload to the media library worked as expected during my tests.

**Comment by vaka2vaka** [comment]
File Uploader (2.0)
Checked on two sites Changed themes. The error remains. When adding the "Advanced File Uploader (2.0)" field
Files pass Letter is sent

index.min.js?ver=1.8.2:30 Uncaught TypeError: Cannot read property ‘fields’ of undefined
at index.min.js?ver=1.8.2:30
at NodeList.forEach (<anonymous>)
at HTMLDocument.<anonymous> (index.min.js?ver=1.8.2:30)
at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
at Object.trigger (jquery.js?ver=1.12.4:3)
at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
at HTMLDocument.<anonymous> (jquery.js?ver=1.12.4:3)
at Function.each (jquery.js?ver=1.12.4:2)
at a.fn.init.each (jquery.js?ver=1.12.4:2)
(anonymous) @ index.min.js?ver=1.8.2:30
(anonymous) @ index.min.js?ver=1.8.2:30
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
trigger @ jquery.js?ver=1.12.4:3
a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous) @ jquery.js?ver=1.12.4:3
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
trigger @ jquery.js?ver=1.12.4:3
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5
load (async)
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5

**Comment by Shelob9** [comment]
Close via #3074
