### ISSUE TITLE
BUG: Conditional Disable

### ISSUE THREAD

**Issue by amrartist2009** [CalderaWP/Caldera-Forms#3056]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms: 1.8.1
WP: 5.0.3
PHP: 7.2.6
Theme: Avada 5.8.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes - only plugin is Caldera Forms Free Version
Theme 2019

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
I created a form with conditionals.
Show and Hide conditionals work as expected.
Disable hides the fields and never conditionally shows them again. They're just gone.
I need them to be present and greyed out. This feature worked perfectly in Caldera Forms 1.7.6. I have actually rolled back the plugin to keep my client's forms as they previously existed.

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by holoeye-photonics** [comment]
The same issue is happening for us which is basically breaking a lot of our forms since the user is expected to enter values into the fields that are not disabled. IMHO this requires an immediate bugfix.

**Comment by Shelob9** [comment]
Should be fixed via #3063 

There is a test build there, I appreciate any feedback y'all can give: https://github.com/CalderaWP/Caldera-Forms/pull/3063#issuecomment-470674618

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/35c70d96d9cae04f4e10c14435a214338fef0112

**Comment by holoeye-photonics** [comment]
I updated to the latest version and added the fix. Seems to work fine. Thanks.
