### ISSUE TITLE
wp.data is accessed when not loaded in front-end in some cases.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3060]
In this comment @paaljoachim reports `Uncaught TypeError: Cannot read property 'data' of undefined`

https://github.com/CalderaWP/Caldera-Forms/pull/3052#issuecomment-470302118

I went to his site, expanded the built client and set a breakpoint on the error:

![screen shot 2019-03-07 at 7 16 34 am](https://user-images.githubusercontent.com/1994311/53956337-5b7bc700-40a9-11e9-80e8-06dc6ade486c.png)

Solution: enqueue wp-data

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/7ea64f27eb053e0966ce913146034aa4ff8e64b9
