### ISSUE TITLE
HTML error in admin screen

### ISSUE THREAD

**Issue by julienappert** [CalderaWP/Caldera-Forms#3064]
Hi,
I notice an HTML error in line 201 of classes/entry/ui.php : 
The "resend" button start with a `"<a>"` tag but end with a `"</button>"` tag.

Caldera Forms Version: 1.8.2

**Comment by New0** [comment]
Hello @julienappert , thank you for reporting that issue.

**Comment by Shelob9** [comment]
Close via #3110 
5e30fde
