### ISSUE TITLE
JavaScript error when submitting form when cf2 component not set.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3068]
Matt reports : `uncaught type error h.getAllFieldValues()`

https://imgur.com/sdxTIVG

I bet this is caused here: https://github.com/CalderaWP/Caldera-Forms/blob/master/clients/render/index.js#L71

#3049 ?

**Comment by Shelob9** [comment]
Should be fixed via  #3069

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/79b09d226cc4c7178041e2faefded2ebad0ccf44
