### ISSUE TITLE
Advanced File Uploader (2.0) - Hide Label option does not work

### ISSUE THREAD

**Issue by evolluti0n** [CalderaWP/Caldera-Forms#3071]
## Is This A Feature Request?
No. I think is a bug

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress: 5.1
PHP version: 7.3
Caldera Forms: 1.8.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The Hide Labe option for Advanced File Uploader (2.0) does not work. The field name is showed in the form preview or when the form is published

http://prntscr.com/mvixp4
http://prntscr.com/mviy12

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors at all

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors at all

**Comment by Shelob9** [comment]
Close via 5a9f549
