### ISSUE TITLE
New Form Save not Working

### ISSUE THREAD

**Issue by ananga2019** [CalderaWP/Caldera-Forms#3072]
The save form option on the form create is not giving success popup. I am using php 7.0 and caldera forms v1.8.2. The php error i am getting is this: PHP Notice:  WC_Cart::get_cart_url is <strong>deprecated</strong> since version 2.5! Use wc_get_cart_url instead. in /home/horizons/public_html/wp-includes/functions.php on line 3923

Your help is highly appreciated.
Regards,
Moses

**Comment by ananga2019** [comment]
My url: https://horizonsmarketing.co.ke

**Comment by kgabalesvideomaker** [comment]
Yes, this is still an issue.

**Comment by Shelob9** [comment]
We do not use the function that is triggering this notice. This must be caused by a WooCommerce add-on. If you have evidence that I am incorrect, please open a new issue with all of the requested information .

https://github.com/CalderaWP/Caldera-Forms/search?q=WC_Cart&unscoped_q=WC_Cart
