### ISSUE TITLE
Javascript to inititalize toggle switches is not included in any minfied builds

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3075]

**Comment by Shelob9** [comment]
A workaround for this issue is avaible here: https://github.com/CalderaWP/Caldera-Forms/issues/3042#issuecomment-469586767

**Comment by Shelob9** [comment]
Related #2470

**Comment by New0** [comment]
Should be closed via https://github.com/CalderaWP/Caldera-Forms/commit/9fd233943595d535a251b30bb4973cefe9791a02
