### ISSUE TITLE
Advanced File Uploader 2.0 problem

### ISSUE THREAD

**Issue by Cassiopea33** [CalderaWP/Caldera-Forms#3085]
Good day! I had a problem using Caldera Forms 1.8.2 plugin for WordPress 5.1
Problem with Advanced File Uploader 2.0. Pictures uploaded to the site do not come in an email. Pictures can be saved in the Word Press media library, but they are not attached to the email sent. I draw your attention to the fact that when using a standard boot loader which allows you to attach 1 file, this problem disappears. The file comes in the mail with the form.
I would like to be able to receive in the mail a lot of downloaded files from the form on the site
Thanks in advance for your reply.

**Comment by New0** [comment]
Hello @Cassiopea33 , thank you for reporting this issue. 
It had been reported in #3046 . We have worked on it and it will be fixed in next version

**Comment by New0** [comment]
Fixed via #3046
