### ISSUE TITLE
Advanced File Uploader not working/showing

### ISSUE THREAD

**Issue by dummykontotest** [CalderaWP/Caldera-Forms#3093]
Hi,

We are using Caldera Forms since January and we never had a problem with file upload. Since the new Advanced File Uploader 2.0 has been updated, we are not be see the file upload on our contact form. We would be grateful if you can help us in this regard.

Our Contact Form is here: https://www.3d-activation.de/information/kontakt/

**Comment by abpprkonsalting** [comment]
I have a similar issue. Not sure if that function worked ever because I'm fixing the site of a client, and as it's expected they don't know what to say. The form works fine and send the emails as long as I don't attach a file with File Uploader. The moment I do it, it stop working.

contact form: https://www.grpexecutivesearch.com/contacto/

**Comment by New0** [comment]
Hello @dummykontotest , @abpprkonsalting , 

Thank you for reporting the issue you are experiencing, I see that both forms on the link you shared have a File field working. I assume update to 1.8.3 solved your issue and will close the issue, feel free to open this again if you have the same issue.

**Comment by abpprkonsalting** [comment]
No, in my case upgrading to 1.8.3 solved nothing.
![Screen Shot 2019-03-20 at 1 33 50 PM](https://user-images.githubusercontent.com/32166875/54684559-f39b9680-4b14-11e9-97de-f11183f3baf2.png)

**Comment by Shelob9** [comment]
This issue is related to the advanced file v1. That field is deprecated. Upgrading those fields to the new type of file field is the recommended solution.

**Comment by pascale2018** [comment]
Hello guys,  I want to stop receiving emails. I unsuscribed but I still receive them. 
Please help me.
thank you
