### ISSUE TITLE
Editing drop down is reset on save back to default form

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#3105]
@Shelob9 

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.1.1PHP Version: 7.2.14MySQL Version: 5.7.24Caldera Forms Version: 1.8.3WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme? 
YES

## What Is The Unexpected Behaviour?
I edited an existing drop down. To where I added additional options. Upon save it removed the edit and went back to what it looked like before I began adding the additional options. 

## What JavaScript Errors Have You Seen While Reproducing This Bug?

I added an option to an existing drop down. 
Then right clicked and in inspect -> Console the following error is seen.

Failed to load resource: the server responded with a status of 404 ()
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.1.1:4 POST https://gaiatravel.no/wp-admin/admin.php?page=caldera-forms 404
send @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.1.1:4
ajax @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.1.1:4
request @ wp-baldrick-full.min.js?ver=1.8.3:2
c @ wp-baldrick-full.min.js?ver=1.8.3:2
(anonymous) @ wp-baldrick-full.min.js?ver=1.8.3:3
dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.1.1:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-position,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-c&load[]=ore,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.1.1:3

![Screen Shot 2019-03-20 at 08 17 13](https://user-images.githubusercontent.com/5323259/54665892-9d186300-4ae8-11e9-844a-b526480cf7a2.png)

Upon save and refresh of the page the additional drop down option is not saved and there is no error message seen:

![Screen Shot 2019-03-20 at 08 18 37](https://user-images.githubusercontent.com/5323259/54665996-e36dc200-4ae8-11e9-9b16-daed1e494564.png)

This means I am at the moment not able to edit an existing drop down to add additional options to it.

Using the WP rollback plugin. The question that comes to mind is how far back do I have to go in Caldera Forms version numbers before I am able to add the additional option to the drop down and have it remain? I will have to explore on a test site and see.

This looks like a similar older issue:
https://github.com/CalderaWP/Caldera-Forms/issues/480

**Comment by Shelob9** [comment]
@paaljoachim The request to save the form is being blocked by your server. This is an issue with your server, not Caldera Forms. It could be a security plugin.

**Comment by paaljoachim** [comment]
Great!
I asked the web host and they checked Mod_Security in cPanel and it had blocked something in the contact form so that I was not able to edit the form. So this is good to know about.
