### ISSUE TITLE
Error in version 1.8.3: ru_RU not available in the catalog

### ISSUE THREAD

**Issue by vaka2vaka** [CalderaWP/Caldera-Forms#3106]
parsley.min.js?ver=1.8.3:2 Uncaught Error: ru_RU is not available in the catalog
    at m.setLocale (parsley.min.js?ver=1.8.3:2)
    at i.window.Parsley.(anonymous function) [as setLocale] (http://...............................ru/wp-content/plugins/caldera-forms/assets/build/js/parsley.min.js?ver=1.8.3:3:15735)
    at zhalyuzi-plisse:1420
setLocale @ parsley.min.js?ver=1.8.3:2
window.Parsley.(anonymous function) @ parsley.min.js?ver=1.8.3:3
(anonymous) @ zhalyuzi-plisse:1420
parsley.min.js?ver=1.8.3:2 Uncaught Error: ru_RU is not available in the catalog
    at m.setLocale (parsley.min.js?ver=1.8.3:2)
    at i.window.Parsley.(anonymous function) [as setLocale] (http:// ...............................ru/wp-content/plugins/caldera-forms/assets/build/js/parsley.min.js?ver=1.8.3:3:15735)
    at zhalyuzi-plisse:1439
setLocale @ parsley.min.js?ver=1.8.3:2
window.Parsley.(anonymous function) @ parsley.min.js?ver=1.8.3:3
(anonymous) @ zhalyuzi-plisse:1439
parsley.min.js?ver=1.8.3:2 Uncaught Error: ru_RU is not available in the catalog
    at m.setLocale (parsley.min.js?ver=1.8.3:2)
    at i.window.Parsley.(anonymous function) [as setLocale] (http:// ...............................ru/wp-content/plugins/caldera-forms/assets/build/js/parsley.min.js?ver=1.8.3:3:15735)
    at zhalyuzi-plisse:1439

Version 1 7 6 is stable and error free

**Comment by vaka2vaka** [comment]
1.8.3 There was a mistake on the second site

Uncaught TypeError: a(...).baldrick is not a function
    at resBaldrickTriggers (caldera-forms-front.min.js?ver=1.8.3:1)
    at HTMLDocument.<anonymous> (caldera-forms-front.min.js?ver=1.8.3:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
parsley.min.js?ver=1.8.3:2 Uncaught Error: ru_RU is not available in the catalog
    at m.setLocale (parsley.min.js?ver=1.8.3:2)
    at i.window.Parsley.(/12745-2/anonymous function) [as setLocale] (http://vaka.pro/wp-content/plugins/caldera-forms/assets/build/js/parsley.min.js?ver=1.8.3:3:15735)
    at (index):938

**Comment by Shelob9** [comment]
One of two problems:
1) Translation file is missing in package.
2) The script to load it, which we changed here #3087  caused problems.

To test, I would say load with language not english and the weglot integration off.

https://github.com/CalderaWP/Caldera-Forms/pull/3087/files#diff-7f01e925875e64c2a1b90354ab910155R880

**Comment by vaka2vaka** [comment]
This problem was not observed in version 1.8.2.

**Comment by Shelob9** [comment]
The file is there in 1.8.3 so it must be loading incorrectly 
https://plugins.svn.wordpress.org/caldera-forms/tags/1.8.3/assets/js/i18n/

Yah, probably #3087 broke how it loads. @vaka2vaka do you see the file yoursite.com/wp-content/plugins/caldera-forms/assets/js/i18n/ru.js loading?

**Comment by vaka2vaka** [comment]
// Validation errors messages for Parsley
// Load this after Parsley

Parsley.addMessages('ru', {
  defaultMessage: "РќРµРєРѕСЂСЂРµРєС‚РЅРѕРµ Р·РЅР°С‡РµРЅРёРµ.",
  type: {
    email:        "Р’РІРµРґРёС‚Рµ Р°РґСЂРµСЃ СЌР»РµРєС‚СЂРѕРЅРЅРѕР№ РїРѕС‡С‚С‹.",
    url:          "Р’РІРµРґРёС‚Рµ URL Р°РґСЂРµСЃ.",
    number:       "Р’РІРµРґРёС‚Рµ С‡РёСЃР»Рѕ.",
    integer:      "Р’РІРµРґРёС‚Рµ С†РµР»РѕРµ С‡РёСЃР»Рѕ.",
    digits:       "Р’РІРµРґРёС‚Рµ С‚РѕР»СЊРєРѕ С†РёС„СЂС‹.",
    alphanum:     "Р’РІРµРґРёС‚Рµ Р±СѓРєРІРµРЅРЅРѕ-С†РёС„СЂРѕРІРѕРµ Р·РЅР°С‡РµРЅРёРµ."
  },
  notblank:       "РС‚Рѕ РїРѕР»Рµ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ Р·Р°РїРѕР»РЅРµРЅРѕ.",
  required:       "РћР±СЏР·Р°С‚РµР»СЊРЅРѕРµ РїРѕР»Рµ.",
  pattern:        "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РЅРµРєРѕСЂСЂРµРєС‚РЅРѕ.",
  min:            "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РЅРµ РјРµРЅРµРµ С‡РµРј %s.",
  max:            "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РЅРµ Р±РѕР»РµРµ С‡РµРј %s.",
  range:          "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РѕС‚ %s РґРѕ %s.",
  minlength:      "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ СЃРѕРґРµСЂР¶Р°С‚СЊ РЅРµ РјРµРЅРµРµ %s СЃРёРјРІРѕР»РѕРІ.",
  maxlength:      "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ СЃРѕРґРµСЂР¶Р°С‚СЊ РЅРµ Р±РѕР»РµРµ %s СЃРёРјРІРѕР»РѕРІ.",
  length:         "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ СЃРѕРґРµСЂР¶Р°С‚СЊ РѕС‚ %s РґРѕ %s СЃРёРјРІРѕР»РѕРІ.",
  mincheck:       "Р’С‹Р±РµСЂРёС‚Рµ РЅРµ РјРµРЅРµРµ %s Р·РЅР°С‡РµРЅРёР№.",
  maxcheck:       "Р’С‹Р±РµСЂРёС‚Рµ РЅРµ Р±РѕР»РµРµ %s Р·РЅР°С‡РµРЅРёР№.",
  check:          "Р’С‹Р±РµСЂРёС‚Рµ РѕС‚ %s РґРѕ %s Р·РЅР°С‡РµРЅРёР№.",
  equalto:        "РС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РґРѕР»Р¶РЅРѕ СЃРѕРІРїР°РґР°С‚СЊ."
});

Parsley.setLocale('ru');

**Comment by Shelob9** [comment]
Thanks @vaka2vaka this helps a lot.

Ok, the bug here is that it's trying to load `ru_RU` when only `ru` exists. The logic in the method that chooses the validation string file to load solves this, but the way we set the language in Parsely does not.

`Caldera_Forms_Render_Assets::get_validator_locale_url()`

**Comment by Shelob9** [comment]
Close via #3111

**Comment by LaurieY** [comment]
I had a similar error but this time en_GB
Applying the commit in pull request #3111 resolved it

**Comment by Shelob9** [comment]
These fixes are included in this test build https://github.com/CalderaWP/Caldera-Forms/files/3010315/1.8.4-b.1.zip

**Comment by vaka2vaka** [comment]
On the test site, the problem disappeared.
ОF
As soon as the problem is solved (Front end page load size increase # 3065), happiness will come.
