### ISSUE TITLE
Remove blank line in {summary} email

### ISSUE THREAD

**Issue by kaypohl** [CalderaWP/Caldera-Forms#3108]
Hi,

is there a way to remove the "blank line" after every magic tag and value? I need to print the mail and with all the blank lines I don't get it on one page.

Kay

WordPress Version: 4.9.5PHP Version: 7.2.4MySQL Version: 5.5.5Caldera Forms Version: 1.7.2WP_DEBUG:

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
