### ISSUE TITLE
Caldera form issue with Elementor

### ISSUE THREAD

**Issue by rahul404error** [CalderaWP/Caldera-Forms#3114]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
Yes, I was referred here from that page only.

## Is This A Feature Request?
*No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
* Every time I try to open the Elementor editor, it crashes with the error message "preview could not be loaded". While inspecting the page the below js errors came up. I have to deactivate Caldera everytime I need to use the editor.

## What PHP Errors Have You Logged While Reproducing This Bug?
* -

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* Uncaught TypeError: Cannot read property 'SelectControl' of undefined
    at Object.calderaForms (8099c.js:9)
    at e (8099c.js:9)
    at Object.calderaForms (8099c.js:9)
    at e (8099c.js:9)
    at calderaForms (8099c.js:9)
    at 8099c.js:9
/wp-content/plugins/elementor-caldera-forms/assets/css/elementor-caldera-forms.css?ver=5.1.1:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by Shelob9** [comment]
`wp.components` is not defined.

![Screen Shot 2019-03-26 at 10 21 37 AM](https://user-images.githubusercontent.com/1994311/55004671-04368b80-4fb1-11e9-9265-b935cb6759f0.png)

**Comment by Shelob9** [comment]
Should be fixed via #3120 - Beta to test can be found here: https://github.com/CalderaWP/Caldera-Forms/pull/3120#issuecomment-476850278

**Comment by Shelob9** [comment]
Close via #3120 
6099c22
