### ISSUE TITLE
Issue with attachments does not work

### ISSUE THREAD

**Issue by malinowy777** [CalderaWP/Caldera-Forms#3116]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Short Debug Information
WordPress Version: 5.1.1PHP Version: 7.0.33MySQL Version: 5.5.5Caldera Forms Version: 1.8.3WP_DEBUG: 1
Full Debug Information
WordPress Version: 5.1.1

PHP Version: 7.0.33

MySQL Version: 5.5.5

Server Software: Apache/2

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: Twenty Nineteen: 1.3

Plugins:

Breadcrumb NavXT: 6.2.1 Active
Caldera Forms: 1.8.3 Active
Caldera Forms Anti Spam: 0.1.2 Active
CF Post Formats: 1.3.1 Active
Codestar Framework: 1.0.1.1 Active
Contact Form 7: 5.1.1 Active
Duplicate Post: 3.2.2 Active
Enhanced Text Widget: 1.4.6 Active
Envato Market: 2.0.1 Active
Max Mega Menu: 2.5.3.2 Active
Slider Revolution: 5.4.8.2 Active
ThemetechMount Brivona Demo Content Setup: 1.0 Active
ThemeTechMount Extras for Brivona Theme: 1.1 Active
WPBakery Page Builder: 5.6 Active
WPFront Scroll Top: 2.0.1 Not Active
Yoast SEO: 9.7 Active

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
YES

## What Is The Unexpected Behaviour?
Not all attachments are hitting server and email. 
I have tried with different configuration and the issue persist. 
Example: I am adding 4 attachments named 1.docx, 2.docx, 3.docx, 4.docx. I did it multiple times. Never all 4 files were uploaded.  One time files 1.docx and 3.docx were uploade, the other time 1.docx and 4.docx, other time 1,2 and 4. 

When trying to upload rar file - just ONE file. I am receiving empty email. 

Can you fix that ?

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors

**Comment by New0** [comment]
Hello @malinowy777 , thank you for reporting, I couldn't reproduce this issue, could you attach a .json export (zipped) of the form please ? What browser did you use when you were testing/experimenting this ?

**Comment by malinowy777** [comment]
Hello @New0 , attaching zipped form definition. I am using chrome. By the way "send" button does not work in Edge but it's different topic. 


[Übersetzen-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/3004170/Ubersetzen-export.zip)

**Comment by New0** [comment]
Thank you , I could reproduce the behavior you're mentioning with file field attachments.

@malinowy777 note that adding files to media library make attachments behave as expected. Please consider using the add to media library option while we fix the issue.

**Comment by Shelob9** [comment]
https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/save.php#L311 - check should_attatch() - not is_private() should fix this, if the data there is correct.

**Comment by malinowy777** [comment]
Hello, 
do you have any estimation when the fix will be released?
Rgds,

**Comment by Shelob9** [comment]
Close via  #3124
