### ISSUE TITLE
Submit button not working

### ISSUE THREAD

**Issue by anauman-ameriforce** [CalderaWP/Caldera-Forms#3118]
## Do You Need Immediate Help?
* Yes, however I cannot find my license key.

## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* Caldera 1.8.3  WP 5.1.1  PHP 4.7.3

## What Is The Unexpected Behaviour?
* I believe I have a paid license, if not I will definitely pay to get this fixed. Our apply button is not working! I tested this on the live form and the preview, not sure what is going on. https://www.ameriforce.com/adwords-el-multi/ 

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by New0** [comment]
Hello @anauman-ameriforce , for support please go to https://calderaforms.com/support/ . 
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab, and report if the issue persists with all other plugins disabled and theme twentynineteen activated.

**Comment by anauman-ameriforce** [comment]
That page is not finding my email address. I just need this fixed and can pay for support if we don’t already have it. Can you look up anauman@ameriforce.com<mailto:anauman@ameriforce.com> as there is not a “register” link?

Andy Nauman
Director of Marketing and Fulfillment

phone: 800-522-8998 x4043
mobile: 904-470-9821

[Facebook icon]<https://www.facebook.com/AmeriForceTheWorkForceSpecialist>[Twitter icon]<https://twitter.com/AmeriForce_Recr>[LinkedIn icon]<https://www.linkedin.com/in/andy-nauman-70646417/>


[Logo]<https://www.ameriforce.com/>

9485 Regency Square Blvd., Suite 300
Jacksonville, FL 32225

www.AmeriForce.com<http://www.ameriforce.com/>


[cid:image007.png@01D43956.81DECCE0]<http://bit.ly/2Lbg1P7>

**Comment by netzih** [comment]
I'm wondering if it is a bug in the current version, Because I just installed Caldera forms on 2 sites and on both sites nothing at all happens when clicking the submit button.

**Comment by anauman-ameriforce** [comment]
In my case it turned out to be a caching issue with another plugin. I disabled it and it began working again. This could be the case with the other sites as well.

Andy Nauman
Director of Marketing and Fulfillment

phone: 800-522-8998 x4043
mobile: 904-470-9821

[Facebook icon]<https://www.facebook.com/AmeriForceTheWorkForceSpecialist>[Twitter icon]<https://twitter.com/AmeriForce_Recr>[LinkedIn icon]<https://www.linkedin.com/in/andy-nauman-70646417/>


[Logo]<https://www.ameriforce.com/>

9485 Regency Square Blvd., Suite 300
Jacksonville, FL 32225

www.AmeriForce.com<http://www.ameriforce.com/>


[cid:image007.png@01D43956.81DECCE0]<http://bit.ly/2Lbg1P7>

**Comment by netzih** [comment]
In my case had to disable the Ajax submission setting. So can only work if opening a new page. Doesn't submit on the same page.

**Comment by New0** [comment]
Hello @anauman-ameriforce , thank you for the feedback. 

@netzih if you have any caching did you flush all cached assets before running tests ? We are investigating this issue at #3098 , if this persist please share your information there.

**Comment by jaydeesigns** [comment]
@new0 don't know if it helps but I've had to roll back to version 1.7.6 to make it work

**Comment by anauman-ameriforce** [comment]
Removing a caching plugin fixed the problem. Thank You.


  *   Andy

**Comment by netzih** [comment]
What caching plugin?
AFAIK I do not have any caching plugins
