### ISSUE TITLE
WordPress Notices Display in Layout Builder

### ISSUE THREAD

**Issue by DevinWalker** [CalderaWP/Caldera-Forms#312]
I have a few persistent notices displaying on this environment and when I go to customize a form they display in the layout builder:

![11-3-2015 3-45-00 pm](https://cloud.githubusercontent.com/assets/1571635/10925344/0cc4ce64-8242-11e5-9514-9c80f483a9b6.png)

The notices should be hidden or moved

**Comment by Shelob9** [comment]
For the record @DevinWalker sent me the export on this and the layout problem is not present. Is this beacuse I am latest and he is the repo version? Is this beacuse of his plugins? I don't know and we need to find out.

**Comment by DevinWalker** [comment]
@Shelob9 try installing the email cop plugin to see a persistent notice

**Comment by paaljoachim** [comment]
Btw I was just about to post something similar.
I have a WP Courseware notice inside the layout builder.

![skjermbilde 2015-11-04 kl 7 24 15 p m](https://cloud.githubusercontent.com/assets/5323259/10947842/c9b8520a-832a-11e5-8025-d5827e714c62.png)

**Comment by Shelob9** [comment]
Close via 		c5a424b
