### ISSUE TITLE
I got some issues with receive the contact form of Caldera form. when a customer fill the form it will NOT send in Chrome but when the click on send but in internet explorer it works. Can you please fix this issue because lots of my customer are complaining.

### ISSUE THREAD

**Issue by thereallife4** [CalderaWP/Caldera-Forms#3125]
I got some issues with receive the contact form of Caldera form. when a customer fill the form it will NOT send in Chrome but when the click on send but in internet explorer it works. Can you please fix this issue because lots of my customer are complaining.

_Originally posted by @thereallife4 in https://github.com/CalderaWP/Caldera-Forms/issues/3098#issuecomment-477495542_

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
