### ISSUE TITLE
SUBMIT FORM IMPOSSIBLE SINCE LAST UPDATE

### ISSUE THREAD

**Issue by PATVALCOU** [CalderaWP/Caldera-Forms#3144]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by huntersbest** [comment]
Uncaught ReferenceError: wp is not defined
    at Object.<anonymous> (index.min.js?ver=1.8.4:30)
    at Object.782 (index.min.js?ver=1.8.4:30)
    at t (index.min.js?ver=1.8.4:1)
    at calderaForms.render.0 (index.min.js?ver=1.8.4:1)
    at index.min.js?ver=1.8.4:1

when opening page with Caldera Form Shortcode

On send obviously:
ajax-core.js?ver=1.8.4:177 Uncaught TypeError: Cannot read property 'CF581b19aa1cea6_1' of undefined
    at Object.init (ajax-core.js?ver=1.8.4:177)
    at HTMLFormElement.<anonymous> (jquery-baldrick.js?ver=1.8.4:258)
    at HTMLFormElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLFormElement.r.handle (jquery.js?ver=1.12.4:3)

**Comment by PATVALCOU** [comment]
Hi,

 

The issue is solved by disactivating and reactivating various plug ins

 

Regards

 



 

Tél :  05 58 70 41 46

 <mailto:contact@boites-et-cie.fr> contact@boites-et-cie.fr

 

 <http://www.boites-et-cie.fr/> www.boites-et-cie.fr

 <http://www.facebook.com/boites.et.cie/> www.facebook.com/boites.et.cie/

 

 

 

 

 

De : huntersbest <notifications@github.com> 
Envoyé : mardi 9 avril 2019 09:48
À : CalderaWP/Caldera-Forms <Caldera-Forms@noreply.github.com>
Cc : PATVALCOU <contact@boites-et-cie.fr>; Author <author@noreply.github.com>
Objet : Re: [CalderaWP/Caldera-Forms] SUBMIT FORM IMPOSSIBLE SINCE LAST UPDATE (#3144)

 

Uncaught ReferenceError: wp is not defined
at Object. (index.min.js?ver=1.8.4:30)
at Object.782 (index.min.js?ver=1.8.4:30)
at t (index.min.js?ver=1.8.4:1)
at calderaForms.render.0 (index.min.js?ver=1.8.4:1)
at index.min.js?ver=1.8.4:1

when opening page with Caldera Form Shortcode

On send obviously:
ajax-core.js?ver=1.8.4:177 Uncaught TypeError: Cannot read property 'CF581b19aa1cea6_1' of undefined
at Object.init (ajax-core.js?ver=1.8.4:177)
at HTMLFormElement. (jquery-baldrick.js?ver=1.8.4:258)
at HTMLFormElement.dispatch (jquery.js?ver=1.12.4:3)
at HTMLFormElement.r.handle (jquery.js?ver=1.12.4:3)

**Comment by New0** [comment]
Hello @PATVALCOU thank you for reporting your issue and letting us know you have it fixed. 

Could you let us know if in the list of plugins you deactivated and reactivated there was a caching plugin ?

**Comment by PATVALCOU** [comment]
Hello,

We had deactivated WP ROCKET plugin and not reactivated.
WP Rocket is a caching plugin.

Now, that’s working properly.

Patrice

**Comment by Shelob9** [comment]
Lets' track this in #3141

**Comment by huntersbest** [comment]
Switching off ajax sendind helps too.

**Comment by jonbhanson** [comment]
Had the same problem... I do not have WP Rocket installed.  Tried disabling caching/optimization plugins.  Ultimately it was turning off Ajax that solved it for me.  Thanks @huntersbest .
