### ISSUE TITLE
Text between two % characters

### ISSUE THREAD

**Issue by teamtacho** [CalderaWP/Caldera-Forms#3157]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
yes

## Is This A Feature Request?
no

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8PHP Version: 7.2.15MySQL Version: 5.6.42Caldera Forms Version: 1.8.4

## What Is The Unexpected Behaviour?
If a text in a textarea field contains two % characters (e.g. ..the incline is between 20% and 30%..)
the % and the text between the % is not shown in the email. Obviously CF interprets this as a slug. The full text is shown in the CF entry viewer but not in the email.

## What PHP Errors Have You Logged While Reproducing This Bug?
-

## What JavaScript Errors Have You Seen While Reproducing This Bug?
-

**Comment by teamtacho** [comment]
Hi
I have updated CF to version 1.8.5 but it isn't solved yet. Please can you give me guidance if I can do something or re-open that task fix the bug in the upcomming version.
Best Regards
Michael

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/a59c771c46e6973fabebeb958a315c17e75722eb -
