### ISSUE TITLE
Limit eligible options for end user in select, dropdown, selectable or list field

### ISSUE THREAD

**Issue by Wolftech-Chile** [CalderaWP/Caldera-Forms#3161]
Hello, dear friends, I have a question that I have not been able to clarify, I have read all the documentation of Caldera Forms and I have not found anything, I need to make a drop-down list, a selectable box, a list of options or selectable tab where the end user can select only the number of options that have been set in the configuration (3, 4, 5, etc) nothing more than that, with that limit pre-established by me. It can be done, how is it done?
Since I thank you for your help and guide friend and I apologize for bothering them
Best regards
Gustavo From Chile

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
