### ISSUE TITLE
Email Recipient isn't receiving anything

### ISSUE THREAD

**Issue by paeddevogt** [CalderaWP/Caldera-Forms#3164]
confirmation mail was receiving but the email recipient isn't getting anything.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
