### ISSUE TITLE
Dropdown value doesn't show

### ISSUE THREAD

**Issue by Alandvisa** [CalderaWP/Caldera-Forms#3165]
I create form with caldera and it's totally ok in macOS and IOS but it isn't showing selected value of dropdown in Windows and Android

**Comment by st3phan76** [comment]
Hi, ... did you check the difference between label, value and calculated value? If no, expand your select-entries (show values) in the right sidebar, to set these values ... https://calderaforms.com/doc/dropdown-select/
good luck

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
