### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given

### ISSUE THREAD

**Issue by Tofandel** [CalderaWP/Caldera-Forms#3167]
On the default install of caldera if I try to view an entry it returns the following PHP Error
PHP Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given

It happens when there is something url encoded in the label of a an option (Eg: %C3%C3) (If you put a link inside the label for example)
That's because the option label tries to apply magic tags when it shouldn't

I tracked it down to the method format_select_options in core.php and the call to `self::do_magic_tags($option['label']);`

Why is the label magic tagged? There is no point in it is there? Anyway even if there was it would cause an error when viewing the entry because the form global is not defined at this point and would throw this error

**Comment by Tofandel** [comment]
#3168

**Comment by Shelob9** [comment]
Close via 8d87bdc  #3207
