### ISSUE TITLE
Way to quickly view a forms embeddable shortcode

### ISSUE THREAD

**Issue by DevinWalker** [CalderaWP/Caldera-Forms#318]
It's convenient to show the form shortcode in an field that can be easily copied from. I don't see any obvious way to find a forms shortcode other than embedding it on a page, copying that shortcode, and then using it in a template.

**Comment by Desertsnowman** [comment]
There's a super secret feature coming that will address this.

**Comment by Shelob9** [comment]
Closing in favor of #565
