### ISSUE TITLE
Datepicker value

### ISSUE THREAD

**Issue by pless84** [CalderaWP/Caldera-Forms#3181]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.1.1PHP Version: 7.2.9MySQL Version: 5.7.23Caldera Forms Version: 1.8.4WP_DEBUG:

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

Where can I get the value of the chosen date?

**Comment by Shelob9** [comment]
@
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Comment by pless84** [comment]
Oh so a simple question needs a full bug repport? Yeah no, just gonna go to an alternative plugin.
