### ISSUE TITLE
Issue with Phone Number Better Field

### ISSUE THREAD

**Issue by nitindigixhub** [CalderaWP/Caldera-Forms#3189]
Hello,

I am using the caldera forms plugin for the first time for my WordPress project.

Currently, I have a major issue with SSL conflict and also not allowing the contact form created by us to submit.

I have set the phone number field type as Phone Number better, from the time we did this out url header shows content block and we can see an error in the console - 

Mixed Content: The page at 'https://www.digixhub.com/#' was loaded over HTTPS, but requested an insecure script 'http://www.digixhub.com/wp-content/plugins/caldera-forms/fields/phone_better/assets/js/utils.js'. This request has been blocked; the content must be served over HTTPS.
send @ jquery.js?ver=1.12.4:1

Find the screenshot below - 

![image](https://user-images.githubusercontent.com/37868602/57195556-bdee2800-6f71-11e9-9148-e381016ff870.png)

![image](https://user-images.githubusercontent.com/37868602/57195543-8bdcc600-6f71-11e9-92f7-1920a2eebb56.png)

As you can see in the screenshot below also when we try to submit the form entering the phone number is shows us undefined which constantly appears.

Also, the size of the field is different, whereas not has been changed in the CSS by me.

I did try to disable all the plugins and check and also change the theme but the same error appers.

![image](https://user-images.githubusercontent.com/37868602/57195524-4e783880-6f71-11e9-9736-117004092fc5.png)

Request you to help me to solve this on an immediate basis.

**Comment by New0** [comment]
Hello @nitindigixhub  , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
