### ISSUE TITLE
Set minimum WP version to 5.1

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3205]
Yoast is dropping support for WordPress 5.0 and below. We have had a few issues trying to support 4.9 with our dependency on Gutenberg scripts.  Would be easier if we mad our minimum 5.1.

https://yoast.com/supporting-older-versions-of-wordpress/

**Comment by Shelob9** [comment]
From a DX perspective, WordPress 5.2 would be great minumum, as @wordpress/createElement exports React hooks in that version.

**Comment by Shelob9** [comment]
We came to a consensus in Basecamp that we change the "Requires At Least" to 5.1, but still load the plugin on 5.0.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/c6649b04bd0d45f4760e62ba96ade4c14a953ce5
