### ISSUE TITLE
Security header is not valid

### ISSUE THREAD

**Issue by zakisp** [CalderaWP/Caldera-Forms#3209]
New version of Caldera is not compatible with Caldera Forms Express Checkout

I'm using latest version of Caldera forms + PayPal Express Just bough it few minute ago

I tried with USD and CAD it doesn't work it say : Security header is not valid and doesnt redirect to PayPal

Thanks

**Comment by New0** [comment]
Hello @zakisp , did you open a support ticket for this issue ? 

As this is a product that entitles to support, please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
