### ISSUE TITLE
Validate email error: 'The captcha wasn't entered correctly. Reset.'

### ISSUE THREAD

**Issue by andyburnsco** [CalderaWP/Caldera-Forms#3217]
Below outlines an example of how using validate email processor and recaptcha do not allow the form to fully work, resulting in user confusion.

1. You go here to sign up:  https://lpky.org/membership/signup/
2. You fill out the form.
3. You checkbox the captcha (invisible captcha gives same error).
4. You click the "Submit"
5. It sends you a confirmation email.
6. You click the link in the confirmation email.
7. It takes you back to the form again, and there's a message about "The captcha wasn't entered correctly. Reset."   Reset is a link that doesn't do anything.
![validate-email-catpcha-error](https://user-images.githubusercontent.com/18341942/58214511-9a3e1800-7cbb-11e9-844d-ef45eeea11c2.PNG)

This breaks the rest of the processes caldera forms is supposed to do:

- No success message
- No email is sent to know that the signup occurred.

We have determined that is essential to have both validate email and recaptcha in use. Validate email prevents dirtying our db, and recaptcha prevents transients stacking up in wp_options. When the latter occurred, it brought our sites to a crawl with over 13K transients.

We are using WP 5.2.1 Caldera Forms 1.8.4. We also use CiviCRM but the data actually gets to Civi.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
