### ISSUE TITLE
Add PHP 7.2/7.3 tests in Travis

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3220]
PHP 7.2 removed here 768008f46dbec6e17f982e5fffe38b545ce6c78e See: https://github.com/CalderaWP/Caldera-Forms/pull/2974#issuecomment-464300898

https://github.com/WordPress/wordpress-develop/blob/master/.travis.yml#L62-L82

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/1ff4bc39c109f8080a2448860cd3ad6d2e2cb3d2
