### ISSUE TITLE
Vertical layout for toggle switch don't work

### ISSUE THREAD

**Issue by evolluti0n** [CalderaWP/Caldera-Forms#3223]
## Do You Need Immediate Help?
Ticket open in https://secure.helpscout.net/conversation/835958498/20677?folderId=2372292

## Is This A Feature Request?
No. I think is a bug.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.1
PHP Version: 7.3.5
MySQL Version: 5.7.26
Caldera Forms Version: 1.8.4

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes. 

## What Is The Unexpected Behaviour?
I created a demo form with only a toggle switch with Vertical orientation. It looks good in Layout builder but not in Preview. The layout remains horizontal. 
I attached the demo form to this message. 

[demo-toggle-switch-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/3213816/demo-toggle-switch-export.zip)

## What PHP Errors Have You Logged While Reproducing This Bug?
There are no PHP errors in logs

## What JavaScript Errors Have You Seen While Reproducing This Bug?
There are no errors in browser console

**Comment by New0** [comment]
Hello @evolluti0n , thank you for opening that issue. I couldn't reproduce this using the export form shared by the user in the support ticket. 

Did you reproduce the issue ? Did or could the user test switching to twenty nineteen theme and disabling other plugins ? That could be a styles interference from the theme or another plugin.

**Comment by kdlaobr** [comment]
Yes, here it's working too.
Maybe it's solved with the last version 1.8.5 upgraded 5 days ago.

**Comment by evolluti0n** [comment]
Hi. Yes !! It's working fine now from my side, also. I updated to 1.8.5 version and the problem gone away.

**Comment by New0** [comment]
Hello @kdlaobr , @evolluti0n , I'm glad it works now !
