### ISSUE TITLE
Caldera Forms does not work on Mobile devices

### ISSUE THREAD

**Issue by abdullahshaker1** [CalderaWP/Caldera-Forms#3230]
Hello 

I created 2 pages form with Caldera, It works fine with Desktop devices, but, It does not transfer the user to page 2 after submitting page 1 in Mobile devices, can you help me, please?

**Comment by New0** [comment]
Hello @abdullahshaker1 , I've not been able to reproduce this issue. As this is a development channel, I would be glad to help here if you submit an issue following the template. For support, please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
