### ISSUE TITLE
Improve webpack config

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3239]
1. Remove vue support - once #3212 is done
2. Upgrade babel and webpack
3. Use @wordpress/scripts for the blocks compilation
4. Exclude React from our front-end builds and block-builds. Include React for our non block admin views.
5. HMR
6. Lazyloading
7. Include front client in admin client?

**Comment by Shelob9** [comment]
Builds should be:

* front -> edit client without React/wp. JSX transformed with wp.createElement load wp-* with wp_enqueue_scripts()
* front-legacy -  edit client + legacy bundle. JSX transformed with wp.createElement. load wp-* with wp_enqueue_scripts()
* admin - render client + admin client. With React 16.8 and wp included. JSX transformed with React.createElement. Do NOT load wp-* with wp_enqueue_scripts()
* privacy - privacy client  With React 16.8 and wp included. JSX transformed with React.createElement. Do NOT load wp-* with wp_enqueue_scripts()
* pro - Nothing, should go away for now, just keep old built files. Never change.

**Comment by Shelob9** [comment]
Related #3065

**Comment by New0** [comment]
@Shelob9 do you want to close this issue after https://github.com/CalderaWP/Caldera-Forms/commit/8d9cf2772af7a4210950a90372fece49a87f381b ?

**Comment by Shelob9** [comment]
Close via 8d9cf27
