### ISSUE TITLE
cant install in wordpress

### ISSUE THREAD

**Issue by daryldauphin** [CalderaWP/Caldera-Forms#3241]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by daryldauphin** [comment]
im having trouble installing the form plug in, it stays its installing for a long time and then it gives an error. Its compatible with my wordpress but it cant instal.

**Comment by New0** [comment]
Hello @daryldauphin , could you describe the process that leads to the issue ? Are you installing Caldera Forms from WordPress.org ?
Could you share the error ?

**Comment by New0** [comment]
Related #3259

**Comment by New0** [comment]
This should have been fixed in the svn channel ( removing an extra folder trunk folder copied to tags/1.8.5 ).
I'm closing as this has stopped being reported since the svn fix.
