### ISSUE TITLE
Some visitors unable to submit form

### ISSUE THREAD

**Issue by MoritzEmbroidery** [CalderaWP/Caldera-Forms#3243]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.1PHP Version: 7.0.32-1~dotdeb+8.1MySQL Version: 5.7.25Caldera Forms Version: 1.8.4WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes 

## What Is The Unexpected Behaviour?
Many visitors of our site contact us and say they are unable to submit requests via our Caldera-Form. They complete the form, click submit, but the form never submits. We have tried to recreate the issue and have been unable to. They get no error messages.

## What PHP Errors Have You Logged While Reproducing This Bug?
None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None.

**Comment by New0** [comment]
Hello @MoritzEmbroidery , I'm sorry this happened. 
This channel is for development issues, for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
