### ISSUE TITLE
Combination of Submit and Next button in Caldera Form and conditional calculation field

### ISSUE THREAD

**Issue by kshitijshah79** [CalderaWP/Caldera-Forms#3246]
## Do You Need Immediate Help?
NO

## Is This A Feature Request?
NO

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
version 1.8.5

## What Is The Unexpected Behaviour?
I have been trying to use Magic Tags in the Final results page(Page-6) of my form and used %loan amount% slug in one of the paragraph/text area fields but the output does not show any value and just shows blank.

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors in the form

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors:

******************************************************************************************************
Hi Everyone.
Apologies if this sounds as a novice question. I am a developing my own website and have basic programming knowledge but am stuck at the final steps on my caldera form which I have developed for my website.

I am stuck in couple of areas and would like to know if anyone can help me out ( I have attached an image of my Caldera forms). I have built a caldera form whereby customer enters their home loan situation and at the end(after they enter their details) they can see if they can save on their current home loan.

Basically depending on the permutation of which option from the customer chooses, there will be 6 outcomes(2 outcomes not permissible here so only 6 possible):
The choices:
Field-1: Home Owner or Investor 
Field -2: Fixed or Variable rate 
Field -3: Interest only or Principle+Interest
I have set variables static for each of these options that are possible.

Output:
I have made conditions so depending on the input from customer only one calculation will be shown to the customer.

My Question:
1. How do I use this output(which will be any one of the 6 conditional calculation fields and subtract my "Total Current Annual Interest" value to show to clients how much they can save in the "Potential Yearly Savings Field". Since the total current annual interest rate output varies, how do I use this output for further calculations?
2. I am collecting all the customer details on Page-5 of my forms and showing the results on Page-6. The button options only allow either Next or Submit. Is there a way to have both i.e I get the customers to submit their details and then it moves to the next page to show them the results?
3. I have been trying to use Magic Tags in the Final results page(Page-6) and used %loan amount% slug in one of the paragraph/text area fields but the output does not show any value and just shows blank.
4. Is there a way to easily change the order of pages of a caldera form developed. Can I drag and drop or is there a way other than creating the entire form from scratch? I have 6 pages and need to change order of pages or insert one page in the middle but cannot find a way to do it.

![Caldera Form question](https://user-images.githubusercontent.com/51263496/58748852-794aa380-84c1-11e9-8205-689cb937f32b.png)

**Comment by New0** [comment]
Hello @kshitijshah79 , the paragraph / textarea field supports system tags {date:*} but not magic tags %field_slug%

For the next, I'm sorry this is not a support channel, for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
