### ISSUE TITLE
Error activating CF plugin with WordPress 4.9.10

### ISSUE THREAD

**Issue by evolluti0n** [CalderaWP/Caldera-Forms#3251]
## Do You Need Immediate Help?
https://secure.helpscout.net/conversation/867583445/21353?folderId=2372292

## Is This A Feature Request?
No. I think is a bug

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Site 1: 
WordPress Version: 4.9.10
PHP Version: 7.2.16-1+0~20190307202206.17+jessie~1.gbpa7be82
MySQL Version: 5.7.25
Caldera Forms Version: 1.8.5

Site 2:
WordPress Version: 4.9.10
PHP Version: 7.3.5
MySQL Version: 5.7.26
Caldera Forms Version: 1.8.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes. 

## What Is The Unexpected Behaviour?
Site 1: Updated Caldera Forms from 1.7.7 version to 1.8.5. The Forms screen layout broke. Please check the screenshots at the end of this message.

Site 2: I installed a new fresh site with WordPress 4.9.10. Then, I installed Caldera Forms 1.8.5 and receive an error activating the plugin. 
I open the Plugins page, the Caldera Forms plugin was installed but not active. I just activated it. 
Then, I open Caldera Forms > Forms. The screen layout is broken. Please check the screenshots at the end of this message. 

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors reported 

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors reported

## Screenshots for errors:

Site 1:
http://prntscr.com/nxow28  (screen layout problem)

Site 2:
http://prntscr.com/nxovd6  (error message activating the plugin)
http://prntscr.com/nxovqz  (screen layout problem)

**Comment by Shelob9** [comment]
@evolluti0n did y'all try deleting the plug-in and reinstalling from dot org?

**Comment by evolluti0n** [comment]
In the vanilla installation, I tried installing from 'Add new' option in plugins page. I will try this. 
Will provide an update very soon.

**Comment by evolluti0n** [comment]
@Shelob9 
I completely wiped the site and reinstalled WordPress 4.9.10. No plugins active, only Akismet installed. 
I removed all themes. Kept only Twenty Nineteen.
Downloaded the .zip file for plugin from WordPress.org
Installed the plugin using the plugin installer: Same error. 

Uninstalled the plugin
Uploaded .zip file using cPanel File Manager
Uncompressed the .zip file
Activated the plugin in WP plugins manager
Checked Caldera Forms > Forms: Same error

http://prntscr.com/nxpbaa

#Full Debug Information

WordPress Version: 4.9.10
PHP Version: 7.3.5
MySQL Version: 5.7.26
Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Session Save Path: /opt/alt/php73/var/lib/php/session
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440

Opcode Cache:
    Apc: No
    Memcached: No
    Redis: No

Object Cache:
    Apc: No
    Apcu: No
    Memcache: No
    Memcached: No
    Redis: No

WP Multisite Mode: No
WP Memory Limit: 40M
Currently Active Theme: Twenty Seventeen: 2.2

Plugins:
    Akismet Anti-Spam: 4.1.2 Not Active
    Caldera Forms: 1.8.5 Active

**Comment by Shelob9** [comment]
But only in WordPress 4.9 ? I can't see this in 5.1 or 5.2. So strange...

Also, this is another reason why we should drop WordPress 4.x support, in my opinion. #3205

**Comment by evolluti0n** [comment]
So far, I only tested in WordPress 4.9.10. Probably, we will have the same problem in previous versions.

**Comment by Shelob9** [comment]
There is no need to test in versions before 4.9

**Comment by Shelob9** [comment]
#3271

**Comment by New0** [comment]
This should have been fixed in the svn channel ( removing an extra folder trunk folder copied to tags/1.8.5 ).
I'm closing as this has stopped being reported since the svn fix.
