### ISSUE TITLE
add a variable to automatically change the price of gold

### ISSUE THREAD

**Issue by ernest102** [CalderaWP/Caldera-Forms#3252]
I created an emulator (calculation form) of the gold price, and I would like to integrate an fixing to have a variable changed automatically in order to get an updated price.

Please i need your held if it's possible to have this feature. Link of emulator: https://upsylone.com/tester-emulateur/ 

Regards,

**Comment by New0** [comment]
Hello @ernest102  , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
