### ISSUE TITLE
Submit + Next Page button missing

### ISSUE THREAD

**Issue by sam-aus** [CalderaWP/Caldera-Forms#3253]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
Missing button that allows "Submit" + "Next Page" functionality. I need the submit button to collect user information and Next Page functionality to show user outcome of their queries on the last page.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.8.5

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment]
You can find the documentation for button fields here: https://calderaforms.com/doc/button/

If you need help, please open a support request at https://calderaforms.com/support
