### ISSUE TITLE
Custom Fields Add Ons - Advanced File Uploader (2.0)

### ISSUE THREAD

**Issue by jenishshrestha** [CalderaWP/Caldera-Forms#3254]
## Is This A Feature Request?
*  No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* Caldera Forms v2.2.1, Wordpress v5.2.1, php v7.1.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* yes

## What Is The Unexpected Behaviour?
* Tried to create a form that edits the custom post type and then in processors section in "save as post type", featured image does not provide the created Advanced File Uploader (2.0) in the dropdown. It only supports Advanced File Uploader (2.0).

## What PHP Errors Have You Logged While Reproducing This Bug?
* No php errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* No javascript errors

**Comment by New0** [comment]
Hello @jenishshrestha thanks for reporting that behavior, I opened a new issue in the custom fields repo for it to be worked on.
https://github.com/CalderaWP/caldera-custom-fields/issues/53
Closing this as it belongs to Custom fields options.
