### ISSUE TITLE
duplicate notifications

### ISSUE THREAD

**Issue by LinearThinker** [CalderaWP/Caldera-Forms#3255]
Others have complained of not receiving notification emails.
I, on the other hand, receive duplicate notifications for each entry.

For testing purposes, I set the Recipient Email (leads@website.com) the same as the From Email (leads@website.com) so that I receive back the notification in an email.

Not stated in the documentation, but if the "From Email" address receives a copy and the "Recipient Email" address receives a copy, that would explain it. Please advise?

Thank you, Gracias, Grazzi, Merci, Dankhe Shein

**Comment by LinearThinker** [comment]
Hello,
Is there anybody in there?
Just nod if you can hear me.
Is there anyone at home?

Come on now
I hear you're feeling down
Well, I can ease your pain
And get you on your feet again

Relax
I'll need some information first
Just the basic facts
Can you show me where it hurts?

There is no pain, you are receding
A distant ship smoke on the horizon
You are only coming through in waves
Your lips move but I can't hear what you're saying
When I was a child I had a fever
My hands felt just like two balloons
Now I've got that feeling once again
I can't explain, you would not understand
This is not how I am
I have become comfortably numb

I have become comfortably numb

O.K.
Just a little pin prick
There'll be no more aaaaaaaah!
But you may feel a little sick

Can you stand up?
I do believe it's working, good
That'll keep you going through the show
Come on, it's time to go.

There is no pain you are receding
A distant ship smoke on the horizon
You are only coming through in waves
Your lips move but I can't hear what you're saying
When I was a child
I caught a fleeting glimpse
Out of the corner of my eye
I turned to look but it was gone
I cannot put my finger on it now
The child is grown
The dream is gone
I have become comfortably numb.

**Comment by Shelob9** [comment]
@LinearThinker  - I appreciate the song lyrics. I am sorry you are having an issue with your site. We are here, for development. Our support can be found here: https://calderaforms.com/support
