### ISSUE TITLE
PHP incompatibility

### ISSUE THREAD

**Issue by dshayne** [CalderaWP/Caldera-Forms#3260]
My domain host (Siteground) says that they tried to upgrade our PHP version to 7.1 but Caldera Forms is incompatible. However, it seems from your site that this should not be a problem. Can you help me out to understand this? Thanks!

www.plumpub.com/kaimen

Full Debug Information

WordPress Version: 5.2.1

PHP Version: 5.6.40

MySQL Version: 5.6.40

Server Software: Apache

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:67.0) Gecko/20100101 Firefox/67.0

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    Redis: No

Object Cache:

    Apc: No
    Apcu: No
    Memcache: Yes
    Memcached: Yes
    Redis: No

WPDB Prefix: hsc5_

WP Multisite Mode: No

WP Memory Limit: 256M

Currently Active Theme: PressPlay: 1.3

Plugins:

    Acunetix WP Security: 4.0.5 Active
    Add Tags And Category To Page And Post Types: 2.1 Active
    Advanced Image Styles: 0.4.1 Active
    Akismet Anti-Spam: 4.1.2 Active
    Byline: 0.25 Not Active
    Caldera Forms: 1.8.5 Active
    Central Color Palette: 1.13.10 Active
    Child Theme Configurator: 2.5.0 Active
    Classic Editor: 1.5 Active
    Dynamic Widgets: 1.5.14 Active
    Easy Custom Sidebars: 1.0.10 Active
    Embedded Video: 4.1 Active
    Exclude Pages from Navigation: 1.92 Active
    GDPR Cookie Compliance: 2.1.1 Active
    Gutenberg: 5.8.0 Not Active
    Health Check & Troubleshooting: 1.3.2 Not Active
    Image Widget: 4.4.7 Active
    Intuitive Category Checklist: 1.0.2 Active
    Jetpack by WordPress.com: 7.4 Active
    Limit Login Attempts: 1.7.1 Active
    Login-Logout: 3.8 Active
    Mad Libs Lite: 1.0 Not Active
    myRepono Backup Plugin: 2.0.12 Active
    Pages Posts: 2.1 Not Active
    Quick Page/Post Redirect Plugin: 5.1.8 Active
    Register Plus Redux: 4.2.4 Active
    SG Optimizer: 5.1.3 Active
    ShopSite: 1.5.7 Active
    Stop Registration Spam: 1.12 Active
    The GDPR Framework: 1.0.31 Active
    Theme Test Drive: 2.9.1 Active
    TinyMCE Advanced: 5.2.1 Active
    Vanilla PDF Embed: 0.0.8 Active
    Video Embed & Thumbnail Generator: 4.6.25 Active
    Weaver II Theme Extras: 2.3.1 Not Active
    Weaver Show Posts: 1.3.16 Not Active
    Weaver Xtreme Theme Support: 4.0.5 Not Active
    Widget Shortcode: 0.3.4 Active
    WP-Optimize: 2.3.3 Active
    WPaudio: 3.1 Not Active
    WP Cerber Security, Antispam & Malware Scan: 8.3 Not Active
    WP Comment Policy Checkbox: 0.3.1 Active
    WP GDPR Compliance: 1.5.2 Not Active
    WPtouch Mobile Plugin: 4.3.37 Active
    Yoast SEO: 11.3 Active

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?

NA

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Goldmark2016** [comment]
I've also had that notification from Siteground (that all my sites using Caldera Forms cannot be updated to PHP 7.1) but can see no information on Caldera's website that indicates there should be a problem, or what they are doing to fix it. Has anyone resolved this issue, or had any advice form Caldera?

**Comment by Shelob9** [comment]
This should not be an issue with Caldera Forms 1.8.6 

See: https://calderaforms.com/updates/caldera-forms-1-8-5/

Please contact support if you have additional questions.

**Comment by Goldmark2016** [comment]
Hello

Thanks for your email, but it refers to 1.8.6 while actually linking to 1.8.5 … 

I already have 1.8.5 installed on my Wordpress sites (updated prior to the Siteground email on 6th June). The Caldera Forms website has no mention of a 1.8.6 update, so I assume I do have the most up-to-date installation. 

Can you confirm if there is a new update now or very soon which rectifies the PHP incompatibility Siteground has identified?

Thanks

Mark
