### ISSUE TITLE
Changing Permissions For The Caldera Forms REST

### ISSUE THREAD

**Issue by lucashfreitas** [CalderaWP/Caldera-Forms#3266]
Hello,

I am trying to get the form entries using Caldera Forms REST API but it returns 401 Unauthorized. 

I would like to change the permissions to the rest API, but the oficial documentation says we can use filters to do that but it does not give any information about which filters, etc. 

[The documentation says](https://calderaforms.com/doc/caldera-forms-rest-api/): 

![image](https://user-images.githubusercontent.com/11416392/59649182-e0f93200-91d5-11e9-835f-de31a183bb1b.png)

Anyone knows how can I manage the authentication on Caldera Forms Rest Api?

**Comment by Shelob9** [comment]
@lucashfreitas I will update the docs today. Here is the example code: https://gist.github.com/Shelob9/98022cd9e9711ab75fa7afc10bdc1c16
