### ISSUE TITLE
User Register and Connected Caldera forms

### ISSUE THREAD

**Issue by tolarcible** [CalderaWP/Caldera-Forms#3268]
Last version Connected Forms et Users
 I create 2 forms 
form1 with textbox to write login and Action User Register
form2 with textbox

I create 1 form connected with relation form1 and form2

Alone, form1 is Ok, user is ok and response html good
But with User Register integrated in Connected Form, i've a probleme. The register is ok, mais page waiting with form1 and no redirect in form2.

------

This is the header
Request URL: http://mylivingbloom.com/?cf_api=CF5d0a814b1f62a&con_current=CF5d096ccdcb645&con_base=CF5d0a814b1f62a
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 54.36.91.62:80
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-cache, must-revalidate, max-age=0
Content-Type: text/html; charset=utf-8
Date: Wed, 19 Jun 2019 19:23:07 GMT
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Server: Apache
Set-Cookie: wordpress_28d64d25126de860cca3405400362039=bobobibi%7C1561144987%7CIzNN4SFbUz5ji8jB6Tsr1ohP4YWU5Ajv5bxj8HLdXVR%7C235567cf23b625f3ec548cfc0bd6175f21f541716e291a4d52e85a2bb226649a; path=/wp-content/plugins; HttpOnly
Set-Cookie: wordpress_28d64d25126de860cca3405400362039=bobobibi%7C1561144987%7CIzNN4SFbUz5ji8jB6Tsr1ohP4YWU5Ajv5bxj8HLdXVR%7C235567cf23b625f3ec548cfc0bd6175f21f541716e291a4d52e85a2bb226649a; path=/wp-admin; HttpOnly
Set-Cookie: wordpress_logged_in_28d64d25126de860cca3405400362039=bobobibi%7C1561144987%7CIzNN4SFbUz5ji8jB6Tsr1ohP4YWU5Ajv5bxj8HLdXVR%7Cbbc1b1b3cb103b2e6dad2adf743ec2bc993903000c5fc49b3f0f57e864c64b78; path=/; HttpOnly
Set-Cookie: SERVERID87219=2720177|XQqLn|XQp+y; path=/
Transfer-Encoding: chunked
X-IPLB-Instance: 17025
X-Powered-By: PHP/7.2
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 2636
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryO5OhshRW070LBHJy
Cookie: _ga=GA1.2.101301333.1560485246; wp-settings-1=libraryContent%3Dbrowse%26edit_element_vcUIPanelWidth%3D650%26edit_element_vcUIPanelLeft%3D212px%26edit_element_vcUIPanelTop%3D177px%26editor%3Dtinymce; redux_blast=1560764097; _gid=GA1.2.1913651389.1560897223; wp-settings-time-1=1560969599; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_28d64d25126de860cca3405400362039=admin2044%7C1561144921%7CwQdAq6KappADp7wsYkiYCEI9F4WJ6dHuDOONJ2kZ8Tx%7C96a54c80973714629453e2e9a6bccc24aaa4b78dd2c2ea896ce9a284ae4c45f8; SERVERID87219=2720177|XQqLf|XQp+y
Host: mylivingbloom.com
Origin: http://mylivingbloom.com
Referer: http://mylivingbloom.com/?page_id=328&preview=1&cf_preview=CF5d0a814b1f62a
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
X-Requested-With: XMLHttpRequest
cf_api: CF5d0a814b1f62a
con_current: CF5d096ccdcb645
con_base: CF5d0a814b1f62a
_cf_verify: a2845a45dc
_wp_http_referer: /?page_id=328&preview=1&cf_preview=CF5d0a814b1f62a
_cf_frm_id: CF5d0a814b1f62a
_cf_frm_ct: 1
cfajax: CF5d0a814b1f62a
_cf_cr_pst: 328
phone: 
fld_9520536: test
fld_4436908: admin2044
fld_1924499: bobobibi
cffld_stage: CF5d096ccdcb645
instance: 1
request: http://mylivingbloom.com/?cf_api=CF5d0a814b1f62a&con_current=CF5d096ccdcb645&con_base=CF5d0a814b1f62a
formId: CF5d0a814b1f62a
postDisable: 0
target: #caldera_notices_1
loadClass: cf_processing
loadElement: _parent
hiderows: true
customCallback: cf_connected_ajax_handler
action: cf_process_ajax_submit
cfajax: CF5d0a814b1f62a
template: #cfajax_CF5d0a814b1f62a-tmpl

**Comment by New0** [comment]
Hello @tolarcible , your are reporting your issue with pro add-ons, please reach our support channel at https://calderaforms.com/support/
