### ISSUE TITLE
Hide Label option breaking Conditional Logic 

### ISSUE THREAD

**Issue by adamjayb** [CalderaWP/Caldera-Forms#3269]
Caldera Forms Version: 1.8.5
PHP Version: 7.0.33

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?

Have yet to attempt. 

**Update: upon testing, it does not seem to be an issue with the plugin as it does now work normally. A plugin or other must be conflicting with it...**

## What Is The Unexpected Behaviour?

Upon enabling the Hide Lable option within a field that is also set to Show or Hide the field via Conditional Logic, the field's Conditional Logic breaks for some reason and does not Show the field at all when proven true.

## What PHP Errors Have You Logged While Reproducing This Bug?

None. I am looking into a staging site for testing.

## What JavaScript Errors Have You Seen While Reproducing This Bug?

None.

**Comment by adamjayb** [comment]
Ginger Cookie plugin was conflicting. Deactivated and works as expected.

**Comment by maxhaslbeck** [comment]
Something similar happend to me. After deactivating plugin [CM Tooltip Glossary](https://www.cminds.com/wordpress-plugins-library/tooltipglossary/) it works as expected.
