### ISSUE TITLE
Not possible installing Caldera

### ISSUE THREAD

**Issue by peterrimsby** [CalderaWP/Caldera-Forms#3271]
I am trying to install Caldera to Wordpress. I have tried several times and only get an errormessage that says that installing was impossible.
![Installing not possible](https://user-images.githubusercontent.com/52165339/60022982-31203a80-9695-11e9-977b-7070b0f836ee.JPG)

**Comment by gitdrift** [comment]
Try downloading from https://wordpress.org/plugins/caldera-forms/ and then upload Caldera Forms plugin folder to your wp-content/plugins directory.

**Comment by Shelob9** [comment]
Related #3259

**Comment by New0** [comment]
This should have been fixed in the svn channel ( removing an extra folder trunk folder copied to tags/1.8.5 ).
I'm closing as this has stopped being reported since the svn fix.
