### ISSUE TITLE
Few Updates that i need

### ISSUE THREAD

**Issue by NabeelMahmood** [CalderaWP/Caldera-Forms#3279]
Hello,

There are a few things that I want to discuss.

1. How can i show warnings in caldera forms against validations?
2. How can i highlight rows with different colors?
3. How can i delete button to remove rows in User - End View?

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template. I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue. Right now I have no idea what is going wrong on your site.

Please open a new ticket following the new issue template.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
