### ISSUE TITLE
Using a mask isn't working

### ISSUE THREAD

**Issue by guyinpv** [CalderaWP/Caldera-Forms#3290]
## Do You Need Immediate Help?
Not really, but would like to finish this project.

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?

WordPress Version: 5.1.1PHP Version: 7.2.18-1+ubuntu18.04.1+deb.sury.org+1MySQL Version: 5.7.26Caldera Forms Version: 1.8.5

## What Is The Unexpected Behaviour?

I used a text field so that I could use the mask on it. I want to be able to enter a standard currency type number, or basically a number with two decimals.

I couldn't get this to work no matter how many tries to adjust the mask. Even something as simple as "9{5}" doesn't work and doesn't limit to 5 chars. The mask I want is something more like "9[.{1}99]". Or "any numbers, and then an optional period with 2 numbers".

When I use the actual number field, there is no mask available, so I had to use the text box field to use a mask. I set the HTML 5 type to number or text, doesn't make a difference.

Even just doing "99999" doesn't limit it to 5 numbers. And when I use something like "9{*}", it still allows the letter "e".

These masks seem to be all over the place, I've been searching for how to simply make a field for entering currency and can't seem to do it. I also need to calculate based on these numbers so I'd like them validated with the mask if possible.

## What PHP Errors Have You Logged While Reproducing This Bug?
No php errors.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None happen.

Thanks.

**Comment by New0** [comment]
Hello @guyinpv , the mask 9[.{1}99] will work with an html5 text kind of field. Also, did you enable the "enable input mask" option ?

If you still have this issue, reopen the ticket describing the steps that lead to the issue, attach an export of the form if possible.
Or if you have trouble setting the mask reach out to our support channel at https://calderaforms.com/support/
