### ISSUE TITLE
Uncaught Error: vi is not available in the catalog

### ISSUE THREAD

**Issue by tuanbbhero** [CalderaWP/Caldera-Forms#3295]
Failed to load resource: the server responded with a status of 404 (Not Found)
mysite.com/wp-content/plugins/caldera-forms/assets/js/i18n/vi.js?ver=1.8.5

Uncaught Error: vi is not available in the catalog
    at m.setLocale (parsley.min.js?ver=1.8.5:2)
    at i.window.Parsley.<computed> [as setLocale] (parsley.min.js?ver=1.8.5:3)
    at (index):1325

I encountered this problem from previous versions, to the current version (when I use Vietnamese at Settings > General).

**Comment by New0** [comment]
Hello @tuanbbhero , thank you for reporting this issue. This comes from the ParsleyJS library that is used for messages in the validation process. Unfortunately it has not been translated to Vietnamese.

In the case you wish to contribute you can on the original repo at https://github.com/guillaumepotier/Parsley.js/blob/master/CONTRIBUTING.md or here sharing a vi.js file formatted as the other files you will find in this repo at  [assets/js/i18n/](https://github.com/CalderaWP/Caldera-Forms/tree/master/assets/js/i18n).

In the case you wish to contribute for general Vietnamese translation of the plugin, you can use https://translate.wordpress.org/projects/wp-plugins/caldera-forms/

**Comment by tuanbbhero** [comment]
@New0 Thanks. I'm not developer. 
So, to solve the problem, I have 2 ways
+ Translating the vi.js file then upload to [assets/js/i18n](https://github.com/CalderaWP/Caldera-Forms/tree/master/assets/js/i18n)
+ Or translate the plugin at Translate.WordPress.org (I'm translating from a few months ago, but it has a lot, so it will probably take some months to complete).

Is that right? Thank you very much <3

**Comment by New0** [comment]
Hey @tuanbbhero , I realize my answer was misleading, I'm sorry.

To fix this precise error message shown in the console logs ( Uncaught Error: vi is not available in the catalog ) you need to add a ( valid ) vi.js file within the assets/js/i18n directory, that is correct.

The files within the assets/js/i18n directory hold the translations for forms validation messages, it is not so long and can be useful to your users if the form catches a validation issue before submission.

The link to Translate.WordPress.org was just to show the way to translate the plugin and is not related to the precise issue you shared here.

In the case you translate the vi.js, please share it to be in a future release for other Vietnamese users.

**Comment by Shelob9** [comment]
@New0 I think this is a bug. If vi language file doesn't exist, we should not try to use it.

**Comment by tuanbbhero** [comment]
@New0 @Shelob9 I downloaded the [en.js](https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/i18n/en.js) file, translated it, and then upload it to assets/js/i18n in Caldera Form folder in my wp-content folder.
And now, it show
index.min.js?h=729675415&ver=1.8.5:30 Uncaught ReferenceError: wp is not defined
    at Object.<anonymous> (index.min.js?h=729675415&ver=1.8.5:30)
    at Object.845 (index.min.js?h=729675415&ver=1.8.5:30)
    at t (index.min.js?h=729675415&ver=1.8.5:1)
    at calderaForms.render.0 (index.min.js?h=729675415&ver=1.8.5:1)
    at index.min.js?h=729675415&ver=1.8.5:1
My site: https://bds05.imar.vn/

**Comment by New0** [comment]
@Shelob9 Thank you, that makes sense I didn't think of the issue all the way.

@tuanbbhero could you share the file please ?

**Comment by tuanbbhero** [comment]
@New0 Here is file https://github.com/tuanbbhero/Custom-Code/blob/master/vi.js

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/b9723874099e053e87fbfbcd03f71c18f9388301
