### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MalaThapar** [CalderaWP/Caldera-Forms#3301]
Please advise? All forms stopped working 
![Screenshot_20190729-120919_Chrome](https://user-images.githubusercontent.com/52290683/62044043-dc269580-b1f9-11e9-8bfe-82c4dc2b227e.jpg)

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by New0** [comment]
Hello @MalaThapar , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

In this case it seems that you already have a caldera-forms folder in wp-content/plugins, delete this folder and try to install again.

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
