### ISSUE TITLE
Caldera Form HTML date language issue - Between 2 dates Condition

### ISSUE THREAD

**Issue by ClaraVassettt** [CalderaWP/Caldera-Forms#3309]
Hi Dear Team, 
>>> I am using Calendera form and don't find how to change the language of the calendar, it is displayed in English, I need it in French.
![Untitled-1](https://user-images.githubusercontent.com/53571369/62300624-6f203380-b477-11e9-8e42-0db55755fbcd.jpg)

>>> In the conditions I would like to set a price between 2 dates, for exemple departure between march and april is 20 € and departure between september and october is 40 €, is it possible? 
![Untitled-2](https://user-images.githubusercontent.com/53571369/62301129-4a788b80-b478-11e9-914c-90adbc5cafb9.jpg)

THANK YOU VERY MUCH FOR YOUR HELP

CALDERA FORMS IS AMAZING!!!

Best Regards, 
Clara

**Comment by New0** [comment]
Hello @ClaraVassettt , thank you for you kind words. There is a date picker field that has a language option in the the select types of fields. Date calculations are not a feature. 

If you need any other help, please contact support via https://calderaforms.com/support/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
