### ISSUE TITLE
How to show the single price, not just the total

### ISSUE THREAD

**Issue by RobertMarshall75** [CalderaWP/Caldera-Forms#3311]
Hi everyone,

how can I show the price of the products and not just the total? 
Adding the price manually after the description of the product is not the best choice, also because the prices would not be aligned. 

Thanks in advance for your help.

- Caldera Forms: 1.8.6 
- WordPress Version: 5.2.2
- PHP Version: 7.2

**Comment by New0** [comment]
Hello @RobertMarshall75  , for support please go to https://calderaforms.com/support/ .

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
