### ISSUE TITLE
round Function is causing a blank total in the new update (manual format)

### ISSUE THREAD

**Issue by noahmason101** [CalderaWP/Caldera-Forms#3316]
round Function is causing a blank total in the new update  manual format)
caldera version 1.8.6 
php version 7.3.7
WP Version 5.2.2
it was working fine before but now it just gives me a blank result

**Comment by New0** [comment]
Thank you for reporting the issue @noahmason101 

Last update introduced a trim to manual calculation during form saving, this caused the r of round to be removed. #3283

**Comment by oldrup** [comment]
Oh just ran into this bug as well, javascript console shows this:

 `function do_calc_fld_3294810_1(state){return ound(30000/state.getCalcValue('fld_6237027_1', false ));}
`
Notice the "ound" vs "round".

Hoping for a quick fix for this one, I use round in so many forms 👍

**Comment by oldrup** [comment]
Issue can be worked around until a fix is present, but prefixing the calculation with 0+

like this

`0+round(30000/%typisk_besparelse%)`

The 0+ does not get trimmed, and does not affect the calculation.

**Comment by paaljoachim** [comment]
Btw
Thanks for the information about adding 0+ that worked for the calculator I am using on the new dev site where I have 1.8.6 installed and the r in round is stripped out. 

The live site
https://celias.no/bestilling/
uses Caldera forms version 1.8.5 and round works there. I am glad I did not update to 1.8.6 on the live site yet.

**Comment by New0** [comment]
Thank you very much @oldrup for your quick fix.

Closed via https://github.com/CalderaWP/Caldera-Forms/commit/c855e0709c95436fae0b492e6054098fdba1eac5
