### ISSUE TITLE
How to fix the filling of the form that has become too slow

### ISSUE THREAD

**Issue by RobertMarshall75** [CalderaWP/Caldera-Forms#3319]
Hi everyone,

I'm creating a form with Caldera Forms.
It is a dropdown form, with conditional groups.
When I publish it online, it is very fast. I like it.
**The issue is during its filling... The form has become obviously quite big and I need about 3 minutes before to complete 1 field! It is so laggy.**

My hosting is good and quite fast.
I disabled the plugins I had installed but the issue remains.

Please, someone have some idea or trick to fix that?

Thanks in advance.

**Comment by New0** [comment]
Hello @RobertMarshall75 , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs

**Comment by RobertMarshall75** [comment]
Why my messages are closed, while others similar to mine are open with several replies?
