### ISSUE TITLE
Remove deleted videos in readme.txt

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3320]
All but the first video in the readme is a 404, we need to remove those links as the videos were deleted.

**Comment by Shelob9** [comment]
Fixed in these SVN commits and addressed in PR #3321
- https://plugins.trac.wordpress.org/changeset/2139028/caldera-forms
- https://plugins.trac.wordpress.org/changeset/2139024/caldera-forms

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/7d92363ce6bcda31b6abc55d555844c0a5c02932
