### ISSUE TITLE
First letter of code stripped - calculations not working

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#3324]
First letter in calculation stripped.

Dugnadskalkulator calculator form. It can be seen here. https://celias.no/bestilling/ 
An unique way of using Caldera Forms.

I import it into a site, and everything looks good.
This calculation:

round(%deltakere_slider%*%antall_produkter_slider%*%utsalgspris_slider%)-(%deltakere_slider%*%antall_produkter_slider%*90)

The r in round is stripped. I even add an additional r and that is also stripped.

The calculator does not work.

Here is the exported form: https://www.dropbox.com/s/r9s1uvof6qgr5pe/dugnadskalkulator-2018-export.json?dl=0

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms: 1.8.6
WordPress: 5.2.2
PHP: 7.3.8

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
I imported the form into a local site using Twenty Nineteen and had only Caldera Forms activated. I noticed the same error there.

## What Is The Unexpected Behaviour?
Stripped away r in round in the calculator field.

![Screen Shot 2019-08-14 at 22 13 25](https://user-images.githubusercontent.com/5323259/63052925-cc3cd000-bee0-11e9-95f8-e9de7f67d9c6.png)

## What JavaScript Errors Have You Seen While Reproducing This Bug?

Console errors:

Uncaught ReferenceError: ound is not defined
    at do_calc_fld_4655952_1 (?page_id=289&preview=1&cf_preview=CF5b8526d7eaa56:328)
    at g (caldera-forms-front.min.js?ver=1.8.6:1)
    at caldera-forms-front.min.js?ver=1.8.6:1
    at g (caldera-forms-front.min.js?ver=1.8.6:1)

![Screen Shot 2019-08-14 at 22 14 53](https://user-images.githubusercontent.com/5323259/63052999-fabaab00-bee0-11e9-98af-de44308298a1.png)

Short Debug Information
WordPress Version: 5.2.2PHP Version: 7.3.1MySQL Version: 5.5.5Caldera Forms Version: 1.8.6WP_DEBUG:
Full Debug Information
WordPress Version: 5.2.2

PHP Version: 7.3.1

MySQL Version: 5.5.5

Server Software: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.1 mod_perl/2.0.8-dev Perl/v5.16.3

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

Session Save Path: /Applications/XAMPP/xamppfiles/temp/

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: Twenty Nineteen: 1.4

**Comment by paaljoachim** [comment]
Duplicate of: https://github.com/CalderaWP/Caldera-Forms/issues/3316

**Comment by New0** [comment]
Hi @paaljoachim , thanks for the details there an open PR for that #3318 , we'd like to push an update really soon to fix this

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/c855e0709c95436fae0b492e6054098fdba1eac5
