### ISSUE TITLE
Caldera-Forms not working subscriber role user login side Bar Intention not showing and not show edit 

### ISSUE THREAD

**Issue by deepvinsoft** [CalderaWP/Caldera-Forms#3325]
Caldera-Forms not working subscriber role user login side Bar Intention not showing and not show popup edit, show this error (" You are not allowed to view this. " )

**Comment by New0** [comment]
Hello @deepvinsoft , we need more information and context, could you detail the step to take to reproduce this issue ?

If it's support that you need, please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
