### ISSUE TITLE
External forms are not available in the widget

### ISSUE THREAD

**Issue by ictbeheer** [CalderaWP/Caldera-Forms#3341]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.3PHP Version: 7.2.22MySQL Version: 5.6.45Caldera Forms Version: 1.8.7WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When external forms are included using the 'caldera_forms_get_forms' they are not available in the widget.

## Cause
This happens because the variable $forms in which they are stored gets overwritten a few lines later.

https://github.com/CalderaWP/Caldera-Forms/blob/ff614a4bd16381f92d6314a0d2f907f4951938d2/classes/forms.php#L186-L199

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by ictbeheer** [comment]
Is same as #3345 which has a pull request.

**Comment by Shelob9** [comment]
I'm reopening this as this describes an effect of the low-level bug described in #3349

**Comment by Shelob9** [comment]
SHOULD be fixed by #3354

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/39f19c2829c80e45035be0deb4d11f66047e0611
