### ISSUE TITLE
Programatically created Form does not play well with DB created Form

### ISSUE THREAD

**Issue by Luc45** [CalderaWP/Caldera-Forms#3345]
Caldera relies on the `caldera_forms_get_forms` filter to provide an "existence" to the Forms that were created programmatically and does not exist in the database.

That filter is applied in `\Caldera_Forms_Forms::get_forms`: https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/forms.php#L178-L199

It applies the filter at line 186, but overrides it again to the original value on line 198.

Despite that, methods such as `\Caldera_Forms::render_form` might continue working, because of a `!empty($forms)` assertion. Check line 4278 of `core.php`: https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L4278

That probably means that two bugs co-exist generating an erratic behavior. If `$forms` return empty, it will not try to check for the existence of the Form, thus will continue the processing and will actually output the form. If `$forms` contain anything (such as a form saved on the database), it will assert if the form ID we are trying to render exists. That will fail because the filter was overridden, so `render_form` will just return null.

Possible solution:

Before:
```
if( $with_details ){
	$forms = self::add_details( static::$index );
}else{
	$forms = static::$index;
}
```

After:
```
if( $with_details ){
	$forms = self::add_details( static::$index );
}
```

**Comment by Luc45** [comment]
PR opened: https://github.com/CalderaWP/Caldera-Forms/pull/3349

**Comment by Shelob9** [comment]
@Luc45 Thanks for the detailed report. I opened #3354 which SHOULD fix this.

**Comment by ictbeheer** [comment]
Could #3354 please be merged? It is working for me, but now I have to manually apply this patch after every CF update to be able to use external forms.

**Comment by Shelob9** [comment]
@New0 is this one on your list for next update? Should be easy win.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/39f19c2829c80e45035be0deb4d11f66047e0611
