### ISSUE TITLE
20 spam emails from Caldera Forms

### ISSUE THREAD

**Issue by vaka2vaka** [CalderaWP/Caldera-Forms#3348]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera  1.8.7
WordPress 5 2 3
PHP 7 2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?

20 letters arrive in one second from the form
The address from which they came to the site is marked as spam  (https://cleantalk.org)
Here are the log files
May help

5.53.120.214 - - [13/Sep/2019:15:20:06 +0300] "GET /rolstavni/rolstavni-dlya-shkafa HTTP/1.0" 200 23641
5.53.120.214 - - [13/Sep/2019:15:20:06 +0300] "POST / HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:06 +0300] "GET /?cf_su=1 HTTP/1.0" 200 106189
5.53.120.214 - - [13/Sep/2019:15:20:07 +0300] "POST /mail.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:07 +0300] "GET /mail.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:08 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:08 +0300] "POST /mail HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:08 +0300] "GET /mail?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:09 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:09 +0300] "POST /feedback HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:09 +0300] "GET /feedback?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:09 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:09 +0300] "POST /feedback.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:10 +0300] "GET /feedback.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:10 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:10 +0300] "POST /action HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:10 +0300] "GET /action?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:10 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "POST /action.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "GET /action.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "POST /callmeback HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "GET /callmeback?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:11 +0300] "POST /callmeback.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "GET /callmeback.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "POST /getcall HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "GET /getcall?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "POST /getcall.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "GET /getcall.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:12 +0300] "POST /getcall.html HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET /getcall.html?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "POST /sm.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET /sm.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "POST /sm.php.html HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET /sm.php.html?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "POST / HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:13 +0300] "GET /?cf_su=1 HTTP/1.0" 200 106189
5.53.120.214 - - [13/Sep/2019:15:20:14 +0300] "POST /index HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:15 +0300] "GET /index?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:15 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:15 +0300] "POST /index.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:15 +0300] "GET /index.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:15 +0300] "GET /?cf_su=1 HTTP/1.0" 200 106189
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "POST /callme HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "GET /callme?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "POST /callme.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "GET /callme.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:16 +0300] "POST /contacts.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "GET /contacts.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "POST /mail3.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "GET /mail3.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "POST /mail_4.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "GET /mail_4.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:17 +0300] "GET / HTTP/1.0" 200 106333
5.53.120.214 - - [13/Sep/2019:15:20:18 +0300] "POST /process.php HTTP/1.0" 302 -
5.53.120.214 - - [13/Sep/2019:15:20:18 +0300] "GET /process.php?cf_su=1 HTTP/1.0" 301 -
5.53.120.214 - - [13/Sep/2019:15:20:18 +0300] "GET / HTTP/1.0" 200 106333

After that, with caldera forms comes 20 email notifications

**Comment by New0** [comment]
Hello @vaka2vaka , Caldera Forms don't trigger emails, you'll find spam issues information at https://calderaforms.com/doc/protect-form-spam-caldera-forms/

For support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
