### ISSUE TITLE
No Stripe token found, please wait for the page to load fully and try again

### ISSUE THREAD

**Issue by robertschmid001** [CalderaWP/Caldera-Forms#3350]
WordPress Version: 4.9.11PHP Version: 5.6.40MySQL Version: 5.6.43Caldera Forms Version: 1.7.2WP_DEBUG: 1

**## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?** YES

**## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.**

Currently using CalderaForms and had to integrate Mailchimp aswell as Stripe into it. 

**BACK:** On submission of the form, I installed the processes, added a value as a hidden value "subscribe_amount=10". placed an email value and added the necessary tokens from the creation of my Stripe account.

**FRONT:** I click on Submit, it turns for a second then relays this error message: 
Status Code: 200 
Error: No Stripe token found, please wait for the page to load fully and try again

I've tried disabling all plugins as well as changing Themes, but it was to no avail.

Any tips and tricks?  I'm new to Wordpress and PhP.
Thank you!

**Comment by New0** [comment]
Hello @robertschmid001 , since this concerns paid add-ons, please reach out to support at https://calderaforms.com/account/

Also make sure to update WordPress and Caldera Forms to test again, this error indicates the Stripe add-on is also an old version.
