### ISSUE TITLE
Map wp-content/plugins in docker-compose so it's easier to work with add-on plugins

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3358]
I always do this locally, meant to commit it. If we map wp-content/plugins in docker-compose, adding an add-on or in my case Ninja Forms, adding an additional plugin is easy, just add it to the directory.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/pull/3359
