### ISSUE TITLE
The resend button in entries list view fails to resend the email

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3365]
Reported : 
- https://secure.helpscout.net/conversation/959846678/23189
- https://secure.helpscout.net/conversation/953797619/23085

While on the form entries list view, clicking the Resend button don't seem to trigger the desired event.

There is an opened issue reporting this that has been opened for a long time and failed our vigilance. 

Related to #3151 and possibly related #2797 

It seems like the markup uses a <button> when it is working with an <a> tag

**Comment by New0** [comment]
Also reported at - https://secure.helpscout.net/conversation/981366373/23542/ -

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/pull/3477

**Comment by cymode** [comment]
This has not been fixed with 1.8.10. None of our pages can resend e-mails from the backend entries section.  It says 'email resent' but nothing is actually being sent.
