### ISSUE TITLE
Variables set in processors are unset after form edition

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3374]
Reported via - https://secure.helpscout.net/conversation/950098119/23002/ -

After creating a variable and setting the variable in a processor, the variable is unset from the processor whenever the form is edited.

If the form is not edited(re-saved) the variable could be not showing but is still set during form processes and appears to work.

**Comment by New0** [comment]
Seems also related - https://secure.helpscout.net/conversation/980498333/0/?folderId=832038 -

**Comment by lukebullock** [comment]
Can confirm this is happening on a site I manage. 

It is extremely frustrating when you have more than 30 processors. The variables are removed from the processor and unavailable from the dropdown selector even though the variables still show up under the variables tab. If you create a new variable the old variable will be made available in the dropdown selector in the processor again.

**The way I am having to workaround this bug:** 

1. Create a new unnecessary variable and then return to the conditional processor; the old variable should now show up in the dropdown list and be selectable...select it.
2. Delete the unnecessary variable you just created.
3. Rinse and repeat for every single processor using the variable. 
4. Save form.
5. Pray that client doesn't want any more updates.

**Comment by Shelob9** [comment]
Close via #3466
