### ISSUE TITLE
Resend Button Not Working and Image URLs show 404 Error

### ISSUE THREAD

**Issue by kaposiopesis** [CalderaWP/Caldera-Forms#3377]
## Do You Need Immediate Help?
It would help if you can

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.4PHP Version: 5.6.40MySQL Version: 10.1.41Caldera Forms Version: 1.8.7WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
I don't want to attempt since my site must be up at all times at this time

## What Is The Unexpected Behaviour?
**Problem 1:** Not all entries sent using [this form](http://www.craftstorycebu.com/christmasfeature/) is sent to our email. Have gone through your FAQs and through the entries here but I can't seem to find a fix for it.
**Problem 2:** When accessing the entry list, nothing happens when i click "Resend".
**Problem 3:** When trying to access the URL of the images that are supposedly uploaded via the form, it shows a 404 Error. For example [this URL](http://www.craftstorycebu.com/wp-content/uploads/6827aa2fd503abddf4045dd885c51207/room1.jpg) is supposed to be an image.

## What PHP Errors Have You Logged While Reproducing This Bug?
N/A?

## What JavaScript Errors Have You Seen While Reproducing This Bug?
N/A?

**Comment by New0** [comment]
@kaposiopesis Problem 2 is being worked on via #3365  your problems 1 and 3 are support questions related to email delivery and files set not to be stored in the files folder of WordPress.

If you are still having these issues, reach out to https://calderaforms.com/support/ .
