### ISSUE TITLE
Problème - je ne reçois pas les emails

### ISSUE THREAD

**Issue by Sallycoh18** [CalderaWP/Caldera-Forms#3384]
Depuis deux semaines, je ne reçois plus les mails qui me sont envoyés depuis mon site.
Mon problème persiste même lorsque je désactive les autres plug-ins et passe à un theme par default... Je ne sais quoi faire.

Ps: Tout est à jours sur le site plugin + la version du PHP.

Merci d'avance pour votre aide.

**Comment by New0** [comment]
Hello @Sallycoh18  , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
