### ISSUE TITLE
U.S. State preset lists Iowa as "IAIowa"

### ISSUE THREAD

**Issue by etoler1841** [CalderaWP/Caldera-Forms#3389]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.4PHP Version: 7.2.24MySQL Version: 5.5.5Caldera Forms Version: 1.8.7WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When using the preset select options for "U.S. States," Iowa populates as "IAIowa"

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/225377ad5951b9ba1f20ee1bd4f837dff8c33c20
