### ISSUE TITLE
Feature: Phone number already exists

### ISSUE THREAD

**Issue by IdioticDoodler** [CalderaWP/Caldera-Forms#3400]
Hi guys.
Cam Caldera form do this? Once the user sends a form, the phone number he used can not be used again anymore. Thanks

**Comment by New0** [comment]
Hello @IdioticDoodler , for support or questions please go to https://calderaforms.com/support/ .

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs
