### ISSUE TITLE
Fields applied a condition are not included in resend emails

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3402]
Reported at -https://secure.helpscout.net/conversation/981366373/23542/ -

When using the resend option in the entry viewer, if fields were applied a condition, the value of the field won't be included in the email. Even in the case the condition is met and a value was given to the field.

**Comment by Shelob9** [comment]
In the class that handles resending the email, the saved data is loaded here: https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/email/resend.php#L90

I tested with a submisison with a saved field that has a SHOW conditional applied to it that should pass. That field's saved value returned by `Caldera_Forms::get_submission_data()` is null, when check conditonals argument is true. Changing that argument to false is NOT a valid solution beacuse we do NOT want fields that should be hidden from being in email.

Not sure if bug is `Caldera_Forms::get_submission_data()` is not working right or that `Caldera_Forms::get_submission_data()` should not be used in this context.

**Comment by Shelob9** [comment]
Should be fixed via #3473

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/1106bb856b53f6df00d881947ccd79901ca45d01 -
