### ISSUE TITLE
Calculation fields do not update when revealed in conditional

### ISSUE THREAD

**Issue by Stegosource** [CalderaWP/Caldera-Forms#3403]
## Do You Need Immediate Help?
It would be nice.

## Is This A Feature Request?
It is not.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.3 PHP Version: 7.2.24 MySQL Version: 5.7.28 Caldera Forms Version: 1.8.8 WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## Steps to reproduce
- Create a form
- Add a number field (no default)
- Add a checkbox field (unchecked by default)
- Add a calculation field that shows the number from the number field
- Create a condition that only shows the calculation if the checkbox is checked.
- Publish and go to form
- Fill in number field
- Check checkbox field 

## Expected behavior
After filling in the number and checking the checkbox, the calculation field should appear and show the calculation based on the number input.

## Actual behavior
After filling in the number and checking the checkbox, the calculation field appears, but the calculation is not implemented. It only fires after the number field is changed again.

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP errors

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No JS errors.

## Comments
It looks like the conditional fields are not added to the page until the condition is met. Then I assume there is an event listener attached to the calculation fields. If this event listener was also fired on the mounted event, that should solve the issue.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/4152f4933216bf69d420d471ee6e8a19d6c20447
