### ISSUE TITLE
Invalid Form - E_ERROR

### ISSUE THREAD

**Issue by kleymc** [CalderaWP/Caldera-Forms#3408]
Received an auto message from Wordpress install about tech difficulties with Caldera form. The forms were working today. i installed a couple of plugins (Better Search and replace and WP Cache) and have now uninstalled to check bt still an issue. I have disabled all plugins installed. Any guidance please:

Error Details
=============
An error of type E_ERROR was caused in line 768 of the file /home/ncwqorg/public_html/2020/wp-content/plugins/caldera-forms/classes/forms.php. Error message: Uncaught TypeError: Argument 1 passed to Caldera_Forms_Forms::get_fields() must be of the type array, string given, called in /home/ncwqorg/public_html/2020/wp-content/plugins/caldera-forms/classes/shortcode/atts.php on line 48 and defined in /home/ncwqorg/public_html/2020/wp-content/plugins/caldera-forms/classes/forms.php:768
Stack trace:
#0 /home/ncwqorg/public_html/2020/wp-content/plugins/caldera-forms/classes/shortcode/atts.php(48): Caldera_Forms_Forms::get_fields('p')
#1 /home/ncwqorg/public_html/2020/wp-includes/class-wp-hook.php(286): Caldera_Forms_Shortcode_Atts::allow_default_set(Array, Array, Array, 'caldera_form')
#2 /home/ncwqorg/public_html/2020/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#3 /home/ncwqorg/public_html/2020/wp-includes/shortcodes.php(575): apply_filters('shortcode_atts_...', Array, Array, Array, 'caldera_form')
#4 /home/ncwqorg/public_html/2020/wp-content/plugins/caldera-forms/classes/core.php(5017): shortcode_atts(Array, Array, 'caldera_form')
#5 /home/ncwqor

**Comment by New0** [comment]
Hello @kleymc  , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:
-  share the details to reproduce the issue
- share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab
- report if the issue persists with all other plugins disabled and theme twentynineteen activated.
- share PHP and JS logs
