### ISSUE TITLE
Infinite adds for a specific question

### ISSUE THREAD

**Issue by nexgraphics** [CalderaWP/Caldera-Forms#3409]
I need to know if Caldera can do this:

Im building this form for an insurance agent and one of the questions is:

1)Vehicle #1:   a)Make   b)Model    c)Value

Once they add that in, then I need to ask "any more vehicles"?   If they click on YES, to have another of the same thing open, as 
Vehicle #2   a)Make   b)Model    c)Value    etc etc etc. 

Someone can have MANY vehicles, is there any way to set this up as "infinite" without me having to constanly in the FORM design keep asking this again and again, another conditon, another conditon, etc because after 10 I stopped it was really annoying....

Thanks!

**Comment by New0** [comment]
Hello @nexgraphics  , for support please go to https://calderaforms.com/support/ .
You will find your license key at https://calderaforms.com/checkout/purchase-history/

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs

**Comment by nexgraphics** [comment]
WOW< I cannot believe it took this long for you guys to get back to me.    That being said, I will not encourage my client to pay for your form if this is how bad the support is.

Sincerely,

Lee Levy
Nex Graphics
www.nexgraphics.com<http://www.nexgraphics.com>
lee@nexgraphics.com<mailto:lee@nexgraphics.com>
818.888.8235
