### ISSUE TITLE
Hide CF Pro menu/ UI if CF Pro not active

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3413]
To reduce confusion, only show CF Pro menu/ tab IF it is active.

Add a filter that sets CF Pro UI to show or not. 
```
/**
 * Should we add Caldera Forms Pro sub-menu page and UI
 *
 * @since 1.8.9
 *
 * @param bool $show_pro Whether to show or not
 */
$show_pro = apply_filters( 'caldera_forms_show_pro_ui', caldera_forms_pro_is_active() );
```

If Caldera Forms Pro is activated, that filter would default to true, and UI would show.  If Caldera Forms Pro is activated, that filter would default to true, and UI would show. 

If Caldera Forms Pro is not active to activate it, customer would have to add this filter:

```
add_filter( 'caldera_forms_show_pro_ui', '__return_true' );
```

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/fd9e9470c85c8102d151696fb959fcccc275c413
