### ISSUE TITLE
Prevent get_field_data() from always returning null for string form IDs

### ISSUE THREAD

**Issue by telwing** [CalderaWP/Caldera-Forms#3416]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.3
PHP Version: 7.3.6
MySQL Version: 8.0.16
Caldera Forms Version: 1.8.8
WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Pass a string form ID to `Caldera_Forms::get_field_data()` and it will always return `null`.

**Comment by telwing** [comment]
See pull request: [https://github.com/CalderaWP/Caldera-Forms/pull/3417](https://github.com/CalderaWP/Caldera-Forms/pull/3417)

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/4ee87fb2cb2ede2d73137422c7d81276295e2883
