### ISSUE TITLE
"Entry limiter" with some limits

### ISSUE THREAD

**Issue by elasticeye** [CalderaWP/Caldera-Forms#3418]
Ok, so I'm testing out Entry Limiter (pro addon) and it has one important limit:
It doesn't work with conditions.

I want to limit entry based on the choice someone makes in a dropdown menu. That is (as far as I am aware of) not possible. 

Could this be implemented?

**Comment by New0** [comment]
Hello @elasticeye  , you will find a filter hook that will help you set the limit by precise option - https://calderaforms.com/doc/cf_entry_limiter_entry_limit/ - if you need more help with that, contact support via https://calderaforms.com/support/ .

Best wishes.

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs
