### ISSUE TITLE
Run php and JS unit tests in gitlab ci

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3437]
The Github actions we have do not work -- old format. Gitlab is already running WordPress integration tests.

**Comment by 123aqua** [comment]
@Shelob9 Hi can you help me with something When I fill up phone number it says undefined I'm using caldera forms here is the screen shot
![16](https://user-images.githubusercontent.com/59171353/72647626-ead55480-39b3-11ea-987d-fc17df279a99.png)

**Comment by Shelob9** [comment]
Close via #3438

**Comment by Shelob9** [comment]
@123aqua Thanks for using Caldera Forms, I appreciate it. I've deleted your comment, as it is not related to this issue. If you belive you have found a bug, please open a new issue and fill out all of the requested information. If you want to submit a fix for the bug, that's super cool, please [review our contributor's guide before submitting a PR](https://github.com/CalderaWP/Caldera-Forms/blob/master/contributing/pull-request-workflow.md)

**Comment by 123aqua** [comment]
Hi can you help me with something When I fill up phone number it says
undefined I'm using caldera forms here is the screen shot
