### ISSUE TITLE
Alternative field names, i.e. slugs as field names

### ISSUE THREAD

**Issue by Bklaushh** [CalderaWP/Caldera-Forms#3452]
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

Hi, I am just starting with Caldera Forms and before buying the Pro version I would like to know if (and how) it is possible to store the input values under slug names (or other self created names) instead of using the field names displayed in the form. 
Example: instead of "Adresse in Hamburg" (displayed in form front end) I would like to use the slug "hh_adresse" or set "hh-adresse" as field name.
The reason is that we are processing the submitted data and would like to keep the field names we used in CF7.
Thanks a lot

**Comment by New0** [comment]
Hello @Bklaushh  , for support or questions please go to https://calderaforms.com/support/ .

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs
