### ISSUE TITLE
Caldera Forms Plugin Layout broken in WP 4.9.13

### ISSUE THREAD

**Issue by andrew01ait** [CalderaWP/Caldera-Forms#3454]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
Already submitted a ticket to the Caldera Pro Heldesk

## Is This A Feature Request?
It's a bug

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.13PHP Version: 7.0.33-0ubuntu0.16.04.9MySQL Version: 5.7.28Caldera Forms Version: 1.8.9WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes

## What Is The Unexpected Behaviour?
Since the update from Caldera Forms 1.7.7 version (last proper working version) to 1.8.9. the layout of both the plugin as well as the form builder is broken. It seems as if the corresponding CSS is not properly loaded? The same situation with WP 4.9 as it was described in the following ticket: https://github.com/CalderaWP/Caldera-Forms/issues/3251

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors reported

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors reported

## Attached Screenshots
https://prnt.sc/qqpmu2
https://prnt.sc/qqpmjo

**Comment by pbasset** [comment]
I encountered the same problem and opened a ticket as well. I needed to roll back to 1.8.0 to get access to my entries. Good luck!

**Comment by Shelob9** [comment]
Related #3205

**Comment by New0** [comment]
This add-on will enqueue admin styles again for WP < 5.0 - https://drive.google.com/open?id=12VvlLWBV4pW6DEQGcCnSBdWYpAEfN6KD -

**Comment by Shelob9** [comment]
I am closing this as WP 4.9 #3205 is not supported in CF 1.8.10 + and there is a workaround for old versions.
