### ISSUE TITLE
Can not access created form (form cache not  cleared)

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3455]
I'm testing with this:

```php
foreach (Caldera_Forms_Forms::get_forms(false,true) as $formId ){
        Caldera_Forms_Forms::delete_form($formId);
    }
    $form = \Caldera_Forms_Forms::create_form([
        'name' => 'One'
    ]);
    $form2 = \Caldera_Forms_Forms::create_form([
        'name' => 'Two'
    ]);
    $forms = \Caldera_Forms_Forms::get_forms(true,true);
    $form2FromDb = \Caldera_Forms_Forms::get_form($form2['ID']);
```

I expect there two be two forms in `$forms` and for `$form2FromDb['name]` to be 'Two'. I actually only have one form, whichever form I create first in `$forms` and `$form2FromDb['name]` is null. In the next session, `$forms = \Caldera_Forms_Forms::get_forms(true,true);` returns two forms.

Only the first created form is known to the API, beacuse get_form(s) methods use a cache that creating a new form does not clear.

**Comment by Shelob9** [comment]
This doesn't happen when using import_form() method, as that clears cache.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/f2a5e2869cf5dfb2e85c0301889be0cc4ee14762
