### ISSUE TITLE
Allow processor template to be a string

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3460]
Currently the processor UI template is loaded with include. https://github.com/CalderaWP/Caldera-Forms/blob/master/ui/panels/processors.php#L315-L320

For the email-crm project, I need to be able to generate the UI as a string of HTML.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/c7f32d76fb05e9d0066929413ba9c9d3fb002367
