### ISSUE TITLE
Introduce new cf2 services to aid in add-on development

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3463]
Related: https://git.saturdaydrive.io/_/engineering-ops/sd-email-crm/email-crm/issues/20 and #3134

## Problem

When developing the add-ons in email-crm project, we need to be able to test processors isolated from Caldera Forms. To do so, we need:

* An interface describing forms API that this also implimented in Caldera Forms core, that we can replace with a mock. I can't mock out `Caldera_Forms_Forms` methods beacuse you can't mock a static class method.

* An interface describing transients API that this also implimented in Caldera Forms core, that we can replace with a mock. [Exists already](https://github.com/CalderaWP/Caldera-Forms/tree/master/cf2/Transients)
* A factory for `Caldera_Forms_Processor_Get_Data` objects -- this class has internal dependencies to hard to mock methods of `Caldera_Forms` class.
* A way to get the real functional version of these services into the add-ons. [Can be done with existing container](https://github.com/CalderaWP/Caldera-Forms/blob/master/cf2/CalderaFormsV2.php) by adding new services

## Solution

Instead of creating this in the email-crm project, and maintaining it there, even though it would only break if core breaks, I will add new services to the CF2 container.

To ensure these service work, I will add unit and integration tests.

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/a853da57ed7cefc8a7921f507a738c50477d2edb -
