### ISSUE TITLE
Anti-Spam Bee support enabled?

### ISSUE THREAD

**Issue by strarsis** [CalderaWP/Caldera-Forms#3467]
As recommended on [this Caldera Forms doc](https://calderaforms.com/doc/protect-form-spam-caldera-forms/) I installed and enabled the [Anti-Spam Bee plugin](https://wordpress.org/plugins/antispam-bee/).
Do I have to enable options in Caldera and Anti-Spam Bee plugin or do I have to add a special form processor? How can I know whether it Anti-Spam Bee is protecting a Caldera Form against spam or not?

**Comment by strarsis** [comment]
https://github.com/pluginkollektiv/antispam-bee/issues/318

**Comment by New0** [comment]
Hello @strarsis  , for support or questions please go to https://calderaforms.com/support/ .

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs
