### ISSUE TITLE
Mark as spam/spam folder

### ISSUE THREAD

**Issue by strarsis** [CalderaWP/Caldera-Forms#3468]
Is it possible to mark specific form submissions as spam?
Is there some kind of spam subfolder?

**Comment by New0** [comment]
Hello @strarsis  , for support or questions please go to https://calderaforms.com/support/ .

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs
