### ISSUE TITLE
Deprecated: Unparenthesized `a ? b : c ? d : e` (deprecated usage in PHP7.4)

### ISSUE THREAD

**Issue by budrick** [CalderaWP/Caldera-Forms#3476]
## What Is The Unexpected Behaviour?
Occasionally, I'll see the following error either logged (or appear on frontend and admin pages with WP_DEBUG and WP_DEBUG_DISPLAY enabled):

```
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in (redacted)/wp-content/plugins/caldera-forms/classes/core.php on line 3724
```

This is due to the use of nested ternary operators and reliance on operator precedence rules without explicit parentheses. This usage of nested ternary operators without parens is deprecated in PHP 7.4, hence the notice. 

I haven't seen any other deprecation notices, but I suppose it doesn't mean they're not possibly there.

## What PHP Errors Have You Logged While Reproducing This Bug?
```
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in (redacted)/wp-content/plugins/caldera-forms/classes/core.php on line 3724

**Comment by ralphjesy12** [comment]
I just quickly enclosed it with parenthesis. If there's anyone who wants to make the PR
`../caldera-forms/classes/core.php:3724`
From:
```
$entry_id = !empty($wp_query->query_vars[ 'cf_entry' ]) ? $wp_query->query_vars[ 'cf_entry' ]
: isset($_GET, $_GET[ 'entry' ]) && absint($_GET[ 'entry' ]) ? $_GET[ 'entry' ] : null;
```

To:
```
$entry_id = !empty($wp_query->query_vars[ 'cf_entry' ]) ? $wp_query->query_vars[ 'cf_entry' ]
: (isset($_GET, $_GET[ 'entry' ]) && absint($_GET[ 'entry' ]) ? $_GET[ 'entry' ] : null);
```

**Comment by New0** [comment]
Thanks for reporting this issue, a PR was opened to address this and be reviwed for 1.9.0 milestone.

**Comment by artshostak** [comment]
Having the very same issue, when can we expect the parentheses to be added as this makes the Wordpress dashboard entirely unusable at the moment:


`The plugin generated 1859 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

![Screenshot 2020-06-12 12 59 54](https://user-images.githubusercontent.com/6820356/84541659-ade46400-acac-11ea-89f5-e23327022077.jpg)

**Comment by Shelob9** [comment]
This issue should be fixed in CF 1.9. a release candidate build, not fully tested can be downloaded here:

https://github.com/CalderaWP/Caldera-Forms/files/4766861/1.9.0-RC.1.zip

We welcome any testing, please let us know if this fixes your issue.

**Comment by artshostak** [comment]
Wonderful, glad you're on it. I am just using my own forked version in the meantime but will switch over to RC1 to provide you with some feedback and testing in the process. Thanks Josh!

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/4cacd21dedbeb6db283d3785e500c34d9ba33d1f -
