### ISSUE TITLE
Caldera Forms-From email name and Subject not working

### ISSUE THREAD

**Issue by Unice** [CalderaWP/Caldera-Forms#3480]
**Hi ,

Can you please verify that when a customer fills out the form on the website  https://www.plymouthcruises.com/contact-us/  that the email that is sent to our customer comes from <email address<email address> 
example: <Helpdesk@infotreeinc.com <Helpdesk@infotreeinc.com>. that is incorrect and is a little confused and wanted to report it to us. 

That should be Name<email address>  example: Plymouth Cruises<helpdesk@infotreeinc.com> 

and the Subject should be Thank you for contacting us. NOT Contat Form.

Below my email thread is a forwarded copy she got.

---------- Forwarded message ---------
From: <Helpdesk@infotreeinc.com <Helpdesk@infotreeinc.com>
Date: Wed, Jan 15, 2020 at 1:26 PM
Subject: Contact Form
To: <plymouthcruises@gmail.com>

When I testing it. I got the email information is correct.
From name is customer's company name with helpdesk@infotreeinc.com. 

---------- Forwarded message ---------
From: Plymouth Cruises <helpdesk@infotreeinc.com>
Date: Thu, Jan 30, 2020 at 2:16 PM
Subject: Thank you for contacting us
To: Unice test <unice@softpower.com.tw>

Please check this out and let me know what is going on.
Thanks,
Unice**

**Comment by New0** [comment]
Hello @Unice  , for support or questions please go to https://calderaforms.com/support/ .

To report an issue here, please \:

- Share details to reproduce the issue

- Share the debug information from your WordPress admin at Caldera Forms -> Support under the debug information tab

- Report if the issue persists with all other plugins disabled and theme twentynineteen activated.

- Share PHP and JS logs
