### ISSUE TITLE
Build script does not copy assets files.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3484]
Right here:https://github.com/CalderaWP/Caldera-Forms/blob/develop/Gruntfile.js#L60-L63 We're copying html and CSS, but not the asset.json file that will be needed here: https://github.com/CalderaWP/Caldera-Forms/blob/develop/classes/render/assets.php#L713

This would explain the test failures that @New0 has on the test site, but not in his local.

```
Uncaught TypeError: Cannot read property 'Component' of undefined
    at Object.227 (index.min.js?ver=1.8.10-b1:1)
```

Safe to assume that is `React.Component`. React SHOULD be loaded from `wp-includes` I do not see it in sources. The build process SHOULD have generated the asset.json file that is used to determine what WordPress files to enqueue. We use [this plugin to generate those files](https://developer.wordpress.org/block-editor/packages/packages-dependency-extraction-webpack-plugin/) [here](https://github.com/CalderaWP/Caldera-Forms/blob/develop/webpack.clients.js#L214).

**Comment by Shelob9** [comment]
@New0 Yep, they are not there in your build. Glad you ran those tests.

![Annotation 2020-02-10 120228](https://user-images.githubusercontent.com/1994311/74178609-da5a7780-4c09-11ea-8b4e-9ae39ae87f48.jpg)

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/086d21f0bb4e30f0a9d6113ed89f72e2ac9bbf8a -
