### ISSUE TITLE
"Add Condition" (in line) button is broken in processors

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3490]
Reported at - https://secure.helpscout.net/conversation/1089362705 -

On a processor interface, Clicking the "Add Condition" button to add a conditional line in a Conditional group replaces/reloads the current line instead of adding a line.

**Comment by New0** [comment]
Link to beta test the related PR - https://drive.google.com/file/d/185hRgILr9aKqmZ6wx_hqzB8VrZnuYmA4/view?usp=sharing -

**Comment by Shelob9** [comment]
Reported here as well: https://wordpress.org/support/topic/fatal-error-3411/

**Comment by New0** [comment]
@Shelob9 this is not the same issue, but I believe the error reported in .org is related to https://github.com/CalderaWP/Caldera-Forms/issues/3426

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/c747db02c4e0ed82145ca3f2fcff03759c106d03 -
