### ISSUE TITLE
Magic tag selector throws error if no variables in form

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3492]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Installed 1.8.10 from WordPress.org to confirm after seeing this on develop branch today.

Test site installed form dot org debug info:

WordPress Version: 5.3.2PHP Version: 7.1.33MySQL Version: 5.5.5Caldera Forms Version: 1.8.10WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?

1. Create new form.
2. Click on a settings field that should show magic tags.
3. Expect magic tag selector, get error "Uncaught TypeError: Cannot read property 'tags' of null
    at HTMLTextAreaElement.<anonymous> (edit.js?ver=1.8.10:1176)"
4. Add a variable to form.
5. Notice that magic tag selector works as expected.

The global `system_values` has null for variables, but it is expected an object litteral.

This conditional here: https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/edit.js#L1176 not good enough as it checks for undefined, not null.

**Comment by New0** [comment]
I could reproduce this issue @Shelob9 - it was the condition I added via https://github.com/CalderaWP/Caldera-Forms/issues/3474 that was not enough as variables are now checked during page load to be listed in Magic tags list.

**Comment by Shelob9** [comment]
Thanks for that @New0 it confirms what I see and I think my fix doesn't undo what you did in #3474 which was also needed. Please check my assumption there.

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/78c0a09a6fdb3487fa648c9cb2ba44789cbccbf9 -
