### ISSUE TITLE
Can not be installed in environment for integration tets

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3504]
Dependencies updates require PHP >= 7.2 but the current image uses php7.1 and is outdated - https://github.com/TetraWeb/docker -. That creates a failure on CI integration tests - https://gitlab.com/caldera-labs/Caldera-Forms/-/jobs/461280289 -

**Comment by Shelob9** [comment]
https://git.saturdaydrive.io/_/engineering-ops/sd-email-crm/email-crm/blob/master/.gitlab-ci.yml#L60-79

**Comment by Shelob9** [comment]
```
 Problem 1
     - pimple/pimple v3.3.0 requires php ^7.2.5 -> your PHP version (7.1.16) does not satisfy that requirement.
     - pimple/pimple v3.3.0 requires php ^7.2.5 -> your PHP version (7.1.16) does not satisfy that requirement.
     - Installation request for pimple/pimple v3.3.0 -> satisfiable by pimple/pimple[v3.3.0].
```

**Comment by Shelob9** [comment]
`calderawp/caldera-container` requires `"pimple/pimple": "^3.2",` Pimple 3.2.x requires PHP 5.3+, Pimple 3.3.x requires PHP 7.2+, hence our error.

* https://packagist.org/packages/pimple/pimple#v3.2.3
* https://packagist.org/packages/pimple/pimple#v3.3.0

In Caldera Forms, we could require pimple `3.2.*` and that should force it to install pimple 3.2.3, which will work.

https://getcomposer.org/doc/articles/versions.md#wildcard-version-range-

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/eb510ad2650029da6a735fd5cefe911e485847cd
