### ISSUE TITLE
Add test coverage for processor conditional editor

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3512]
In order to resolve #1354 the processor UI's conditional logic editor will need to be moved to the new system introduced in #3445 

There are not tests proving:

- [ ]  When a processor has conditionals, the saved settings load in the editor correctly.
- [ ] We can add new conditional groups to a processor.
- [ ] We can remove conditional groups from a processor.
- [ ] When a field type changes from text to checkbox/radio/dropdown/select2 the conditional value switches from magic tags, to list of field options in both editors, with the current options for that field.
- [ ] When the options for a checkbox/radio/dropdown/select2 change, the options for conditional value in effected conditionals -- current conditionals and new conditionals -- are updated.
- [ ] All of the above changes can be saved, the form editor reloaded, and the settings are the same.

Some of these tests might have been added in #3442
See:
https://github.com/CalderaWP/Caldera-Forms/pull/3445#issuecomment-575948420

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/3ca1179d6dda518aa640bb9a82628885264f7051 -
