### ISSUE TITLE
Variables are reversed mentionned in document

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3529]
https://github.com/CalderaWP/Caldera-Forms/blob/68535d017e873dd751a82cd712b2d27344c23b25/classes/save.php#L507

**Comment by Shelob9** [comment]
@New0 When we address this, let's add a note about how to get entry ID. 

```php
add_action( 'caldera_forms_mailer_complete', function($mail,$data){
  if(isset($data["_entry_id")){
           $entryId = $data["_entry_id"];
        }
},2);
```

**Comment by New0** [comment]
@Shelob9  I thought I had closed this issue it was just my own confusion.
