### ISSUE TITLE
DUPLICATE. Please Ignore. Sorry :) Unparenthesized ternary operator PHP 7.4 in CF 1.8.11

### ISSUE THREAD

**Issue by avalonstudios** [CalderaWP/Caldera-Forms#3541]
There is an issue in

`caldera-forms\classes\core.php on line 3732`

with an unparenthesized ternary operation.

Current code:

`$entry_id = !empty($wp_query->query_vars[ 'cf_entry' ]) ? $wp_query->query_vars[ 'cf_entry' ]
: isset($_GET, $_GET[ 'entry' ]) && absint($_GET[ 'entry' ]) ? $_GET[ 'entry' ] : null;`

Fix:

`$entry_id = !empty($wp_query->query_vars[ 'cf_entry' ]) ? $wp_query->query_vars[ 'cf_entry' ]
: ( isset($_GET, $_GET[ 'entry' ]) && absint($_GET[ 'entry' ]) ? $_GET[ 'entry' ] : null );`

**Comment by New0** [comment]
Thanks for reporting this @avalonstudios I'm closing this it will be fixed via - https://github.com/CalderaWP/Caldera-Forms/pull/3539 -
