### ISSUE TITLE
Broken feature: Processors > Form Processors > Add Processor

### ISSUE THREAD

**Issue by Docsibobo** [CalderaWP/Caldera-Forms#3560]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
On both: WordPress Version: 5.4.2 PHP Version: 7.1.33 MySQL Version: 5.5.5 Caldera Forms Version: 1.9.0 and WordPress Version: 5.4.2 PHP Version: 7.4.6 MySQL Version: 5.5.5 Caldera Forms Version: 1.9.0

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes, but existing processors are not affected!

## What Is The Unexpected Behaviour?

1. When adding a processor with Conditions, e.g. with Auto Reponder, the Conditions tab is completely blank
2. After filling out a processor's settings, saving the form and applying a page refresh, the added processor is not saved and therefore not available from  the Form Processors list

Note: Existing processors are maintained and even their conditions, but do they work correctly I wonder now

**Comment by Shelob9** [comment]
@Docsibobo Thanks for reporting this bug

I see an error when adding a processor, which would explain the behaviour you are describing. I am going to take some time to see what I did wrong this morning.

![Annotation 2020-06-19 094535](https://user-images.githubusercontent.com/1994311/85139043-d5d64900-b211-11ea-9ebc-00d14c545b64.jpg)

Possibly same issue: #3559

**Comment by Shelob9** [comment]
This is the line with error https://github.com/CalderaWP/Caldera-Forms/blob/master/clients/form-builder/index.js#L283 `c` is `addProcessor` which should be returned from `ProcessorsContext` --

https://git.saturdaydrive.io/_/caldera-forms/tools/form-builder/blob/master/src/Processors/ProcessorsContext.tsx#L55

**Comment by Shelob9** [comment]
- 1.9.0 installed from dot org -- issue is present.
- master branch -- issue is not present.
- develop branch -- issue is not present.

**Comment by Shelob9** [comment]
Close via #3561

I just tested with a clean install from WordPress.org of CF 1.9.1 and it worked as expected.

**Comment by Docsibobo** [comment]
I confirm it now does, thanks.
