### ISSUE TITLE
Using Plain Permalinks Breaks the Entry Editor

### ISSUE THREAD

**Issue by riverBanjo** [CalderaWP/Caldera-Forms#3568]
## Replication steps

1. Change Permalink settings to plain ( ?p=123 )
2. Install Caldera Forms
3. Make a form
4. Submit the form
5. View entry
6. Edit entry
7. See that the entry editor is covered by a home page

## Debug Info
WordPress Version: 5.4.2

PHP Version: 7.3.19

MySQL Version: 5.7.30

Server Software: Apache/2.4.38 (Debian)

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: Twenty Nineteen: 1.5

Plugins:

Akismet Anti-Spam: 4.1.6 Not Active
Authorize.net for Caldera Forms: 2.1.4 Active
Caldera Forms: 1.9.1 Active
CalderaWP License Manager: 1.2.10 Active
MailPoet 2: 2.13 Not Active
Ninja Forms: 3.4.24.3 Not Active
Ninja Forms - ActiveCampaign: 3.0.6 Not Active
Ninja Forms - Addon Manager: 3.0.13 Not Active
Ninja Forms - AWeber: 3.1.1 Not Active
Ninja Forms - Campaign Monitor: 3.0.5 Not Active
Ninja Forms - Capsule CRM: 3.4.0 Not Active
Ninja Forms - CleverReach: 3.1.3 Not Active
Ninja Forms - ClickSend: 3.0.1 Not Active
Ninja Forms - Conditional Logic: 3.0.26 Not Active
Ninja Forms - Constant Contact: 3.0.4 Not Active
Ninja Forms - ConvertKit: 3.0.2 Not Active
Ninja Forms - Elavon Payment Gateway: 3.1.0 Not Active
Ninja Forms - EmailOctopus: 3.0.0 Not Active
Ninja Forms - Emma: 3.0.4 Not Active
Ninja Forms - Excel Export: 3.3.1 Not Active
Ninja Forms - File Uploads: 3.3.4 Not Active
Ninja Forms - Help Scout: 3.1.3 Not Active
Ninja Forms - Highrise CRM: 3.0.0 Not Active
Ninja Forms - Insightly CRM: 3.2.0 Not Active
Ninja Forms - Layout & Styles: 3.0.28 Not Active
Ninja Forms - Mail Chimp: 3.1.11 Not Active
Ninja Forms - MailPoet: 3.0.0 Not Active
Ninja Forms - Multi-Part Forms: 3.0.26 Not Active
Ninja Forms - OnepageCRM: 3.0.0 Not Active
Ninja Forms - PayPal Express: 3.0.15 Not Active
Ninja Forms - PDF Form Submissions: 3.1.2 Not Active
Ninja Forms - Pipeline Deals CRM: 3.0.1 Not Active
Ninja Forms - Post Creation: 3.0.9 Not Active
Ninja Forms - Recurly: 3.0.4 Not Active
Ninja Forms - Salesforce CRM: 3.2.0 Not Active
Ninja Forms - Save Progress: 3.0.24.2 Not Active
Ninja Forms - Slack: 3.0.3 Not Active
Ninja Forms - Stripe: 3.1.3 Not Active
Ninja Forms - Trello: 3.0.3 Not Active
Ninja Forms - Twilio SMS: 3.0.1 Not Active
Ninja Forms - User Analytics: 3.0.0 Not Active
Ninja Forms - User Management: 3.0.12 Not Active
Ninja Forms - Webhooks: 3.0.5 Not Active
Ninja Forms - WebMerge: 3.0.3 Not Active
Ninja Forms - Zapier: 3.0.8 Not Active
Ninja Forms - Zoho CRM: 3.4 Not Active
Slack Integration for Caldera Forms: 1.0.0 Active
Verify Email for Caldera Forms: 1.2.0 Not Active
WP Mail Logging: 1.9.6 Not Active

**Comment by New0** [comment]
Thank you for reporting this issue @riverBanjo 

I can see that when Plain Permalinks are set, clicking the "Edit Entry" button on the Modal view of an Entry result in the home page set for the site to get displayed.
the Query seems broken , mixing a pretty permalink and plain permalink structure \:

{"GET":{"scheme":"https","host":"local.lndo.site","filename":"/","query":{"cf_apiCF5eb5616ea264f/232/?cf-api":"CF5eb5616ea264f","modal":"view_entry","modalElement":"div","modalTitle":"Editing Entry  #232","modalButtons":"Save Changes|{\"data-for\":\"#view_entry_baldrickModalBody .caldera_forms_form\"}|right button-primary;View Entry|{\"data-for\":\".view-entry-btn.current-view\"}|","method":"get","loadClass":"spinner","activeClass":"current-edit","request":"https://local.lndo.site/?cf_apiCF5eb5616ea264f/232/?cf-api=CF5eb5616ea264f","modalHeight":"auto","modalWidth":"700","group":"editentry","form":"CF5eb5616ea264f","entry":"232","static":"true","_":"1594639914164"},"remote":{"Adresse":"127.0.0.1:443"}}}

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/4560a7bd637bfd94e11b2fa68a82d69e6628a07f -

**Comment by New0** [comment]
Closed via - 4560a7b -
