### ISSUE TITLE
Caldera Forms - Privacy Settings: "Unexpected token E in JSON at position 0"

### ISSUE THREAD

**Issue by amelsens** [CalderaWP/Caldera-Forms#3577]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
> Already open a ticket.

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
> No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
Short Debug Information
WordPress Version: 5.4.2PHP Version: 7.4.7MySQL Version: 5.5.5Caldera Forms Version: 1.9.1WP_DEBUG:
Full Debug Information
WordPress Version: 5.4.2

PHP Version: 7.4.7

MySQL Version: 5.5.5

Server Software: Microsoft-IIS/10.0

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

Session Save Path: C:\WINDOWS\Temp\

Session Save Path Exists: Yes

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 128M

Currently Active Theme: Astra Child: 1.0.0

Plugins:

Akismet Anti-Spam: 4.1.6 Not Active
Astra Bulk Edit: 1.2.4 Active
Astra Customizer Reset: 1.0.4 Active
Astra Widgets: 1.2.4 Active
Caldera Forms: 1.9.1 Active
Custom Fonts: 1.2.2 Active
Customizer Search: 1.1.4 Active
Disable Comments: 1.10.2 Active
Duplicate Post Page Menu & Custom Post Type: 1.5.0 Active
Duplicator: 1.3.36 Active
Elementor: 2.9.13 Active
Elementor - Header, Footer & Blocks: 1.5.1 Active
Essential Addons for Elementor: 4.0.4 Active
Import / Export Customizer Settings: 1.0.3 Active
Sidebar Manager: 1.1.3 Active
Starter Templates: 2.3.2 Active
Style Kits for Elementor: 1.6.9 Active

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
> YES
The error message is still there!

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
> Caldera Forms > Privacy Settings > 
![2020-07-06 10_44_11-Privacy Settings ‹ WP Develop Local — WordPress - Brave](https://user-images.githubusercontent.com/10380856/86574221-c9722000-bf75-11ea-9d33-9d1abc1fc4e4.jpg)
After choosing my form:
Error message: "Unexpected token E in JSON at position 0" in red rectangle. See also screencapture in attachment.
No other things are possible. I can't contnue with the privacy settings. There is nothing else on the screen except the standard notes on the bottom of the page.
I have this problem on many different websites with the latest version of Caldera Forms 1.9.1.
With a previous version 1.8.11 there was no problem with the Privacy Settings. No errors and it worked.
So I really think it's a bug. 
Attention: I use always my local Windows IIS webserver platform to start and test websites. But normaly I have no problems.
I use also a Windows IIS webserver 2016 as production platform.
## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/
> There is nothing saved in the PHP logging file. No errors, no warnings concerning my website with this issue.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
> In the Chrome JavaScript console there are following messages:
load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.4.2:8 JQMIGRATE: Migrate is installed, version 1.4.1
/wp-json/cf-api/v2/forms/CF5f02dbb5dc912?preview=false&_wpnonce=f07d103c48:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/wp-json/cf-api/v2/forms/CF5f02dbb5dc912?privacy=true:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/9849137d9741ff5931c9464c2589044cd8fd51c7
