### ISSUE TITLE
Input Mask Question: Is there any way to allow for specific characters?

### ISSUE THREAD

**Issue by regiside** [CalderaWP/Caldera-Forms#3584]
Is there a way to use the input mask to allow for specific characters. For instance, I'd like to be able to let users enter any combination of numbers, dashes, and parentheses, but nothing else. Obviously this could be done using standard regex, but does the Caldera Input mask have a way to do this?

**Comment by New0** [comment]
Hello @regiside , for support please reach out via - https://calderaforms.com/support-form/ -

Short answer: If an input mask is not enough, you can add an [HTML5 pattern](https://www.w3schools.com/tags/att_input_pattern.asp) attribute to the field via - [caldera_forms_field_attributes](https://calderaforms.com/doc/caldera_forms_field_attributes/) - filter hook.
