### ISSUE TITLE
Automatically generate a ZIP when a tag or release is generated

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3590]
When a tag is applied:

- Install and build for release
- ZIP files that we ship
- Attatch to release

Use this as reference:
https://github.com/Shelob9/actions-test/blob/master/.github/workflows/uploader.yml

Related #3575

**Comment by New0** [comment]
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/40696f7e12328e06cd4c169762e5b019ac8a0ed8 -
