### ISSUE TITLE
Is it possible to display the full path instead of the c:/fakepath path?

### ISSUE THREAD

**Issue by zoomwebstudio** [CalderaWP/Caldera-Forms#36]
Hello, 
i am trying to build a form with preview of the values directly by the user on the filling form page.

On the backend, I have this configuration : 
![caldera_backend](https://cloud.githubusercontent.com/assets/5471307/4264360/6f23ce0e-3c23-11e4-86f2-1c9c32b2e563.png)

And on the front end I got this when i enter data.
![caldera_front](https://cloud.githubusercontent.com/assets/5471307/4264355/49a7e2fa-3c23-11e4-97c6-78a32912b7b4.png)

The think is that I would like to have access to the full path or a temporary upload path instead of the c:/fakepath.

Is that possible?

Have a nice day guys!

**Comment by janzilka** [comment]
How do I remove the "C:\fakepath" message text from currently latest published revision that gets installed via Wordpress plugin install ?

Thanks
