### ISSUE TITLE
Forms won't save anymore

### ISSUE THREAD

**Issue by mihaibenta** [CalderaWP/Caldera-Forms#3626]
## Do You Need Immediate Help?
no

## Is This A Feature Request?
no

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.5.1PHP Version: 7.4.8MySQL Version: 5.5.5Caldera Forms Version: 1.9.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
* Forms wont save after pressing the ''save form'' button

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by New0** [comment]
This kind of issue was worked on for - https://downloads.wordpress.org/plugin/caldera-forms.1.9.4.zip - don't hesitate to reopen if that wouldn't be the case.

Thank you for reporting an issue and for your patience.
