### ISSUE TITLE
Export feature is broken on WordPress 5.6 RC1

### ISSUE THREAD

**Issue by Zodiac1978** [CalderaWP/Caldera-Forms#3639]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.6-RC1-49667PHP Version: 7.3.23MySQL Version: 5.6.19Caldera Forms Version: 1.9.2WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
Clicked on "Export" and the screen just darkens without anything happen after that.

## What PHP Errors Have You Logged While Reproducing This Bug?

No PHP errors, but a JS error.

## What JavaScript Errors Have You Seen While Reproducing This Bug?

Uncaught TypeError: d.triggerClass is undefined
    params http://example.de/wp-content/plugins/caldera-forms/assets/build/js/wp-baldrick-full.min.js?ver=1.9.2:3
    c http://example.de/wp-content/plugins/caldera-forms/assets/build/js/wp-baldrick-full.min.js?ver=1.9.2:2
    baldrick http://example.de/wp-content/plugins/caldera-forms/assets/build/js/wp-baldrick-full.min.js?ver=1.9.2:3
    jQuery 9
    baldrick http://example.de/wp-content/plugins/caldera-forms/assets/build/js/wp-baldrick-full.min.js?ver=1.9.2:3
    jQuery 2
    baldrick http://example.de/wp-content/plugins/caldera-forms/assets/build/js/wp-baldrick-full.min.js?ver=1.9.2:3
    baldrickTriggers http://example.de/wp-content/plugins/caldera-forms/assets/build/js/admin.min.js?ver=1.9.2:1
    <anonymous> http://example.de/wp-content/plugins/caldera-forms/assets/build/js/admin.min.js?ver=1.9.2:1
    jQuery 13
        e
        t
        setTimeout handler*l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>

**Comment by Zodiac1978** [comment]
Not sure if this could be related to jQuery update:
https://make.wordpress.org/core/2020/11/05/updating-core-jquery-to-version-3-part-2/

**Comment by New0** [comment]
To add precision to the comment at https://github.com/CalderaWP/Caldera-Forms/issues/3642#issuecomment-746309213 in this issue.

- defaults.triggerClass is defined in wp-baldrick.full.js l4078 by this.selector but this is not set as it was using 1.12.4

**Comment by New0** [comment]
Test zip - https://github.com/CalderaWP/Caldera-Forms/releases/download/1.9.3-b4/1.9.3-b4.zip -

This should be closed via - https://github.com/CalderaWP/Caldera-Forms/commit/1c1c4607c41df287c192f36734c45c56ef121d5b -

An official update will be pushed as soon as possible. Don't hesitate to reopen this if the test zip is not working ( making sure all assets are refreshed in the browser ).

Thank you @Zodiac1978 for opening this issue and sharing details.
