### ISSUE TITLE
Radio Button List Rendering Incorrectly.

### ISSUE THREAD

**Issue by SFPink** [CalderaWP/Caldera-Forms#364]
I have just noticed my radio buttons are rendering incorrectly. They seem to be rendering inside one another:

```
    <div class="radio">
        <label>
            <input type="radio" />
            Label One
            <div class="radio">
	        <label>
                    <input type="radio" />
                    Label Two
                </label>
            </div>
        </label>
    </div>
```

Hopefully that makes sense.

This only seems to occur if the radio has a condition linked to it.

**Comment by Desertsnowman** [comment]
@SFPink - I cant replicate this. is it possible to get the example form exported?

**Comment by SFPink** [comment]
I've attached an exported test version hopefully it helps. I also added an image of how the code form is rendering for me. You can see the radio buttons are being nested in one another.

[radio-button-test-export.zip](https://github.com/Desertsnowman/Caldera-Forms/files/214590/radio-button-test-export.zip)

![radiotest](https://cloud.githubusercontent.com/assets/3307197/14454477/b59b29ba-0092-11e6-8b79-ee566a40fc78.png)

**Comment by Desertsnowman** [comment]
@SFPink - what browser are you using?

**Comment by SFPink** [comment]
I'm using Chrome: Version 49.0.2623.112 m

It does the same on Firefox (46.0.1)

**Comment by Shelob9** [comment]
Closing as no longer an issue
