### ISSUE TITLE
Cannot create new forms, cannot edit existing forms, cannot import.

### ISSUE THREAD

**Issue by Rule72** [CalderaWP/Caldera-Forms#3654]
Version: The latest version.

**Persists after disabling everything.**
Yes.

**What PHP Errors Have You Logged While Reproducing This Bug?**
None

**What JavaScript Errors Have You Seen While Reproducing This Bug?**
Nothing of note (failed to load SourceMap).

## Details
I can't click on the button to start a new form, nor use a template, nor edit and save existing forms. This is across at least 4 managed client sites, and 2 new (within two weeks) sites, various hosts, etc., and seems to be related to an October update from Wordpress, possibly even earlier.

All that happens is that the "Create Form" button shows an "active" pseudo element state change, and that's it.

My existing forms continue to function, but I can't build new website forms. I did try to create a form on an earlier-versioned site (WP 5.5.3, CF v1.9.2) on which the plugin DOES work as expected, and export the JSON... but reimporting into a failing CF implement on the latest everything regardless of site status (fresh install, existing site, etc) accomplishes nothing.

![image](https://user-images.githubusercontent.com/76264718/102698585-bdb0a800-41fb-11eb-83b9-a4804f98ce29.png)

**Comment by New0** [comment]
This issue should be fixed in 1.9.4 - https://downloads.wordpress.org/plugin/caldera-forms.1.9.4.zip - don't hesitate to open this issue again if this wasn't the case.

Thank you for reporting this issue and for your patience.
