### ISSUE TITLE
Mailer section ambiguity - for user or for admin?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#366]
Hey

I am teaching my client to use Caldera Forms.
The mailer section..
Email Notification Settings

The section could use some more clarity in that this section is setup for how the e-mail is submitted to the admin or the caretaker of the site.

Right now if one quickly reads through it it can be taken both ways. Even though the auto responder might have been filled out the Mailer section can give an uncertainty if it is for the user or the admin. 

<b>NB!</b> 
Email Message section. I am missing the brackets to insert fields similar to what is done in the auto responder message section. As one might want to split the fields up into logical groupings making it more readable for the admin who receives the information.

**Comment by Shelob9** [comment]
It can go both ways. It's up to you. This is covered in our new getting started guide which soon new users will be directed to #848
