### ISSUE TITLE
Stripe processor makes the "Save Form" Button disappear

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3662]
On the Form edition page, after adding a Stripe processor to the Form and reloading the page, the "Save Form " button doesn't appear.
![Screenshot_2020-12-31 Caldera Forms Admin ‹ VSLAN — WordPress](https://user-images.githubusercontent.com/16348693/103422923-2a388900-4ba4-11eb-8081-97c881fc0c85.png)

**Comment by omniacode** [comment]
Same thing is happening with the Authorize.net Addon.

**Comment by New0** [comment]
This issue should be fixed in 1.9.4 - https://downloads.wordpress.org/plugin/caldera-forms.1.9.4.zip - don't hesitate to reopen this issue if this wasn't the case.

Thank you for reporting this issue and for your patience.
