### ISSUE TITLE
Can't Create Forms

### ISSUE THREAD

**Issue by heykymmie** [CalderaWP/Caldera-Forms#3668]
Hi, I'm using Version 1.8.3 of Caldera Forms. Wordpress is Version 5.6.1. I can't clone nor create a new form. Help!

**Comment by New0** [comment]
This issue should be fixed in 1.9.4 - https://downloads.wordpress.org/plugin/caldera-forms.1.9.4.zip - don't hesitate to reopen this issue if it is not the case.

Thank you for reporting this issue and for your patience.
