### ISSUE TITLE
Save Button and conditions edits unavailable in some forms depending on processors.

### ISSUE THREAD

**Issue by KilakwaBT** [CalderaWP/Caldera-Forms#3671]
We have upgraded to ver 1.9.3 with WP 5.6. While this new version has solved some of the jQuery issues there is still an issue with some forms. When specific processors are added to the form. The Save button and the ability to add and edit conditions are not available when opening for editing. We have identified the following processors as causing this.

- User Registration
- User login
- Stripe

There may be others we have yet to identify. 

WordPress Version: 5.6PHP Version: 7.3.26MySQL Version: 5.7.32Caldera Forms Version: 1.9.3WP_DEBUG: 1

**Comment by jackssn** [comment]
I have same problem on my very old form with email confirmation. And the problem appeared after update Wordpress (and plugins)

In debugger firefox I see empty button:

`<div id="caldera-header-save-button"></div>` by event in `/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1`

**Comment by OldItalian** [comment]
I've had to result to loading older versions of jQuery using Enable jQuery Migrate Helper. Many people seem to be in the same boat. Hopefully 1.9.4 is released to fix issues with WP 5.6 and jQuery compatibility.

**Comment by racemaniacs** [comment]
I had the same issue using the auto-responder processor.
After updating to 1.9.4-b1 the problem seems to be resolved

**Comment by kevin39** [comment]
Same issue here. All is up-to-date but "Save form" missing. I had to  load older jQuery version.

**Comment by kevin39** [comment]
Oops.
Just saw 1.9.4-b1 is available : https://github.com/CalderaWP/Caldera-Forms/releases/tag/1.9.4-b1

All is fine now ! I restored the official jQuery version and disable "jQuery Migrate Helper".

**Comment by Upperholme** [comment]
1.9.4-b1 didn't work for me. I installed it and then couldn't navigate through the tabbed settings for my forms - lots of red alerts in my browser console. Sticking with 1.9.3 and implementing the legacy jQuery with the Enable jQuery Migrate Helper plugin got me a result. Interesting only one of the forms on my site - the first to be created - seems to be affected.

**Comment by nixonwhite** [comment]
I can say that 1.9.4-b1 didn't work for me. jQuery Migrate Helper is also useless.

**Comment by ericger** [comment]
the beta let me work on the forms but makes my fusion builder useless. Can't open anything anymore. and when you don't deactivate your Paypal pro plugin before installing the beta, you are screwed.

**Comment by New0** [comment]
This issue should be fixed in 1.9.4 - https://downloads.wordpress.org/plugin/caldera-forms.1.9.4.zip - don't hesitate to open this issue again if this wasn't your case.

Thank you all for reporting this issue and for your patience.
