### ISSUE TITLE
Submissions get deleted when a new condition is added

### ISSUE THREAD

**Issue by riverBanjo** [CalderaWP/Caldera-Forms#3691]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.8.2
PHP Version: 7.4.1
MySQL Version: 8.0.16
Caldera Forms Version: 1.9.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
If you have entries on a form and then add a new condition the entries will be deleted.

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP error logs.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No JS errors I could see.

**Comment by riverBanjo** [comment]
Also occurs on WordPress Version: 5.8.2 PHP Version: 7.4.25 MySQL Version: 5.7.32 Caldera Forms Version: 1.9.5

Upon further investigation the entries are deleted from the database along with entry values.

**Comment by New0** [comment]
Fixed via #3692
