### ISSUE TITLE
Missing Numerals

### ISSUE THREAD

**Issue by BobReeves** [CalderaWP/Caldera-Forms#394]
when I receive an email from a form the leading zero of a telephone number is always visable. When viewing the entry from within WP dashboard Caldera forms the leading zero on telephone numbers is sometimes missing.

**Comment by Desertsnowman** [comment]
browse_entries is an ajax call. The entry returned in json to the view is treating the number as an `INT` hence the leading 0 being dropped.

Fix by creating a view handler filter for telephone to cast as string.
