### ISSUE TITLE
Question : Retrieve and Display Form Stats

### ISSUE THREAD

**Issue by samblackk** [CalderaWP/Caldera-Forms#417]
Hey there!

I've built a pretty large assessment form all fields are either radio or checkbox field types.

What I want to know is if there is a way I can pull statistical data from the form entries and display them on the front-end of my theme.

The use of this will be to give a user who has taken the assessment a comparison of how their entries compare to the others who have taken it.

Example:
Question 1 - You answered the same as 24% of the users who have also answered this question.

This totally a question, not a bug or enhancement request.
Thank you!

**Comment by singram26** [comment]
No one has any ideas towards this?
