### ISSUE TITLE
BUG: Form Processor Break doesn't work as expected

### ISSUE THREAD

**Issue by brandbrilliance** [CalderaWP/Caldera-Forms#430]
In the Form Processor Boilerplate, the following code is provided to break the validation. However the ERROR NOTE works, but not the FIELDS part of the sample - which doesn't work at all. 

```
$break = array(
    'type'   => 'break type [error|success|info|warning]', // sets banner color/class
    'note'   => 'note to display to user',
    'fields'     => array( // optional if fields have failed.
        'field_id'  =>  'fail reason'
    )
);
return $break;
```

**Comment by Desertsnowman** [comment]
the field_id has to be the ID of the field so it should be something like `fld_27344`

**Comment by brandbrilliance** [comment]
Yep, I've done that correctly. However, only the notice is triggered, not the field part.

**Comment by Desertsnowman** [comment]
Don't actually code the ID. it would most likely be something like `$config['mysetting'] => 'fail reason'`

**Comment by brandbrilliance** [comment]
Here is the output of the variable before I return. It simply doesn't work at all.

```
Array ( 
[type] => error 
[note] => Duplicate entry found: john@email.com 
[fields] => Array ( 
     [fld_3597343] => Database entry already exists for john@email.co.za 
))
```

**Comment by brandbrilliance** [comment]
I've installed the boilerplate and added a form with the two fields from the boilerplate. I've added the first option to be added to the notice, and you have to enter "die" into the second option to trigger the processor. Once it triggers only the error notice will appear, nothing appears next to the second field which is in the array of fields.

`http:// code . brandbrilliance . co . za/boilerplate-test/ (remove spaces)`

**Comment by Shelob9** [comment]
I have a form from a user ( @Desertsnowman I am emailing you the export ) where entry limiter correctly causes an error to return, but the error notice is not displayed... It just doesn't submit. 

In my console, I see this response from the CF-API: 
```
{"fields":{"fld_5916702":"Ta termin je poln. Izberite drugega."},"data":{"page_id":"9","preview":"true","cf_preview":"CF56ccd660e3c76","cf_er":"_cf_process_56ccd7fca864e"},"html":"","type":"error","form_id":"CF56ccd660e3c76","form_name":"eee","status":"error"}
```

That looks totally right to me.

**Comment by Shelob9** [comment]
I just checked @brandbrilliance form. It actually worked fine. Here is what the CF API responded with:

```
{"fields":{"fld_4688836":"Dont like die"},"result":"Nope. Sorry. First Option:JOSH","data":{"cf_er":"_cf_process_56ccd920abbac"},"html":"<div class=\" alert alert-error\">Nope. Sorry. First Option:JOSH<\/div>","type":"error","form_id":"CF56c6d78c48786","form_name":"Boilerplate Test","status":"preprocess"}
```

And visual response:
![screen shot 2016-02-23 at 5 12 46 pm](https://cloud.githubusercontent.com/assets/1994311/13268481/b853f988-da50-11e5-98e5-b846d925df72.png)

Hmmm, now I'm more confused.

**Comment by brandbrilliance** [comment]
Yes. Notice at top works, but error next to the field doesn't. That's missing.

**Comment by brandbrilliance** [comment]
Seems to work right in the latest version. Thanks guys.

![boilerplate-test-2](https://cloud.githubusercontent.com/assets/1362479/13546584/e192d374-e2ba-11e5-83da-03ec6126c90d.jpg)

**Comment by brandbrilliance** [comment]
Tell me something. Is there a way to target a specific option value? Currently, if you flag a field that is radio, the field "error" appears below every option??

**Comment by Desertsnowman** [comment]
hmm interesting. will check it out

**Comment by brandbrilliance** [comment]
Currently this is what happens.

![seat-limitation-test](https://cloud.githubusercontent.com/assets/1362479/13546860/ba10294c-e2c3-11e5-925e-dd194177b71e.jpg)

**Comment by Desertsnowman** [comment]
this happens to any required field. reopening for a fix quick

**Comment by Desertsnowman** [comment]
closed via 4a0082d

**Comment by brandbrilliance** [comment]
Installed the latest version with your changes, however, this still flags every item just like before, as your code only does checkboxes, and doesn't consider radio fields. Perhaps we could target a specific option as well in the reply, otherwise I will have to simply make the error visible at the top (instead of the option value), however on long forms, the user will struggle to quickly identify the actual option that is causing the requirement.

You can see it here: 
http://code .brandbrilliance .co .za/ formprocessor-breakouts/ (remove spaces)

Suggestion:
```
Array ( 
[type] => error 
[note] => Seat Limit reached for Location: Cape Town (0 free seats)
[fields] => Array ( 
     [fld_3597343] => array (
          [opt1697861] => No Free Seats for Location: Cape Town (0 free seats) 
))

```

**Comment by Desertsnowman** [comment]
@brandbrilliance try the current dev branch quick

**Comment by brandbrilliance** [comment]
It still highlights both options as red (which some users might not understand), but now it does put the error message below the all options list (bottom of field).

![breakout-error](https://cloud.githubusercontent.com/assets/1362479/14140173/b170d08a-f677-11e5-9056-7629ec205933.jpg)

**Comment by Desertsnowman** [comment]
Great. That is how it should be. Highlight all options and a single message

**Comment by brandbrilliance** [comment]
Nag => But I would like a single option to be highlighted :-( as a form processor could be identifying a single option as the issue.

**Comment by Desertsnowman** [comment]
It's a nice feature to have. I'll look at adding it. For now that's not supported. 

Can you open up an issue for it?
