### ISSUE TITLE
upload file not working for ios mobile

### ISSUE THREAD

**Issue by williamjwallace** [CalderaWP/Caldera-Forms#444]
this form on our site will not accept file uploads from mobile users on iPhones. I've read on the internet that Apple intentionally is blocking file uploads from within Safari Mobile? I find it hard to believe.

form location: http://partytours.com/redeem-coupons/

Please help.

william@partytours.com
![image4](https://cloud.githubusercontent.com/assets/17647260/13531047/601beea2-e1d9-11e5-8bdc-585c389f6fcc.PNG)

**Comment by Shelob9** [comment]
According to this: http://stackoverflow.com/a/31501426 It is possible.

@williamjwallace What version of Caldera Forms and WordPress are you using?

**Comment by Desertsnowman** [comment]
@williamjwallace - phones sometime set the extension as jpeg. Give that a try as the allowed type.

**Comment by dchacons** [comment]
Remember that in this version .jpg,.gif is not the same as .JPG,.GIF, maybe the image extension is in uppercase, so add .JPG,.GIF... to the allowed extensions too.

**Comment by williamjwallace** [comment]
I have .jpg, .png(iphone default), and .pdf extensions set as acceptable. will also try .JPG and PNG to see if that helps.

I am on Caldera Forms 1.3.3.1 and WP 4.3.3

**Comment by williamjwallace** [comment]
form admin will not let me add JPG, PNG, etc..... in CAPS.

**Comment by Desertsnowman** [comment]
thats interesting. I'll see if I can do something with case sensitivity

**Comment by Desertsnowman** [comment]
@williamjwallace - can you try create a new form with just a file field set to JPG,JPEG and try the upload from mobile?

**Comment by williamjwallace** [comment]
looks like that worked.

www.partytours.com/test/
