### ISSUE TITLE
Datepicker language selection not operational 

### ISSUE THREAD

**Issue by StephGH** [CalderaWP/Caldera-Forms#451]
Hello Gentlemen,
I started to use your Caldera Forms plugin but I can't change the default datepicker language (english).
The English version is displayed even if I change the language from the drop down list. Whatever the language chosen, it keeps displaying in English.
According to the forums I went through, your plugin seemed to have had this issue about 1 year ago but it seems you already solved this issue ...
My version of CF is up to date (1.3.3.1).
Thanks in advance for your information.
Steph.

**Comment by zcztig** [comment]
I´m having the same issue, but only for modal-forms.

**Comment by Shelob9** [comment]
Closing as this works in 1.4.4+

**Comment by Neovinter** [comment]
Hello! 

The same bug back again with CF 1.6.2
Datepicker in CF 1.6.1.1 works fine.
