### ISSUE TITLE
Phone Number Field - Bug with custom masking

### ISSUE THREAD

**Issue by diegoliv** [CalderaWP/Caldera-Forms#47]
Hey,

First, thanks for this amazing plugin. It's already my go-to solution for complex forms! Simply the best!

I noticed bug with the phone number field. The default and International options works ok at the back end and the front end. But the custom option works only on the back end (when I set a default value, for example, the custom mask is applied). But at the front end, the custom mask is not used and the mask applied is the default one. My custom mask is really simple: (99) 9999-9999.

Can you take a lot at it and see if you can reproduce the issue?

Thanks!

**Comment by Desertsnowman** [comment]
Sorry on such delayed replies.
I'm working on the masking to allow more complex patterns.

**Comment by diegoliv** [comment]
Cool, that's good to know! Thanks for the info, I'll be looking for this in future releases!

**Comment by Shelob9** [comment]
Closing out this old issue as I'm updating masking and phone fields via #1118
