### ISSUE TITLE
Clone form doesn’t copy mailer settings

### ISSUE THREAD

**Issue by Desertsnowman** [CalderaWP/Caldera-Forms#505]
From https://wordpress.org/support/topic/the-more-i-get-to-know-it-the-happier-i-get?replies=1

**Comment by Shelob9** [comment]
Close via 9906672

**Comment by zyminger** [comment]
Caldera Forms Version: 1.4.9
When cloning a form:
-  Form Settings  - Success Message is not cloned
- Email Notification Settings - Form Name is not cloned and defaults back to "Caldera Forms Notification"
