### ISSUE TITLE
Cannot view entries in form.

### ISSUE THREAD

**Issue by SFPink** [CalderaWP/Caldera-Forms#530]
Hello,

I have just updated to the latest version of Caldera and now can no longer view the form entries in one of my forms.

I am getting this error in the console:

"Uncaught TypeError: Cannot read property 'total' of null"

It appears to be breaking in this function:

function setup_pagination(obj)

On this line as "rawData" is null:

var total = obj.rawData.total

Note:: I have 51 entries.

**Comment by Shelob9** [comment]
Possibly related to #508, we need to look further. @Desertsnowman

**Comment by Shelob9** [comment]
I'm closing this as we have reworked the entry viewer heavily in 1.3.6 and the pagination is working fine.
