### ISSUE TITLE
Form validation for required radio button entries - no error message output

### ISSUE THREAD

**Issue by ngwebspinner** [CalderaWP/Caldera-Forms#537]
The problem I am reporting here is one to do with form validation for required radio button entries. For a multi-page form, the "next" button refuses to work, which is fine. However, there is no message output to the user to explain why. I am using:
WordPress version 4.4.2
PHP version 5.5.31
Caldera Form plugin version 1.3.4.2
MySQL version 5.5.40-36.1-log

**Comment by Desertsnowman** [comment]
Additionally select2 and toggle switches don't work correctly either.
