### ISSUE TITLE
Calculation

### ISSUE THREAD

**Issue by ChookChook** [CalderaWP/Caldera-Forms#539]
For example,
1.30 - 1.15 = 0.15000000000000013

**Comment by Desertsnowman** [comment]
Been fighting with this for a while. it has to do with Floating-Point Arithmetic. 
this explains it pretty well http://floating-point-gui.de/

will work on solutions...

**Comment by Desertsnowman** [comment]
Pushing it to next version as I want to look at revising the calculation to use http://mathjs.org

**Comment by Shelob9** [comment]
Closing in favor of #1016
