### ISSUE TITLE
Phone Number Required

### ISSUE THREAD

**Issue by ghost** [CalderaWP/Caldera-Forms#547]
Not sure if this is the same version that available via wordpress. Via https://github.com/wp-plugins/caldera-forms. 

When making an element type of phone number required, it allows you to only enter one digit. I believe that in all use cases where phone number is required that all digits would need to be entered before processing. I am not sure if there is a work around for me since I am using multi page and don't want to wait till the submit to do add_filter hook.

**Comment by hydtek** [comment]
Is this a dead project?

**Comment by paaljoachim** [comment]
Hey hydtek

The project is alive but it can feel like waves hitting a beach.... Sometimes it feels very quiet other times bang a one wave comes in and the guys release a new version. Also sometimes it can take a while before they reply to some threads.

**Comment by Shelob9** [comment]
Hey, we work on this almost every day and have done three releases in last two months or so -- see https://plugins.trac.wordpress.org/log/caldera-forms/  Sorry if we have not gotten to this issue yet, but we have to prioritize. Pull requests are welcome.

**Comment by Shelob9** [comment]
Phone fields are getting major overhaul in 1.5 #902
