### ISSUE TITLE
BUG: Phone Fields do not support all international formats

### ISSUE THREAD

**Issue by brandbrilliance** [CalderaWP/Caldera-Forms#549]
It looks like the Phone field simply ignores the custom template you setup. 

Create a Phone Field and setup a custom profile: 999-999-9999
When you preview the form it still shows (**_)-**_-____ although there are no () brackets in my custom setup. This means you have to go back to using a standard text field with custom validation profile for it to work.

In South Africa Regional Codes are not optional so they can't have () around them, as they must be dialled in all cases.

**Comment by Shelob9** [comment]
Makes sense that we should support this. I would have thought @Desertsnowman would optimize for South African compatibility.

**Comment by waldbach** [comment]
Same goes for me, I might use a regular text input for now until this issue has been fixed and released in the next update.
Dutch support for Dutch mobile phone numbers would have the following structure:
99 99999999
or
99-99999999

Right now, whatever I change in the custom style option, doesn't appear in the form, it remains in the standard format.

I would really appreciate a fix here. Thanks in advance.

**Comment by Shelob9** [comment]
BEtter phone fields will support this in 1.5 #902
