### ISSUE TITLE
Entry list view is showing entry time in UTC

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#557]
In the list table for entries, time is displayed in 12H UTC, does not reflect WordPress timezone setting.

This is helpscout ticket #62

**Comment by Desertsnowman** [comment]
@Shelob9 - give this a test to be sure

**Comment by Shelob9** [comment]
I just tested and reproduced. WordPress was set to Josh Standard Time.
Displayed in UTC.

**Comment by Shelob9** [comment]
This confuses @shelob9 beacuse at ui/admin.php L743 we have this:

`$data['entries']['E' . $row->_entryid]['_date'] = date_i18n( $dateformat.' '.$timeformat, get_date_from_gmt( $row->_date_submitted, 'U'));`

**Comment by Desertsnowman** [comment]
Did you test with a new entry?

**Comment by Desertsnowman** [comment]
Entries where being captured in local time. Then taking that value and thinking it's UTC so made local again

**Comment by Shelob9** [comment]
Yes, new entry -- 100% bug.

--
JoshPress.net <http://joshpress.net/>
CalderaWP.com <http://calderawp.com/>
IngotHQ.com
@Josh412 <http://twitter.com/Josh412>

**Comment by Desertsnowman** [comment]
Ok so what should the time be shown in?

**Comment by Josh412** [comment]
WordPress' settings.

**Comment by Shelob9** [comment]
@Desertsnowman  I reversed c0371cf for the following reasons:
1) It did not fix the issue, I still see in entry viewer and entry list time in UTC, not my local timezone. And even if that had fixed it for new entries (it didn't) it wouldn't fix old entries.
2) The problem wasn't in how it was saved. It should be saved in UTC, but it should display in local time and adapt to changes in setting for gmt_offset.

**Comment by Shelob9** [comment]
Close via 	1841984
