### ISSUE TITLE
Pressing "Enter" on create new form modal makes it go away, this is displeasing.

### ISSUE THREAD

**Issue by Desertsnowman** [CalderaWP/Caldera-Forms#563]
This really annoys me. Currently you have to click "Create Form" for the form to be created. I constantly press enter after entering a name and it just closes the modal.

So lets fix that shall we.

**Comment by Shelob9** [comment]
Was about to report same issue, annoys me hard.

**Comment by Shelob9** [comment]
oops, didn't mean to re-open.
