### ISSUE TITLE
Show shotcode for form in shortcode form builder, should be click to copy

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#565]
Needed beacuse in most themes that use the Visual Composer plugin, the button to add the shortcode to a page is hidden

We should do this like in Ingot's test group admin.

**Comment by Desertsnowman** [comment]
@Shelob9 - concept to show the shortcode when clicked. maybe needs to be a little more obvious...

![cf-get-shortcode](https://cloud.githubusercontent.com/assets/307466/16407905/6f3e2b0a-3d16-11e6-8e1b-8745bab16cdd.gif)

**Comment by Shelob9** [comment]
We discussed this and agreed there is nothing intuitive about this.

Lets put in the header of the form editor the actual shortcode with `<pre>` tags, that way it looks like a shortcode that someone would want to copy, not a logo that no one would ever think reveals a shortcode. Then on hover, click to copy.

**Comment by Shelob9** [comment]
Also @Desertsnowman if you're going to do this instead of me, please re-assign to me.

**Comment by Shelob9** [comment]
@Desertsnowman I agree and disagree with 	689a305
The "get shortcode" in the form list table is great. +2 points. But why are we hiding it in the form editor itself? I really don't see why it would logically go in Form Settings when a shortcode is not a setting. It's not intuitive at all to put it there.

I will accept nothing less than it being 100% obvious what the shortcode is for the form you are currently editing. I don't see anyway to do that besides putting it in the top nav bar.

![screenshot from 2016-06-29 21-36-12](https://cloud.githubusercontent.com/assets/1994311/16474088/8e40eb42-3e41-11e6-9f37-639392cac868.png)

**Comment by paaljoachim** [comment]
Another option to show the shortcode is under the quick edit bar for each form. Something like this...

![cf-shortcode](https://cloud.githubusercontent.com/assets/5323259/16519830/0f629978-3f8c-11e6-94fd-19f7cb9530b2.jpg)

**Comment by Desertsnowman** [comment]
@paaljoachim I merged much of the new stuff to the stable-dev branch. Try that one.

**Comment by paaljoachim** [comment]
This? https://github.com/CalderaWP/Caldera-Forms/tree/current-dev

**Comment by paaljoachim** [comment]
Ok yeah it is the right one. I notice the text Get Shortcode.

![screen shot 2016-07-01 at 14 20 29](https://cloud.githubusercontent.com/assets/5323259/16521418/02ce6128-3f97-11e6-90f4-82a31b546780.png)

It would be nice to Adjust the font size of Form - Entries to 16px. <th>Form</th>  and then the form title to 16px. Keep quick edit at 14px.
Add left padding of 10px to span.cf-form-shortcode-preview. It gives just a little more space.
Add some padding to form title and entry numbers. Add a link to entry number that goes straight to the Entries section.

**Comment by paaljoachim** [comment]
Where do you want feedback on the current-dev branch?

**Comment by Shelob9** [comment]
I like this now closing.
