### ISSUE TITLE
Improvments For Advanced File Fields

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#569]
https://wordpress.org/support/topic/file-upload-fields-not-working-as-advertised

- [x] Limit file types
- [x] Attach all files to entry
- [x] Attach all files to emails
- [x] Limit size based on WP rules
- [x] Add to media library
- [ ] Remove beta label once above are satisfied

**Comment by Desertsnowman** [comment]
closed via 170474b
