### ISSUE TITLE
Picture wont upload

### ISSUE THREAD

**Issue by 760bennie** [CalderaWP/Caldera-Forms#573]
The file element is not uploading pictures. I have it as a required field, I could attach the picture but after i click submit nothing happens. I see that the upload file field is highlighted in red.

**Comment by 760bennie** [comment]
![image](https://cloud.githubusercontent.com/assets/18430160/14999826/93fd7f7e-1140-11e6-9b51-7d516ff5647d.png)

**Comment by 760bennie** [comment]
This is the step by step
1. Click on the date field
2. Select today's date from the calendar
3. click on add files
4. select a picture (any picture) from your computer
5. click submit

The page will reload and if you notice the picture field will be highlighted in red with the message "picture is required", meaning the file did not upload.

Here is the link to the page:
http://supplychain.institute/wp/manna/?cf_er=_cf_process_572accf7b3d0d

password is: Manna

**Comment by Desertsnowman** [comment]
The new file uploader requires the form to be in Ajax mode. @Shelob9 should selecting the field force the form into Ajax or should the field somehow work independently ( have its own Ajax methods )? This my be complicated though.

**Comment by Shelob9** [comment]
Ummm, the 2nd option is preferable, I'm not 100% "do it that way" beacuse when form submissions throw PHP notices/warnings which is a thing on like every WordPress site, we turn of AJAX submission...

**Comment by Desertsnowman** [comment]
@Shelob9 I agree and that was my first consideration. However, the ajax fail is due to php warnings or whatever, breaks the javascript, which in tern will break the uploader. making it not possible to work anyway.

**Comment by Desertsnowman** [comment]
I did changes on the validation and now I'm not able to replicate this, indicating its resolved for me. I think it's safe to say its fixed now, but more testing by @760bennie would be useful. other than that, I'll say this is done.
