### ISSUE TITLE
More accesible hide/show of field

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#574]
If a field is hidden set aria-hidden attribute to "true" and visibility css attribute to "hidden" When a field is shown make it aria-hidden="true" visibility = "visible"

`$( el ).show().attr( 'aria-hidden', 'false' ).css( 'visibility', 'visible' );`

`$( el ).hide().attr( 'aria-hidden', 'true' ).css( 'visibility', 'hidden' );

**Comment by Desertsnowman** [comment]
@Shelob9 - The front end isn't simply a show and hide, but rather an add and remove field.
7fd0a22 addresses this by making it an aria live region
