### ISSUE TITLE
Using default value and input mask prevents input on mobile

### ISSUE THREAD

**Issue by Ribice** [CalderaWP/Caldera-Forms#589]
Hi,

Used single_line_text element.

Set 'default' value to 1, masking to 9, and type override to text.

On mobile, can't change the default value (it's 1 always).

Link to form:

http://web.holandtravel.ba/vip-rezervacija/

Field: Broj dana

Regards,

**Comment by Desertsnowman** [comment]
Pushing to next version. requires an update to the masked import which I don't want to do just yet as its untested and I would prefer to improve it properly.

**Comment by Shelob9** [comment]
Closing in favor of #1118
