### ISSUE TITLE
Caldera Forms Uploading Really Slow....

### ISSUE THREAD

**Issue by ShadyNicNack** [CalderaWP/Caldera-Forms#598]
Caldera Forms,
At starter, I really did like your plugin.  But starting to have issue with the plugin and your basic support page is keep on redirecting me off it, so it is starting to get very frustrated.  So this is the only way I can get a hold of you guys...  
I am currently having issues with the form uploading ABSOLUTLY SLOW.  
I have created a price quote form.  I have separated the price quote into 7 different states which we have created 7 different forms.  Each state has the normal form of entering name, email and etc. and then below there is a check items of about 25 to 40 items.  
When they click on the item, the form will then show or unhide the item price and then they can pick out the number of years and/or quantity depending the item.  At the bottom, it will calculate all the items they have picked out.  Once they hit submit, it will send information to the sales rep and then to the office person so they can file the form.  
My issue is when the form is pulling up in both chrome, firefox and especially edge, the form takes a while to pull up or even pop up.   Why is this issue happening? Is there a way to fix this and make this quicker to pull up?

It is currently on a local host using a wamp server.  I have files attached to show what the form looks like.  

![image](https://cloud.githubusercontent.com/assets/19393139/15296897/22ee35f4-1b5d-11e6-88d7-e6066ad1f32e.png)

![image](https://cloud.githubusercontent.com/assets/19393139/15296908/325d1686-1b5d-11e6-943e-da9dd30adb06.png)

![image](https://cloud.githubusercontent.com/assets/19393139/15296920/3c4e31de-1b5d-11e6-89cc-baeab890c6fe.png)

Thanks,

Nicholas Bowers
Web Design & Developer
Vanguard Appraisals, Inc.
NicB@camavision.com

**Comment by Shelob9** [comment]
I'm sorry but this is not the correct place for support. Our support policy is explained here: CalderaWP.com/support That page explains that you must make a purchase to receive support.
