### ISSUE TITLE
Improve language in form editor naviagation

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#604]
Here is my proposal based on some Jason ideas :
<img width="702" alt="screen shot 2016-05-18 at 10 58 45 pm" src="https://cloud.githubusercontent.com/assets/1994311/15381288/4ad8575c-1d4c-11e6-9a9f-dd49d09ec61d.png">

In this I have:
1) Renamed "General Settings" to "Settings".
1) Changed the order and item names of the lower menu:
* Layout
* Email (formerly mailer)
* Events (formerly processor)
* Logic (conditionals and variables)
- Responsive goes inside of "settings"
1) I have relabeled "Update Form" to "Save"
1) I have updated "Preview Form" to "Preview"
1) I have relabeled "Add Element" to "Add Field"

**Comment by Shelob9** [comment]
@Desertsnowman  I'm super into this, and other ways to be more new user friendly right now.

**Comment by dlincoln** [comment]
+1 from user bleachers.

On Wed, May 18, 2016 at 11:05 PM, Josh Pollock <notifications@github.com>
wrote:

> @Desertsnowman <https://github.com/Desertsnowman> I'm super into this,
> and other ways to be more new user friendly right now.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CalderaWP/Caldera-Forms/issues/604#issuecomment-220216564>
>



-- 

   Dave Davis
   Partner, Media Design + Operations
*   c. *513.253.3702
*   w. *theallnightparty.com

**Comment by Shelob9** [comment]
Another option, slighly less drastic option:
![screen shot 2016-05-23 at 10 55 52 pm](https://cloud.githubusercontent.com/assets/1994311/15490868/86ad85ea-2139-11e6-9a14-56e560c3c40b.png)

In this option I have:
1) Renamed "Mailer" to "Email" and made it the second tab.
2) Put conditions, variables and response under an "Advanced Settings" tab.
3) Changed "General Settings" to "Form Settings"
4) Changed "Update Form" to "Save Form"
5) Changed "Form Preview" to "Preview Form"
6) Changed "Add Element" to "Add Field"

**Comment by DevinWalker** [comment]
All the form content changes sound great. What I'd like to see more is some UI changes. Are we open to that here or is this more of a text update change?

**Comment by Shelob9** [comment]
@DevinWalker Do you prefer the first or second option?

Open to whatever other ideas you have. We have a few issues open on this milestone for UI improvments: 
#607 #606 #605

If it doesn't fit into that, we can discuss here and I can parse to new issues as need be.

**Comment by Shelob9** [comment]
@Desertsnowman What is the status of this? I'd really like to get rid of the responsive settings tab (move inside of settings and rename "Form Settings" to just "Settings"

**Comment by paaljoachim** [comment]
Hey guys

Title - Contact -- what about clicking the title brings it back to the all form screen?

Form Settings -> Settings
Save Form -> Save
Preview Form ->  Preview

Layout
Email
Events/Processors -> Processors is an ok name for it.
Advanced Settings or Logic -> I think it is good enough with one setting for a form. So it would be better to name it Logic that contain the conditionals and variables and then place the responsive into settings area.

Add Element -> Add Field is a good idea.

NB! It would also be good to add an Entry tab.

My conclusion the tabs would then be:
Contact (title clickable brings one back to the all forms screen) - Settings - Save - Preview
Layout - Email - Processors - Logic - Entries
