### ISSUE TITLE
Improve initial state on form editor load

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#605]
When you first enter the Caldera Forms form editor, you should have:
1) Focus on the first field in the first row so, the pencil icon and row management icons are active.
1) If no fields, focus on first row.
1) If no fields, the "Add Element" (or Add Field per #604) should slowly pulse between primary color and non primary button color to draw you in.

**Comment by danmilward** [comment]
Can you upload some screenshots please

**Comment by paaljoachim** [comment]
I believe Josh is saying these things:

**Focus on the first field in the first row so, the pencil icon and row management icons are active.**

![screen shot 2016-07-01 at 13 24 20](https://cloud.githubusercontent.com/assets/5323259/16520258/42917866-3f8f-11e6-8b22-cc79b993acee.png)

**If no fields, focus on first row.**
(Actually there is no first row and one has to click to create the first row. If the form is empty then there should automatically be 1 row in the form.)

![screen shot 2016-07-01 at 13 25 38](https://cloud.githubusercontent.com/assets/5323259/16520272/5db4efec-3f8f-11e6-8cbc-9eda0db70f64.png)

**Comment by Shelob9** [comment]
@Desertsnowman Where are we on this?

We really need to at least get the initial focus done. Giving users no indication that these random white rectangles are editable is not intuitive.

**Comment by Desertsnowman** [comment]
Got to still take a look. But I'm able to sort it out tomorrow morning.

**Comment by Desertsnowman** [comment]
closed via ac900ab
