### ISSUE TITLE
New Form Modal Should STRONGLY Encourage Form Templates

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#606]
- [x] Remove all the fields besides name.
- [x] Remove the save button

Now it's just a name field.
- [x] Make modal 90% width

- [x] Show templates as images that are representations of the grid layout, with some detail. One will be empty.
- [x] Have focus start on contact form template
- [ ] On hover overlay a plus button that when clicked, chooses new form template and makes it so.

**Comment by Shelob9** [comment]
@Desertsnowman I'm happy with the new form modal. But I am concerned about its width. Why not make it 70-90% of the width of screen? I'm worried that having only two templates wide could lead to lots of scrolling if you have a few add-ons active that could be avoided by not wasting so much of the screen on greyed out background... Feel free to disagree, but I don't see the harm in making the modal wider.

**Comment by Desertsnowman** [comment]
@Shelob9 -creating on selecting a template gives too much room for error. need a final confirmation.
see 70ad65e which does this:
![new-form-modal](https://cloud.githubusercontent.com/assets/307466/16615222/60ef9204-4375-11e6-9a86-c43bc6826bae.gif)

**Comment by Shelob9** [comment]
@Desertsnowman After 	d8dd4fd things look good, but the overflow on templates doesn't look great. Can you shrink larger templates or set overflow to hidden?

![screenshot from 2016-07-06 21-47-49](https://cloud.githubusercontent.com/assets/1994311/16640135/87a75ce4-43c3-11e6-9402-229d4288025a.png)

**Comment by Shelob9** [comment]
I've been living with new modal for a few days now. Very happy with how it turned out.

Awarding a fair amount of points to @Desertsnowman and closing as "vastly improved"
