### ISSUE TITLE
Description / Caption text as a info tooltip

### ISSUE THREAD

**Issue by adeelpk3** [CalderaWP/Caldera-Forms#610]
Hi, I want to use description/ caption text as a info tool tip just like attached jpg.
Can you suggest on which file should I do this?
Regards
Adeel Fiaz
![description](https://cloud.githubusercontent.com/assets/18465823/15632546/b761f948-25a6-11e6-9fce-6d9ff51a1773.jpg)

**Comment by Shelob9** [comment]
This is a support request not an issue. Please use https://CalderaWP.com/support for support.

The short answer to your question is each field has its own file here: https://github.com/CalderaWP/Caldera-Forms/tree/current-stable/fields
