### ISSUE TITLE
Select Fields Duplicated in Entry List

### ISSUE THREAD

**Issue by iannich** [CalderaWP/Caldera-Forms#613]
Hi,

Caldera Forms Version 1.3.5.3 

Myself and 2 other users at Wordpress.org have noticed an issue with Select field values being duplicated in the Entry details. See here: https://wordpress.org/support/topic/viewing-entries-have-duplicates-of-select-fields

I noticed that the issue is not with all select fields in a form, so investigated. The following is a copy of my post on the Wordpress support topic above:

-------------------------
Same here but it doesn't seem to happen for all select fields.
After trying to track down what's different with the fields that are duplicated and those that aren't the only thing I could find was as follows:

The values of the select fields that are not duplicated allow the user to choose imperial sizes such as 4ft 10" or just 20". Don't know if it has anything to do with it but it seems strange, or a coincidence, that those that are not duplicated contain the double quote character.

Just tested the above. I created a small form with 2 select fields. 
In the first I added the values 1, 2 and 3
In the 2nd I added the values 1", 2" and 3"

Submitted the form multiple times then swapped the values around. (First select with inches and 2nd without). The results were consistent, The fields with an integer are always duplicated in the entry list and those with the double quote were not duplicated. Note: fields containing text but not a double quote are also duplicated so it's nothing todo with integers.

Obviously once the entry duplication is fixed it won't matter why this strange behaviour but it might help track down the bug?

I am reporting this on the plugin's GitHub page.

------------------------------------------

Hope you can help.

Regards

Ian

**Comment by Desertsnowman** [comment]
closed via  45ecec6
