### ISSUE TITLE
W3 Total Cache and Date Field problem

### ISSUE THREAD

**Issue by devotas** [CalderaWP/Caldera-Forms#615]
Enabling W3 Total Cache Plugin's Minify javascript module makes Caldera form's date-field without any Calendar pop-up when clicked.
Is there any temporary solution to this?

**Comment by Shelob9** [comment]
Our Javascript is already minified. Re-minfy it is not needed and will likely break it.

Also, you must set a cache exemption on the page with our form for this to work.

If you need additional help, you should open a support ticket at https://calderawp.com/support but I'm not sure what else I can tell you.

**Comment by Shelob9** [comment]
See: #1007
