### ISSUE TITLE
Export entries stopped working in 1.3.5

### ISSUE THREAD

**Issue by cbhtcomputers** [CalderaWP/Caldera-Forms#621]
I was able to export entries in early May.  Tried again a couple of days ago and it no longer works.  If I rollback to 1.3.4.3, then it works.

Tried it with different browsers and different logins (from admin to an author role) with the same results.

I can see all the entries, but when I select export, the screen goes back to the list of forms.  No popup asking whether to save or open with excel.

No errors in debug logs.  Javascript shows NetworkError.  Looking at the network tool, I see several 304 status returns on caldera items.  I've included snapshots.

In 1.3.4.3 I see the following when I select export:
admin.php?page=caldera-forms&export=CF56e023188461a and the type is css

In 1.3.5.3 the type is html

![caldera network page 2](https://cloud.githubusercontent.com/assets/19737470/15793290/ef3d3c98-29b0-11e6-8929-5f3618447778.JPG)
![caldera network page 1](https://cloud.githubusercontent.com/assets/19737470/15793289/ef3bb88c-29b0-11e6-8e6f-e9d64fd98d76.JPG)

**Comment by cbhtcomputers** [comment]
Oops.In 1.3.4.3 the type is csv...not css

**Comment by Shelob9** [comment]
@cbhtcomputers We have not been able to reporduce this. A 304 code would indicate those files are being cached, and this is a server issue. If you need additional help, please open a support ticket at https://CalderaWP.com/support
