### ISSUE TITLE
Entries list table is not responsive && a general mess.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#627]
OK, I'm done accepting how bad the entries list table is. How can we make "responsive" such a big deal and our entries list in main UI:
1) Is given no space.
2) Everything escapes the container

It is an embarrassing mess on my 13 inch laptop screen. "You can pin to menu" is not an acceptable excuse, no one knows what that feature is.

We must:

- [x] Make list table responsive.
- [x] Make items not escape container when shrunk
- [x] When viewing entries, get rid of forms list table.
- [x] Add a close button to close entries list and get forms list table back.
- [x] Make all of the above items not make our accessibility issues worse.

**Comment by Desertsnowman** [comment]
cleaned up with 4ee0209

**Comment by Shelob9** [comment]
Very good. I see a few remaining small issues:

 

- [ ] In small screen sizes, the toolbar items above entry list does overlaps and does not stack well.
- [ ] On very narrow screens there is no way to get to the entry list, I can't side scroll to the right.
- [ ] When WP admin bar gets taller, it covers some of the Caldera header.

<img width="510" alt="screen shot 2016-06-09 at 1 51 11 pm" src="https://cloud.githubusercontent.com/assets/1994311/15940352/b62e4472-2e49-11e6-8a1e-efcae3abf2bc.png">
<img width="820" alt="screen shot 2016-06-09 at 1 50 58 pm" src="https://cloud.githubusercontent.com/assets/1994311/15940353/b62eee40-2e49-11e6-901d-0e1ea00d1471.png">
<img width="1124" alt="screen shot 2016-06-09 at 1 50 46 pm" src="https://cloud.githubusercontent.com/assets/1994311/15940354/b62f86d4-2e49-11e6-96f2-8395dbaf506a.png">

**Comment by Desertsnowman** [comment]
@Shelob9 - I merged new changes with current dev- please evaluate

**Comment by Shelob9** [comment]
It looks good. I'm closing this, but my concerns listed in #660 remain.
