### ISSUE TITLE
Rearrange pages

### ISSUE THREAD

**Issue by lefty55104** [CalderaWP/Caldera-Forms#63]
Is there a way to rearrange pages or add a page in between two others? It would also be helpful if there was a way to move a field to a different page.

**Comment by Desertsnowman** [comment]
Wish I could get this in the next update. Will need to wait.

**Comment by bkonia** [comment]
Any update on this feature? It would be great if we could just drag/drop the page buttons to rearrange them.

**Comment by Ajguy** [comment]
Agreed. This feature feels long overdue.

**Comment by onefreeborn** [comment]
I also vote for the ability to rearrange pages via drag/drop.  
I would be nice to start with a template, and then not have to move those fields manually to page two or three of the form. 
Instead, simply add a new page, and drag it to the Page1 position.

**Comment by Chris2011** [comment]
Anything new here? This feature would be very handy and is needed.

**Comment by JamieBohannaWebDev** [comment]
Bump?

Looks like this issue was raised in 2015 but still can't arrange pages?

Sucks when you realise you forgot to add a page halfway through so you have to delete all the trailing pages to get to the place you need to be or rearrange fields around :(

**Comment by johnnyvenom** [comment]
+1 - this functionality is very much needed. Thanks.

**Comment by Zodiac1978** [comment]
Any news on that?

**Comment by Tofandel** [comment]
Up

I would really like this feature as well, when you have to add a page before another one you have to manually move everything and when you have more than a hundred fields it's just not something you wanna do..

**Comment by pascalknecht** [comment]
This feature would be great to have indeed.

**Comment by princejnvg** [comment]
Its more than 3years this issue was opened.
Its really needed.

**Comment by regiside** [comment]
I agree, not having this ability is costing me hours of work. Please come up with some way to insert pages between other pages, or change page order.

**Comment by oldrup** [comment]
+1 extending forms that need an additional page before any existing page, in reality requires you to build the form from scratch. There is no way to import/export individual pages as far as I can see. Can the page order be hacked by manipulating the database directly?

**Comment by rawcat** [comment]
Still nothing… :(

**Comment by espiat** [comment]
Hey. Is this feature planned in the next 5 years?

**Comment by bitsgit** [comment]
Does anybody has a solution for this? (I have a 30 page form and need to insert a new page right in the middle :)  :( )

**Comment by espiat** [comment]
Unfortunately, I have no solution for this

**Comment by Tofandel** [comment]
You can unserialize the data in the database and add the page in the middle reserialize and save, and come back to edit the form

**Comment by jcserrao** [comment]
+1

**Comment by GuillaumeSorel** [comment]
moving pages and fields set would be a huge improvement. :-(

**Comment by espiat** [comment]
Okay.
We should close this issue and all the orthers.
Thanks Caldera Team for the good work.
https://calderaforms.com/2021/03/the-future-of-caldera-forms/
