### ISSUE TITLE
Warning: invalid argument supplied for foreach() -- wp-content\plugins\caldera-forms\classes\core.php (line 3771)

### ISSUE THREAD

**Issue by taylortyger** [CalderaWP/Caldera-Forms#630]
Hi,

I have a client that owns a website with Caldera Forms installed. She contacted me the other day telling me that she was getting a warning/error message on the site that said the following:

> Warning: invalid argument supplied for foreach() in \wp-content\plugins\caldera-forms\classes\core.php on line 3771

The site uses the Divi theme. However, my client has other sites that use the Divi theme and Caldera Forms with no warning message.

This is the foreach in question: 

> foreach ($sidebars as $sidebar => $set) 

And here is where the $sidebars variable is initialized:

> $sidebars = get_option('sidebars_widgets');

I was able to get rid of the warning by adding the following if statement to check the $sidebars variable before running the foreach:

> if (is_array($sidebars)) { 
			foreach ($sidebars as $sidebar => $set) {

However, since this was added to the plugin itself, it will be lost when updated. Is this something you would consider addressing in an update?

I thought this may be something you would want to add to the plugin, which is why I posted it here.

Thanks,

Taylor

**Comment by Shelob9** [comment]
@taylortyger  Thanks for reporting this. I will load up my copy of Divi and take a look.

**Comment by Shelob9** [comment]
close via 		0f12dfd
