### ISSUE TITLE
reCAPTCHA - Error: ReCAPTCHA placeholder element must be empty

### ISSUE THREAD

**Issue by rickyspires** [CalderaWP/Caldera-Forms#634]
Hello.

the reCAPTCHA is breaking my conditional logic because of a bug:

Error: ReCAPTCHA placeholder element must be empty
...s not exist");if(0!=je(c).length)throw Error("ReCAPTCHA placeholder element must...
recaptcha__en.js (line 356, col 306)

I have followed there steps;

Paste this snippet before the closing </head> tag on your HTML template:
<script src='https://www.google.com/recaptcha/api.js'></script>

Paste this snippet at the end of the <form> where you want the reCAPTCHA widget to appear:
<div class="g-recaptcha" data-sitekey="6LcOjiITAAAAAAJgsIlxPZR63cs1RxqxMEV5ThGZ"></div>
NOTE: I pasted this in to a html content block at the bottom of the form under the submit button

I read in a forum that <script src='https://www.google.com/recaptcha/api.js'></script> is no longer needed so i tried with and without but still get the error

Any ideas ? 
Thanks

WordPress 4.5.2

**Comment by Shelob9** [comment]
@rickyspires Do I understand correctly that you are adding your own reCapthca? I'm not sure I can help with that.

I would ask if you are experiencing any issues with the default anti-spam in Caldera Forms? Usually is is almost 100% effective, without the reduction in conversions that you get from using a Captcha. If you were getting more than 1 or 2 spams a month when using our default anti-spam, that is something I want to know about and adresses right away.

**Comment by rickyspires** [comment]
Hello.

Thankyou for your reply.

I am not adding my own reCapthca. It is the default one that comes with caldera forms that i am talking about.

i got the details from google (i.e the secret) and put that in but it wasn't showing so i thought i had to add the other code in the head of my site and at the bottom of the form. so i dont need to add any other code then . so it must be a another reason.

**Comment by Shelob9** [comment]
Oh in that case, just take out the reCaptcha field and you will be fine. It doesn't do anything anyway.
