### ISSUE TITLE
Submenu (pinned) entry viewer AJAX does not reflect permissions of pinned entry viewer

### ISSUE THREAD

**Issue by maxpen** [CalderaWP/Caldera-Forms#635]
So there are a couple of entries in trash and 1 is not and I can see them fine but when I switch to an editor acc with also a bbpress mod role they cannot see anything. i've double checked the form settings and permissions of user acc and roles.

This is a clear bug.

**Comment by Shelob9** [comment]
@maxpen To clarify is your bug that you can not see trashed entries when logged in as a editor?

Are you referring to the main admin or in the submenu for the entry viewer? Also can you please tell me what version of Caldera Forms you are testing with?

**Comment by maxpen** [comment]
It seems that no matter what I do only admins can access the forms page or see entries.

/wp-admin/admin.php?page=caldera-forms-pin-somenumershere


gets: You do not have sufficient permissions to access this **admin page**.

And to clarify I can't see anything. I use the Switch TO plugin to quickly see what other users see. I don't think that plugin is giving any false info. I'm using the latest version that was released 3 weeks ago.

**Comment by Shelob9** [comment]
@maxpen Thanks for the additional information. I changed the title to reflect this. We will do our best to get this bug addressed in the next release.

**Comment by Shelob9** [comment]
In `Caldera_Forms_Entry_UI::view_entries()` and `Caldera_Forms_Entry_UI::view_entry` we use our cap check. Need to filter that by pin role value.

**Comment by Shelob9** [comment]
Close via 	4d8006b
