### ISSUE TITLE
Sprout invoice and Caldera Forms client problems

### ISSUE THREAD

**Issue by danovici2005** [CalderaWP/Caldera-Forms#639]
Hi I have Caldera forms on my website and it works ok, I have implemented Sprout Invoice to create invoices from form submision...well the problem is that when I edit the Estimate at the Client field it shows only the user from the first submited form...it should load the data from that form that I am editing. I have created the processors for sprout invoice and Client...if anyone can help I will be glad to provide maybe a user and passoword. Thanks

**Comment by Shelob9** [comment]
Can you email @Desertsnowman about this, David@CalderaWP.com please and send him your login details. he can help with this one.

**Comment by danovici2005** [comment]
Thank you I will write.
