### ISSUE TITLE
Form entries not captured - MariaDB 10+ innodb index key length limitations

### ISSUE THREAD

**Issue by ignusvermaak** [CalderaWP/Caldera-Forms#647]
On both sites I did my test with the latest versions of WP and the latest theme versions.

We have a test site for Caldera here: https://caldera.feedmybeta.com/ submit the form here: https://caldera.feedmybeta.com/contact/ Entries are captured fine.

Oddly, when I test the form here https://easymealplans.feedmybeta.com/contact-us-2/ entries are not captured. Same thing happens with only Twenty Sixteen and Caldera active.

**Comment by ignusvermaak** [comment]
How can I send you login details privately?

**Comment by Desertsnowman** [comment]
@ignusvermaak - I have access details and will check and confirm.

**Comment by Desertsnowman** [comment]
Issue relates to innodb index column lengths. in this case particularly to MariaDB 10+
see https://answers.launchpad.net/maria/+question/241612 as it give a good explination.

@Shelob9 - the solution is to add `ROW_FORMAT=DYNAMIC` to table creation ( `COMPRESSED` will also work ) We'll need to add this to the activation method.

**Comment by Desertsnowman** [comment]
@Shelob9 - woocommerce had this issue a while back as well- see https://github.com/woothemes/woocommerce/issues/10483
I like how they fixed it - see https://github.com/woothemes/woocommerce/commit/b86e16cef46e14543ce1ccdca28bcdec469c0fcb

**Comment by Shelob9** [comment]
@Desertsnowman I'm rea-assigning to you based on our conversation.

**Comment by Desertsnowman** [comment]
closed via 3f6d562
