### ISSUE TITLE
New new form modal doesn't work with connected forms

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#648]
After changes in #606 activating connected forms busts the new form modal.

`Notice: Undefined index: layout_grid in /srv/www/wordpress-trunk/wp-content/plugins/Caldera-Forms/classes/admin.php on line 197` gets thrown in the middle of the modal and breaks the layout.

@Desertsnowman Please validate that `layout_grid` isset.

Also, I think a good solution here is to add a "Create Connected Form" button to the left of the new form button when connected forms is active. I'm OK with that requiring an update to connected forms for compatibility with 1.3.6

**Comment by Desertsnowman** [comment]
@Shelob9 +1 on the connected form button, but not yet for 1.3.6 as this opens up UI changes that will affect things.

**Comment by Shelob9** [comment]
@Desertsnowman I'd say we should add a hook to the footer of that modal, but that doesn't seem doable with the way modals are built. It would be nice to have a way for connected forms or other add-ons to add in something there.
