### ISSUE TITLE
Weird <br> Elements Must Be Removed

### ISSUE THREAD

**Issue by ahmadawais** [CalderaWP/Caldera-Forms#650]
I had an issue with CalderaFroms http://cloud.ahmda.ws/v8xDk9I
Let me know where these ` <br>` elements are, would love to contribute by removing them.
One should never use ` <br>` elements. Instead, style the input elements as block elements via `display:block;`

**Comment by ahmadawais** [comment]
On a separate note, I am pretty sure there are two console errors due to CF, can you check what is this 

http://cloud.ahmda.ws/qtGyvgH

**Comment by Desertsnowman** [comment]
@ahmadawais - same issue as with #651

**Comment by ahmadawais** [comment]
@Desertsnowman That is a completely different issue don't you think? Or are you telling me that those `<br>` elements were added by the theme? Just wondering. Let me know.

**Comment by Desertsnowman** [comment]
wptexturize and wpautop is run on do_shortcodes. single line breaks are replaced as `<br>` and double breaks as `<p>` 
at least I'm pretty sure of it.

**Comment by ahmadawais** [comment]
@Desertsnowman Thanks for letting me know. I double checked, you are right. I removed the filters and the error is gone. Thanks for creating Caldera Forms 👍
