### ISSUE TITLE
Forms do not display sent message alert

### ISSUE THREAD

**Issue by ahmadawais** [CalderaWP/Caldera-Forms#651]
I am going to uninstall CF coz of these errors since no one gets the form sent message.

I am pretty sure there are two console errors due to CF, can you check what is this 

http://cloud.ahmda.ws/qtGyvgH

![](https://i.imgur.com/V79uPM4.png)

**Comment by Shelob9** [comment]
This is a sign that your theme is applying wpautop or wptexturize after core runs do_shortcode. Nothing I can do about that. Please fix this in your theme.
