### ISSUE TITLE
Textarea's Background Doesn't Turn Green on Valid Input

### ISSUE THREAD

**Issue by ahmadawais** [CalderaWP/Caldera-Forms#653]
Found a minor issue. I submitted the empty form, it turned the empty inputs read, perfect! Then when I entered valid input values, they turned green, which is pretty good UX. Only the `textarea` didn't turn green.

![](https://i.imgur.com/83vE9LX.png)

Let me know if I can help. Or if this is not related to your plugin.

There are no JS errors in the console 

![](https://i.imgur.com/Bnxw9PL.png)

**Comment by andrewlimaza** [comment]
Unable to recreate this issue on my local environment, works as expected version on version 1.4.7

**Comment by Shelob9** [comment]
@andrewlimaza me neither. I am closing as "fixed by accident" beacuse I know this used to be a problem.
