### ISSUE TITLE
Redirect doesn't work

### ISSUE THREAD

**Issue by zbanga** [CalderaWP/Caldera-Forms#654]
The redirect doesn't work. The form redirects to the form after you press submit not redirecting to the link provided.

**Comment by Shelob9** [comment]
@zbanga This is not the correct place for support requests. Please use https://CalderaWP.com/support

Why I consider this a support request is that the redirect processor does work, but something on your site is causing it to not work. That's something we can help you troubleshoot as part of our support service.
