### ISSUE TITLE
A string of html comment comes bare

### ISSUE THREAD

**Issue by devotas** [CalderaWP/Caldera-Forms#656]
When a field appears or disappears on a condition (toggle), a string of html comment comes bare in the frontend.

Here is screen shot
![nn](https://cloud.githubusercontent.com/assets/14121199/16356035/30b0e04c-3ae8-11e6-97b2-940f157a5aee.jpg)
The live form is [here](https://ontrip.in/lake-view-nest-khecheopalri/) 
Just check the "Date is not fixed yet" field and then uncheck it. First the date field disappears and then it reappears with the bare string of html.

**Comment by devotas** [comment]
When we deactivated the W3 Total Cache plugin the error goes away. As we have deactivated it for now, the live form shows no error. But, we can see that W3 Total Cache plugin has major problems with Cadera forms.

**Comment by Shelob9** [comment]
@devotas You should always add a cache exemption for W3 Total Cache or any other static HTML cache plugin on the page with your form. There is no other way to make it work.
