### ISSUE TITLE
Recent main admin changes have made plugin less accessible 

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#660]
New changes are visually appealing, but create add new issues for those using assistive devices.

- [x] The opener for the settings modal uses an icon with no screen reader text. 
* I like using icons when they are super obvious, but we can't end user user reads English or is not blind.
* https://github.com/CalderaWP/Caldera-Forms/blob/5bc1cc6cc562bf4d058a9dc519c2fff085ac3996/ui/admin.php#L47
* https://make.wordpress.org/accessibility/2015/02/09/hiding-text-for-screen-readers-with-wordpress-core/

- [x] The title attribute for the element that opens the settings modal is not semantic or clear. "General Display Settings" would empty there are other Display Settings. This is the only Display Settings, therefore adding "General" reduces clarity and increases confusion.

- [x] The entry viewer changes the markup of page significantly in a section of the page that has no `aria-live` attribute.
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

- [x] The new toggle arrows are hidden and shown with improper CSS and no `aria-hidden` attribute. * Always use visibility and display CSS rules
* Any element that is dynamically hidden/ shown must use a `aria-hidden` attribute
* https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/

**Comment by Desertsnowman** [comment]
changes also included in 05a1e967a22bf4753d9aa40244bb0ed172bb070c

**Comment by Desertsnowman** [comment]
@Shelob9 - please review

**Comment by Shelob9** [comment]
@Desertsnowman See my comments on both commits.

Also, maybe I missed it, but did you add screen reader text to the toggle and settings icon? If you're going to use an icon, you must use screen reader text so someone using a screen reader will know what it does. https://make.wordpress.org/accessibility/2015/02/09/hiding-text-for-screen-readers-with-wordpress-core/

**Comment by Shelob9** [comment]
@Desertsnowman Look at 	ebbc7cf for how screen reader text should work.

**Comment by Desertsnowman** [comment]
@Shelob9 - I saw. But I also removed the icon and used text instead, like in the email settings button.
