### ISSUE TITLE
Review email UI

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#661]
@Desertsnowman I have merged new email system #527 

This introduces new UI to main admin. I did my best to mimic the 

Please do not put in a modal -- modals are too narrow and add to our responsive and accessibility issues. There are only two settings now, there will be a lot of additional settings added here either later in 1.3.6 dev or future versions.

**Comment by Desertsnowman** [comment]
I think we should look at creating this to a settings system, not just for email, but all settings like the display settings as well. A central place to put things in.

**Comment by Shelob9** [comment]
@Desertsnowman I agree, we should abstract new class `Caldera_Forms_Email_Settings` into one we can use for all settings groups.

**Comment by Shelob9** [comment]
@Desertsnowman I think it looks good after your revisions. Please address my two comments on 	e3561f1 and then close.
