### ISSUE TITLE
Slug with  accentuated letter "é ù ..." 

### ISSUE THREAD

**Issue by lipaonline** [CalderaWP/Caldera-Forms#668]
Hello,
when we name a field with accentuated letter , they will be deleted and not replaced.
ex:
"prénom" , slug -> "prnom" and not "prenom"

**Comment by Shelob9** [comment]
@lipaonline This is intentional. The slugs are used as HTML attributes and in dynamically generated JavaScript and therefore can not contain special characters.

**Comment by lipaonline** [comment]
The problem is that this special character is deleted and not replaced by a "normal" one.

"prénom" , slug -> "prnom" it should be :  "prenom"
