### ISSUE TITLE
Star ratings and range sliders don't reinitialize properly when unhidden by conditional logic

### ISSUE THREAD

**Issue by systems-CHL** [CalderaWP/Caldera-Forms#669]
Possible bug - star ratings reset when conditional logic fires.
I've tried this on a few individual forms across different sites.
Example - https://cornerstonehousing.com.au/testsurvey/
Not sure if it relates to #599 ?

**Comment by Shelob9** [comment]
Could also be related to #670

**Comment by Shelob9** [comment]
Also affects range sliders now :(
