### ISSUE TITLE
Ajax option not working on Mac Safari

### ISSUE THREAD

**Issue by SBenoit5** [CalderaWP/Caldera-Forms#677]
I have to disable the Ajax option or the form won't send on Mac Safari, and the warning tooltips won't popup.

**Short Debug Information**
WordPress Version: 4.5.3PHP Version: 5.6.21MySQL Version: 5.5.48Caldera Forms Version: 1.3.5.3WP_DEBUG:
**Full Debug Information**
WordPress Version: 4.5.3
PHP Version: 5.6.21
MySQL Version: 5.5.48
Server Software: Apache
Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
Session Save Path: /tmp
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache:
Apc: No
Memcached: No
Redis: No
Object Cache:
Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: coop_
WP Multisite Mode: No
WP Memory Limit: 40M
Currently Active Theme: Extra: 1.3.9
Currently Active Plugins:
Akismet: 3.1.11
BackupBuddy: 7.1.4.6
Caldera Forms: 1.3.5.3
Caldera SMTP Mailer: 1.0.1
Disable Emojis: 1.5.1
Favicon by RealFaviconGenerator: 1.3.5
iThemes Sync: 1.10.0
Members: 1.1.2
PA Modal Login: 1.3.1
Revision Control: 2.3.2
Snazzy Maps: 1.1.2
Subscribe to Comments Reloaded: 160115
SVG Support: 2.2.3.2
Sélecteur de menus:
TinyMCE Advanced: 4.3.10.1
WP-Optimize: 1.9.1
WP-Polls: 2.73.1
WP First Letter Avatar: 2.2.6.1

**Comment by bkonia** [comment]
I have the same problem in Chrome.
