### ISSUE TITLE
Field validation is running on future pages

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#693]
@Desertsnowman Not sure what you did, but if I have a 2 page form with required fields on page 2, their validation is now running when I click next button on page 1 and I do not advance to page 2.

**Comment by Shelob9** [comment]
Maybe https://github.com/CalderaWP/Caldera-Forms/commit/1ee75065e930aa9d292c62773d9dd628470a1fdf ??

**Comment by Desertsnowman** [comment]
@Shelob9 - no that should not be stopping progression. I'll check and correct.

**Comment by Desertsnowman** [comment]
closed via 268f4f8
