### ISSUE TITLE
Entry viewer: there is no longer a way to change the number of entries per page

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#695]

**Comment by Shelob9** [comment]
@Desertsnowman We need to bring back that setting. In entry viewer, it has disappeared.

**Comment by Shelob9** [comment]
@Desertsnowman The value is pulled from POST request here:
https://github.com/CalderaWP/Caldera-Forms/blob/current-dev/classes/entry/ui.php#L101

But nothing is being sent with request and no UI control exists.

**Comment by Desertsnowman** [comment]
:facepalm:

**Comment by Desertsnowman** [comment]
closed via 4eabbf2
