### ISSUE TITLE
Advanced file button markup does not play well with TwentySixteen

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#704]
In the default WordPress theme, file upload buttons are black background, black text. This makes it quite hard to read.

Should be background black, text white. Really should be picking up theme style with out our style ovveridding, which is what is happening for text color.

I know, can't make it right on all themes, but 2014-2016 should work.

![screenshot from 2016-07-20 13-15-03](https://cloud.githubusercontent.com/assets/1994311/16995750/05d25b1a-4e7c-11e6-8c61-33299ca9d4c9.png)

**Comment by Desertsnowman** [comment]
Agreed. Will make the field styling simpler.

**Comment by Desertsnowman** [comment]
closed via 3b3e492
