### ISSUE TITLE
Two advanced file fields on one page breaks file type restrictions

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#705]
To reproduce:

Add an advanced file field restricted to jpg.

Add an advanced file field after it restricted to png.

Notice that you can add a jpg or png to 2nd field. 

Restriction works if only one file field.

@Desertsnowman Don't forget about what I told you in Slack re: this.

**Comment by Desertsnowman** [comment]
closed via 9dd5eaa

**Comment by Shelob9** [comment]
Reopening. After the last commit, if you add an invalid file type to the file field, it shows a visual error, but does not prevent field submission. Instead it makes it so no data is saved, but returns no error.

To be clear providing an invalid file to a file field should
1)  Display a validation error client-side
2) Disable the submit button.
3) If an invalid file type is submitted (by form or WordPress settings) form submission should return an error code and cause an error message to be displayed.

**Comment by Shelob9** [comment]
@Desertsnowman  Before closing this issue, please test with this form http://pastebin.com/MeUtHFZQ\

Please try putting invalid file types in one field, with valid types in the other (try both combinations) and see if you can submit or not. Also, once client-side validation is correct, force the submission and ensure that the server-side validation causes the right error.

**Comment by Desertsnowman** [comment]
closed via 3134667
