### ISSUE TITLE
New fields now show up next to last field in row, not below.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#706]
![screenshot from 2016-07-20 13-42-13](https://cloud.githubusercontent.com/assets/1994311/16996547/c8726996-4e7f-11e6-8f2f-978fdc304c2c.png)

**Comment by Desertsnowman** [comment]
Wow so confused. Will check it out.

**Comment by Desertsnowman** [comment]
closed via 3ae1092
