### ISSUE TITLE
Present possible issues in main admin screen

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#736]
We are tracking email fails. We should show a list of those in main admin screen.

Also I wonder if we can capture and log JavaScript errors on pages with forms, or errors during submission and put them there to.

**Comment by Desertsnowman** [comment]
Really like this idea. I initially wanted to have some stats here, one of the things that inspired me to make formworks.

**Comment by Shelob9** [comment]
Close via 	1f8d2c9
