### ISSUE TITLE
Google Re-Captcha

### ISSUE THREAD

**Issue by greg-hyatt** [CalderaWP/Caldera-Forms#750]
Have not been able to access link to former boxes that contained where you would place Google Re-Captcha. I have noticed on all client sites that I have updated this plugin on, the option for Google Re-Captcha seems to have been removed. 

Is there any plans to put it back in or how can I achieve putting it in manually?

Thanks,

Greg

**Comment by Shelob9** [comment]
Greg -

You are right, we have been slowly phasing out the reCaptcha field for a few months now. I detailed why here:
https://calderawp.com/doc/recaptcha-field/

Short version is reCaptchas are less effective than our default anti-spam, while hurting conversions, page load time performance and accessibility.
