### ISSUE TITLE
How to make it possible for user role other than admin to trash entries

### ISSUE THREAD

**Issue by bustapaladin** [CalderaWP/Caldera-Forms#752]
"Frm delete entries" doesn't work as a permission setting. It seems only admins can trash entries or is this a bug?

**Comment by Shelob9** [comment]
@bustapaladin Thanks for using Caldera Forms. Can I ask that you please not use this issue tracker for support requests, but only for bugs.

There is a filter for modifying permissions. See: https://calderawp.com/doc/caldera_forms_manage_cap/

 If you need help using this, please open a support request at https://CalderaWP.com/support

**Comment by bustapaladin** [comment]
So it is intentional that only admins can trash entries?

**Comment by Shelob9** [comment]
@bustapaladin It is intentional. Can you please open a support ticket and explain your needs and provide the required information? I'd be happy to help there.
