### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by obstschale** [CalderaWP/Caldera-Forms#760]
I updated to 1.4.1 and the following Warning is shown. I use a custom build function to retrieve content from Caldera Forms and display it on a public site. On this page, the error is shown.

```
Warning: Invalid argument supplied for foreach() in /path/wordpress/wp-content/plugins/caldera-forms/classes/entry/entries.php on line 138
```

I had to downgrade to 1.3.x to get rid of this Warning.

**Comment by Shelob9** [comment]
Probably related: #758

**Comment by Shelob9** [comment]
@obstschale Can you please share the code you are using that led to this warning? That would really help me figure out what is causing it.

**Comment by obstschale** [comment]
I have a class `Caldera_Forms`, which registers a new shortcode `flats_shortcode()` and calls `get_entries()` to fetch caldera form entries.

https://gist.github.com/obstschale/482330ada800287e28d0d687b4ad4517

**Comment by Shelob9** [comment]
close via 	1780d74
