### ISSUE TITLE
Add option in general settings to turn off tracking

### ISSUE THREAD

**Issue by ribice** [CalderaWP/Caldera-Forms#781]
Hi,

Missclicked and enabled tracking on installation. Can't find a way to disable it.

Uninstalled and installed plugin, but got no request for tracking. I assume it's somewhere in database. Is there an option to disable tracking, or it has to be done manually in DB?

Thanks!

**Comment by Shelob9** [comment]
@Ribice We should add a UI option for this.

You can just change the value of the _caldera_forms_tracking_allowed option to 0 to disable it.
