### ISSUE TITLE
Renaming toogle - keeps old name in conditional logic page?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#786]
I am translating our film clubs reserve a ticket form from Norwegian to English. 
But as I changed the name of the toogle terms in the layout screen it still shows the old name. See screenshot right column.

![screen shot 2016-08-29 at 11 39 20](https://cloud.githubusercontent.com/assets/5323259/18047586/ef1c9a30-6ddd-11e6-96cc-1de75bdd0145.png)

Btw
How would I go about using two identical forms in two languages? I will have to explore this and see what I come up with.

**Comment by Shelob9** [comment]
@paaljoachim We don't have a good translation system yet. It's a project I am working on. You can use the "caldera_forms_render_get_field" filter to change the field label and description based on current language.
https://calderawp.com/doc/caldera_forms_render_get_field/

**Comment by paaljoachim** [comment]
Thanks Josh! I will look into it.
