### ISSUE TITLE
Caldera Contact Standard Form Will not work with WP 4.6 - Will work with 4.5.3

### ISSUE THREAD

**Issue by RonDee** [CalderaWP/Caldera-Forms#787]
I have installed Caldera Standard Contact Form on WP 4.6 - Could not get it to work sending our the contact information - CALL my Provider, Bluehost, they said this new version WP 4.6 was having issues using contact forms - they placed me on 4.5.3 and it is working. However, a reply back goes to another bluehost box that can't be replied to - Could I change to that address in the Admin area of email and it would be able to reply?

Really like this Contact Form - I can add Header Custom name and also customize the form too!
Get a +A for this Form!

**Comment by Shelob9** [comment]
@RonDee Thanks for using Caldera Forms. This is not the right place to open a support ticket. Please use https://CalderaWP.com/support
