### ISSUE TITLE
"Show in entry" list stop working

### ISSUE THREAD

**Issue by SBenoit5** [CalderaWP/Caldera-Forms#791]
The option "show in entry list" stop working, and when you want to use the "conditions" tool, the "Applied Fields" list contains all the elements of the form.

**Comment by Shelob9** [comment]
@SBenoit5 Can you please clarify your concern? The "show in entry list" option is for changing which fields apear in the list table view of the entry viewer, it is not related to the conditional logic system.

**Comment by SBenoit5** [comment]
Ouch! My mistake. Really sorry. Definitely I misunderstood the function of this option.
