### ISSUE TITLE
Magic tag button doesn't work in Chrome #FML

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#794]
In Chrome, the magic tag button does not open the magic tag list.

This is an issue with 1.4.1, IE recent changes for #777 are probably not to blame.

This has been confirmed to happen in Chrome for Mac and Ubuntu. DOES NOT happen in Firefox, Chromium or Safari.

**Comment by JiveDig** [comment]
I'm seeing this issue as well. Tested on these versions:
Mac/Chrome Version 52.0.2743.116 (64-bit)
Mac/Chrome Version 53.0.2785.89 (64-bit)

**Comment by Shelob9** [comment]
Issue is most likely somewhere in here:
https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/edit.js#L982-L1186

**Comment by Shelob9** [comment]
This works in 1.4.0, but not 1.4.1 or 1.4.2

**Comment by Shelob9** [comment]
41645d4 makes it so the magic tag button isn't needed, the autocomplete just works on focus in. Not 100% sold on this, but I think it's good. I might back out of this. Or I might remove the button, which still doesn't work (sigh...)...

**Comment by Shelob9** [comment]
So happy to close via 	1cfd0d8 :) That button is over.

https://www.youtube.com/watch?v=YlGqN3AKOsA
