### ISSUE TITLE
Cloning forms 404's admin-ajax.php

### ISSUE THREAD

**Issue by JiveDig** [CalderaWP/Caldera-Forms#798]
Same on Chrome and Safari (Mac)

<img width="1319" alt="image 2016-09-01 at 1 54 05 pm" src="https://cloud.githubusercontent.com/assets/540990/18178346/fd036de8-704b-11e6-8e7d-a53096ea5027.png">

**Comment by Shelob9** [comment]
It's missing the nonce.

**Comment by Shelob9** [comment]
clsoe via 	318a533
