### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by Leon1974** [CalderaWP/Caldera-Forms#80]
Hi, I find a issue in phone number. The custom option egs. (99999)999-9999 does not work.  It only shows the local than. Now I use a text field. It works as well. I guess someone notice it before...  But I also want to say thank you for that amazing plugin. I work with smart forms before and I pay for it.  But it has many bugs and problems with sending mails to our webserver.  After I install caldera forms I was surprized that is is so fantastic.  Thanks

**Comment by Desertsnowman** [comment]
Thanks. I'm glad you like it.
the phone number is interesting since there are many formats. I chose the two basic and used the text field to have custom masking.

**Comment by Shelob9** [comment]
Closing out this old issue as I'm updating masking and phone fields via #1118
