### ISSUE TITLE
No reaction clicking Magic Tags in Chrome

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#809]
I am working on a .dev offline site.
Filling out the Email area. 
I notice the magic tag icon </> to the right of many of the fields.
Clicking it does nothing. I would expect a pop up/drop down of available magic tags to show up.

Ahhh it is a Chrome thing. Sigh. It looks nice in Firefox so I will have to take the code from there.

**Comment by Shelob9** [comment]
This is a duplicate of #794
