### ISSUE TITLE
Hiding Label in checkbox also hides Required red star

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#813]
The goal is to create a checkbox the user needs to click to accept that they have read the terms.

Label: I have read the terms.
Option: I have read the terms.

![screen shot 2016-09-10 at 21 20 55](https://cloud.githubusercontent.com/assets/5323259/18412983/7d0fcc8c-779c-11e6-92ee-318cc91aae1c.png)

To me it looks nice having the terms text beside the checkbox.
So I hide the label and leave the text in the option with the result that the required red star disappears.

Label: hidden and so is the required red star.
Option: I have read the terms

![screen shot 2016-09-10 at 21 23 24](https://cloud.githubusercontent.com/assets/5323259/18412998/d6d8febe-779c-11e6-8a18-8393585083cc.png)

If I was going to use the label and not the option the result would be that the checkbox disappears.

Label: I have read the terms
Option: Removed.

![screen shot 2016-09-10 at 21 26 08](https://cloud.githubusercontent.com/assets/5323259/18413016/39f9639e-779d-11e6-8787-2a9934dba32e.png)

To keep the checkbox I need to keep the option.

Label: I have read the terms
Option: blank - Just not filled in. Default greyed out text here is label.

![screen shot 2016-09-10 at 21 34 23](https://cloud.githubusercontent.com/assets/5323259/18413063/623645c4-779e-11e6-9b6e-08be13096b21.png)

So this means I will need to perhaps just use the option and then hide the label. Or have to add some additional text. Such as

![screen shot 2016-09-10 at 21 28 03](https://cloud.githubusercontent.com/assets/5323259/18413031/7ac16e9e-779d-11e6-92d7-eca2784e5da1.png)

Here is a html color and bold hack:
![screen shot 2016-09-10 at 21 41 45](https://cloud.githubusercontent.com/assets/5323259/18413106/683de50c-779f-11e6-93f8-805300ca4a61.png)

In the option I added: 
`<b>I have read the terms <font color="red">*</font></b>`

Hmm did I just make a mini tutorial.....

**Comment by Shelob9** [comment]
@paaljoachim This isn't practical as the * is removed with the rest of the field.

I think this is good fodder for a tutorial you should write, but not an edge case I'd like to add an option and new complexity over.
