### ISSUE TITLE
Adjusting the default green background on Success Message

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#814]
Hey

It would be nice to just remove the light background green and the thin green border around the Success Message.

My suggestion would be to change the default CSS to (or just remove background color and border color):
```
.caldera-grid .alert-success {
    background-color: #fff;
    border-color: #fff;
    color: #000000;
    font-size: 14px;
}
```

The result (I have added a bunch of p tags and a few b tags to give more space and some boldness to the text):
![screen shot 2016-09-10 at 21 51 24](https://cloud.githubusercontent.com/assets/5323259/18413183/c19a0ab2-77a0-11e6-8af3-fd4a4f6f6a65.png)

The original:
![screen shot 2016-09-10 at 21 54 40](https://cloud.githubusercontent.com/assets/5323259/18413201/332299ce-77a1-11e6-8ded-eee4d37f10b5.png)

The green is too narrow in scope. Having a standard black text on a white background is a lot more practical.

**Comment by Shelob9** [comment]
@paaljoachim I disagree. Green is a pretty universal success. It can be easily changed in child theme.

Also, and the real reason I'm closing is that we can't make a change like this to people's sites, they expect it to be green, we'd be affecting existing users. Even if it was a bad decision, it was the decision and now its what is expected.

**Comment by paaljoachim** [comment]
Gotcha. It is easy enough to use CSS to adjust from green to white etc.
