### ISSUE TITLE
Submitting form -> jump page to top of form?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#817]
We have a very long form and the page has three columns:
http://cpanel56.proisp.no/~celiayjo/bestilling/  (This is a test page.)

Submitting the form. The form goes away and the success message is not seen because it is further up on the page. It would be good to have an auto jump to top of screen or top of form when form is submitted.

**Comment by Shelob9** [comment]
Close via 	bdf3c69
