### ISSUE TITLE
How to do about showing option label and not value in a summery.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#818]
Hey

The user selects through drop down options how many boxes to purchase.

![screen shot 2016-09-14 at 09 53 18](https://cloud.githubusercontent.com/assets/5323259/18504146/1b2f73ba-7a61-11e6-9b5c-fba49893d9e3.png)

Value - Label
0 - 0 boxes
1400 - 20 boxes
2800 - 40 boxes
etc

The summery shows the value in Norwegian Kr. How would I go about showing the label instead?

The summery will list:
Amount of boxes
1400

Where I want the summery to list:
Amount of boxes
20

**Comment by Shelob9** [comment]
This is documented here: https://calderawp.com/doc/using-magic-tags-caldera-forms/

**Comment by paaljoachim** [comment]
Thank you Josh!

**Comment by paaljoachim** [comment]
Since I can not use Summery because I have to show the slug:label of boxes.
I will have to insert every field individually.
What is the easiest way to insert a magic tag for each field?
