### ISSUE TITLE
update processor removed on form  submission 

### ISSUE THREAD

**Issue by kibarda** [CalderaWP/Caldera-Forms#819]
Hi there! 
I've got a custom processor used to update some data. 
Update does not work, the processor is not run. 
It appears that the processor is removed from the form['processors']  in process_submission()  
with this test: 

```
            if( !empty( $transdata['edit'] ) && empty( $processor['runtimes']['update'] ) ){
                // is editing and is set to not allow it so remove processor
                unset( $form['processors'][ $processor_id ] );
                continue;
            }

```

$transdata['edit']   is set to the entry_id    I am updating. 
$processor['runtimes']['update']   is not set. ( it appears the code to set this ['runtimes']['update'] has been commented in ui/panels/processors.php months ago)
Feels like a bug .. or did I miss something ...? 
Best,

**Comment by Shelob9** [comment]
@kibarda Sorry, I'm not sure I follow what you mean.

`ui/panels/processors.php` is only used in admin, not in processing.

We have changed processor loading in 1.3.0 -- moving it into the `Caldera_Forms_Processor_Load` class, but that should have been backwords compatible, since it is still using the `caldera_forms_get_form_processors` hook.

**Comment by kibarda** [comment]
Hi, 

(I probably misunderstood something... )

I am indeed using caldera_forms_get_form_processors . 
My processor is removed in the submission process ( process_submission()) with the code here above ('Remove processors that are not allowed to run on this pass' ) 

I was expecting a mechanism within the UI to allow my processor to do 'update'. 

In the UI, there is a button to enable/disable processors but I have not found something related specifically to update authorization. And my processor is indeed removed from the processors in process_submission ( because of: empty( $processor['runtimes']['update']  ).  On the other hand my processor has ['runtimes']['insert'].  

I haven't been in the code history details but it seems something related to 'update' auth ( 'Run processor on Update'  ) was replaced months ago in ui/panels/processors.php  by this disable/enable processor button. 

Does it clarify my question ? Thanks !

**Comment by kibarda** [comment]
@Shelob9 Hi, do you need more information? does it clarify my issue ? Best regards, thanks !
