### ISSUE TITLE
global $post and ICL_LANGUAGE_CODE returning wrong values within caldera_forms_render_get_field

### ISSUE THREAD

**Issue by mdorchain** [CalderaWP/Caldera-Forms#820]
Hi,

I'm trying to translate manually the field before the display.
However I noticed that ICL_LANGUAGE_CODE remains unchanged within the filter caldera_forms_render_get_field.
So I tried to check the current post_id, and it seems that the current $post returned is not correct.

Is there any reason for that ?

Thanks

Michael

**Comment by mdorchain** [comment]
It seems to only happen with the modal and not the regular shortcode.

**Comment by Shelob9** [comment]
@mdorchain The modal is not actually loaded in a context that the global $post variable would be set.

**Comment by Shelob9** [comment]
@mdorchain If you need help integrating with WPML, please open a support ticket at https://CalderaWP.com/support
