### ISSUE TITLE
wpColorPicker wrecks TinyMCE only on Editor role

### ISSUE THREAD

**Issue by mathetos** [CalderaWP/Caldera-Forms#824]
We couldn't replicate this locally, but it was happening live on our givewp site.

@devinwalker dug into it and it looks like the shortcode js needed to call wpColorPicker as a dependency.

Here's his fix:
```
if ( $screen->base === 'post' ) {
			wp_enqueue_style( 'wp-color-picker' );
			wp_enqueue_script( 'wp-color-picker' );
			wp_enqueue_style( $this->plugin_slug . '-modal-styles', CFCORE_URL . 'assets/css/modals.css', array(), self::VERSION );
			wp_enqueue_script( $this->plugin_slug . '-shortcode-insert', CFCORE_URL . 'assets/js/shortcode-insert.min.js', array( 'jquery', 'wp-color-picker' ), self::VERSION );		
}
```

**Comment by mathetos** [comment]
The tricky part of this is that it's definitely related to user roles or capabilities. It's on our GiveWP site, so could be related to EDD capabilities.

**Comment by Shelob9** [comment]
Hey @mathetos I couldn't reproduce this. But I put the fix in anyway because I can see how it might be a problem. Can you please test 1.4.x branch to see if it fixes your issue?

**Comment by Shelob9** [comment]
Close via 	9da03eb and 	b5ab22d
