### ISSUE TITLE
Connected Caldera Forms

### ISSUE THREAD

**Issue by julianareed** [CalderaWP/Caldera-Forms#829]
We have downloaded Connected Caldera Forms plug-in and it is not working. It opens a white page and it is not possible to create the forms. We have updated WordPress and the plugin is still not working. We use Caldera Forms already and it works very well, but Connected Caldera Forms is not working. Thanks.

![connected_caldera](https://cloud.githubusercontent.com/assets/22396874/18789878/09279bec-8183-11e6-8a56-f01af37bf2d6.png)

**Comment by Shelob9** [comment]
Do you have any other forms? If not, this is correct. You must create other forms first.

If you have created other forms then this is likely caused by an error on your site. I'd be happy to help you work through those issues via our support system. Please open a ticket at CalderaWP.com/support
