### ISSUE TITLE
Verification doesn’t work if link is clicked from a different browser/client

### ISSUE THREAD

**Issue by skipthedrive** [CalderaWP/Caldera-Forms#830]
This is pertaining to the **Verify Email for Caldera Forms** plugin.

There seems to be a bug with the validation link. If I fill out the form in google chrome and click the validation link in firefox (or vice versa), the validation link takes me to a blank page and the form entries do not update with the new email address.

**Comment by dax702** [comment]
I echo this bug. Except for me, I get a blank page regardless of same or different browser =(

**Comment by dax702** [comment]
Been 24 days and no update on this. When I click the verify link in the email, I'm taken to a plain white browser window with nothing in it and the entry doesn't get recorded.  ? ?

**Comment by TheAccountingStudio** [comment]
I too am having the same issue. Has there been any progress on this? I get a blank screen when going cross browser. I've looked at the code but its beyond my capabilities

**Comment by Shelob9** [comment]
This is fixed in the next update for Verify email, fix will require Caldera Forms 1.5.0, no way to get around this in 1.4.x without gutting nonce validation
