### ISSUE TITLE
file header isn't responsive in purchase email

### ISSUE THREAD

**Issue by thisismyurl** [CalderaWP/Caldera-Forms#846]
![screen shot 2016-10-01 at 12 46 55 pm](https://cloud.githubusercontent.com/assets/577207/19015575/2c76a45a-87d5-11e6-9200-3d7505cbb6d5.png)

**Comment by Shelob9** [comment]
Shit, that's huge. I just changed it to one that is the same width as the table. Points awarded to @thisismyurl
