### ISSUE TITLE
mailchimp api key

### ISSUE THREAD

**Issue by thisismyurl** [CalderaWP/Caldera-Forms#852]
each form requires me to resubmit the Mailchimp API key, instead of using it as a global variable

![screen shot 2016-10-01 at 3 46 35 pm](https://cloud.githubusercontent.com/assets/577207/19016636/5c6fbdd6-87ee-11e6-99b8-a5756120ddd0.png)

**Comment by Shelob9** [comment]
Yes, that's annoying and will be fixed in 1.5 via #329
