### ISSUE TITLE
escape slashes for text output

### ISSUE THREAD

**Issue by skipthedrive** [CalderaWP/Caldera-Forms#862]
Hello -

I'm outputting some text within a form by using **{get:search}**. The problem is, double quotes are not being escaped when displaying the text. For example, if in my URL there's a querystring such as **search="test"**, the form label will show **\"test\"**. I tried urlencoding the search variable so that the value would be **%22test%22**, but the URL immediately changes (rewrites?) it to be **"test"**.

**Comment by Shelob9** [comment]
Thought a lot about this, but supporting double quotes from GET vars is not going to be possible without introducing security issues.
