### ISSUE TITLE
Multiple reply to address not working

### ISSUE THREAD

**Issue by CimbaloMecoil** [CalderaWP/Caldera-Forms#865]
Sending an email notification to multiple address separated by comma fail without any warning.

I solved the issue removing single guillemet from[ **classes/save.php** line 216
](https://github.com/CalderaWP/Caldera-Forms/blob/bcf3350433a8513f1c5091b0fbf1a8d15263a49c/classes/save.php#L216)

Is there any better solution?

**Comment by Shelob9** [comment]
@CimbaloMecoil 
How are you setting up the email notification for multiple addresses? It should work with a comma separated list in the recipients field. I'm not sure what the reply-to value has to do with this, that's only supposed to have one email address in it.

**Comment by CimbaloMecoil** [comment]
@Shelob9 
The first line of my issue is incorrect, it should say:
Sending an email notification with multiple reply-to address separated by comma fail without any warning.

In [RCF5322](https://tools.ietf.org/html/rfc5322#section-3.6.2) reply-to field is defined as:

> reply-to        =       "Reply-To:" **address-list** CRLF

The current implementation of the reply-to field make impossible to set multiple address such as "FOO \<foo@example.com>, BAR \<bar@example.com>"

**Comment by Shelob9** [comment]
@CimbaloMecoil Thanks. I understand now.

I think this issue should be retitled: "Prevent adding more than one email to reply-to field in email notification." But I think you want that to be supported, which we should be able to do. Right?

I'd like to keep the `<` and `>` in if we do though.

**Comment by CimbaloMecoil** [comment]
Yes, I would like this feature supported.
If you think it is a good idea I can submit a pull request using bcc field code as model.

**Comment by CimbaloMecoil** [comment]
@Shelob9 
A pull request, using bcc field code as model, can speed up the process to support this feature?

**Comment by Shelob9** [comment]
@CimbaloMecoil Yes, a pull request against the 1.5.x branch would be appreciated.

**Comment by CimbaloMecoil** [comment]
@Shelob9 
I think Travis ci is broken for CalderaWP:1.5.x branch.
Let me know if any modification is needed to the pull request #892

**Comment by Shelob9** [comment]
Close via #892
