### ISSUE TITLE
All conditional logic deleted

### ISSUE THREAD

**Issue by logicalfantasy** [CalderaWP/Caldera-Forms#866]
Setup a complex 5 page form with a lot of conditional logic. Added a sixth page, only change being adding a "submit" button and a summary. Saved, and all conditional logic was completely wiped.

**Comment by Shelob9** [comment]
Sorry about that.

To help me better understand this issue, can you please tell me the
following:

1) What version of Caldera Forms are you using?
2) Are you seeing any errors in your JavaScript console?
3) Is this a one time thing  or a persistent issue?

**Comment by logicalfantasy** [comment]
1 - Caldera Forms 1.4.2
2 - No errors
3 - This is the first form of this scope I've made in Caldera Forms, however previous, simpler forms were unaffected.

I should also mention that this was a completely clean (and up to date) install of Wordpress - the form was the first thing I worked on.

**Comment by Shelob9** [comment]
@logicalfantasy  Thanks for the followup. Can you please try it again with the current version of Caldera Forms 1.4.3.1 and see if you can get this to happen again or not?

**Comment by logicalfantasy** [comment]
I did so today. I used the same form, as all conditions had been wiped but roughly 100 fields with options/notes/values/slugs etc remained. I rebuilt all logic today and tested the form - and it works as intended. I have backed up the form.

The only change I did not replicate from the last time is the very last, just before the issue occurred - creating a html field, with {summary} listed.
