### ISSUE TITLE
glitchy entry

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#878]
As I adjusted a few of the fields and went to the entries I noticed this:

![screen shot 2016-10-12 at 14 15 04](https://cloud.githubusercontent.com/assets/5323259/19322290/6a0b401e-9086-11e6-99d5-71350fd19bd5.png)

I had something similar in another field, and made some adjustments to the form and then the weirdness moved to another field entry.

**Comment by Shelob9** [comment]
@paaljoachim This should have been fixed in 1.4.4 Can you please confirm and if so close?

**Comment by paaljoachim** [comment]
I believe it is ok now. I will close it and if for whatever reason it shows up again I will comment on it.
