### ISSUE TITLE
Range sliders are being wonky?

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#881]
from .org support form -- https://wordpress.org/support/topic/range-slider-not-working-2/

Is there any known problem with the range sliders? I can’t seem to get them to work.

I get those errors:

SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:648:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:662:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:727:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:741:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:763:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:894:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:908:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:977:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:991:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:1082:44
SyntaxError: expected expression, got ‘<‘[En savoir plus]simulation-personnalisee:1096:44

When I check those lines, the code here is the same:

window.addEventListener(“load”, function(){</p>

**Comment by Shelob9** [comment]
Maybe related #545 
Totally related: #259 #826

**Comment by Shelob9** [comment]
Actually this is the theme's fault, they are filtering the_content wrong and adding HTML to our inline JavaScript. Also, it works fine for me with default theme.
