### ISSUE TITLE
Connected Forms Not Advancing

### ISSUE THREAD

**Issue by RandyKing** [CalderaWP/Caldera-Forms#884]
# **Forms 1.4.3.1 with Connected 1.0.5 on WP 4.6.1**

Connected forms built with no conditionals - just created the "out" node and attached it to the next form.  There are 4 total forms, each "out" has "BACK" enabled.  It was working - sort-of - now it won't even advance to the next form.

Test URL:  http://www.madisonreiacoaching.com/coaching-application/

**Comment by Shelob9** [comment]
@randyking I am closing this as it's not a issue in the core plugin. Please open a support ticket at https://CalderaWP.com/support and I'll be happy to help figure out what on your site is preventing this is from working properly.
