### ISSUE TITLE
1 CSS class to change all button colors?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#887]
My client wants all the buttons to contain the same background color. It would be nice with 1 CSS class to make changes to all the buttons.

**Comment by Shelob9** [comment]
@paaljoachim Use `.caldera-grid .btn` See the documentation for more information: https://calderawp.com/doc/button/

**Comment by paaljoachim** [comment]
Thanks Josh!

This is what I end up doing:

/* -- colors for send button --*/
.caldera-grid button, .caldera-grid html input[type=button], .caldera-grid input[type=reset], .caldera-grid input[type=submit] {
    background: #79a9b0 !important;
    color: #fff !important;   
}

/* -- colors for toogle button - When selected it shows a blue color. */
.btn-success {
     background: #79a9b0 !important;
}
