### ISSUE TITLE
Emailed CSV checkboxes contain JSON with internal db option name

### ISSUE THREAD

**Issue by qubez** [CalderaWP/Caldera-Forms#888]
I'm trying to get usable data emailed in a CSV and have encountered some challenges. The emailed CSV is quite different from the UI-exported CSV file, and has unexpected, undocumented data.

The biggest problem is with checkboxes - the CSV file attached to email contains JSON-like data with the internal database name for the option, which is not only useless to the recipient, it cannot be parsed by any spreadsheet or other program that would import normal CSV data.

Example form:
![caldera-test-screenshot1](https://cloud.githubusercontent.com/assets/1425520/19420184/0c0acecc-939b-11e6-89db-4f7e2d2ed3cb.png)

For the field "Multiple Item Checkbox" we get these very different data:

_exported:_
"Option 2, Option 3"

_emailed:_
"{""opt1721046"":""Option 2"",""opt1137830"":""Option 3""}"

Note the multiple-non-JSON quotes that break import of the field also.

Other things are inconsistent:
- emailed CSV fields are by the order they were added, not the form order, and there is no way to re-sort,
- emailed CSV completely omits both header and field of unchecked checkboxes and unfilled fields
- emailed CSV does not include auto-generated "Submitted" field with date,

Wordpress 4.6.1
PHP version 5.4.43 (same issue with 5.6)
Caldera forms version 1.4.3.1

Example output of this demo form attached.

[checktest-test3-export.csv.txt](https://github.com/CalderaWP/Caldera-Forms/files/532060/checktest-test3-export.csv.txt)
[checktest-test3-emailed.csv.txt](https://github.com/CalderaWP/Caldera-Forms/files/532061/checktest-test3-emailed.csv.txt)

...Then a feature. Tab-delimited CSV is required for apps like Acrobat forms. A per-form UI option to email (or export) CSV with tab delimiters would solve my hack of editing save.php file, adding fputcsv tab delimiters at line 332,333.

**Comment by Shelob9** [comment]
@qubez Thanks for reporting this. Are you using the `{summary}`summary magic tag?

I suspect when I redid the formatting for the `{summary}` tag in 1.4.0, I removed whatever was decoding this. If that's the case, it's an easy fix.

**Comment by qubez** [comment]
I am also using summary, but I just changed the body to "hello" for the test form and the CSV is the same.

**Comment by Shelob9** [comment]
@qubez Can you email me an export of the form that is having this issue please (Josh@CalderaWP.com) I've been testing and can't seem to reproduce this.

**Comment by qubez** [comment]
I made this demo form for the bug report, and it duplicated the issue found in other forms exactly, so it seems like it should be reproducible. Likely not a bug with the form but the way emailed CSVs are created. Attached is the export of the above screenshotted form.

[checktest-export.json.txt](https://github.com/CalderaWP/Caldera-Forms/files/545284/checktest-export.json.txt)

**Comment by Shelob9** [comment]
@qubez  Thanks for the example form, that helped.

Close via 	bbd4f03
