### ISSUE TITLE
Using SendGrid option doesn't work

### ISSUE THREAD

**Issue by dax702** [CalderaWP/Caldera-Forms#890]
I'm using SendGrid in general on my site and it works fine, however it doesn't work with Caldera Forms. I even tried creating a new API key instead of using my existing one. Entries are being recorded, but no emails are sending.

**Comment by Shelob9** [comment]
@dax702 I'm going to look into this bug for 1.4.4, but if you're using the SendGrid plugin for your site, that will cover Caldera Forms emails as well. You would only use both if you wanted to use separate keys or needed different reporting for Caldera Forms.

**Comment by dax702** [comment]
Ahh right you are. When I changed the method back to Wordpress, the mails were sent, and they were sent via SendGrid. Although, when I tried the different new API key, it still didn't work when used alongside the SendGrid plugin, so that part of it you may still want to investigate.

**Comment by Shelob9** [comment]
@dax702 OK good. I'm going to look into it, just wanted to point out a quick fix for you.

**Comment by Shelob9** [comment]
I'm unable to reproduce this. I wonder if original issue was @dax702  was using our SendGrid system and the SendGrid plugin. That's not recommended.
