### ISSUE TITLE
Hiding field by clicking eye icon?

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#899]
Hey

I decided on creating this issue instead of adding it to the below issues.

Here is a possible wireframe:
![hide-field](https://cloud.githubusercontent.com/assets/5323259/19687581/3f1b9fc6-9ac6-11e6-9c39-373bf41efb53.jpg)

Associated issues:
https://github.com/CalderaWP/Caldera-Forms/issues/351
and
https://github.com/CalderaWP/Caldera-Forms/issues/402

**Comment by Shelob9** [comment]
@paaljoachim  This is a duplicate of those issue. Can you please post that mockup, which I like on #402
