### ISSUE TITLE
Limit file size upload

### ISSUE THREAD

**Issue by rhcarlos** [CalderaWP/Caldera-Forms#900]
Hello, can i limit upload size of form?
Because i don't want to use my limit size of wordpress (64mb), so i need limit the file field to only 5mb

can i do it with caldera forms?

Thanks!

**Comment by Shelob9** [comment]
You can use the upload_size_limit filter for this. Add it conditionally if Caldera Forms is submitting. Check for the WordPress query var `cf_api`

https://developer.wordpress.org/reference/hooks/upload_size_limit/

If you need help implementing this, please open a support ticket at https://CalderaWP.com/support
