### ISSUE TITLE
Checkbox / Radio - Show results in newline instead of comma separated

### ISSUE THREAD

**Issue by slavamartin** [CalderaWP/Caldera-Forms#903]
Hi there.

I would like to thank you guys for building Caldera Forms (Total Awesomeness)!

Not really a bug, but can be a pain when creating price list. what do I need to change and where in order to be able to output checkbox / radio output in the email one per line rather than comma separated.

Would really appreciate a solution. I've searching the net for two days now, but no luck.

Tried this - /plugins/caldera-forms/includes/field_processors.php - add_filter('caldera_forms_view_field_checkbox'
Changing this
`return implode( ', ', $viewer );`
to this
`return implode( “\r\n”', $viewer );`

but nothing.

I would really appreciate solution to this.

Regards
Slava

**Comment by slavamartin** [comment]
Awesome!!! 14 days no reply. I definitely WON'T pay for support in the future.

Even "We don't know" would of been an acceptable answer.

Very disappointing.

**Comment by Shelob9** [comment]
@slavamartin I'm sorry your frustrated, but this isn't a support channel, it is an issue tracker. We offer 1 business day turn around for support requests at https://CalderaWP.com/support

I would recommend using the caldera_forms_mailer filter for customizing the output of the email message.  https://calderawp.com/doc/caldera_forms_mailer/
