### ISSUE TITLE
specify whether the decimal place is marked by a comma or a period and whether the thousands place is marked by a comma or a period

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#910]
Reported on WordPress.org: https://wordpress.org/support/topic/calculation-field-format/

I imagine it makes the most sense to just have a format option that includes
0.000,00
and
0,000.00

no one does 0.000.00, that would make brains hurt.

**Comment by albershans** [comment]
I agree. I think thousands separator and decimal separator are never the same, always either's opposite.

Regards, Hans

**Comment by Shelob9** [comment]
Related: #441

**Comment by Shelob9** [comment]
Decimal and thousands separators are now two different controls via ebba56c
