### ISSUE TITLE
Save a session variable in a text field

### ISSUE THREAD

**Issue by TheGreenArrow** [CalderaWP/Caldera-Forms#918]
We can save a GET, POST and REQUEST variable in an input value.
How can i do the same for a session variable ?
I found this solution : https://calderawp.com/doc/caldera_forms_submit_post_process/ but i don't know how to add this code : 

> add_action( 'caldera_forms_submit_post_process', function( $form, $referrer, $process_id, $entry_id  ){
>    //Save field data from a SESSION var if it is set
>    if( isset( $_SESSION, $_SESSION[ 'foo' ] ) ){
>       //make sure to update the field ID
>       Caldera_Forms::set_field_data( 'fld1234567', $_SESSION[ 'foo' ], $form, $entry_id );
>    }
> 
> }, 10, 4 );

**Comment by Shelob9** [comment]
You should create a seperate plugin for this code or add it your (child) theme's functions.php

If you need help getting this working please open a support request at https://CalderaWP.com/support

**Comment by TheGreenArrow** [comment]
I added this code to my functions.php
```
add_action( 'caldera_forms_submit_post_process', function( $form, $referrer, $process_id, $entry_id ){
//Save field data from a SESSION var if it is set
    if( isset( $_SESSION, $_SESSION['Email'] ) ){
//make sure to update the field ID
        Caldera_Forms::set_field_data( 'fld_7683514', $_SESSION['Email'], $form, $entry_id );
    } 
// added by me, just to check
else { Caldera_Forms::set_field_data( 'fld_7683514', "empty", $form, $entry_id ); }

}, 10, 4 );
```

but it show the "empty" value. 
I verified that $_SESSION['Email'] exist.
