### ISSUE TITLE
Increment Processor Should add value passed to hidden field it is mapped to if  value isset && is_numeric()

### ISSUE THREAD

**Issue by mathetos** [CalderaWP/Caldera-Forms#927]
The way the UI is setup for the Increment Processor, it looks like I should be able to set the value of the increment with values of a field. 

I believe I set everything up correctly, and I think I see why in the code of the Increment Processor it does NOT increment correctly. So first, how I've set it up (in case I missed a step):

## My Setup
1. I made sure the “Number of People” has values that are Numbers, not words
2. I set the value of the hidden field to be the Number of People value, like so:

![image](https://cloud.githubusercontent.com/assets/930724/20234123/39e4735c-a82c-11e6-934c-9f37470f05a0.png)

That works in the form exactly as it should, as seen here:
![image](https://cloud.githubusercontent.com/assets/930724/20234129/55c68380-a82c-11e6-8765-bec925a30e8b.png)

3. I set the Increment Processor like so:
![image](https://cloud.githubusercontent.com/assets/930724/20234130/6151458c-a82c-11e6-9960-ad6b3f756cb4.png)

The only option I found in the database that referenced this at all is:
`$gettotal = get_option('_increment_fp_44172309');`

4. When I output that via a shortcode, it increments -- but always ONLY by 1, not per the value of the toggle. 

## The Problem in the Code

I expected it to increment based on the value populated from the "Increment Field" But by looking at the `increment_value` function, it does't look like it references that value at all.

https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L1021-L1034

Specifically line 1026:
`update_option( '_increment_' . $config['processor_id'], $increment_value + 1 );`

That +1 at the end should be the dynamic value populated from the "Increment Field" field. I experimented by setting the +1 to +2 and it incremented by 2 instead of 1 correctly.

**Comment by Shelob9** [comment]
This is a UI issue. I see why you would think it would work that way. But
that's not how it works. The value of the field is not taken into account
by design.

Based on what you told me on Facebook. I can say what you're trying to do
isn't doable from the UI. I would filter the value at pre_update_option.
I'll sned you code for it tomorrow.

**Comment by Shelob9** [comment]
Close via 	f225e12 #himatt
