### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by omniacode** [CalderaWP/Caldera-Forms#931]
Getting this error after last update to Caldera Forms (1.4.4.1)

Warning: array_merge(): Argument #2 is not an array in /home/xxxx/www/www/wp-content/plugins/caldera-forms/classes/admin.php on line 1850

Form still works but wanted to bring it to your attention. Thanks.

**Comment by Shelob9** [comment]
Close via 	7146043
