### ISSUE TITLE
Default WP email is used when using caldera_forms_mailer filter.

### ISSUE THREAD

**Issue by adamx12m** [CalderaWP/Caldera-Forms#932]
Using calera_forms 1.4.4 and the caldera_forms_mailer to control recipient list based upon a form value, the default WP email is being set in the array by default.  Any recipient values added after are just appended.  Added the unset to the $mail['recipient'] array as the fix.  Not really a big problem but the docs https://calderawp.com/doc/caldera_forms_mailer/ should reflect this behavior.  Sending emails via postman_smtp plugin but shouldn't matter.

add_filter( 'caldera_forms_mailer', function( $mail, $data, $form ) {
	//MAKE SURE TO CHANGE FORM ID
	if( 'CF57068f9700961' == $form[ 'ID' ] ) {

		unset($mail[ 'recipients' ][0]);  // remove default admin user email id

		$state =  $data[ 'fld_6524634' ];
		switch ($state) {
		case "Oklahoma":
		 $mail[ 'recipients' ][] = 'blahblah@blah.com';
		break;
		default:
		 $mail[ 'recipients' ][] = 'blahmaster@blah.com';
		}
	}
	return $mail;
}, 10, 3 );

**Comment by Shelob9** [comment]
@adamx12m  If you don't set a valid email in the email notification settings, Caldera Forms resets it to admin email.  That is before this filter runs. I will mention that in the docs.
