### ISSUE TITLE
Color contrast for get shortcode link in main form list is insufficent

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#933]

**Comment by paaljoachim** [comment]
I agree.
While you are at it... What about making the title of the form go to the edit/layout page?

Btw
I really think we need to brainstorm how to make the Forms screen pretty. There is only a little square to the left with all this empty space around it.

Here are green shortcodes and I have snuck in a visited column...:) I will work more on the Forms screen as we got to make it pretty. It is the initial view users get of CF.

![cf-forms-screen](https://cloud.githubusercontent.com/assets/5323259/20600852/ea663fc0-b255-11e6-9dda-ee9b404bba86.jpg)

**Comment by Shelob9** [comment]
Close via 		fdc721e

**Comment by paaljoachim** [comment]
Ugh what happened here....

![screen shot 2016-12-01 at 17 55 56](https://cloud.githubusercontent.com/assets/5323259/20803422/76ab87b2-b7ef-11e6-8a91-7436e3757cab.png)

The shortcode is taking over the box.
The most important is actually the title not the shortcode....
 
![screen shot 2016-12-01 at 17 57 12](https://cloud.githubusercontent.com/assets/5323259/20803462/a0d3af88-b7ef-11e6-99f2-f5d11a868ef3.png)

Got to find something to say something nice about....
The Caldera logo looks nice....
