### ISSUE TITLE
toggle switch not working + conditional groups only 1 field work 

### ISSUE THREAD

**Issue by gilbert-mjp** [CalderaWP/Caldera-Forms#961]
hi 
first thanks for this plugin. very professional. i started using your nice forms recently but noticed that the toggle switch doesn't work and conditional groups allow only 1 to work per form. but EVEN THEN only one target field will hide or show for a condition
e.g. if i want to hide 3 fields for a given condition, only the first one will be hidden. the rest wont. 
Can you provide some guidance on this?
And toggle switch are not working. 

p.s. I use cloudflare for caching

**Comment by paaljoachim** [comment]
Hey Gilbert. Turn off the various plugins and see if there is a plugin conflict. If there is then post about it here.

**Comment by gilbert-mjp** [comment]
No plugin conflict. Disabled plugins, same problem.

**Comment by paaljoachim** [comment]
Ok. Josh will need to look into it when he has the time.

**Comment by gilbert-mjp** [comment]
thanks. will be waiting

**Comment by Shelob9** [comment]
@gilbert-mjp  I think that we already discussed this in support, if not can you please open a support ticket at https://CalderaWP.com/support

I am closing this as its not an issue with the plugin, but a site conflict.

**Comment by shooroop87** [comment]
I've same problem. I cann't find site conflict. Could you take a look this page https://kidopass.com/devenir-partenaire/ ?
