### ISSUE TITLE
JS error when edit post (error from CF)

### ISSUE THREAD

**Issue by nandotess** [CalderaWP/Caldera-Forms#962]
Hello.

Our client website is displaying an JS error in console related with Caldera Forms:
```
/wp-content/plugins/caldera-forms/assets/js/frontend-script-init.min.js:1
Uncaught TypeError: Cannot read property 'on' of undefined
```

After install a new and empty WordPress in localhost, we found a pattern to see the issue:
**1)** Install **Caldera Forms** AND **Caldera Custom Fields** plugins.
**2)** Create a form and add a processor from **Caldera Custom Fields**.
**3)** Try edit a simple post, the error is displayed.

Others plugins are broken because of this error.

**Extra information:** this error only happens when we have **Caldera Forms** AND **Caldera Custom Fields** plugins installed and activated together, and we have at least one form with the **Caldera Custom Fields** processor configured.

Please, can you support us? Thanks.

PS: error also reported in WordPress [**Caldera Custom Fields** support page](https://wordpress.org/support/topic/js-error-when-edit-post-error-from-cf/).

**Comment by Shelob9** [comment]
@nandotess I have opened an issue in the repo for that plugin. I will take a look at it next week. https://github.com/CalderaWP/caldera-custom-fields/issues/6

Please note if you need immediate support, you should open a support request https://CalderaWP.com/support

**Comment by Shelob9** [comment]
@nandotess I do appologize that you're getting sent all over the place. I wish WordPress.org would allow plugin developers to indicate how they wish to handle support in a clear and conistent manner.
