### ISSUE TITLE
WP Rocket files optimisation and CF conditional logic etc

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#963]
Hey

I have been using WP Rocket for a client site. I clicked everything. Got to get some good results on Pingdom speed test...:)

One setting is the Files Optimisation area:
HTML - Inline CSS and Inline JS
Google Fonts
CSS
JS

Turning on CSS and JS the conditional logic stopped working. The customer did not get a confirmation message and the admin did not get the e-mail.

Maybe it has to do with all the little text below here......

Minification removes any spaces and comments present in the CSS and JavaScript files.
This mechanism reduces the weight of each file and allows a faster reading of browsers and search engines.
Concatenation combines all CSS and JavaScript files.
This mechanism reduces the number of HTTP requests and improves the loading time.
Warning: Concatenating files can cause display errors.
Warning: In case of any errors we recommend you to turn off this option or watch the following video: http://www.youtube.com/embed/kymoxCwW03c.

![screen shot 2016-11-24 at 14 22 41](https://cloud.githubusercontent.com/assets/5323259/20600243/e86d4b9e-b252-11e6-8d46-a74c19327d4f.png)

Yup I turned off the CSS and JS again.... not much choice really.

**Comment by Shelob9** [comment]
@paaljoachim  - Minifgying minimized JavaScript and CSS hardly ever ends well. In Caldera Forms 1.5 you will be able to turn off our minification, if you wish to minify yourself.
