### ISSUE TITLE
Changing the From Email and reply to Email

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#964]
I changed the various From Emails and Reply to Emails because of...

From Email I had to fill in a fake address to be on the safe side I guess.
Reply to Email I have been told that if the person uses hotmail, gmail etc that it might end up in the spam folder. So this too has a fake e-mail address. BUT lately a bunch of the e-mails end up going to Spam folder anyhow.... 
I am not sure what to do about it.

**Comment by Shelob9** [comment]
@paaljoachim This is not really a question about Caldera Forms. This is a question about how to send an email without getting sent to spam. I would recommend using SendGrid or AWS SES and setting proper DKIM and SPF records. If you need help setting this up, please open a support request.

Here are the stats for our emails sent on our site (Caldera Forms, EDD and core)

![screenshot from 2016-11-25 19-32-46](https://cloud.githubusercontent.com/assets/1994311/20636965/153a32ba-b346-11e6-82ff-29d0c2118cf5.png)

SendGrid is the best $0 a month I spend.
