### ISSUE TITLE
Submission of Hidden Fields and Conditional Fields Bug?

### ISSUE THREAD

**Issue by iannich** [CalderaWP/Caldera-Forms#965]
Caldera Forms Version 1.4.4.1 

I have found a bug or bugs with the submission of Select Fields populated through CF filters, Hidden Fields and Conditional Fields:

Scenario:

I have a series of DropDown Select fields (created as normal in CF form builder)
I have not created any options for these fields, instead I am using CF "_render_get_field_slug" 
filters to populate the options from Custom Post Types created with PODS. 

Problem 1:

All of the above works as desired in the front end but when I use the CF "_submit_complete" action 
to create emails I am unable to access the data from the fields above.

Solution (temp) 1:

Created a "Single Line Text Field" for each corresponding Select field to hold the value selected on the front end.
I then use JQuery to set the value when the user changes the selection.

Problem 2:
 
The above worked until I changed these fields from "Single Line Text Field" to "Hidden" fields. 
Again no data to create my emails.

Solution 2: 

Changed the field type back to "Single Line Text"
Hid the fields using CSS, success, I can now access the data for my emails. :)

Problem 3:

Using a Redirect Processor to send a variable from one form to another works if the data is stored in a "Single Line Text Field" in the first form.
If I change the field type to Hidden the data value is no longer visible as a _Get variable in the url.

Observations:

I have discovered that the data in each of these situations is never sent with the form, at least when using ajax.
The Request Header's - Request Payload does not contain these hidden data fields or the data from the Select fields.

Problem 4:

This issue may be related, or may be a separate bug?

I have a couple of CF show/hide conditionals that work fine on the front end but again, the data is not submitted via ajax when the fields are "visible".
If I remove the condition the data is submitted.

Solution 3:

I will need to handle the conditions myself with JQuery.

Looking forward to your insights.

regards,

Ian

**Comment by Shelob9** [comment]
@iannich  Thanks for using Caldera Forms. These are not really bugs, more like implementation issues. I'd be happy to help walk you through the customizations you are working on through a support ticket. https://CalderaWP.com/support

**Comment by iannich** [comment]
Hi Josh,

I'm intrigued. I have just emailed your team a pre sales enquiry regarding the purchase of a custom add-on bundle. Hopefully I will be able to send a support request within a couple of days. 

Regards, Ian
