### ISSUE TITLE
New Forms screen suggestions

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#966]
The Forms screen is the first look someone gets of Caldera Forms.
It would be nice to have it as an info dashboard giving more information about the forms. As a quick overview.

![cf-new-forms-wireframe](https://cloud.githubusercontent.com/assets/5323259/20609886/a2fbda2c-b292-11e6-943c-98d85923bbb6.jpg)

The first suggestion to inspire new thoughts on the forms screen.
Showing a thumbnail of the existing form. Hover over a section and the quick edit bar is seen. As well as a thin green border around the section.

**Comment by Shelob9** [comment]
@paaljoachim These are good suggestions. Issue is duplicate of #960 I will note there that you made some nice suggestions here.
