### ISSUE TITLE
Advanced File Uploader stop the form submission

### ISSUE THREAD

**Issue by tedchong1980** [CalderaWP/Caldera-Forms#967]
The form with Advanced File Uploader cannot be submitted but it is submitted without Advanced File Uploader. Anybody can tell me the solution? Thanks

**Comment by Shelob9** [comment]
@tedchong1980 Thank you for using Caldera Forms. This is not the correct place for a support request.

It sounds like a PHP or JavaScript error is affecting file uploads. Please check the troubleshooting steps on our support page https://CalderaWP.com/support which will help you identify the error. If you need help troubleshooting this issue, then please open a support ticket.
