### ISSUE TITLE
forms not sending

### ISSUE THREAD

**Issue by h4r00n123** [CalderaWP/Caldera-Forms#969]
I am having issues with the form on both the contact and clients page of my website. www.rewindmemories.co.uk. It was working but suddenly stopped. It only seems to work when I am logged into wordpress. Please help. 

Thanks

**Comment by Shelob9** [comment]
@h4r00n123  Thanks for using Caldera Forms. Please note this is not a support channel. If you need help troubleshooting, please open a support ticket at https://CalderaWP.com/support

If a form isn't submitting when not logged in that would indicate that your static html caching is too aggressive and causing a stale version of our verification token from being served.

You might try the Cache Buddy plugin, or disabling your static html cache on the page with your form.

**Comment by h4r00n123** [comment]
Hi



Thanks for the reply. I am using w3 total cache and autoptimize. If I disable w3 total cache would it resolve the issue? I have disabled it and the form seems to be working but this was the case previously too. It is only after a few days that it would stop working, so I shall test it again in a few days.



Kind Regards



Aaron Raymond

Digital Account Manager

(GForce Certified Search Consultant)



t: 0121 661 6595

e: aaron@gforcewebdesign.co.uk





www.gforcewebdesign.co.uk

mobile | tablet | desktop







Please consider the environment before printing this email.






---- On Sat, 26 Nov 2016 00:27:52 +0000 Josh Pollock &lt;notifications@github.com&gt; wrote ----




@h4r00n123 Thanks for using Caldera Forms. Please note this is not a support channel. If you need help troubleshooting, please open a support ticket at https://CalderaWP.com/support

If a form isn't submitting when not logged in that would indicate that your static html caching is too aggressive and causing a stale version of our verification token from being served.

You might try the Cache Buddy plugin, or disabling your static html cache on the page with your form.

**Comment by Shelob9** [comment]
Not sure, but I can tell you that w3tc's static page caching needs to be bypassed on the page with Caldera Forms.

**Comment by Shelob9** [comment]
See: #1007
