### ISSUE TITLE
Advanced File Uploader stop my form submission

### ISSUE THREAD

**Issue by tedchong1980** [CalderaWP/Caldera-Forms#971]
Form can't be submitted with Advanced File Loader but it can submit with Advanced File Loader. Can anybody tell me the solution to solve this issue?

**Comment by cicichirinos** [comment]
hey Josh, looks like this is happening to a handful of people on the wordpress.org support forum as well. let's take a look.

https://wordpress.org/support/topic/advanced-file-uploader-stop-my-form-submission/#post-8483920
https://wordpress.org/support/topic/bug-upload-file-not-saved/

**Comment by Shelob9** [comment]
@tedchong1980 Can you please explain how you are setting up this file field and also turn on debug logging as explained here: https://calderawp.com/2016/05/wordpress-debug-logging/ ?

If this is a bug then I will fix it if I can figure out how to reproduce it. Please share details on your form setup and a list of JavaScript errors or PHP errors your encountering. If you need help finding these, please open a support ticket at https://CalderaWP.com/support

I'm testing with 2 advanced file fields one with multiple files, one with out. In both cases if I check "Upload to Media Library" it is uploaded to the media library. If I don't then it is not, but in neither case does form submission stop.

When you're experincing a situation where you click submit and then form submission doesn't complete, this is likely a JavaScript or PHP error, please see our support page https://CalderaWP.com/support

**Comment by Shelob9** [comment]
Duplicate of #967
