### ISSUE TITLE
WordFence thinks fields/states/config_template.php is malicious - it is not.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#979]
It's an empty file. I'll put something there in hopes it makes them happy.

**Comment by Shelob9** [comment]
Close via 	27c0bf3

**Comment by rbritton** [comment]
The file was flagged because the file matched the signature `Win.Malware.Agent1592130909/CRDF-1` from the ClamAV databases. This and one other signature were hashes for single byte files (this one was a single \n character), so we've manually removed those two from the list we check against.

**Comment by Shelob9** [comment]
Thanks @rbritton
