### ISSUE TITLE
Backing up with Duplicator I get a Table Details warning

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#983]
Hey

Have fun at WCUS Josh!

I am noticing lately that I am getting this:

![screen shot 2016-12-01 at 19 13 46](https://cloud.githubusercontent.com/assets/5323259/20806284/9783d498-b7fa-11e6-8a32-9ac33ff81979.png)

**Comment by Shelob9** [comment]
What's triggering it? Those tables are all under 100k rows.

**Comment by paaljoachim** [comment]
Ahhh... I did not look far enough down.
It has nothing to do with CF...

I'll look into it...

wp_wfBadLeechers
Case:1
Rows:0
Size:16KB
wp_wfBlockedIPLog
Case:1
Rows:0
Size:16KB
wp_wfBlocks
Case:1
Rows:0
Size:32KB
wp_wfBlocksAdv
Case:1
Rows:0
Size:16KB
wp_wfConfig
Case:1
Rows:142
Size:16KB
wp_wfCrawlers
Case:1
Rows:0
Size:16KB
wp_wfFileMods
Case:1
Rows:2,833
Size:1.52MB
wp_wfHits
Case:1
Rows:156
Size:112KB
wp_wfHoover
Case:1
Rows:0
Size:32KB
wp_wfIssues
Case:1
Rows:2
Size:16KB
wp_wfKnownFileList
Case:1
Rows:2,967
Size:272KB
wp_wfLeechers
Case:1
Rows:52
Size:16KB
wp_wfLockedOut
Case:1
Rows:0
Size:16KB
wp_wfLocs
Case:1
Rows:0
Size:16KB
wp_wfLogins
Case:1
Rows:0
Size:48KB
wp_wfNet404s
Case:1
Rows:0
Size:32KB
wp_wfReverseCache
Case:1
Rows:0
Size:16KB
wp_wfSNIPCache
Case:1
Rows:0
Size:48KB
wp_wfScanners
Case:1
Rows:0
Size:16KB
wp_wfStatus
Case:1
Rows:764
Size:176KB
wp_wfThrottleLog
Case:1
Rows:0
Size:32KB
wp_wfVulnScanners
Case:1
Rows:0
Size:16KB
