### ISSUE TITLE
SOS - Bootstrap is broken!!!!!!!!!!!!!!!!! in New Update

### ISSUE THREAD

**Issue by ghoseandco** [CalderaWP/Caldera-Forms#989]
This is extreme serious issue related to UI. Bootstrap CSS is NOT loading in the new version.

**Comment by Shelob9** [comment]
@ghoseandco Thanks for using Caldera Forms. I am sorry you are having this issue. 

This is not a support channel. If you need help figuring out what is causing this on your site, please open a support request at https://CalderaForms.com/support
