### ISSUE TITLE
Unable to send in Firefox and IE problem

### ISSUE THREAD

**Issue by ncompass** [CalderaWP/Caldera-Forms#993]
Chrome works fine.... but forms won't submit in Firefox or IE/Edge... I upgraded to WordPress 4.7 and have latest versions of the plug in installed.

Does anyone else get this problem?

**Comment by Shelob9** [comment]
@ncompass Thanks for using Caldera Forms. Can you please provide more information than `won't submit`. On our support page (https://CalderaForms.com/support) are instructions for logging JavaScript and PHP errors. If you could please list all errors you find and provide your full debug information, I would be able to say if this is a conflict with a plugin/theme which should be addressed through support or a buig we can work through here.

**Comment by Shelob9** [comment]
@ncompass I am unable to reproduce in Firefox. I wonder maybe if you are using a bad combo of magic tags, or some other JavaScript error is happening?

**Comment by Shelob9** [comment]
Closing, no response.
