### ISSUE TITLE
Bootstrap loading

### ISSUE THREAD

**Issue by ghoseandco** [CalderaWP/Caldera-Forms#994]
This is more like a question. Looking at the code, I could not figure out how Bootstrap grid css is loading in the caldera embeded form in widget. Is it loading from a CDN or has static link?

**Comment by Shelob9** [comment]
@ghoseandco Depending on your settings its either loaded from here:
https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/css/caldera-grid.css

or here:
https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/css/caldera-forms-front.min.css

If you have all three style includes set in the general settings, caldera-forms-front.min.css is used, if not, the caldera-grid.css, caldera-form.css and caldera-alert.css are loaded conditionally. 

See #889
