### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by karl-hive** [CalderaWP/Caldera-Forms#997]
I'm using Cloudflare with my website which seems to effect the sending / receiving of forms.

Is this a known issue?

**Comment by Shelob9** [comment]
Yes, you need to set the TTL to be shorter than the nonce lifespan (12 hours by default) or the security token will not validate. Also make sure you are not caching POST requests and are providing an exception for our API requests.

Even better would be not not cache the page with the form at all.

**Comment by Shelob9** [comment]
If you need further assitance, please use our support form: calderaforms.com/support

**Comment by Shelob9** [comment]
See: #1007
